# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

AllCops:
  Exclude:
    - "nuxt_side/**/*"
    - "nuxt_side_small/**/*"
    - "share_board_order_setting_modal_ui_mock_experiment/**/*"

# ↓これが理想だけど強制的に [1,2,] が [1,2] になってしまうため役に立たない
#
# Style/TrailingCommaInArrayLiteral
#   EnforcedStyleForMultiline: consistent_comma
#   EnforcedStyleForSingleline: ignore
#
# Style/TrailingCommaInHashLiteral
#   EnforcedStyleForMultiline: consistent_comma
#   EnforcedStyleForSingleline: ignore
#
# Style/TrailingCommaInArguments
#   EnforcedStyleForMultiline: consistent_comma
#   EnforcedStyleForSingleline: ignore

################################################################################ しょうがないので無効にしている

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

################################################################################ こだわりルール

# 最後に return を書いてもよい。rubocop は最後より内側の return まで判定してしまうので仕方なく無効にする。
Style/RedundantReturn:
  Enabled: false

# Rails では ->(x) とするルールらしいが、かなり気持ちわるいので -> (x) とする
Layout/SpaceInLambdaLiteral:
  EnforcedStyle: require_space

# [ 1, 2 ] は冗長なので [1, 2] でもよい
Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

# { :a => 1, b: 2 } のように混在は避けよ、なら EnforcedStyle: no_mixed_keys でいいらしいのだが、
# class: だけは :class => と書かないと ruby-mode.el がおかしくなるので混在は意図的なもの。
# なので無効化する
Style/HashSyntax:
  # EnforcedStyle: no_mixed_keys
  Enabled: false

# -> x {} を -> (x) {} にされたくない
Style/StabbyLambdaParentheses:
  Enabled: false
