# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

AllCops:
  Exclude:
    - "nuxt_side/**/*"
    - "nuxt_side_small/**/*"
    - "share_board_order_setting_modal_ui_mock_experiment/**/*"

# ↓これが理想だけど強制的に [1,2,] が [1,2] になってしまうため役に立たない
#
# Style/TrailingCommaInArrayLiteral
#   EnforcedStyleForMultiline: consistent_comma
#   EnforcedStyleForSingleline: ignore
#
# Style/TrailingCommaInHashLiteral
#   EnforcedStyleForMultiline: consistent_comma
#   EnforcedStyleForSingleline: ignore
#
# Style/TrailingCommaInArguments
#   EnforcedStyleForMultiline: consistent_comma
#   EnforcedStyleForSingleline: ignore

################################################################################ しょうがないので無効にしている

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

################################################################################

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/StabbyLambdaParentheses:
  Enabled: false

# a = -> (x, y) { x + y }
Layout/SpaceInLambdaLiteral:
  EnforcedStyle: require_space

Layout/EmptyLineAfterMagicComment:
  Enabled: false

# 最後に return を書いてもよい
Style/RedundantReturn:
  Enabled: false

Layout/LeadingCommentSpace:
  Enabled: false
