# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

AllCops:
  Exclude:
    - "workbench/**/*"

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/StabbyLambdaParentheses:
  Enabled: false

Layout/SpaceInLambdaLiteral:
  Enabled: false

Layout/EmptyLineAfterMagicComment:
  Enabled: false
