sudo: required
dist: trusty

addons:
  code_climate:
    repo_token: 9d29c9321ce417d4527021094652f5fe47ccc2ab3e099ff201bf3fab507a2031
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

language: ruby

rvm: 2.5.0

# なくても動いている
# services:
#   - mysql

cache:
  directories:
    - vendor/bundle
    - node_modules
    - $HOME/.npm
    - $HOME/.cache

before_install:
  - pwd
  - whoami
  - ls -al
  - env

  # LoadError: cannot load such file -- bundler/dep_proxy 対策
  # https://github.com/travis-ci/travis-ci/issues/8978
  - gem update --system

  # Other
  - cp -av config/database.travis.yml config/database.yml

bundler_args: --without production --deployment

before_script:
  # E2Eテスト用
  # https://github.com/travis-ci/travis-ci/issues/7650#issuecomment-306909354
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

  - bin/yarn
  - bundle exec rake db:create
  - bundle exec rake db:migrate

script:
  bundle exec rspec -f d

after_success:
  - env
  - bundle exec codeclimate-test-reporter
