language: ruby
rvm: 2.5.0
services:
  - mysql
bundler_args: --without production --deployment
cache: bundler
before_install:
  # https://github.com/travis-ci/travis-ci/issues/8978
  - gem update --system
  - cp -av config/database.travis.yml config/database.yml
before_script:
  - env
  - bundle exec rake db:create
  - bundle exec rake db:migrate
script:
  bundle exec rake spec
