sudo: required
dist: trusty

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

language: ruby

rvm: 2.5.0

# services:
#   - mysql

cache:
  directories:
    - vendor/bundle
    - node_modules
    - $HOME/.npm
    - $HOME/.cache

before_install:
  # LoadError: cannot load such file -- bundler/dep_proxy 対策
  # https://github.com/travis-ci/travis-ci/issues/8978
  - gem update --system

  # Other
  - cp -av config/database.travis.yml config/database.yml

bundler_args: --without production --deployment

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - bin/yarn
  - bundle exec rake db:create
  - bundle exec rake db:migrate

script:
  bundle exec rspec --formatf documentation
