#!/bin/sh
r -wx folder_methods folder_methods app lib spec experiment
r -wx FolderMod FolderMethods app lib spec experiment
n -wx folder_methods folder_methods app lib spec experiment
n -wx FolderMod FolderMethods app lib spec experiment
r -wx user_mod user_methods app lib spec experiment
r -wx UserMod UserMethods app lib spec experiment
n -wx user_mod user_methods app lib spec experiment
n -wx UserMod UserMethods app lib spec experiment
r -wx avatar_mod avatar_methods app lib spec experiment
r -wx AvatarMod AvatarMethods app lib spec experiment
n -wx avatar_mod avatar_methods app lib spec experiment
n -wx AvatarMod AvatarMethods app lib spec experiment
r -wx import_export_mod import_export_methods app lib spec experiment
r -wx ImportExportMod ImportExportMethods app lib spec experiment
n -wx import_export_mod import_export_methods app lib spec experiment
n -wx ImportExportMod ImportExportMethods app lib spec experiment
r -wx membership_time_chart_mod membership_time_chart_methods app lib spec experiment
r -wx MembershipTimeChartMod MembershipTimeChartMethods app lib spec experiment
n -wx membership_time_chart_mod membership_time_chart_methods app lib spec experiment
n -wx MembershipTimeChartMod MembershipTimeChartMethods app lib spec experiment
r -wx add_json_link_mod add_json_link_methods app lib spec experiment
r -wx AddJsonLinkMod AddJsonLinkMethods app lib spec experiment
n -wx add_json_link_mod add_json_link_methods app lib spec experiment
n -wx AddJsonLinkMod AddJsonLinkMethods app lib spec experiment
r -wx error_show_mod error_show_methods app lib spec experiment
r -wx ErrorShowMod ErrorShowMethods app lib spec experiment
n -wx error_show_mod error_show_methods app lib spec experiment
n -wx ErrorShowMod ErrorShowMethods app lib spec experiment
r -wx page_title_mod page_title_methods app lib spec experiment
r -wx PageTitleMod PageTitleMethods app lib spec experiment
n -wx page_title_mod page_title_methods app lib spec experiment
n -wx PageTitleMod PageTitleMethods app lib spec experiment
r -wx visibility_hidden_mod visibility_hidden_methods app lib spec experiment
r -wx VisibilityHiddenMod VisibilityHiddenMethods app lib spec experiment
n -wx visibility_hidden_mod visibility_hidden_methods app lib spec experiment
n -wx VisibilityHiddenMod VisibilityHiddenMethods app lib spec experiment
r -wx form_mod form_methods app lib spec experiment
r -wx FormMod FormMethods app lib spec experiment
n -wx form_mod form_methods app lib spec experiment
n -wx FormMod FormMethods app lib spec experiment
r -wx add_params_print_mod add_params_print_methods app lib spec experiment
r -wx AddParamsPrintMod AddParamsPrintMethods app lib spec experiment
n -wx add_params_print_mod add_params_print_methods app lib spec experiment
n -wx AddParamsPrintMod AddParamsPrintMethods app lib spec experiment
r -wx columns_colum_mod columns_colum_methods app lib spec experiment
r -wx ColumnsColumMod ColumnsColumMethods app lib spec experiment
n -wx columns_colum_mod columns_colum_methods app lib spec experiment
n -wx ColumnsColumMod ColumnsColumMethods app lib spec experiment
r -wx link_mod link_methods app lib spec experiment
r -wx LinkMod LinkMethods app lib spec experiment
n -wx link_mod link_methods app lib spec experiment
n -wx LinkMod LinkMethods app lib spec experiment
r -wx post_redirect_mod post_redirect_methods app lib spec experiment
r -wx PostRedirectMod PostRedirectMethods app lib spec experiment
n -wx post_redirect_mod post_redirect_methods app lib spec experiment
n -wx PostRedirectMod PostRedirectMethods app lib spec experiment
r -wx support_mod support_methods app lib spec experiment
r -wx SupportMod SupportMethods app lib spec experiment
n -wx support_mod support_methods app lib spec experiment
n -wx SupportMod SupportMethods app lib spec experiment
r -wx user_mod user_methods app lib spec experiment
r -wx UserMod UserMethods app lib spec experiment
n -wx user_mod user_methods app lib spec experiment
n -wx UserMod UserMethods app lib spec experiment
r -wx user_race_mod user_race_methods app lib spec experiment
r -wx UserRaceMod UserRaceMethods app lib spec experiment
n -wx user_race_mod user_race_methods app lib spec experiment
n -wx UserRaceMod UserRaceMethods app lib spec experiment
r -wx sort_mod sort_methods app lib spec experiment
r -wx SortMod SortMethods app lib spec experiment
n -wx sort_mod sort_methods app lib spec experiment
n -wx SortMod SortMethods app lib spec experiment
r -wx tag_mod tag_methods app lib spec experiment
r -wx TagMod TagMethods app lib spec experiment
n -wx tag_mod tag_methods app lib spec experiment
n -wx TagMod TagMethods app lib spec experiment
r -wx palette_mod palette_methods app lib spec experiment
r -wx PaletteMod PaletteMethods app lib spec experiment
n -wx palette_mod palette_methods app lib spec experiment
n -wx PaletteMod PaletteMethods app lib spec experiment
r -wx user_profile_mod user_profile_methods app lib spec experiment
r -wx UserProfileMod UserProfileMethods app lib spec experiment
n -wx user_profile_mod user_profile_methods app lib spec experiment
n -wx UserProfileMod UserProfileMethods app lib spec experiment
r -wx image_mod image_methods app lib spec experiment
r -wx ImageMod ImageMethods app lib spec experiment
n -wx image_mod image_methods app lib spec experiment
n -wx ImageMod ImageMethods app lib spec experiment
r -wx user_staff_mod user_staff_methods app lib spec experiment
r -wx UserStaffMod UserStaffMethods app lib spec experiment
n -wx user_staff_mod user_staff_methods app lib spec experiment
n -wx UserStaffMod UserStaffMethods app lib spec experiment
r -wx user_chore_mod user_chore_methods app lib spec experiment
r -wx UserChoreMod UserChoreMethods app lib spec experiment
n -wx user_chore_mod user_chore_methods app lib spec experiment
n -wx UserChoreMod UserChoreMethods app lib spec experiment
r -wx share_board_mod share_board_methods app lib spec experiment
r -wx ShareBoardMod ShareBoardMethods app lib spec experiment
n -wx share_board_mod share_board_methods app lib spec experiment
n -wx ShareBoardMod ShareBoardMethods app lib spec experiment
r -wx user_free_battle_mod user_free_battle_methods app lib spec experiment
r -wx UserFreeBattleMod UserFreeBattleMethods app lib spec experiment
n -wx user_free_battle_mod user_free_battle_methods app lib spec experiment
n -wx UserFreeBattleMod UserFreeBattleMethods app lib spec experiment
r -wx user_core_mod user_core_methods app lib spec experiment
r -wx UserCoreMod UserCoreMethods app lib spec experiment
n -wx user_core_mod user_core_methods app lib spec experiment
n -wx UserCoreMod UserCoreMethods app lib spec experiment
r -wx user_devise_mod user_devise_methods app lib spec experiment
r -wx UserDeviseMod UserDeviseMethods app lib spec experiment
n -wx user_devise_mod user_devise_methods app lib spec experiment
n -wx UserDeviseMod UserDeviseMethods app lib spec experiment
r -wx user_crawl_reservation_mod user_crawl_reservation_methods app lib spec experiment
r -wx UserCrawlReservationMod UserCrawlReservationMethods app lib spec experiment
n -wx user_crawl_reservation_mod user_crawl_reservation_methods app lib spec experiment
n -wx UserCrawlReservationMod UserCrawlReservationMethods app lib spec experiment
r -wx user_avatar_mod user_avatar_methods app lib spec experiment
r -wx UserAvatarMod UserAvatarMethods app lib spec experiment
n -wx user_avatar_mod user_avatar_methods app lib spec experiment
n -wx UserAvatarMod UserAvatarMethods app lib spec experiment
r -wx user_tag_mod user_tag_methods app lib spec experiment
r -wx UserTagMod UserTagMethods app lib spec experiment
n -wx user_tag_mod user_tag_methods app lib spec experiment
n -wx UserTagMod UserTagMethods app lib spec experiment
r -wx user_xy_master_mod user_xy_master_methods app lib spec experiment
r -wx UserXyMasterMod UserXyMasterMethods app lib spec experiment
n -wx user_xy_master_mod user_xy_master_methods app lib spec experiment
n -wx UserXyMasterMod UserXyMasterMethods app lib spec experiment
r -wx battle_model_mod battle_model_methods app lib spec experiment
r -wx BattleModelMod BattleModelMethods app lib spec experiment
n -wx battle_model_mod battle_model_methods app lib spec experiment
n -wx BattleModelMod BattleModelMethods app lib spec experiment
r -wx user_zip_dl_log_mod user_zip_dl_log_methods app lib spec experiment
r -wx UserZipDlLogMod UserZipDlLogMethods app lib spec experiment
n -wx user_zip_dl_log_mod user_zip_dl_log_methods app lib spec experiment
n -wx UserZipDlLogMod UserZipDlLogMethods app lib spec experiment
r -wx page_mod page_methods app lib spec experiment
r -wx PageMod PageMethods app lib spec experiment
n -wx page_mod page_methods app lib spec experiment
n -wx PageMod PageMethods app lib spec experiment
r -wx user_ts_master_mod user_ts_master_methods app lib spec experiment
r -wx UserTsMasterMod UserTsMasterMethods app lib spec experiment
n -wx user_ts_master_mod user_ts_master_methods app lib spec experiment
n -wx UserTsMasterMod UserTsMasterMethods app lib spec experiment
r -wx time_chart_mod time_chart_methods app lib spec experiment
r -wx TimeChartMod TimeChartMethods app lib spec experiment
n -wx time_chart_mod time_chart_methods app lib spec experiment
n -wx TimeChartMod TimeChartMethods app lib spec experiment
r -wx folder_methods folder_methods app lib spec experiment
r -wx FolderMod FolderMethods app lib spec experiment
n -wx folder_methods folder_methods app lib spec experiment
n -wx FolderMod FolderMethods app lib spec experiment
r -wx vote_mod vote_methods app lib spec experiment
r -wx VoteMod VoteMethods app lib spec experiment
n -wx vote_mod vote_methods app lib spec experiment
n -wx VoteMod VoteMethods app lib spec experiment
r -wx clip_mod clip_methods app lib spec experiment
r -wx ClipMod ClipMethods app lib spec experiment
n -wx clip_mod clip_methods app lib spec experiment
n -wx ClipMod ClipMethods app lib spec experiment
r -wx import_export_mod import_export_methods app lib spec experiment
r -wx ImportExportMod ImportExportMethods app lib spec experiment
n -wx import_export_mod import_export_methods app lib spec experiment
n -wx ImportExportMod ImportExportMethods app lib spec experiment
r -wx info_mod info_methods app lib spec experiment
r -wx InfoMod InfoMethods app lib spec experiment
n -wx info_mod info_methods app lib spec experiment
n -wx InfoMod InfoMethods app lib spec experiment
r -wx folder_methods folder_methods app lib spec experiment
r -wx FolderMod FolderMethods app lib spec experiment
n -wx folder_methods folder_methods app lib spec experiment
n -wx FolderMod FolderMethods app lib spec experiment
r -wx user_mod user_methods app lib spec experiment
r -wx UserMod UserMethods app lib spec experiment
n -wx user_mod user_methods app lib spec experiment
n -wx UserMod UserMethods app lib spec experiment
r -wx xrecord_share_mod xrecord_share_methods app lib spec experiment
r -wx XrecordShareMod XrecordShareMethods app lib spec experiment
n -wx xrecord_share_mod xrecord_share_methods app lib spec experiment
n -wx XrecordShareMod XrecordShareMethods app lib spec experiment
r -wx kif_show_mod kif_show_methods app lib spec experiment
r -wx KifShowMod KifShowMethods app lib spec experiment
n -wx kif_show_mod kif_show_methods app lib spec experiment
n -wx KifShowMod KifShowMethods app lib spec experiment
r -wx scripts_controller_mod scripts_controller_methods app lib spec experiment
r -wx ScriptsControllerMod ScriptsControllerMethods app lib spec experiment
n -wx scripts_controller_mod scripts_controller_methods app lib spec experiment
n -wx ScriptsControllerMod ScriptsControllerMethods app lib spec experiment
r -wx current_user_mod current_user_methods app lib spec experiment
r -wx CurrentUserMod CurrentUserMethods app lib spec experiment
n -wx current_user_mod current_user_methods app lib spec experiment
n -wx CurrentUserMod CurrentUserMethods app lib spec experiment
r -wx zip_dl_mod zip_dl_methods app lib spec experiment
r -wx ZipDlMod ZipDlMethods app lib spec experiment
n -wx zip_dl_mod zip_dl_methods app lib spec experiment
n -wx ZipDlMod ZipDlMethods app lib spec experiment
r -wx remember_swars_user_keys_mod remember_swars_user_keys_methods app lib spec experiment
r -wx RememberSwarsUserKeysMod RememberSwarsUserKeysMethods app lib spec experiment
n -wx remember_swars_user_keys_mod remember_swars_user_keys_methods app lib spec experiment
n -wx RememberSwarsUserKeysMod RememberSwarsUserKeysMethods app lib spec experiment
r -wx index_mod index_methods app lib spec experiment
r -wx IndexMod IndexMethods app lib spec experiment
n -wx index_mod index_methods app lib spec experiment
n -wx IndexMod IndexMethods app lib spec experiment
r -wx show_mod show_methods app lib spec experiment
r -wx ShowMod ShowMethods app lib spec experiment
n -wx show_mod show_methods app lib spec experiment
n -wx ShowMod ShowMethods app lib spec experiment
r -wx shogi_error_rescue_mod shogi_error_rescue_methods app lib spec experiment
r -wx ShogiErrorRescueMod ShogiErrorRescueMethods app lib spec experiment
n -wx shogi_error_rescue_mod shogi_error_rescue_methods app lib spec experiment
n -wx ShogiErrorRescueMod ShogiErrorRescueMethods app lib spec experiment
r -wx encode_mod encode_methods app lib spec experiment
r -wx EncodeMod EncodeMethods app lib spec experiment
n -wx encode_mod encode_methods app lib spec experiment
n -wx EncodeMod EncodeMethods app lib spec experiment
r -wx zip_dl_mod zip_dl_methods app lib spec experiment
r -wx ZipDlMod ZipDlMethods app lib spec experiment
n -wx zip_dl_mod zip_dl_methods app lib spec experiment
n -wx ZipDlMod ZipDlMethods app lib spec experiment
r -wx debug_mod debug_methods app lib spec experiment
r -wx DebugMod DebugMethods app lib spec experiment
n -wx debug_mod debug_methods app lib spec experiment
n -wx DebugMod DebugMethods app lib spec experiment
r -wx png_show_mod png_show_methods app lib spec experiment
r -wx PngShowMod PngShowMethods app lib spec experiment
n -wx png_show_mod png_show_methods app lib spec experiment
n -wx PngShowMod PngShowMethods app lib spec experiment
r -wx kento_json_mod kento_json_methods app lib spec experiment
r -wx KentoJsonMod KentoJsonMethods app lib spec experiment
n -wx kento_json_mod kento_json_methods app lib spec experiment
n -wx KentoJsonMod KentoJsonMethods app lib spec experiment
r -wx adapter_mod adapter_methods app lib spec experiment
r -wx AdapterMod AdapterMethods app lib spec experiment
n -wx adapter_mod adapter_methods app lib spec experiment
n -wx AdapterMod AdapterMethods app lib spec experiment
r -wx battle_channel_versus_mod battle_channel_versus_methods app lib spec experiment
r -wx BattleChannelVersusMod BattleChannelVersusMethods app lib spec experiment
n -wx battle_channel_versus_mod battle_channel_versus_methods app lib spec experiment
n -wx BattleChannelVersusMod BattleChannelVersusMethods app lib spec experiment
r -wx active_users_notify_mod active_users_notify_methods app lib spec experiment
r -wx ActiveUsersNotifyMod ActiveUsersNotifyMethods app lib spec experiment
n -wx active_users_notify_mod active_users_notify_methods app lib spec experiment
n -wx ActiveUsersNotifyMod ActiveUsersNotifyMethods app lib spec experiment
r -wx battle_channel_versus_mod battle_channel_versus_methods app lib spec experiment
r -wx BattleChannelVersusMod BattleChannelVersusMethods app lib spec experiment
n -wx battle_channel_versus_mod battle_channel_versus_methods app lib spec experiment
n -wx BattleChannelVersusMod BattleChannelVersusMethods app lib spec experiment
r -wx active_users_notify_mod active_users_notify_methods app lib spec experiment
r -wx ActiveUsersNotifyMod ActiveUsersNotifyMethods app lib spec experiment
n -wx active_users_notify_mod active_users_notify_methods app lib spec experiment
n -wx ActiveUsersNotifyMod ActiveUsersNotifyMethods app lib spec experiment

