#!/bin/sh

# Google Chrome 再起動
# osascript -e 'tell app "Google Chrome" to quit'
# osascript -e 'tell app "Google Chrome" to activate'

# いったんウインドウやプロセスをまとめて削除
tmux kill-window -t shogi

tmux new-window -n shogi

tmux split-window -v -t shogi
tmux split-window -h -t shogi.0
tmux split-window -h -t shogi.2
# |---+---|
# | 0 | 1 |
# |---+---|
# | 2 | 3 |
# |---+---|

tmux send-keys -t shogi.0 'cd ~/src/shogi-extend' C-m

tmux send-keys -t shogi.1 'cd ~/src/shogi-player' C-m
tmux send-keys -t shogi.1 'nuxt dev -p 5000' C-m

tmux send-keys -t shogi.2 'cd ~/src/shogi-extend' C-m
tmux send-keys -t shogi.2 'fs' C-m

tmux send-keys -t shogi.3 'cd ~/src/shogi-extend' C-m
tmux send-keys -t shogi.3 'cd front_app' C-m
tmux send-keys -t shogi.3 'nuxt dev -p 4000' C-m

tmux select-pane -t shogi.3

sleep 5
open http://0.0.0.0:3000/admin
open http://0.0.0.0:4000
open http://0.0.0.0:5000

# open http://0.0.0.0:4000
# open https://bulma.io/
# open https://buefy.org/documentation/
# open https://ja.nuxtjs.org/guide/
# open https://misc.0o0o.org/chartjs-doc-ja/
