require "./setup"
tp QuickScript::Swars::PrisonPostScript.new(_method: "post", swars_user_key: "foo").as_json # => {:body=>"testarossa00 は登録済みです", :__script_meta__=>{:qs_group_key=>"swars", :qs_page_key=>"prison-post", :link_path=>"/bin/swars/prison-post", :qs_group_info=>#<QuickScript::QsGroupInfo:0x000000010dfd3ff0 @attributes={:key=>:swars, :name=>"将棋ウォーズ", :admin_only=>true, :code=>0}>}, :form_method=>:post, :button_label=>"実行", :params_add_submit_key=>nil, :form_parts=>[{:label=>"将棋ウォーズID", :key=>:swars_user_key, :type=>:string, :default=>"foo", :placeholder=>"AKABAN_TARO"}], :router_push_failed_then_fetch=>false, :button_with_nuxt_login_required=>false, :flash=>{}, :meta=>{:title=>"将棋ウォーズ囚人登録", :description=>"指定のウォーズIDが牢獄に入っていたら囚人とする", :og_image_key=>nil}, :redirect_to=>nil, :fetch_then_auto_exec_action=>nil}
# >> |---------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
# >> |                            body | testarossa00 は登録済みです                                                                                                                                                                                                                |
# >> |                 __script_meta__ | {:qs_group_key=>"swars", :qs_page_key=>"prison-post", :link_path=>"/bin/swars/prison-post", :qs_group_info=>#<QuickScript::QsGroupInfo:0x000000010dfd3ff0 @attributes={:key=>:swars, :name=>"将棋ウォーズ", :admin_only=>true, :code=>0}>} |
# >> |                     form_method | post                                                                                                                                                                                                                                       |
# >> |                    button_label | 実行                                                                                                                                                                                                                                       |
# >> |           params_add_submit_key |                                                                                                                                                                                                                                            |
# >> |                      form_parts | [{:label=>"将棋ウォーズID", :key=>:swars_user_key, :type=>:string, :default=>"foo", :placeholder=>"AKABAN_TARO"}]                                                                                                                          |
# >> |   router_push_failed_then_fetch | false                                                                                                                                                                                                                                      |
# >> | button_with_nuxt_login_required | false                                                                                                                                                                                                                                      |
# >> |                           flash | {}                                                                                                                                                                                                                                         |
# >> |                            meta | {:title=>"将棋ウォーズ囚人登録", :description=>"指定のウォーズIDが牢獄に入っていたら囚人とする", :og_image_key=>nil}                                                                                                                       |
# >> |                     redirect_to |                                                                                                                                                                                                                                            |
# >> |     fetch_then_auto_exec_action |                                                                                                                                                                                                                                            |
# >> |---------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
