require "./setup"
tp QuickScript::Swars::PrisonSearchScript.new(query: "十段").as_json # => {:body=>{:_component=>"QuickScriptViewValueAsTable", :rows=>[], :paginated=>true, :total=>0, :current_page=>1, :per_page=>1000, :always_table=>true, :header_hide=>false}, :__script_meta__=>{:qs_group_key=>"swars", :qs_page_key=>"prison-search", :link_path=>"/bin/swars/prison-search", :qs_group_info=>#<QuickScript::QsGroupInfo:0x000000010a114620 @attributes={:key=>:swars, :name=>"将棋ウォーズ", :admin_only=>true, :code=>0}>}, :form_method=>:get, :button_label=>"検索", :params_add_submit_key=>nil, :form_parts=>[{:label=>"検索文字列", :key=>:query, :type=>:string, :default=>"十段"}], :router_push_failed_then_fetch=>false, :button_with_nuxt_login_required=>false, :flash=>{}, :meta=>{:title=>"将棋ウォーズ囚人検索", :description=>"検察結果を収監観測日の直近順に表示する", :og_image_key=>nil}, :redirect_to=>nil, :fetch_then_auto_exec_action=>nil}
Kaminari.config.max_per_page                 # => 1000
# >> |---------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
# >> |                            body | {:_component=>"QuickScriptViewValueAsTable", :rows=>[], :paginated=>true, :total=>0, :current_page=>1, :per_page=>1000, :always_table=>true, :header_hide=>false}                                                                              |
# >> |                 __script_meta__ | {:qs_group_key=>"swars", :qs_page_key=>"prison-search", :link_path=>"/bin/swars/prison-search", :qs_group_info=>#<QuickScript::QsGroupInfo:0x000000010a114620 @attributes={:key=>:swars, :name=>"将棋ウォーズ", :admin_only=>true, :code=>0}>} |
# >> |                     form_method | get                                                                                                                                                                                                                                            |
# >> |                    button_label | 検索                                                                                                                                                                                                                                           |
# >> |           params_add_submit_key |                                                                                                                                                                                                                                                |
# >> |                      form_parts | [{:label=>"検索文字列", :key=>:query, :type=>:string, :default=>"十段"}]                                                                                                                                                                       |
# >> |   router_push_failed_then_fetch | false                                                                                                                                                                                                                                          |
# >> | button_with_nuxt_login_required | false                                                                                                                                                                                                                                          |
# >> |                           flash | {}                                                                                                                                                                                                                                             |
# >> |                            meta | {:title=>"将棋ウォーズ囚人検索", :description=>"検察結果を収監観測日の直近順に表示する", :og_image_key=>nil}                                                                                                                                   |
# >> |                     redirect_to |                                                                                                                                                                                                                                                |
# >> |     fetch_then_auto_exec_action |                                                                                                                                                                                                                                                |
# >> |---------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
