require "./setup"
tp QuickScript::Swars::PrisonNewScript.new(_method: "post", swars_user_key: "foo").as_json # => {:body=>nil, :__script_meta__=>{:qs_group_key=>"swars", :qs_page_key=>"prison-new", :link_path=>"/bin/swars/prison-new", :qs_group_info=>#<QuickScript::QsGroupInfo:0x000000010afd9a48 @attributes={:key=>:swars, :name=>"将棋ウォーズ", :admin_only=>false, :code=>0}>}, :form_method=>:post, :button_label=>"登録", :params_add_submit_key=>nil, :get_then_axios_get=>false, :router_push_failed_then_fetch=>false, :button_click_loading=>false, :form_parts=>[{:label=>"将棋ウォーズID", :key=>:swars_user_key, :type=>:string, :default=>"foo", :placeholder=>"AKABAN_TARO"}], :button_with_nuxt_login_required=>false, :flash=>{:notice=>"testarossa00 は登録済みです"}, :meta=>{:title=>"将棋ウォーズ囚人登録", :description=>"指定ユーザーを囚人とする", :og_image_key=>nil, :og_card_size=>true}, :redirect_to=>nil, :fetch_then_auto_exec_action=>nil, :axios_process_type=>:server, :navibar_show=>true}
# >> |---------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
# >> |                            body |                                                                                                                                                                                                                                           |
# >> |                 __script_meta__ | {:qs_group_key=>"swars", :qs_page_key=>"prison-new", :link_path=>"/bin/swars/prison-new", :qs_group_info=>#<QuickScript::QsGroupInfo:0x000000010afd9a48 @attributes={:key=>:swars, :name=>"将棋ウォーズ", :admin_only=>false, :code=>0}>} |
# >> |                     form_method | post                                                                                                                                                                                                                                      |
# >> |                    button_label | 登録                                                                                                                                                                                                                                      |
# >> |           params_add_submit_key |                                                                                                                                                                                                                                           |
# >> |              get_then_axios_get | false                                                                                                                                                                                                                                     |
# >> |   router_push_failed_then_fetch | false                                                                                                                                                                                                                                     |
# >> |            button_click_loading | false                                                                                                                                                                                                                                     |
# >> |                      form_parts | [{:label=>"将棋ウォーズID", :key=>:swars_user_key, :type=>:string, :default=>"foo", :placeholder=>"AKABAN_TARO"}]                                                                                                                         |
# >> | button_with_nuxt_login_required | false                                                                                                                                                                                                                                     |
# >> |                           flash | {:notice=>"testarossa00 は登録済みです"}                                                                                                                                                                                                  |
# >> |                            meta | {:title=>"将棋ウォーズ囚人登録", :description=>"指定ユーザーを囚人とする", :og_image_key=>nil, :og_card_size=>true}                                                                                                              |
# >> |                     redirect_to |                                                                                                                                                                                                                                           |
# >> |     fetch_then_auto_exec_action |                                                                                                                                                                                                                                           |
# >> |              axios_process_type | server                                                                                                                                                                                                                                    |
# >> |                    navibar_show | true                                                                                                                                                                                                                                      |
# >> |---------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
