require "./setup"
tp QuickScript::Swars::ProScript.new.as_json
# >> |-------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
# >> |                          body |                                                                                                                                                                                                                                                                     |
# >> |               __script_meta__ | {:qs_group_key=>"swars", :qs_page_key=>"pro", :qs_path=>"/lab/swars/pro", :qs_group_info=>#<QuickScript::QsGroupInfo:0x000000010ba97ed0 @attributes={:key=>:swars, :name=>"将棋ウォーズ", :admin_only=>false, :sitemap=>true, :code=>0}>}                           |
# >> |                   form_method |                                                                                                                                                                                                                                                                     |
# >> |                  button_label | 実行                                                                                                                                                                                                                                                                |
# >> |         params_add_submit_key |                                                                                                                                                                                                                                                                     |
# >> |            get_then_axios_get | false                                                                                                                                                                                                                                                               |
# >> | router_push_failed_then_fetch | false                                                                                                                                                                                                                                                               |
# >> |          button_click_loading | false                                                                                                                                                                                                                                                               |
# >> |                    form_parts | []                                                                                                                                                                                                                                                                  |
# >> |                          meta | {:title=>"プロの棋力", :description=>"プロ棋士のウォーズの段位をまとめて表示する (棋力一覧に遷移する)", :og_image_key=>"quick_script/swars/pro_script", :og_card_size=>:large, :primary_error_message=>nil}                                                         |
# >> |                main_component | {:_component=>"QuickScriptViewDefault"}                                                                                                                                                                                                                             |
# >> |                  navibar_show | true                                                                                                                                                                                                                                                                |
# >> |               container_width | large                                                                                                                                                                                                                                                               |
# >> |                 body_position | below                                                                                                                                                                                                                                                               |
# >> |    nuxt_login_required_timing |                                                                                                                                                                                                                                                                     |
# >> |               login_link_show | false                                                                                                                                                                                                                                                               |
# >> |         primary_error_message |                                                                                                                                                                                                                                                                     |
# >> |                         flash | {}                                                                                                                                                                                                                                                                  |
# >> |                   redirect_to | {:to=>"/lab/swars/user-group?order_by=grade&user_items_text=%E5%B1%B1%E6%9C%AC%E7%9C%9F%E4%B9%9F+chanlili%0A%E4%BA%95%E5%87%BA%E9%9A%BC%E5%B9%B3+ideon_shogi%0A%E8%B0%B7%E5%90%88%E5%BB%A3%E7%B4%80+T_Hiroki_323%0A%E4%B8%AD%E6%9D%91%E5%A4%AA%E5%9C%B0+Taichan0... |
# >> |              auto_exec_action |                                                                                                                                                                                                                                                                     |
# >> |                auto_exec_code |                                                                                                                                                                                                                                                                     |
# >> |            axios_process_type | server                                                                                                                                                                                                                                                              |
# >> |                  custom_style |                                                                                                                                                                                                                                                                     |
# >> |             sideber_menu_show | false                                                                                                                                                                                                                                                               |
# >> |           sideber_menu_groups | []                                                                                                                                                                                                                                                                  |
# >> |                   parent_link |                                                                                                                                                                                                                                                                     |
# >> |                    title_click_behaviour | url_params_remove                                                                                                                                                                                                                                                      |
# >> |-------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
