require "./setup"
tp QuickScript::Swars::ProScript.new.as_json
# >> |---------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
# >> |                            body |                                                                                                                                                                                                                             |
# >> |                 __script_meta__ | {:qs_group_key=>"swars", :qs_page_key=>"pro", :link_path=>"/lab/swars/pro", :qs_group_info=>#<QuickScript::QsGroupInfo:0x000000011091f468 @attributes={:key=>:swars, :name=>"将棋ウォーズ", :admin_only=>false, :code=>0}>} |
# >> |                     form_method |                                                                                                                                                                                                                             |
# >> |                    button_label | 実行                                                                                                                                                                                                                        |
# >> |           params_add_submit_key |                                                                                                                                                                                                                             |
# >> |              get_then_axios_get | false                                                                                                                                                                                                                       |
# >> |   router_push_failed_then_fetch | false                                                                                                                                                                                                                       |
# >> |            button_click_loading | false                                                                                                                                                                                                                       |
# >> |                      form_parts | []                                                                                                                                                                                                                          |
# >> | nuxt_login_required_timing | false                                                                                                                                                                                                                       |
# >> |                           flash | {}                                                                                                                                                                                                                          |
# >> |                            meta | {:title=>"プロの棋力", :description=>"プロ棋士のウォーズの段位をまとめて表示する", :og_image_key=>nil, :og_card_size=>true}                                                                                        |
# >> |                     redirect_to | {:to=>"/lab/swars/user?order_by=grade&swars_user_keys=BOUYATETSU5+Dsuke213+GOMUNINGEN+MurachanLions+Odenryu+TOBE_CHAN+Taichan0601+chanlili+ideon_shogi+itoshinTV+pagagm"}                                                         |
# >> |     auto_exec_action |                                                                                                                                                                                                                             |
# >> |              axios_process_type | server                                                                                                                                                                                                                      |
# >> |                    navibar_show | true                                                                                                                                                                                                                        |
# >> |---------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
