require "./setup"
sql
user_key = SecureRandom.hex
alice = Swars::User.create!(key: user_key)
2.times do
  Swars::Battle.create! do |e|
    e.memberships.build(user: alice)
  end
end
instance = QuickScript::Swars::UserGroupScript.new({ user_items_text: "(xname) #{user_key}" }, { _method: "post" })
instance.current_user_keys   # => ["562517b7a6bd786135e3970f355615e9"]
instance.db_exist_user_keys  # => ["562517b7a6bd786135e3970f355615e9"]
tp instance.rows

# sql
# user_key = SecureRandom.hex
# alice = Swars::User.create!(key: user_key)
# Swars::Battle.create! do |e|
#   e.memberships.build(user: alice)
# end
# QuickScript::Swars::UserGroupScript.new(user_items_text: user_key).call[:_v_bind][:value][:rows].size # => 1
#
# GoogleApi::ExpirationTracker.destroy_all
# QuickScript::Swars::UserGroupScript.new(user_items_text: user_key, google_sheet: true).call
# GoogleApi::ExpirationTracker.count          # => 1
# GoogleApi::ExpirationTracker.destroy_all

# >>   TRANSACTION (0.2ms)  BEGIN /*application='ShogiWeb'*/
# >>   ↳ app/models/swars/grade.rb:47:in 'block (3 levels) in <class:Grade>'
# >>   Swars::Grade Load (2.1ms)  SELECT `swars_grades`.* FROM `swars_grades` WHERE `swars_grades`.`key` = '30級' ORDER BY `swars_grades`.`priority` ASC LIMIT 1 /*application='ShogiWeb'*/
# >>   ↳ app/models/application_memory_record.rb:36:in 'ApplicationMemoryRecord#db_record!'
# >>   Swars::Grade Count (0.5ms)  SELECT COUNT(*) FROM `swars_grades` /*application='ShogiWeb'*/
# >>   ↳ app/models/swars/user/grade_methods.rb:11:in 'block (3 levels) in <class:User>'
# >>   Swars::Grade Load (0.4ms)  SELECT `swars_grades`.* FROM `swars_grades` WHERE `swars_grades`.`id` = 39 ORDER BY `swars_grades`.`priority` ASC LIMIT 1 /*application='ShogiWeb'*/
# >>   Swars::User Create (3.7ms)  INSERT INTO `swars_users` (`user_key`, `grade_id`, `last_reception_at`, `search_logs_count`, `created_at`, `updated_at`, `ban_at`, `latest_battled_at`, `soft_crawled_at`, `hard_crawled_at`) VALUES ('562517b7a6bd786135e3970f355615e9', 39, NULL, 0, '2025-04-30 12:02:28', '2025-04-30 12:02:28', NULL, '2025-04-30 12:02:28', '2025-04-30 12:02:28', '2025-04-30 12:02:28') /*application='ShogiWeb'*/
# >>   Swars::Profile Create (1.8ms)  INSERT INTO `swars_profiles` (`user_id`, `ban_at`, `ban_crawled_at`, `ban_crawled_count`, `created_at`, `updated_at`) VALUES (1055264, NULL, '2025-04-30 12:02:28', 0, '2025-04-30 12:02:28', '2025-04-30 12:02:28') /*application='ShogiWeb'*/
# >>   TRANSACTION (1.0ms)  COMMIT /*application='ShogiWeb'*/
# >>   TRANSACTION (0.4ms)  BEGIN /*application='ShogiWeb'*/
# >>   ↳ app/models/concerns/memory_record_bind.rb:107:in 'block (3 levels) in <module:MemoryRecordBind>'
# >>   Preset Load (1.1ms)  SELECT `presets`.* FROM `presets` WHERE `presets`.`key` = '平手' ORDER BY `presets`.`position` ASC LIMIT 1 /*application='ShogiWeb'*/
# >>   ↳ app/models/application_memory_record.rb:36:in 'ApplicationMemoryRecord#db_record!'
# >>   Swars::Rule Load (0.3ms)  SELECT `swars_rules`.* FROM `swars_rules` WHERE `swars_rules`.`key` = 'ten_min' ORDER BY `swars_rules`.`position` ASC LIMIT 1 /*application='ShogiWeb'*/
# >>   ↳ app/models/application_memory_record.rb:36:in 'ApplicationMemoryRecord#db_record!'
# >>   Swars::Final Load (0.3ms)  SELECT `swars_finals`.* FROM `swars_finals` WHERE `swars_finals`.`key` = 'TORYO' ORDER BY `swars_finals`.`position` ASC LIMIT 1 /*application='ShogiWeb'*/
# >>   ↳ app/models/application_memory_record.rb:36:in 'ApplicationMemoryRecord#db_record!'
# >>   Swars::Xmode Load (0.3ms)  SELECT `swars_xmodes`.* FROM `swars_xmodes` WHERE `swars_xmodes`.`key` = '野良' ORDER BY `swars_xmodes`.`position` ASC LIMIT 1 /*application='ShogiWeb'*/
# >>   ↳ app/models/application_memory_record.rb:36:in 'ApplicationMemoryRecord#db_record!'
# >>   Swars::Rule Load (0.3ms)  SELECT `swars_rules`.* FROM `swars_rules` WHERE `swars_rules`.`id` = 1 ORDER BY `swars_rules`.`position` ASC LIMIT 1 /*application='ShogiWeb'*/
# >>   ↳ app/models/application_record.rb:91:in 'Kernel#public_send'
# >>   Swars::Grade Load (0.3ms)  SELECT `swars_grades`.* FROM `swars_grades` WHERE `swars_grades`.`key` = '30級' ORDER BY `swars_grades`.`priority` ASC LIMIT 1 /*application='ShogiWeb'*/
# >>   ↳ app/models/application_memory_record.rb:36:in 'ApplicationMemoryRecord#db_record!'
# >>   Swars::Grade Count (0.3ms)  SELECT COUNT(*) FROM `swars_grades` /*application='ShogiWeb'*/
# >>   ↳ app/models/swars/user/grade_methods.rb:11:in 'block (3 levels) in <class:User>'
# >>   Swars::User Count (351.3ms)  SELECT COUNT(*) FROM `swars_users` /*application='ShogiWeb'*/
# >>   ↳ app/models/swars/user.rb:69:in 'block in <class:User>'
# >>   Swars::Grade Load (0.6ms)  SELECT `swars_grades`.* FROM `swars_grades` WHERE `swars_grades`.`id` = 39 ORDER BY `swars_grades`.`priority` ASC LIMIT 1 /*application='ShogiWeb'*/
# >>   ↳ app/models/swars/battle/basic_methods.rb:67:in 'block (4 levels) in <class:Battle>'
# >>   Swars::User Create (0.7ms)  INSERT INTO `swars_users` (`user_key`, `grade_id`, `last_reception_at`, `search_logs_count`, `created_at`, `updated_at`, `ban_at`, `latest_battled_at`, `soft_crawled_at`, `hard_crawled_at`) VALUES ('user1055206', 39, NULL, 0, '2025-04-30 12:02:29', '2025-04-30 12:02:29', NULL, '2025-04-30 12:02:29', '2025-04-30 12:02:29', '2025-04-30 12:02:29') /*application='ShogiWeb'*/
# >>   ↳ app/models/swars/battle/basic_methods.rb:67:in 'block (4 levels) in <class:Battle>'
# >>   Swars::Profile Create (0.2ms)  INSERT INTO `swars_profiles` (`user_id`, `ban_at`, `ban_crawled_at`, `ban_crawled_count`, `created_at`, `updated_at`) VALUES (1055265, NULL, '2025-04-30 12:02:29', 0, '2025-04-30 12:02:29', '2025-04-30 12:02:29') /*application='ShogiWeb'*/
# >>   ↳ app/models/swars/battle/basic_methods.rb:67:in 'block (4 levels) in <class:Battle>'
# >>   Swars::Imode Load (0.3ms)  SELECT `swars_imodes`.* FROM `swars_imodes` WHERE `swars_imodes`.`key` = 'normal' ORDER BY `swars_imodes`.`position` ASC LIMIT 1 /*application='ShogiWeb'*/
# >>   ↳ app/models/application_memory_record.rb:36:in 'ApplicationMemoryRecord#db_record!'
# >>   Preset Load (0.2ms)  SELECT `presets`.* FROM `presets` WHERE `presets`.`id` = 1 ORDER BY `presets`.`position` ASC LIMIT 1 /*application='ShogiWeb'*/
# >>   Location Load (0.4ms)  SELECT `locations`.* FROM `locations` WHERE `locations`.`key` = 'black' ORDER BY `locations`.`position` ASC LIMIT 1 /*application='ShogiWeb'*/
# >>   ↳ app/models/concerns/memory_record_bind.rb:77:in 'MemoryRecordBind::Base::ClassMethods#lookup'
# >>   Judge Load (0.1ms)  SELECT `judges`.* FROM `judges` WHERE `judges`.`key` = 'win' ORDER BY `judges`.`position` ASC LIMIT 1 /*application='ShogiWeb'*/
# >>   ↳ app/models/concerns/memory_record_bind.rb:77:in 'MemoryRecordBind::Base::ClassMethods#lookup'
# >>   Swars::Membership Exists? (0.1ms)  SELECT 1 AS one FROM `swars_memberships` WHERE `swars_memberships`.`location_id` = 1 AND `swars_memberships`.`battle_id` IS NULL LIMIT 1 /*application='ShogiWeb'*/
# >>   Swars::Membership Exists? (0.1ms)  SELECT 1 AS one FROM `swars_memberships` WHERE `swars_memberships`.`user_id` = 1055264 AND `swars_memberships`.`battle_id` IS NULL LIMIT 1 /*application='ShogiWeb'*/
# >>   Swars::Membership Exists? (0.1ms)  SELECT 1 AS one FROM `swars_memberships` WHERE `swars_memberships`.`op_user_id` = 1055265 AND `swars_memberships`.`battle_id` IS NULL LIMIT 1 /*application='ShogiWeb'*/
# >>   Location Load (0.1ms)  SELECT `locations`.* FROM `locations` WHERE `locations`.`key` = 'white' ORDER BY `locations`.`position` ASC LIMIT 1 /*application='ShogiWeb'*/
# >>   ↳ app/models/concerns/memory_record_bind.rb:77:in 'MemoryRecordBind::Base::ClassMethods#lookup'
# >>   Judge Load (0.1ms)  SELECT `judges`.* FROM `judges` WHERE `judges`.`key` = 'lose' ORDER BY `judges`.`position` ASC LIMIT 1 /*application='ShogiWeb'*/
# >>   ↳ app/models/concerns/memory_record_bind.rb:77:in 'MemoryRecordBind::Base::ClassMethods#lookup'
# >>   Swars::Membership Exists? (0.1ms)  SELECT 1 AS one FROM `swars_memberships` WHERE `swars_memberships`.`location_id` = 2 AND `swars_memberships`.`battle_id` IS NULL LIMIT 1 /*application='ShogiWeb'*/
# >>   Swars::Membership Exists? (0.1ms)  SELECT 1 AS one FROM `swars_memberships` WHERE `swars_memberships`.`user_id` = 1055265 AND `swars_memberships`.`battle_id` IS NULL LIMIT 1 /*application='ShogiWeb'*/
# >>   Swars::Membership Exists? (0.1ms)  SELECT 1 AS one FROM `swars_memberships` WHERE `swars_memberships`.`op_user_id` = 1055264 AND `swars_memberships`.`battle_id` IS NULL LIMIT 1 /*application='ShogiWeb'*/
# >>   Swars::Final Load (0.1ms)  SELECT `swars_finals`.* FROM `swars_finals` WHERE `swars_finals`.`id` = 1 ORDER BY `swars_finals`.`position` ASC LIMIT 1 /*application='ShogiWeb'*/
# >>   Swars::Xmode Load (0.1ms)  SELECT `swars_xmodes`.* FROM `swars_xmodes` WHERE `swars_xmodes`.`id` = 1 ORDER BY `swars_xmodes`.`position` ASC LIMIT 1 /*application='ShogiWeb'*/
# >>   Swars::Imode Load (0.1ms)  SELECT `swars_imodes`.* FROM `swars_imodes` WHERE `swars_imodes`.`id` = 1 ORDER BY `swars_imodes`.`position` ASC LIMIT 1 /*application='ShogiWeb'*/
# >>   Swars::Xmode Load (0.1ms)  SELECT `swars_xmodes`.* FROM `swars_xmodes` WHERE `swars_xmodes`.`key` = '指導' ORDER BY `swars_xmodes`.`position` ASC LIMIT 1 /*application='ShogiWeb'*/
# >>   ↳ app/models/application_memory_record.rb:36:in 'ApplicationMemoryRecord#db_record!'
# >>   Swars::Imode Load (0.1ms)  SELECT `swars_imodes`.* FROM `swars_imodes` WHERE `swars_imodes`.`key` = 'sprint' ORDER BY `swars_imodes`.`position` ASC LIMIT 1 /*application='ShogiWeb'*/
# >>   ↳ app/models/application_memory_record.rb:36:in 'ApplicationMemoryRecord#db_record!'
# >>   Swars::Style Load (1.7ms)  SELECT `swars_styles`.* FROM `swars_styles` WHERE `swars_styles`.`key` = '王道' ORDER BY `swars_styles`.`position` ASC LIMIT 1 /*application='ShogiWeb'*/
# >>   ↳ app/models/application_memory_record.rb:36:in 'ApplicationMemoryRecord#db_record!'
# >>   Swars::Style Load (0.4ms)  SELECT `swars_styles`.* FROM `swars_styles` WHERE `swars_styles`.`key` = '準王道' ORDER BY `swars_styles`.`position` ASC LIMIT 1 /*application='ShogiWeb'*/
# >>   ↳ app/models/application_memory_record.rb:36:in 'ApplicationMemoryRecord#db_record!'
# >>   Swars::Battle Create (5.9ms)  INSERT INTO `swars_battles` (`key`, `battled_at`, `csa_seq`, `win_user_id`, `turn_max`, `meta_info`, `created_at`, `updated_at`, `start_turn`, `critical_turn`, `sfen_body`, `image_turn`, `outbreak_turn`, `accessed_at`, `sfen_hash`, `xmode_id`, `preset_id`, `rule_id`, `final_id`, `analysis_version`, `starting_position`, `imode_id`) VALUES ('7d210783be933ac10dc85041e630e2ab', '2025-04-30 12:02:29', '---\n- - \"+7968GI\"\n  - 600\n- - \"-8232HI\"\n  - 600\n- - \"+5756FU\"\n  - 600\n- - \"-3334FU\"\n  - 600\n- - \"+6857GI\"\n  - 600\n', 1055264, 5, '--- {}\n', '2025-04-30 12:02:29', '2025-04-30 12:02:29', NULL, NULL, 'position sfen lnsgkgsnl/1r5b1/ppppppppp/9/9/9/PPPPPPPPP/1B5R1/LNSGKGSNL b - 1 moves 7i6h 8b3b 5g5f 3c3d 6h5g', NULL, NULL, '2025-04-30 12:02:28', '7b7e2206a9d4cdf21d06bc390228ced8', 1, 1, 1, 1, 3, NULL, 1) /*application='ShogiWeb'*/
# >>   Swars::Membership Exists? (0.9ms)  SELECT 1 AS one FROM `swars_memberships` WHERE `swars_memberships`.`location_id` = 1 AND `swars_memberships`.`battle_id` = 59679587 LIMIT 1 /*application='ShogiWeb'*/
# >>   Swars::Membership Exists? (1.2ms)  SELECT 1 AS one FROM `swars_memberships` WHERE `swars_memberships`.`user_id` = 1055264 AND `swars_memberships`.`battle_id` = 59679587 LIMIT 1 /*application='ShogiWeb'*/
# >>   Swars::Membership Exists? (1.0ms)  SELECT 1 AS one FROM `swars_memberships` WHERE `swars_memberships`.`op_user_id` = 1055265 AND `swars_memberships`.`battle_id` = 59679587 LIMIT 1 /*application='ShogiWeb'*/
# >>   Swars::Membership Load (5.4ms)  SELECT `swars_memberships`.* FROM `swars_memberships` WHERE `swars_memberships`.`battle_id` = 59679587 AND (`swars_memberships`.`position` IS NOT NULL) ORDER BY `swars_memberships`.`position` DESC LIMIT 1 /*application='ShogiWeb'*/
# >>   Swars::Membership Create (5.2ms)  INSERT INTO `swars_memberships` (`battle_id`, `user_id`, `grade_id`, `position`, `created_at`, `updated_at`, `grade_diff`, `think_max`, `op_user_id`, `think_last`, `think_all_avg`, `think_end_avg`, `ai_drop_total`, `judge_id`, `location_id`, `style_id`, `ek_score_without_cond`, `ek_score_with_cond`, `ai_wave_count`, `ai_two_freq`, `ai_noizy_two_max`, `ai_gear_freq`, `opponent_id`) VALUES (59679587, 1055264, 39, 0, '2025-04-30 12:02:29', '2025-04-30 12:02:29', 0, 0, 1055265, 0, 0, 0, 0, 1, 1, 1, 0, NULL, 0, 0.0, 0, 0.0, NULL) /*application='ShogiWeb'*/
# >>   Swars::User Update (0.5ms)  UPDATE `swars_users` SET `swars_users`.`latest_battled_at` = '2025-04-30 12:02:29' WHERE `swars_users`.`id` = 1055264 /*application='ShogiWeb'*/
# >>   ↳ app/models/swars/membership.rb:163:in 'block in <class:Membership>'
# >>   Swars::MembershipExtra Create (1.2ms)  INSERT INTO `swars_membership_extras` (`membership_id`, `used_piece_counts`, `created_at`, `updated_at`) VALUES (118847109, '{\"S0\":2,\"P0\":1}', '2025-04-30 12:02:29.659990', '2025-04-30 12:02:29.659990') /*application='ShogiWeb'*/
# >>   ActsAsTaggableOn::Tag Load (3.6ms)  SELECT `tags`.* FROM `tags` INNER JOIN `taggings` ON `tags`.`id` = `taggings`.`tag_id` WHERE `taggings`.`taggable_id` = 118847109 AND `taggings`.`taggable_type` = 'Swars::Membership' AND (taggings.context = 'defense_tags' AND taggings.tagger_id IS NULL) ORDER BY taggings.id /*application='ShogiWeb'*/
# >>   ActsAsTaggableOn::Tag Load (52.9ms)  SELECT `tags`.* FROM `tags` WHERE (LOWER(name) = LOWER('新嬉野流')) /*application='ShogiWeb'*/
# >>   ActsAsTaggableOn::Tag Load (0.5ms)  SELECT `tags`.* FROM `tags` INNER JOIN `taggings` ON `tags`.`id` = `taggings`.`tag_id` WHERE `taggings`.`taggable_id` = 118847109 AND `taggings`.`taggable_type` = 'Swars::Membership' AND (taggings.context = 'attack_tags' AND taggings.tagger_id IS NULL) ORDER BY taggings.id /*application='ShogiWeb'*/
# >>   ActsAsTaggableOn::Tag Load (0.2ms)  SELECT `tags`.* FROM `tags` WHERE `tags`.`id` = 201090 LIMIT 1 /*application='ShogiWeb'*/
# >>   ActsAsTaggableOn::Tagging Exists? (5.8ms)  SELECT 1 AS one FROM `taggings` WHERE `taggings`.`tag_id` = 201090 AND `taggings`.`taggable_type` = 'Swars::Membership' AND `taggings`.`taggable_id` = 118847109 AND `taggings`.`context` = 'attack_tags' AND `taggings`.`tagger_id` IS NULL AND `taggings`.`tagger_type` IS NULL LIMIT 1 /*application='ShogiWeb'*/
# >>   ActsAsTaggableOn::Tagging Create (0.8ms)  INSERT INTO `taggings` (`tag_id`, `taggable_type`, `taggable_id`, `tagger_type`, `tagger_id`, `context`, `created_at`) VALUES (201090, 'Swars::Membership', 118847109, NULL, NULL, 'attack_tags', '2025-04-30 12:02:29') /*application='ShogiWeb'*/
# >>   ActsAsTaggableOn::Tag Update All (0.2ms)  UPDATE `tags` SET `tags`.`taggings_count` = COALESCE(`tags`.`taggings_count`, 0) + 1 WHERE `tags`.`id` = 201090 /*application='ShogiWeb'*/
# >>   ActsAsTaggableOn::Tag Load (0.3ms)  SELECT `tags`.* FROM `tags` INNER JOIN `taggings` ON `tags`.`id` = `taggings`.`tag_id` WHERE `taggings`.`taggable_id` = 118847109 AND `taggings`.`taggable_type` = 'Swars::Membership' AND (taggings.context = 'technique_tags' AND taggings.tagger_id IS NULL) ORDER BY taggings.id /*application='ShogiWeb'*/
# >>   ActsAsTaggableOn::Tag Load (32.3ms)  SELECT `tags`.* FROM `tags` WHERE (LOWER(name) = LOWER('対振り飛車') OR LOWER(name) = LOWER('対抗形')) /*application='ShogiWeb'*/
# >>   ActsAsTaggableOn::Tag Load (0.3ms)  SELECT `tags`.* FROM `tags` INNER JOIN `taggings` ON `tags`.`id` = `taggings`.`tag_id` WHERE `taggings`.`taggable_id` = 118847109 AND `taggings`.`taggable_type` = 'Swars::Membership' AND (taggings.context = 'note_tags' AND taggings.tagger_id IS NULL) ORDER BY taggings.id /*application='ShogiWeb'*/
# >>   ActsAsTaggableOn::Tag Load (0.2ms)  SELECT `tags`.* FROM `tags` WHERE `tags`.`id` = 122779 LIMIT 1 /*application='ShogiWeb'*/
# >>   ActsAsTaggableOn::Tagging Exists? (5.0ms)  SELECT 1 AS one FROM `taggings` WHERE `taggings`.`tag_id` = 122779 AND `taggings`.`taggable_type` = 'Swars::Membership' AND `taggings`.`taggable_id` = 118847109 AND `taggings`.`context` = 'note_tags' AND `taggings`.`tagger_id` IS NULL AND `taggings`.`tagger_type` IS NULL LIMIT 1 /*application='ShogiWeb'*/
# >>   ActsAsTaggableOn::Tagging Create (0.2ms)  INSERT INTO `taggings` (`tag_id`, `taggable_type`, `taggable_id`, `tagger_type`, `tagger_id`, `context`, `created_at`) VALUES (122779, 'Swars::Membership', 118847109, NULL, NULL, 'note_tags', '2025-04-30 12:02:29') /*application='ShogiWeb'*/
# >>   ActsAsTaggableOn::Tag Update All (0.4ms)  UPDATE `tags` SET `tags`.`taggings_count` = COALESCE(`tags`.`taggings_count`, 0) + 1 WHERE `tags`.`id` = 122779 /*application='ShogiWeb'*/
# >>   ActsAsTaggableOn::Tag Load (0.2ms)  SELECT `tags`.* FROM `tags` WHERE `tags`.`id` = 122777 LIMIT 1 /*application='ShogiWeb'*/
# >>   ActsAsTaggableOn::Tagging Exists? (3.9ms)  SELECT 1 AS one FROM `taggings` WHERE `taggings`.`tag_id` = 122777 AND `taggings`.`taggable_type` = 'Swars::Membership' AND `taggings`.`taggable_id` = 118847109 AND `taggings`.`context` = 'note_tags' AND `taggings`.`tagger_id` IS NULL AND `taggings`.`tagger_type` IS NULL LIMIT 1 /*application='ShogiWeb'*/
# >>   ActsAsTaggableOn::Tagging Create (0.2ms)  INSERT INTO `taggings` (`tag_id`, `taggable_type`, `taggable_id`, `tagger_type`, `tagger_id`, `context`, `created_at`) VALUES (122777, 'Swars::Membership', 118847109, NULL, NULL, 'note_tags', '2025-04-30 12:02:29') /*application='ShogiWeb'*/
# >>   ActsAsTaggableOn::Tag Update All (0.2ms)  UPDATE `tags` SET `tags`.`taggings_count` = COALESCE(`tags`.`taggings_count`, 0) + 1 WHERE `tags`.`id` = 122777 /*application='ShogiWeb'*/
# >>   Swars::Membership Exists? (0.2ms)  SELECT 1 AS one FROM `swars_memberships` WHERE `swars_memberships`.`location_id` = 2 AND `swars_memberships`.`battle_id` = 59679587 LIMIT 1 /*application='ShogiWeb'*/
# >>   Swars::Membership Exists? (0.1ms)  SELECT 1 AS one FROM `swars_memberships` WHERE `swars_memberships`.`user_id` = 1055265 AND `swars_memberships`.`battle_id` = 59679587 LIMIT 1 /*application='ShogiWeb'*/
# >>   Swars::Membership Exists? (0.1ms)  SELECT 1 AS one FROM `swars_memberships` WHERE `swars_memberships`.`op_user_id` = 1055264 AND `swars_memberships`.`battle_id` = 59679587 LIMIT 1 /*application='ShogiWeb'*/
# >>   Swars::Membership Load (0.3ms)  SELECT `swars_memberships`.* FROM `swars_memberships` WHERE `swars_memberships`.`battle_id` = 59679587 AND (`swars_memberships`.`position` IS NOT NULL) ORDER BY `swars_memberships`.`position` DESC LIMIT 1 /*application='ShogiWeb'*/
# >>   Swars::Membership Create (2.0ms)  INSERT INTO `swars_memberships` (`battle_id`, `user_id`, `grade_id`, `position`, `created_at`, `updated_at`, `grade_diff`, `think_max`, `op_user_id`, `think_last`, `think_all_avg`, `think_end_avg`, `ai_drop_total`, `judge_id`, `location_id`, `style_id`, `ek_score_without_cond`, `ek_score_with_cond`, `ai_wave_count`, `ai_two_freq`, `ai_noizy_two_max`, `ai_gear_freq`, `opponent_id`) VALUES (59679587, 1055265, 39, 1, '2025-04-30 12:02:29', '2025-04-30 12:02:29', 0, 0, 1055264, 0, 0, 0, 0, 2, 2, 2, 0, NULL, 0, 0.0, 0, 0.0, NULL) /*application='ShogiWeb'*/
# >>   Swars::MembershipExtra Create (0.2ms)  INSERT INTO `swars_membership_extras` (`membership_id`, `used_piece_counts`, `created_at`, `updated_at`) VALUES (118847110, '{\"R0\":1,\"P0\":1}', '2025-04-30 12:02:29.816445', '2025-04-30 12:02:29.816445') /*application='ShogiWeb'*/
# >>   ActsAsTaggableOn::Tag Load (0.3ms)  SELECT `tags`.* FROM `tags` INNER JOIN `taggings` ON `tags`.`id` = `taggings`.`tag_id` WHERE `taggings`.`taggable_id` = 118847110 AND `taggings`.`taggable_type` = 'Swars::Membership' AND (taggings.context = 'defense_tags' AND taggings.tagger_id IS NULL) ORDER BY taggings.id /*application='ShogiWeb'*/
# >>   ActsAsTaggableOn::Tag Load (21.4ms)  SELECT `tags`.* FROM `tags` WHERE (LOWER(name) = LOWER('2手目△3ニ飛戦法')) /*application='ShogiWeb'*/
# >>   ActsAsTaggableOn::Tag Load (0.2ms)  SELECT `tags`.* FROM `tags` INNER JOIN `taggings` ON `tags`.`id` = `taggings`.`tag_id` WHERE `taggings`.`taggable_id` = 118847110 AND `taggings`.`taggable_type` = 'Swars::Membership' AND (taggings.context = 'attack_tags' AND taggings.tagger_id IS NULL) ORDER BY taggings.id /*application='ShogiWeb'*/
# >>   ActsAsTaggableOn::Tag Load (0.1ms)  SELECT `tags`.* FROM `tags` WHERE `tags`.`id` = 201462 LIMIT 1 /*application='ShogiWeb'*/
# >>   ActsAsTaggableOn::Tagging Exists? (7.7ms)  SELECT 1 AS one FROM `taggings` WHERE `taggings`.`tag_id` = 201462 AND `taggings`.`taggable_type` = 'Swars::Membership' AND `taggings`.`taggable_id` = 118847110 AND `taggings`.`context` = 'attack_tags' AND `taggings`.`tagger_id` IS NULL AND `taggings`.`tagger_type` IS NULL LIMIT 1 /*application='ShogiWeb'*/
# >>   ActsAsTaggableOn::Tagging Create (0.2ms)  INSERT INTO `taggings` (`tag_id`, `taggable_type`, `taggable_id`, `tagger_type`, `tagger_id`, `context`, `created_at`) VALUES (201462, 'Swars::Membership', 118847110, NULL, NULL, 'attack_tags', '2025-04-30 12:02:29') /*application='ShogiWeb'*/
# >>   ActsAsTaggableOn::Tag Update All (0.2ms)  UPDATE `tags` SET `tags`.`taggings_count` = COALESCE(`tags`.`taggings_count`, 0) + 1 WHERE `tags`.`id` = 201462 /*application='ShogiWeb'*/
# >>   ActsAsTaggableOn::Tag Load (0.3ms)  SELECT `tags`.* FROM `tags` INNER JOIN `taggings` ON `tags`.`id` = `taggings`.`tag_id` WHERE `taggings`.`taggable_id` = 118847110 AND `taggings`.`taggable_type` = 'Swars::Membership' AND (taggings.context = 'technique_tags' AND taggings.tagger_id IS NULL) ORDER BY taggings.id /*application='ShogiWeb'*/
# >>   ActsAsTaggableOn::Tag Load (25.5ms)  SELECT `tags`.* FROM `tags` WHERE (LOWER(name) = LOWER('振り飛車') OR LOWER(name) = LOWER('対抗形')) /*application='ShogiWeb'*/
# >>   ActsAsTaggableOn::Tag Load (0.2ms)  SELECT `tags`.* FROM `tags` INNER JOIN `taggings` ON `tags`.`id` = `taggings`.`tag_id` WHERE `taggings`.`taggable_id` = 118847110 AND `taggings`.`taggable_type` = 'Swars::Membership' AND (taggings.context = 'note_tags' AND taggings.tagger_id IS NULL) ORDER BY taggings.id /*application='ShogiWeb'*/
# >>   ActsAsTaggableOn::Tag Load (0.1ms)  SELECT `tags`.* FROM `tags` WHERE `tags`.`id` = 122776 LIMIT 1 /*application='ShogiWeb'*/
# >>   ActsAsTaggableOn::Tagging Exists? (3.1ms)  SELECT 1 AS one FROM `taggings` WHERE `taggings`.`tag_id` = 122776 AND `taggings`.`taggable_type` = 'Swars::Membership' AND `taggings`.`taggable_id` = 118847110 AND `taggings`.`context` = 'note_tags' AND `taggings`.`tagger_id` IS NULL AND `taggings`.`tagger_type` IS NULL LIMIT 1 /*application='ShogiWeb'*/
# >>   ActsAsTaggableOn::Tagging Create (0.2ms)  INSERT INTO `taggings` (`tag_id`, `taggable_type`, `taggable_id`, `tagger_type`, `tagger_id`, `context`, `created_at`) VALUES (122776, 'Swars::Membership', 118847110, NULL, NULL, 'note_tags', '2025-04-30 12:02:29') /*application='ShogiWeb'*/
# >>   ActsAsTaggableOn::Tag Update All (0.2ms)  UPDATE `tags` SET `tags`.`taggings_count` = COALESCE(`tags`.`taggings_count`, 0) + 1 WHERE `tags`.`id` = 122776 /*application='ShogiWeb'*/
# >>   ActsAsTaggableOn::Tag Load (0.1ms)  SELECT `tags`.* FROM `tags` WHERE `tags`.`id` = 122777 LIMIT 1 /*application='ShogiWeb'*/
# >>   ActsAsTaggableOn::Tagging Exists? (1.1ms)  SELECT 1 AS one FROM `taggings` WHERE `taggings`.`tag_id` = 122777 AND `taggings`.`taggable_type` = 'Swars::Membership' AND `taggings`.`taggable_id` = 118847110 AND `taggings`.`context` = 'note_tags' AND `taggings`.`tagger_id` IS NULL AND `taggings`.`tagger_type` IS NULL LIMIT 1 /*application='ShogiWeb'*/
# >>   ActsAsTaggableOn::Tagging Create (0.3ms)  INSERT INTO `taggings` (`tag_id`, `taggable_type`, `taggable_id`, `tagger_type`, `tagger_id`, `context`, `created_at`) VALUES (122777, 'Swars::Membership', 118847110, NULL, NULL, 'note_tags', '2025-04-30 12:02:29') /*application='ShogiWeb'*/
# >>   ActsAsTaggableOn::Tag Update All (0.3ms)  UPDATE `tags` SET `tags`.`taggings_count` = COALESCE(`tags`.`taggings_count`, 0) + 1 WHERE `tags`.`id` = 122777 /*application='ShogiWeb'*/
# >>   Swars::Membership Update (0.9ms)  UPDATE `swars_memberships` SET `swars_memberships`.`opponent_id` = 118847110 WHERE `swars_memberships`.`id` = 118847109 /*application='ShogiWeb'*/
# >>   ↳ app/models/swars/battle/basic_methods.rb:104:in 'block (3 levels) in <class:Battle>'
# >>   Swars::Membership Update (0.2ms)  UPDATE `swars_memberships` SET `swars_memberships`.`opponent_id` = 118847109 WHERE `swars_memberships`.`id` = 118847110 /*application='ShogiWeb'*/
# >>   ↳ app/models/swars/battle/basic_methods.rb:105:in 'block (3 levels) in <class:Battle>'
# >>   ActsAsTaggableOn::Tagging Load (1.4ms)  SELECT `taggings`.* FROM `taggings` WHERE `taggings`.`taggable_id` = 59679587 AND `taggings`.`taggable_type` = 'Swars::Battle' /*application='ShogiWeb'*/
# >>   TRANSACTION (0.6ms)  COMMIT /*application='ShogiWeb'*/
# >>   TRANSACTION (0.2ms)  BEGIN /*application='ShogiWeb'*/
# >>   ↳ app/models/application_memory_record.rb:36:in 'ApplicationMemoryRecord#db_record!'
# >>   Preset Load (1.8ms)  SELECT `presets`.* FROM `presets` WHERE `presets`.`key` = '平手' ORDER BY `presets`.`position` ASC LIMIT 1 /*application='ShogiWeb'*/
# >>   ↳ app/models/application_memory_record.rb:36:in 'ApplicationMemoryRecord#db_record!'
# >>   Swars::Rule Load (0.2ms)  SELECT `swars_rules`.* FROM `swars_rules` WHERE `swars_rules`.`key` = 'ten_min' ORDER BY `swars_rules`.`position` ASC LIMIT 1 /*application='ShogiWeb'*/
# >>   ↳ app/models/application_memory_record.rb:36:in 'ApplicationMemoryRecord#db_record!'
# >>   Swars::Final Load (0.2ms)  SELECT `swars_finals`.* FROM `swars_finals` WHERE `swars_finals`.`key` = 'TORYO' ORDER BY `swars_finals`.`position` ASC LIMIT 1 /*application='ShogiWeb'*/
# >>   ↳ app/models/application_memory_record.rb:36:in 'ApplicationMemoryRecord#db_record!'
# >>   Swars::Xmode Load (0.2ms)  SELECT `swars_xmodes`.* FROM `swars_xmodes` WHERE `swars_xmodes`.`key` = '野良' ORDER BY `swars_xmodes`.`position` ASC LIMIT 1 /*application='ShogiWeb'*/
# >>   ↳ app/models/application_memory_record.rb:36:in 'ApplicationMemoryRecord#db_record!'
# >>   Swars::Rule Load (0.1ms)  SELECT `swars_rules`.* FROM `swars_rules` WHERE `swars_rules`.`id` = 1 ORDER BY `swars_rules`.`position` ASC LIMIT 1 /*application='ShogiWeb'*/
# >>   ↳ app/models/application_record.rb:91:in 'Kernel#public_send'
# >>   Swars::Grade Load (0.2ms)  SELECT `swars_grades`.* FROM `swars_grades` WHERE `swars_grades`.`key` = '30級' ORDER BY `swars_grades`.`priority` ASC LIMIT 1 /*application='ShogiWeb'*/
# >>   ↳ app/models/application_memory_record.rb:36:in 'ApplicationMemoryRecord#db_record!'
# >>   Swars::Grade Count (0.1ms)  SELECT COUNT(*) FROM `swars_grades` /*application='ShogiWeb'*/
# >>   ↳ app/models/swars/user/grade_methods.rb:11:in 'block (3 levels) in <class:User>'
# >>   Swars::User Count (100.4ms)  SELECT COUNT(*) FROM `swars_users` /*application='ShogiWeb'*/
# >>   ↳ app/models/swars/user.rb:69:in 'block in <class:User>'
# >>   Swars::Grade Load (0.2ms)  SELECT `swars_grades`.* FROM `swars_grades` WHERE `swars_grades`.`id` = 39 ORDER BY `swars_grades`.`priority` ASC LIMIT 1 /*application='ShogiWeb'*/
# >>   ↳ app/models/swars/battle/basic_methods.rb:67:in 'block (4 levels) in <class:Battle>'
# >>   Swars::User Create (0.3ms)  INSERT INTO `swars_users` (`user_key`, `grade_id`, `last_reception_at`, `search_logs_count`, `created_at`, `updated_at`, `ban_at`, `latest_battled_at`, `soft_crawled_at`, `hard_crawled_at`) VALUES ('user1055207', 39, NULL, 0, '2025-04-30 12:02:30', '2025-04-30 12:02:30', NULL, '2025-04-30 12:02:30', '2025-04-30 12:02:30', '2025-04-30 12:02:30') /*application='ShogiWeb'*/
# >>   ↳ app/models/swars/battle/basic_methods.rb:67:in 'block (4 levels) in <class:Battle>'
# >>   Swars::Profile Create (0.2ms)  INSERT INTO `swars_profiles` (`user_id`, `ban_at`, `ban_crawled_at`, `ban_crawled_count`, `created_at`, `updated_at`) VALUES (1055266, NULL, '2025-04-30 12:02:30', 0, '2025-04-30 12:02:30', '2025-04-30 12:02:30') /*application='ShogiWeb'*/
# >>   ↳ app/models/swars/battle/basic_methods.rb:67:in 'block (4 levels) in <class:Battle>'
# >>   Swars::Imode Load (0.2ms)  SELECT `swars_imodes`.* FROM `swars_imodes` WHERE `swars_imodes`.`key` = 'normal' ORDER BY `swars_imodes`.`position` ASC LIMIT 1 /*application='ShogiWeb'*/
# >>   ↳ app/models/application_memory_record.rb:36:in 'ApplicationMemoryRecord#db_record!'
# >>   Preset Load (0.2ms)  SELECT `presets`.* FROM `presets` WHERE `presets`.`id` = 1 ORDER BY `presets`.`position` ASC LIMIT 1 /*application='ShogiWeb'*/
# >>   Location Load (0.2ms)  SELECT `locations`.* FROM `locations` WHERE `locations`.`key` = 'black' ORDER BY `locations`.`position` ASC LIMIT 1 /*application='ShogiWeb'*/
# >>   ↳ app/models/concerns/memory_record_bind.rb:77:in 'MemoryRecordBind::Base::ClassMethods#lookup'
# >>   Judge Load (0.1ms)  SELECT `judges`.* FROM `judges` WHERE `judges`.`key` = 'win' ORDER BY `judges`.`position` ASC LIMIT 1 /*application='ShogiWeb'*/
# >>   ↳ app/models/concerns/memory_record_bind.rb:77:in 'MemoryRecordBind::Base::ClassMethods#lookup'
# >>   Swars::Membership Exists? (0.1ms)  SELECT 1 AS one FROM `swars_memberships` WHERE `swars_memberships`.`location_id` = 1 AND `swars_memberships`.`battle_id` IS NULL LIMIT 1 /*application='ShogiWeb'*/
# >>   Swars::Membership Exists? (0.1ms)  SELECT 1 AS one FROM `swars_memberships` WHERE `swars_memberships`.`user_id` = 1055264 AND `swars_memberships`.`battle_id` IS NULL LIMIT 1 /*application='ShogiWeb'*/
# >>   Swars::Membership Exists? (0.1ms)  SELECT 1 AS one FROM `swars_memberships` WHERE `swars_memberships`.`op_user_id` = 1055266 AND `swars_memberships`.`battle_id` IS NULL LIMIT 1 /*application='ShogiWeb'*/
# >>   Location Load (0.1ms)  SELECT `locations`.* FROM `locations` WHERE `locations`.`key` = 'white' ORDER BY `locations`.`position` ASC LIMIT 1 /*application='ShogiWeb'*/
# >>   ↳ app/models/concerns/memory_record_bind.rb:77:in 'MemoryRecordBind::Base::ClassMethods#lookup'
# >>   Judge Load (0.1ms)  SELECT `judges`.* FROM `judges` WHERE `judges`.`key` = 'lose' ORDER BY `judges`.`position` ASC LIMIT 1 /*application='ShogiWeb'*/
# >>   ↳ app/models/concerns/memory_record_bind.rb:77:in 'MemoryRecordBind::Base::ClassMethods#lookup'
# >>   Swars::Membership Exists? (0.1ms)  SELECT 1 AS one FROM `swars_memberships` WHERE `swars_memberships`.`location_id` = 2 AND `swars_memberships`.`battle_id` IS NULL LIMIT 1 /*application='ShogiWeb'*/
# >>   Swars::Membership Exists? (0.1ms)  SELECT 1 AS one FROM `swars_memberships` WHERE `swars_memberships`.`user_id` = 1055266 AND `swars_memberships`.`battle_id` IS NULL LIMIT 1 /*application='ShogiWeb'*/
# >>   Swars::Membership Exists? (0.1ms)  SELECT 1 AS one FROM `swars_memberships` WHERE `swars_memberships`.`op_user_id` = 1055264 AND `swars_memberships`.`battle_id` IS NULL LIMIT 1 /*application='ShogiWeb'*/
# >>   Swars::Final Load (0.1ms)  SELECT `swars_finals`.* FROM `swars_finals` WHERE `swars_finals`.`id` = 1 ORDER BY `swars_finals`.`position` ASC LIMIT 1 /*application='ShogiWeb'*/
# >>   Swars::Xmode Load (0.1ms)  SELECT `swars_xmodes`.* FROM `swars_xmodes` WHERE `swars_xmodes`.`id` = 1 ORDER BY `swars_xmodes`.`position` ASC LIMIT 1 /*application='ShogiWeb'*/
# >>   Swars::Imode Load (0.2ms)  SELECT `swars_imodes`.* FROM `swars_imodes` WHERE `swars_imodes`.`id` = 1 ORDER BY `swars_imodes`.`position` ASC LIMIT 1 /*application='ShogiWeb'*/
# >>   Swars::Xmode Load (0.2ms)  SELECT `swars_xmodes`.* FROM `swars_xmodes` WHERE `swars_xmodes`.`key` = '指導' ORDER BY `swars_xmodes`.`position` ASC LIMIT 1 /*application='ShogiWeb'*/
# >>   ↳ app/models/application_memory_record.rb:36:in 'ApplicationMemoryRecord#db_record!'
# >>   Swars::Imode Load (0.2ms)  SELECT `swars_imodes`.* FROM `swars_imodes` WHERE `swars_imodes`.`key` = 'sprint' ORDER BY `swars_imodes`.`position` ASC LIMIT 1 /*application='ShogiWeb'*/
# >>   ↳ app/models/application_memory_record.rb:36:in 'ApplicationMemoryRecord#db_record!'
# >>   Swars::Style Load (0.2ms)  SELECT `swars_styles`.* FROM `swars_styles` WHERE `swars_styles`.`key` = '王道' ORDER BY `swars_styles`.`position` ASC LIMIT 1 /*application='ShogiWeb'*/
# >>   ↳ app/models/application_memory_record.rb:36:in 'ApplicationMemoryRecord#db_record!'
# >>   Swars::Style Load (0.1ms)  SELECT `swars_styles`.* FROM `swars_styles` WHERE `swars_styles`.`key` = '準王道' ORDER BY `swars_styles`.`position` ASC LIMIT 1 /*application='ShogiWeb'*/
# >>   ↳ app/models/application_memory_record.rb:36:in 'ApplicationMemoryRecord#db_record!'
# >>   Swars::Battle Create (0.6ms)  INSERT INTO `swars_battles` (`key`, `battled_at`, `csa_seq`, `win_user_id`, `turn_max`, `meta_info`, `created_at`, `updated_at`, `start_turn`, `critical_turn`, `sfen_body`, `image_turn`, `outbreak_turn`, `accessed_at`, `sfen_hash`, `xmode_id`, `preset_id`, `rule_id`, `final_id`, `analysis_version`, `starting_position`, `imode_id`) VALUES ('449bb77ce2676e2449eb0e0085beb897', '2025-04-30 12:02:30', '---\n- - \"+7968GI\"\n  - 600\n- - \"-8232HI\"\n  - 600\n- - \"+5756FU\"\n  - 600\n- - \"-3334FU\"\n  - 600\n- - \"+6857GI\"\n  - 600\n', 1055264, 5, '--- {}\n', '2025-04-30 12:02:30', '2025-04-30 12:02:30', NULL, NULL, 'position sfen lnsgkgsnl/1r5b1/ppppppppp/9/9/9/PPPPPPPPP/1B5R1/LNSGKGSNL b - 1 moves 7i6h 8b3b 5g5f 3c3d 6h5g', NULL, NULL, '2025-04-30 12:02:29', '7b7e2206a9d4cdf21d06bc390228ced8', 1, 1, 1, 1, 3, NULL, 1) /*application='ShogiWeb'*/
# >>   Swars::Membership Exists? (0.2ms)  SELECT 1 AS one FROM `swars_memberships` WHERE `swars_memberships`.`location_id` = 1 AND `swars_memberships`.`battle_id` = 59679588 LIMIT 1 /*application='ShogiWeb'*/
# >>   Swars::Membership Exists? (0.1ms)  SELECT 1 AS one FROM `swars_memberships` WHERE `swars_memberships`.`user_id` = 1055264 AND `swars_memberships`.`battle_id` = 59679588 LIMIT 1 /*application='ShogiWeb'*/
# >>   Swars::Membership Exists? (0.1ms)  SELECT 1 AS one FROM `swars_memberships` WHERE `swars_memberships`.`op_user_id` = 1055266 AND `swars_memberships`.`battle_id` = 59679588 LIMIT 1 /*application='ShogiWeb'*/
# >>   Swars::Membership Load (0.3ms)  SELECT `swars_memberships`.* FROM `swars_memberships` WHERE `swars_memberships`.`battle_id` = 59679588 AND (`swars_memberships`.`position` IS NOT NULL) ORDER BY `swars_memberships`.`position` DESC LIMIT 1 /*application='ShogiWeb'*/
# >>   Swars::Membership Create (0.3ms)  INSERT INTO `swars_memberships` (`battle_id`, `user_id`, `grade_id`, `position`, `created_at`, `updated_at`, `grade_diff`, `think_max`, `op_user_id`, `think_last`, `think_all_avg`, `think_end_avg`, `ai_drop_total`, `judge_id`, `location_id`, `style_id`, `ek_score_without_cond`, `ek_score_with_cond`, `ai_wave_count`, `ai_two_freq`, `ai_noizy_two_max`, `ai_gear_freq`, `opponent_id`) VALUES (59679588, 1055264, 39, 0, '2025-04-30 12:02:30', '2025-04-30 12:02:30', 0, 0, 1055266, 0, 0, 0, 0, 1, 1, 1, 0, NULL, 0, 0.0, 0, 0.0, NULL) /*application='ShogiWeb'*/
# >>   Swars::User Update (0.2ms)  UPDATE `swars_users` SET `swars_users`.`latest_battled_at` = '2025-04-30 12:02:30' WHERE `swars_users`.`id` = 1055264 /*application='ShogiWeb'*/
# >>   ↳ app/models/swars/membership.rb:163:in 'block in <class:Membership>'
# >>   Swars::MembershipExtra Create (0.2ms)  INSERT INTO `swars_membership_extras` (`membership_id`, `used_piece_counts`, `created_at`, `updated_at`) VALUES (118847111, '{\"S0\":2,\"P0\":1}', '2025-04-30 12:02:30.078550', '2025-04-30 12:02:30.078550') /*application='ShogiWeb'*/
# >>   ActsAsTaggableOn::Tag Load (0.3ms)  SELECT `tags`.* FROM `tags` INNER JOIN `taggings` ON `tags`.`id` = `taggings`.`tag_id` WHERE `taggings`.`taggable_id` = 118847111 AND `taggings`.`taggable_type` = 'Swars::Membership' AND (taggings.context = 'defense_tags' AND taggings.tagger_id IS NULL) ORDER BY taggings.id /*application='ShogiWeb'*/
# >>   ActsAsTaggableOn::Tag Load (18.9ms)  SELECT `tags`.* FROM `tags` WHERE (LOWER(name) = LOWER('新嬉野流')) /*application='ShogiWeb'*/
# >>   ActsAsTaggableOn::Tag Load (0.3ms)  SELECT `tags`.* FROM `tags` INNER JOIN `taggings` ON `tags`.`id` = `taggings`.`tag_id` WHERE `taggings`.`taggable_id` = 118847111 AND `taggings`.`taggable_type` = 'Swars::Membership' AND (taggings.context = 'attack_tags' AND taggings.tagger_id IS NULL) ORDER BY taggings.id /*application='ShogiWeb'*/
# >>   ActsAsTaggableOn::Tag Load (0.1ms)  SELECT `tags`.* FROM `tags` WHERE `tags`.`id` = 201090 LIMIT 1 /*application='ShogiWeb'*/
# >>   ActsAsTaggableOn::Tagging Exists? (0.3ms)  SELECT 1 AS one FROM `taggings` WHERE `taggings`.`tag_id` = 201090 AND `taggings`.`taggable_type` = 'Swars::Membership' AND `taggings`.`taggable_id` = 118847111 AND `taggings`.`context` = 'attack_tags' AND `taggings`.`tagger_id` IS NULL AND `taggings`.`tagger_type` IS NULL LIMIT 1 /*application='ShogiWeb'*/
# >>   ActsAsTaggableOn::Tagging Create (0.2ms)  INSERT INTO `taggings` (`tag_id`, `taggable_type`, `taggable_id`, `tagger_type`, `tagger_id`, `context`, `created_at`) VALUES (201090, 'Swars::Membership', 118847111, NULL, NULL, 'attack_tags', '2025-04-30 12:02:30') /*application='ShogiWeb'*/
# >>   ActsAsTaggableOn::Tag Update All (0.1ms)  UPDATE `tags` SET `tags`.`taggings_count` = COALESCE(`tags`.`taggings_count`, 0) + 1 WHERE `tags`.`id` = 201090 /*application='ShogiWeb'*/
# >>   ActsAsTaggableOn::Tag Load (0.2ms)  SELECT `tags`.* FROM `tags` INNER JOIN `taggings` ON `tags`.`id` = `taggings`.`tag_id` WHERE `taggings`.`taggable_id` = 118847111 AND `taggings`.`taggable_type` = 'Swars::Membership' AND (taggings.context = 'technique_tags' AND taggings.tagger_id IS NULL) ORDER BY taggings.id /*application='ShogiWeb'*/
# >>   ActsAsTaggableOn::Tag Load (25.5ms)  SELECT `tags`.* FROM `tags` WHERE (LOWER(name) = LOWER('対振り飛車') OR LOWER(name) = LOWER('対抗形')) /*application='ShogiWeb'*/
# >>   ActsAsTaggableOn::Tag Load (0.3ms)  SELECT `tags`.* FROM `tags` INNER JOIN `taggings` ON `tags`.`id` = `taggings`.`tag_id` WHERE `taggings`.`taggable_id` = 118847111 AND `taggings`.`taggable_type` = 'Swars::Membership' AND (taggings.context = 'note_tags' AND taggings.tagger_id IS NULL) ORDER BY taggings.id /*application='ShogiWeb'*/
# >>   ActsAsTaggableOn::Tag Load (0.2ms)  SELECT `tags`.* FROM `tags` WHERE `tags`.`id` = 122779 LIMIT 1 /*application='ShogiWeb'*/
# >>   ActsAsTaggableOn::Tagging Exists? (0.3ms)  SELECT 1 AS one FROM `taggings` WHERE `taggings`.`tag_id` = 122779 AND `taggings`.`taggable_type` = 'Swars::Membership' AND `taggings`.`taggable_id` = 118847111 AND `taggings`.`context` = 'note_tags' AND `taggings`.`tagger_id` IS NULL AND `taggings`.`tagger_type` IS NULL LIMIT 1 /*application='ShogiWeb'*/
# >>   ActsAsTaggableOn::Tagging Create (0.2ms)  INSERT INTO `taggings` (`tag_id`, `taggable_type`, `taggable_id`, `tagger_type`, `tagger_id`, `context`, `created_at`) VALUES (122779, 'Swars::Membership', 118847111, NULL, NULL, 'note_tags', '2025-04-30 12:02:30') /*application='ShogiWeb'*/
# >>   ActsAsTaggableOn::Tag Update All (0.2ms)  UPDATE `tags` SET `tags`.`taggings_count` = COALESCE(`tags`.`taggings_count`, 0) + 1 WHERE `tags`.`id` = 122779 /*application='ShogiWeb'*/
# >>   ActsAsTaggableOn::Tag Load (0.1ms)  SELECT `tags`.* FROM `tags` WHERE `tags`.`id` = 122777 LIMIT 1 /*application='ShogiWeb'*/
# >>   ActsAsTaggableOn::Tagging Exists? (0.3ms)  SELECT 1 AS one FROM `taggings` WHERE `taggings`.`tag_id` = 122777 AND `taggings`.`taggable_type` = 'Swars::Membership' AND `taggings`.`taggable_id` = 118847111 AND `taggings`.`context` = 'note_tags' AND `taggings`.`tagger_id` IS NULL AND `taggings`.`tagger_type` IS NULL LIMIT 1 /*application='ShogiWeb'*/
# >>   ActsAsTaggableOn::Tagging Create (0.2ms)  INSERT INTO `taggings` (`tag_id`, `taggable_type`, `taggable_id`, `tagger_type`, `tagger_id`, `context`, `created_at`) VALUES (122777, 'Swars::Membership', 118847111, NULL, NULL, 'note_tags', '2025-04-30 12:02:30') /*application='ShogiWeb'*/
# >>   ActsAsTaggableOn::Tag Update All (0.2ms)  UPDATE `tags` SET `tags`.`taggings_count` = COALESCE(`tags`.`taggings_count`, 0) + 1 WHERE `tags`.`id` = 122777 /*application='ShogiWeb'*/
# >>   Swars::Membership Exists? (0.1ms)  SELECT 1 AS one FROM `swars_memberships` WHERE `swars_memberships`.`location_id` = 2 AND `swars_memberships`.`battle_id` = 59679588 LIMIT 1 /*application='ShogiWeb'*/
# >>   Swars::Membership Exists? (0.1ms)  SELECT 1 AS one FROM `swars_memberships` WHERE `swars_memberships`.`user_id` = 1055266 AND `swars_memberships`.`battle_id` = 59679588 LIMIT 1 /*application='ShogiWeb'*/
# >>   Swars::Membership Exists? (0.1ms)  SELECT 1 AS one FROM `swars_memberships` WHERE `swars_memberships`.`op_user_id` = 1055264 AND `swars_memberships`.`battle_id` = 59679588 LIMIT 1 /*application='ShogiWeb'*/
# >>   Swars::Membership Load (0.2ms)  SELECT `swars_memberships`.* FROM `swars_memberships` WHERE `swars_memberships`.`battle_id` = 59679588 AND (`swars_memberships`.`position` IS NOT NULL) ORDER BY `swars_memberships`.`position` DESC LIMIT 1 /*application='ShogiWeb'*/
# >>   Swars::Membership Create (0.2ms)  INSERT INTO `swars_memberships` (`battle_id`, `user_id`, `grade_id`, `position`, `created_at`, `updated_at`, `grade_diff`, `think_max`, `op_user_id`, `think_last`, `think_all_avg`, `think_end_avg`, `ai_drop_total`, `judge_id`, `location_id`, `style_id`, `ek_score_without_cond`, `ek_score_with_cond`, `ai_wave_count`, `ai_two_freq`, `ai_noizy_two_max`, `ai_gear_freq`, `opponent_id`) VALUES (59679588, 1055266, 39, 1, '2025-04-30 12:02:30', '2025-04-30 12:02:30', 0, 0, 1055264, 0, 0, 0, 0, 2, 2, 2, 0, NULL, 0, 0.0, 0, 0.0, NULL) /*application='ShogiWeb'*/
# >>   Swars::MembershipExtra Create (0.2ms)  INSERT INTO `swars_membership_extras` (`membership_id`, `used_piece_counts`, `created_at`, `updated_at`) VALUES (118847112, '{\"R0\":1,\"P0\":1}', '2025-04-30 12:02:30.152061', '2025-04-30 12:02:30.152061') /*application='ShogiWeb'*/
# >>   ActsAsTaggableOn::Tag Load (0.2ms)  SELECT `tags`.* FROM `tags` INNER JOIN `taggings` ON `tags`.`id` = `taggings`.`tag_id` WHERE `taggings`.`taggable_id` = 118847112 AND `taggings`.`taggable_type` = 'Swars::Membership' AND (taggings.context = 'defense_tags' AND taggings.tagger_id IS NULL) ORDER BY taggings.id /*application='ShogiWeb'*/
# >>   ActsAsTaggableOn::Tag Load (19.1ms)  SELECT `tags`.* FROM `tags` WHERE (LOWER(name) = LOWER('2手目△3ニ飛戦法')) /*application='ShogiWeb'*/
# >>   ActsAsTaggableOn::Tag Load (0.2ms)  SELECT `tags`.* FROM `tags` INNER JOIN `taggings` ON `tags`.`id` = `taggings`.`tag_id` WHERE `taggings`.`taggable_id` = 118847112 AND `taggings`.`taggable_type` = 'Swars::Membership' AND (taggings.context = 'attack_tags' AND taggings.tagger_id IS NULL) ORDER BY taggings.id /*application='ShogiWeb'*/
# >>   ActsAsTaggableOn::Tag Load (0.1ms)  SELECT `tags`.* FROM `tags` WHERE `tags`.`id` = 201462 LIMIT 1 /*application='ShogiWeb'*/
# >>   ActsAsTaggableOn::Tagging Exists? (0.3ms)  SELECT 1 AS one FROM `taggings` WHERE `taggings`.`tag_id` = 201462 AND `taggings`.`taggable_type` = 'Swars::Membership' AND `taggings`.`taggable_id` = 118847112 AND `taggings`.`context` = 'attack_tags' AND `taggings`.`tagger_id` IS NULL AND `taggings`.`tagger_type` IS NULL LIMIT 1 /*application='ShogiWeb'*/
# >>   ActsAsTaggableOn::Tagging Create (0.2ms)  INSERT INTO `taggings` (`tag_id`, `taggable_type`, `taggable_id`, `tagger_type`, `tagger_id`, `context`, `created_at`) VALUES (201462, 'Swars::Membership', 118847112, NULL, NULL, 'attack_tags', '2025-04-30 12:02:30') /*application='ShogiWeb'*/
# >>   ActsAsTaggableOn::Tag Update All (0.2ms)  UPDATE `tags` SET `tags`.`taggings_count` = COALESCE(`tags`.`taggings_count`, 0) + 1 WHERE `tags`.`id` = 201462 /*application='ShogiWeb'*/
# >>   ActsAsTaggableOn::Tag Load (0.3ms)  SELECT `tags`.* FROM `tags` INNER JOIN `taggings` ON `tags`.`id` = `taggings`.`tag_id` WHERE `taggings`.`taggable_id` = 118847112 AND `taggings`.`taggable_type` = 'Swars::Membership' AND (taggings.context = 'technique_tags' AND taggings.tagger_id IS NULL) ORDER BY taggings.id /*application='ShogiWeb'*/
# >>   ActsAsTaggableOn::Tag Load (25.1ms)  SELECT `tags`.* FROM `tags` WHERE (LOWER(name) = LOWER('振り飛車') OR LOWER(name) = LOWER('対抗形')) /*application='ShogiWeb'*/
# >>   ActsAsTaggableOn::Tag Load (0.2ms)  SELECT `tags`.* FROM `tags` INNER JOIN `taggings` ON `tags`.`id` = `taggings`.`tag_id` WHERE `taggings`.`taggable_id` = 118847112 AND `taggings`.`taggable_type` = 'Swars::Membership' AND (taggings.context = 'note_tags' AND taggings.tagger_id IS NULL) ORDER BY taggings.id /*application='ShogiWeb'*/
# >>   ActsAsTaggableOn::Tag Load (0.2ms)  SELECT `tags`.* FROM `tags` WHERE `tags`.`id` = 122776 LIMIT 1 /*application='ShogiWeb'*/
# >>   ActsAsTaggableOn::Tagging Exists? (0.3ms)  SELECT 1 AS one FROM `taggings` WHERE `taggings`.`tag_id` = 122776 AND `taggings`.`taggable_type` = 'Swars::Membership' AND `taggings`.`taggable_id` = 118847112 AND `taggings`.`context` = 'note_tags' AND `taggings`.`tagger_id` IS NULL AND `taggings`.`tagger_type` IS NULL LIMIT 1 /*application='ShogiWeb'*/
# >>   ActsAsTaggableOn::Tagging Create (0.2ms)  INSERT INTO `taggings` (`tag_id`, `taggable_type`, `taggable_id`, `tagger_type`, `tagger_id`, `context`, `created_at`) VALUES (122776, 'Swars::Membership', 118847112, NULL, NULL, 'note_tags', '2025-04-30 12:02:30') /*application='ShogiWeb'*/
# >>   ActsAsTaggableOn::Tag Update All (0.2ms)  UPDATE `tags` SET `tags`.`taggings_count` = COALESCE(`tags`.`taggings_count`, 0) + 1 WHERE `tags`.`id` = 122776 /*application='ShogiWeb'*/
# >>   ActsAsTaggableOn::Tag Load (0.1ms)  SELECT `tags`.* FROM `tags` WHERE `tags`.`id` = 122777 LIMIT 1 /*application='ShogiWeb'*/
# >>   ActsAsTaggableOn::Tagging Exists? (0.3ms)  SELECT 1 AS one FROM `taggings` WHERE `taggings`.`tag_id` = 122777 AND `taggings`.`taggable_type` = 'Swars::Membership' AND `taggings`.`taggable_id` = 118847112 AND `taggings`.`context` = 'note_tags' AND `taggings`.`tagger_id` IS NULL AND `taggings`.`tagger_type` IS NULL LIMIT 1 /*application='ShogiWeb'*/
# >>   ActsAsTaggableOn::Tagging Create (0.2ms)  INSERT INTO `taggings` (`tag_id`, `taggable_type`, `taggable_id`, `tagger_type`, `tagger_id`, `context`, `created_at`) VALUES (122777, 'Swars::Membership', 118847112, NULL, NULL, 'note_tags', '2025-04-30 12:02:30') /*application='ShogiWeb'*/
# >>   ActsAsTaggableOn::Tag Update All (0.2ms)  UPDATE `tags` SET `tags`.`taggings_count` = COALESCE(`tags`.`taggings_count`, 0) + 1 WHERE `tags`.`id` = 122777 /*application='ShogiWeb'*/
# >>   Swars::Membership Update (0.2ms)  UPDATE `swars_memberships` SET `swars_memberships`.`opponent_id` = 118847112 WHERE `swars_memberships`.`id` = 118847111 /*application='ShogiWeb'*/
# >>   ↳ app/models/swars/battle/basic_methods.rb:104:in 'block (3 levels) in <class:Battle>'
# >>   Swars::Membership Update (0.2ms)  UPDATE `swars_memberships` SET `swars_memberships`.`opponent_id` = 118847111 WHERE `swars_memberships`.`id` = 118847112 /*application='ShogiWeb'*/
# >>   ↳ app/models/swars/battle/basic_methods.rb:105:in 'block (3 levels) in <class:Battle>'
# >>   ActsAsTaggableOn::Tagging Load (0.2ms)  SELECT `taggings`.* FROM `taggings` WHERE `taggings`.`taggable_id` = 59679588 AND `taggings`.`taggable_type` = 'Swars::Battle' /*application='ShogiWeb'*/
# >>   TRANSACTION (0.5ms)  COMMIT /*application='ShogiWeb'*/
# >>   Swars::User Pluck (0.3ms)  SELECT DISTINCT `swars_users`.`user_key` FROM `swars_users` LEFT OUTER JOIN `swars_grades` ON `swars_grades`.`id` = `swars_users`.`grade_id` LEFT OUTER JOIN `swars_memberships` ON `swars_memberships`.`user_id` = `swars_users`.`id` WHERE `swars_users`.`user_key` = '562517b7a6bd786135e3970f355615e9' /*application='ShogiWeb'*/
# >>   ↳ app/models/quick_script/swars/user_group_script.rb:238:in 'QuickScript::Swars::UserGroupScript#db_exist_user_keys'
# >>   Swars::User Load (0.2ms)  SELECT `swars_users`.* FROM `swars_users` WHERE `swars_users`.`user_key` = '562517b7a6bd786135e3970f355615e9' ORDER BY FIELD(swars_users.user_key, '562517b7a6bd786135e3970f355615e9') /*application='ShogiWeb'*/
# >>   ↳ app/models/quick_script/swars/user_group_script.rb:119:in 'Enumerable#collect'
# >>   Swars::Grade Load (0.2ms)  SELECT `swars_grades`.* FROM `swars_grades` WHERE `swars_grades`.`id` = 39 ORDER BY `swars_grades`.`priority` ASC /*application='ShogiWeb'*/
# >>   ↳ app/models/quick_script/swars/user_group_script.rb:119:in 'Enumerable#collect'
# >>   Swars::Membership Load (0.2ms)  SELECT `swars_memberships`.* FROM `swars_memberships` WHERE `swars_memberships`.`user_id` = 1055264 /*application='ShogiWeb'*/
# >>   ↳ app/models/quick_script/swars/user_group_script.rb:119:in 'Enumerable#collect'
# >>   Swars::Membership Ids (0.2ms)  SELECT `swars_memberships`.`id` FROM `swars_memberships` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` WHERE `swars_memberships`.`user_id` = 1055264 ORDER BY `swars_battles`.`battled_at` DESC LIMIT 500 /*application='ShogiWeb'*/
# >>   ↳ app/models/swars/user/stat/scope_ext.rb:31:in 'Swars::User::Stat::ScopeExt#scope_ids'
# >>   Swars::Membership Load (0.3ms)  SELECT swars_rules.key AS rule_key, MIN(swars_grades.priority) AS min_priority FROM `swars_memberships` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` INNER JOIN `swars_imodes` ON `swars_imodes`.`id` = `swars_battles`.`imode_id` INNER JOIN `swars_rules` ON `swars_rules`.`id` = `swars_battles`.`rule_id` INNER JOIN `swars_grades` ON `swars_grades`.`id` = `swars_memberships`.`grade_id` WHERE `swars_memberships`.`id` IN (118847111, 118847109) AND `swars_imodes`.`key` = 'normal' GROUP BY `rule_key` /*application='ShogiWeb'*/
# >>   ↳ app/models/swars/user/stat/grade_by_rules_stat.rb:72:in 'block (2 levels) in Swars::User::Stat::GradeByRulesStat#normal_grades_hash'
# >>   Swars::Membership Load (0.3ms)  SELECT MIN(swars_grades.priority) AS min_priority FROM `swars_memberships` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` INNER JOIN `swars_imodes` ON `swars_imodes`.`id` = `swars_battles`.`imode_id` INNER JOIN `swars_grades` ON `swars_grades`.`id` = `swars_memberships`.`grade_id` WHERE `swars_memberships`.`id` IN (118847111, 118847109) AND `swars_imodes`.`key` = 'sprint' LIMIT 1 /*application='ShogiWeb'*/
# >>   ↳ app/models/swars/user/stat/grade_by_rules_stat.rb:50:in 'block in Swars::User::Stat::GradeByRulesStat#dr_sprint'
# >>   Swars::Membership Count (0.2ms)  SELECT COUNT(*) AS `count_all`, `judges`.`key` AS `judges_key` FROM `swars_memberships` INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` WHERE `swars_memberships`.`id` IN (118847111, 118847109) GROUP BY `judges`.`key` /*application='ShogiWeb'*/
# >>   ↳ app/models/swars/user/stat/membership_global_extension.rb:14:in 'Swars::User::Stat::MembershipGlobalExtension::ClassMethods#total_judge_counts'
# >>   Swars::Membership Count (0.2ms)  SELECT COUNT(*) FROM `swars_memberships` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` WHERE `swars_memberships`.`id` IN (118847111, 118847109) AND `swars_battles`.`battled_at` >= '2025-04-25 12:02:30' /*application='ShogiWeb'*/
# >>   ↳ app/models/swars/user/stat/vitality_stat.rb:30:in 'block in Swars::User::Stat::VitalityStat#count'
# >>   Swars::Membership Count (0.2ms)  SELECT COUNT(*) FROM `swars_memberships` WHERE `swars_memberships`.`id` IN (118847111, 118847109) /*application='ShogiWeb'*/
# >>   ↳ app/models/swars/user/stat/scope_ext.rb:41:in 'Swars::User::Stat::ScopeExt#ids_count'
# >>   Swars::Membership Count (0.2ms)  SELECT COUNT(*) AS `count_all`, `swars_xmodes`.`key` AS `swars_xmodes_key`, `judges`.`key` AS `judges_key` FROM `swars_memberships` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` INNER JOIN `swars_xmodes` ON `swars_xmodes`.`id` = `swars_battles`.`xmode_id` INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` WHERE `swars_memberships`.`id` IN (118847111, 118847109) GROUP BY `swars_xmodes`.`key`, `judges`.`key` /*application='ShogiWeb'*/
# >>   ↳ app/models/swars/user/stat/xmode_judge_stat.rb:113:in 'block in Swars::User::Stat::XmodeJudgeStat#counts_hash'
# >>   Swars::Membership Count (0.3ms)  SELECT COUNT(*) AS `count_all`, `judges`.`key` AS `judges_key`, `swars_finals`.`key` AS `swars_finals_key` FROM `swars_memberships` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` INNER JOIN `swars_finals` ON `swars_finals`.`id` = `swars_battles`.`final_id` INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` WHERE `swars_memberships`.`id` IN (118847111, 118847109) AND `swars_battles`.`turn_max` >= 2 GROUP BY `judges`.`key`, `swars_finals`.`key` /*application='ShogiWeb'*/
# >>   ↳ app/models/swars/user/stat/judge_final_stat.rb:66:in 'block in Swars::User::Stat::JudgeFinalStat#counts_hash'
# >>   Swars::Membership Average (0.2ms)  SELECT AVG(`turn_max`) AS `average_turn_max`, `judges`.`key` AS `judges_key` FROM `swars_memberships` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` INNER JOIN `swars_imodes` ON `swars_imodes`.`id` = `swars_battles`.`imode_id` INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` WHERE `swars_memberships`.`id` IN (118847111, 118847109) AND `swars_imodes`.`key` = 'normal' GROUP BY `judges`.`key` /*application='ShogiWeb'*/
# >>   ↳ app/models/swars/user/stat/average_moves_by_outcome_stat.rb:31:in 'block in Swars::User::Stat::AverageMovesByOutcomeStat#averages_hash'
# >>   Swars::Membership Count (0.3ms)  SELECT COUNT(*) AS `count_all`, `tags`.`name` AS `tags_name`, `judges`.`key` AS `judges_key` FROM `swars_memberships` INNER JOIN `taggings` ON `taggings`.`taggable_type` = 'Swars::Membership' AND `taggings`.`taggable_id` = `swars_memberships`.`id` INNER JOIN `tags` ON `tags`.`id` = `taggings`.`tag_id` INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` WHERE `swars_memberships`.`id` IN (118847111, 118847109) GROUP BY `tags`.`name`, `judges`.`key` /*application='ShogiWeb'*/
# >>   ↳ app/models/swars/user/stat/tag_stat.rb:236:in 'block in Swars::User::Stat::TagStat#internal_counts_hash'
# >>   Swars::Membership Count (0.5ms)  SELECT COUNT(*) FROM `swars_memberships` INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` WHERE `swars_memberships`.`id` IN (118847111, 118847109) AND `judges`.`key` = 'draw' /*application='ShogiWeb'*/
# >>   ↳ app/models/swars/user/stat/sub_scope_methods.rb:43:in 'Swars::User::Stat::SubScopeMethods#draw_count'
# >>   Swars::Membership Average (0.2ms)  SELECT AVG(`swars_memberships`.`think_all_avg`) FROM `swars_memberships` WHERE `swars_memberships`.`id` IN (118847111, 118847109) /*application='ShogiWeb'*/
# >>   ↳ app/models/swars/user/stat/think_stat.rb:44:in 'Swars::User::Stat::ThinkStat#average'
# >>   Swars::Membership Count (0.3ms)  SELECT COUNT(*) FROM `swars_memberships` INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` INNER JOIN `swars_imodes` ON `swars_imodes`.`id` = `swars_battles`.`imode_id` INNER JOIN `swars_finals` ON `swars_finals`.`id` = `swars_battles`.`final_id` WHERE `swars_memberships`.`id` IN (118847111, 118847109) AND `judges`.`key` = 'lose' AND `swars_imodes`.`key` = 'normal' AND (`swars_finals`.`key` = 'TORYO' OR `swars_finals`.`key` = 'CHECKMATE') AND `swars_battles`.`turn_max` BETWEEN 14 AND 44 /*application='ShogiWeb'*/
# >>   ↳ app/models/swars/user/stat/lethargy_stat.rb:34:in 'block in Swars::User::Stat::LethargyStat#count'
# >>   Swars::Membership Count (0.3ms)  SELECT COUNT(*) FROM `swars_memberships` INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` INNER JOIN `swars_imodes` ON `swars_imodes`.`id` = `swars_battles`.`imode_id` INNER JOIN `swars_finals` ON `swars_finals`.`id` = `swars_battles`.`final_id` WHERE `swars_memberships`.`id` IN (118847111, 118847109) AND `judges`.`key` = 'lose' AND `swars_imodes`.`key` = 'normal' AND (`swars_finals`.`key` = 'TORYO' OR `swars_finals`.`key` = 'CHECKMATE') AND `swars_battles`.`turn_max` < 14 /*application='ShogiWeb'*/
# >>   ↳ app/models/swars/user/stat/skill_adjust_stat.rb:27:in 'block in Swars::User::Stat::SkillAdjustStat#count'
# >>   Swars::Membership Count (0.2ms)  SELECT COUNT(*) FROM `swars_memberships` INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` INNER JOIN `swars_finals` ON `swars_finals`.`id` = `swars_battles`.`final_id` WHERE `swars_memberships`.`id` IN (118847111, 118847109) AND `judges`.`key` = 'win' AND `swars_memberships`.`think_last` >= 45 AND `swars_finals`.`key` = 'CHECKMATE' /*application='ShogiWeb'*/
# >>   ↳ app/models/swars/user/stat/taunt_mate_stat.rb:42:in 'Swars::User::Stat::TauntMateStat#count'
# >>   Swars::Membership Count (0.2ms)  SELECT COUNT(*) FROM `swars_memberships` INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` INNER JOIN `swars_finals` ON `swars_finals`.`id` = `swars_battles`.`final_id` WHERE `swars_memberships`.`id` IN (118847111, 118847109) AND `judges`.`key` = 'win' AND `swars_memberships`.`think_last` >= 45 AND `swars_finals`.`key` = 'TIMEOUT' /*application='ShogiWeb'*/
# >>   ↳ app/models/swars/user/stat/taunt_mate_stat.rb:42:in 'Swars::User::Stat::TauntMateStat#count'
# >>   Swars::Membership Count (0.2ms)  SELECT COUNT(*) FROM `swars_memberships` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` WHERE `swars_memberships`.`id` IN (118847111, 118847109) AND (`swars_memberships`.`ai_wave_count` >= 3 OR `swars_memberships`.`ai_drop_total` >= 15 OR `swars_memberships`.`ai_two_freq` >= 0.6 AND `swars_battles`.`turn_max` >= 50 OR `swars_memberships`.`ai_gear_freq` >= 0.22 AND `swars_battles`.`turn_max` >= 50) /*application='ShogiWeb'*/
# >>   ↳ app/models/swars/user/stat/fraud_stat.rb:13:in 'Swars::User::Stat::FraudStat#count'
# >>   Swars::Membership Count (1.8ms)  SELECT COUNT(*) FROM `swars_memberships` INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` INNER JOIN `swars_xmodes` ON `swars_xmodes`.`id` = `swars_battles`.`xmode_id` WHERE `swars_memberships`.`id` IN (118847111, 118847109) AND `judges`.`key` = 'win' AND `swars_xmodes`.`key` = '野良' AND `swars_memberships`.`grade_diff` >= 10 /*application='ShogiWeb'*/
# >>   ↳ app/models/swars/user/stat/gdiff_stat.rb:67:in 'block in Swars::User::Stat::GdiffStat#row_grade_pretend_count'
# >>   Swars::Membership Average (0.2ms)  SELECT AVG(`swars_memberships`.`grade_diff`) FROM `swars_memberships` WHERE `swars_memberships`.`id` IN (118847111, 118847109) /*application='ShogiWeb'*/
# >>   ↳ app/models/swars/user/stat/gdiff_stat.rb:52:in 'Swars::User::Stat::GdiffStat#average'
# >>   Swars::Membership Count (0.2ms)  SELECT COUNT(*) FROM `swars_memberships` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` INNER JOIN `swars_imodes` ON `swars_imodes`.`id` = `swars_battles`.`imode_id` WHERE `swars_memberships`.`id` IN (118847111, 118847109) AND `swars_imodes`.`key` = 'normal' AND `swars_memberships`.`think_max` >= 180 /*application='ShogiWeb'*/
# >>   ↳ app/models/swars/user/stat/prolonged_deliberation_stat.rb:30:in 'block in Swars::User::Stat::ProlongedDeliberationStat#count'
# >>   Swars::Membership Count (0.2ms)  SELECT COUNT(*) FROM `swars_memberships` INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` INNER JOIN `swars_finals` ON `swars_finals`.`id` = `swars_battles`.`final_id` WHERE `swars_memberships`.`id` IN (118847111, 118847109) AND `judges`.`key` = 'lose' AND `swars_finals`.`key` = 'TIMEOUT' AND `swars_memberships`.`think_last` >= 60 /*application='ShogiWeb'*/
# >>   ↳ app/models/swars/user/stat/leave_alone_stat.rb:49:in 'Swars::User::Stat::LeaveAloneStat#count'
# >>   Swars::Membership Count (0.2ms)  SELECT COUNT(*) FROM `swars_memberships` INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` WHERE `swars_memberships`.`id` IN (118847111, 118847109) AND `judges`.`key` = 'lose' AND `swars_memberships`.`think_last` IS NOT NULL AND `swars_memberships`.`think_max` != `swars_memberships`.`think_last` AND `swars_memberships`.`think_max` >= 300 AND `swars_battles`.`turn_max` >= 14 /*application='ShogiWeb'*/
# >>   ↳ app/models/swars/user/stat/waiting_to_leave_stat.rb:34:in 'block in Swars::User::Stat::WaitingToLeaveStat#count'
# >>   Swars::Membership Count (0.3ms)  SELECT COUNT(*) FROM `swars_memberships` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` INNER JOIN `swars_finals` ON `swars_finals`.`id` = `swars_battles`.`final_id` INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` WHERE `swars_memberships`.`id` IN (118847111, 118847109) AND `swars_battles`.`turn_max` < 2 AND `swars_finals`.`key` = 'DISCONNECT' AND `judges`.`key` = 'lose' /*application='ShogiWeb'*/
# >>   ↳ app/models/swars/user/stat/unstable_network_stat.rb:28:in 'block in Swars::User::Stat::UnstableNetworkStat#count'
# >>   ActsAsTaggableOn::Tag Load (0.3ms)  SELECT tags.*, taggings.tags_count AS count FROM `tags` JOIN (SELECT taggings.tag_id, COUNT(taggings.tag_id) AS tags_count FROM `taggings` WHERE (taggings.taggable_type = 'Swars::Membership' AND taggings.context = 'attack_tags') AND (taggings.taggable_id IN(SELECT `swars_memberships`.`id` FROM `swars_memberships` WHERE `swars_memberships`.`id` IN (118847111, 118847109))) GROUP BY `taggings`.`tag_id` HAVING (COUNT(taggings.tag_id) > 0)) AS taggings ON taggings.tag_id = tags.id ORDER BY count DESC, tags.id ASC LIMIT 1 /*application='ShogiWeb'*/
# >>   ↳ app/models/swars/user/stat/simple_matrix_stat.rb:79:in 'Swars::User::Stat::SimpleMatrixStat#find_one'
# >>   ActsAsTaggableOn::Tag Load (0.3ms)  SELECT tags.*, taggings.tags_count AS count FROM `tags` JOIN (SELECT taggings.tag_id, COUNT(taggings.tag_id) AS tags_count FROM `taggings` WHERE (taggings.taggable_type = 'Swars::Membership' AND taggings.context = 'defense_tags') AND (taggings.taggable_id IN(SELECT `swars_memberships`.`id` FROM `swars_memberships` WHERE `swars_memberships`.`id` IN (118847111, 118847109))) GROUP BY `taggings`.`tag_id` HAVING (COUNT(taggings.tag_id) > 0)) AS taggings ON taggings.tag_id = tags.id ORDER BY count DESC, tags.id ASC LIMIT 1 /*application='ShogiWeb'*/
# >>   ↳ app/models/swars/user/stat/simple_matrix_stat.rb:79:in 'Swars::User::Stat::SimpleMatrixStat#find_one'
# >> |---------+------------------------------------------------------------------------------------------------------------------------------------------+------+------+-----+------+----+-------+------+-------+--------+----------+----------+--------+------------+-----------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------+-----------------|
# >> | 名前    | ウォーズID                                                                                                                               | 最高 | 10分 | 3分 | 10秒 | ス | 勝率  | 勢い | 規範  | 居飛車 | 振り飛車 | 主戦法   | 主囲い | 直近対局   | リンク1                                                                                                         | リンク2                                                                                                                  | リンク3                                                                                                     | リンク4                                                                                                                    | 最高段位(index) |
# >> |---------+------------------------------------------------------------------------------------------------------------------------------------------+------+------+-----+------+----+-------+------+-------+--------+----------+----------+--------+------------+-----------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------+-----------------|
# >> | (xname) | {_nuxt_link: {name: "562517b7a6bd786135e3970f355615e9", to: {name: "swars-search", query: {query: "562517b7a6bd786135e3970f355615e9"}}}} | 30級 | 30級 |     |      |    | 100 % | 13 % | 60 点 | 0 %    | 0 %      | 新嬉野流 |        | 2025-04-30 | {_nuxt_link: {name: "棋譜(2)", to: {name: "swars-search", query: {query: "562517b7a6bd786135e3970f355615e9"}}}} | {_nuxt_link: {name: "プレイヤー情報", to: {name: "swars-users-key", params: {key: "562517b7a6bd786135e3970f355615e9"}}}} | <a href="https://shogiwars.heroz.jp/users/mypage/562517b7a6bd786135e3970f355615e9" target="_blank">本家</a> | <a href="https://www.google.co.jp/search?q=562517b7a6bd786135e3970f355615e9+%E5%B0%86%E6%A3%8B" target="_blank">ググる</a> |              39 |
# >> |---------+------------------------------------------------------------------------------------------------------------------------------------------+------+------+-----+------+----+-------+------+-------+--------+----------+----------+--------+------------+-----------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------+-----------------|
