require "./setup"
sql
_ { QuickScript::Swars::UserScript.new(user_keys: "SiroChannel, Kato_Hifumi").call[:rows] } # => "245.26 ms"
s { tp QuickScript::Swars::UserScript.new(user_keys: "SiroChannel, Kato_Hifumi").call[:rows] } # => [{"名前"=>{:_nuxt_link=>{:name=>"SiroChannel", :to=>{:name=>"swars-search", :query=>{:query=>"SiroChannel"}}}}, "最高"=>"十段", "10分"=>"十段", "3分"=>"", "10秒"=>"", "勝率"=>"75 %", "勢い"=>"0.00", "規範"=>"87 点", "居飛車"=>"0 %", "振り飛車"=>"100 %", "主戦法"=>"四間飛車", "主囲い"=>"高美濃囲い", "直近対局"=>"2024-06-28", "リンク1"=>{:_nuxt_link=>{:name=>"棋譜(4)", :to=>{:name=>"swars-search", :query=>{:query=>"SiroChannel"}}}}, "リンク2"=>{:_nuxt_link=>{:name=>"プレイヤー情報", :to=>{:name=>"swars-users-key", :params=>{:key=>"SiroChannel"}}}}, "リンク3"=>"<a href=\"https://shogiwars.heroz.jp/users/mypage/SiroChannel\" target=\"_blank\">本家</a>", "リンク4"=>"<a href=\"https://www.google.co.jp/search?q=SiroChannel+%E5%B0%86%E6%A3%8B\" target=\"_blank\">ググる</a>", "最高段位(index)"=>0}, {"名前"=>{:_nuxt_link=>{:name=>"Kato_Hifumi", :to=>{:name=>"swars-search", :query=>{:query=>"Kato_Hifumi"}}}}, "最高"=>"十段", "10分"=>"十段", "3分"=>"", "10秒"=>"", "勝率"=>"0 %", "勢い"=>"0.00", "規範"=>"99 点", "居飛車"=>"100 %", "振り飛車"=>"0 %", "主戦法"=>"棒銀", "主囲い"=>"ボナンザ囲い", "直近対局"=>"2024-06-28", "リンク1"=>{:_nuxt_link=>{:name=>"棋譜(1)", :to=>{:name=>"swars-search", :query=>{:query=>"Kato_Hifumi"}}}}, "リンク2"=>{:_nuxt_link=>{:name=>"プレイヤー情報", :to=>{:name=>"swars-users-key", :params=>{:key=>"Kato_Hifumi"}}}}, "リンク3"=>"<a href=\"https://shogiwars.heroz.jp/users/mypage/Kato_Hifumi\" target=\"_blank\">本家</a>", "リンク4"=>"<a href=\"https://www.google.co.jp/search?q=Kato_Hifumi+%E5%B0%86%E6%A3%8B\" target=\"_blank\">ググる</a>", "最高段位(index)"=>0}]
# >>   Swars::User Pluck (0.5ms)  SELECT `swars_users`.`user_key` FROM `swars_users` WHERE `swars_users`.`user_key` IN ('SiroChannel', 'Kato_Hifumi')
# >>   ↳ app/models/quick_script/swars/user_script.rb:51:in `call'
# >>   Swars::User Exists? (0.3ms)  SELECT 1 AS one FROM `swars_users` WHERE `swars_users`.`user_key` IN ('SiroChannel', 'Kato_Hifumi') LIMIT 1
# >>   ↳ app/models/quick_script/swars/user_script.rb:57:in `call'
# >>   Swars::User Count (0.3ms)  SELECT COUNT(*) FROM `swars_users` WHERE `swars_users`.`user_key` IN ('SiroChannel', 'Kato_Hifumi')
# >>   ↳ app/models/quick_script/swars/user_script.rb:61:in `call'
# >>   Swars::User Load (0.4ms)  SELECT `swars_users`.* FROM `swars_users` WHERE `swars_users`.`user_key` IN ('SiroChannel', 'Kato_Hifumi') ORDER BY FIELD(swars_users.user_key, 'SiroChannel','Kato_Hifumi')
# >>   ↳ app/models/quick_script/swars/user_script.rb:173:in `collect'
# >>   Swars::Grade Load (0.3ms)  SELECT `swars_grades`.* FROM `swars_grades` WHERE `swars_grades`.`id` = 40 ORDER BY `swars_grades`.`priority` ASC
# >>   ↳ app/models/quick_script/swars/user_script.rb:173:in `collect'
# >>   Swars::Membership Load (0.5ms)  SELECT `swars_memberships`.* FROM `swars_memberships` WHERE `swars_memberships`.`user_id` IN (23502, 23501)
# >>   ↳ app/models/quick_script/swars/user_script.rb:173:in `collect'
# >>   Swars::Membership Ids (0.5ms)  SELECT `swars_memberships`.`id` FROM `swars_memberships` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` WHERE `swars_memberships`.`user_id` = 23502 ORDER BY `swars_battles`.`battled_at` DESC LIMIT 50
# >>   ↳ app/models/swars/user/stat/scope_ext.rb:30:in `scope_ids'
# >>   Swars::Membership Load (0.7ms)  SELECT swars_rules.key AS rule_key, MIN(swars_grades.priority) AS min_priority FROM `swars_memberships` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` INNER JOIN `swars_rules` ON `swars_rules`.`id` = `swars_battles`.`rule_id` INNER JOIN `swars_grades` ON `swars_grades`.`id` = `swars_memberships`.`grade_id` WHERE `swars_memberships`.`id` IN (9818693, 8999691, 8999693, 8997060) GROUP BY `rule_key`
# >>   ↳ app/models/swars/user/stat/grade_by_rules_stat.rb:40:in `block (2 levels) in grades_hash'
# >>   Swars::Membership Count (0.5ms)  SELECT COUNT(*) AS `count_all`, `judges`.`key` AS `judges_key` FROM `swars_memberships` INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` WHERE `swars_memberships`.`id` IN (9818693, 8999691, 8999693, 8997060) GROUP BY `judges`.`key`
# >>   ↳ app/models/swars/user/stat/membership_global_extension.rb:14:in `total_judge_counts'
# >>   Swars::Membership Count (0.4ms)  SELECT COUNT(*) FROM `swars_memberships` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` WHERE `swars_memberships`.`id` IN (9818693, 8999691, 8999693, 8997060) AND `swars_battles`.`battled_at` >= '2024-07-10 05:36:34'
# >>   ↳ app/models/swars/user/stat/vitality_stat.rb:25:in `block in count'
# >>   Swars::Membership Count (0.3ms)  SELECT COUNT(*) FROM `swars_memberships` WHERE `swars_memberships`.`id` IN (9818693, 8999691, 8999693, 8997060)
# >>   ↳ app/models/swars/user/stat/scope_ext.rb:40:in `ids_count'
# >>   Swars::Membership Count (0.6ms)  SELECT COUNT(*) AS `count_all`, `swars_xmodes`.`key` AS `swars_xmodes_key`, `judges`.`key` AS `judges_key` FROM `swars_memberships` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` INNER JOIN `swars_xmodes` ON `swars_xmodes`.`id` = `swars_battles`.`xmode_id` INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` WHERE `swars_memberships`.`id` IN (9818693, 8999691, 8999693, 8997060) GROUP BY `swars_xmodes`.`key`, `judges`.`key`
# >>   ↳ app/models/swars/user/stat/xmode_judge_stat.rb:113:in `block in counts_hash'
# >>   Swars::Membership Count (0.7ms)  SELECT COUNT(*) AS `count_all`, `judges`.`key` AS `judges_key`, `swars_finals`.`key` AS `swars_finals_key` FROM `swars_memberships` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` INNER JOIN `swars_finals` ON `swars_finals`.`id` = `swars_battles`.`final_id` INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` WHERE `swars_memberships`.`id` IN (9818693, 8999691, 8999693, 8997060) AND `swars_battles`.`turn_max` >= 2 GROUP BY `judges`.`key`, `swars_finals`.`key`
# >>   ↳ app/models/swars/user/stat/judge_final_stat.rb:66:in `block in counts_hash'
# >>   Swars::Membership Average (0.5ms)  SELECT AVG(turn_max) AS `average_turn_max`, `judges`.`key` AS `judges_key` FROM `swars_memberships` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` WHERE `swars_memberships`.`id` IN (9818693, 8999691, 8999693, 8997060) GROUP BY `judges`.`key`
# >>   ↳ app/models/swars/user/stat/average_moves_by_outcome_stat.rb:30:in `block in averages_hash'
# >>   Swars::Membership Count (1.2ms)  SELECT COUNT(*) AS `count_all`, `tags`.`name` AS `tags_name`, `judges`.`key` AS `judges_key` FROM `swars_memberships` INNER JOIN `taggings` ON `taggings`.`taggable_type` = 'Swars::Membership' AND `taggings`.`taggable_id` = `swars_memberships`.`id` INNER JOIN `tags` ON `tags`.`id` = `taggings`.`tag_id` INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` WHERE `swars_memberships`.`id` IN (9818693, 8999691, 8999693, 8997060) GROUP BY `tags`.`name`, `judges`.`key`
# >>   ↳ app/models/swars/user/stat/tag_stat.rb:236:in `block in inside_counts_hash'
# >>   Swars::Membership Count (0.5ms)  SELECT COUNT(*) FROM `swars_memberships` INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` WHERE `swars_memberships`.`id` IN (9818693, 8999691, 8999693, 8997060) AND `judges`.`key` = 'draw'
# >>   ↳ app/models/swars/user/stat/sub_scope_methods.rb:43:in `draw_count'
# >>   Swars::Membership Average (0.3ms)  SELECT AVG(`swars_memberships`.`think_all_avg`) FROM `swars_memberships` WHERE `swars_memberships`.`id` IN (9818693, 8999691, 8999693, 8997060)
# >>   ↳ app/models/swars/user/stat/think_stat.rb:44:in `average'
# >>   Swars::Membership Count (0.8ms)  SELECT COUNT(*) FROM `swars_memberships` INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` INNER JOIN `swars_finals` ON `swars_finals`.`id` = `swars_battles`.`final_id` WHERE `swars_memberships`.`id` IN (9818693, 8999691, 8999693, 8997060) AND `judges`.`key` = 'lose' AND (`swars_finals`.`key` = 'TORYO' OR `swars_finals`.`key` = 'CHECKMATE') AND `swars_battles`.`turn_max` BETWEEN 14 AND 44
# >>   ↳ app/models/swars/user/stat/lethargy_stat.rb:32:in `block in count'
# >>   Swars::Membership Count (0.7ms)  SELECT COUNT(*) FROM `swars_memberships` INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` INNER JOIN `swars_finals` ON `swars_finals`.`id` = `swars_battles`.`final_id` WHERE `swars_memberships`.`id` IN (9818693, 8999691, 8999693, 8997060) AND `judges`.`key` = 'lose' AND (`swars_finals`.`key` = 'TORYO' OR `swars_finals`.`key` = 'CHECKMATE') AND `swars_battles`.`turn_max` < 14
# >>   ↳ app/models/swars/user/stat/skill_adjust_stat.rb:25:in `block in count'
# >>   Swars::Membership Count (0.6ms)  SELECT COUNT(*) FROM `swars_memberships` INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` INNER JOIN `swars_finals` ON `swars_finals`.`id` = `swars_battles`.`final_id` WHERE `swars_memberships`.`id` IN (9818693, 8999691, 8999693, 8997060) AND `judges`.`key` = 'win' AND `swars_memberships`.`think_last` >= 45 AND `swars_finals`.`key` = 'CHECKMATE'
# >>   ↳ app/models/swars/user/stat/taunt_mate_stat.rb:42:in `count'
# >>   Swars::Membership Count (0.4ms)  SELECT COUNT(*) FROM `swars_memberships` INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` INNER JOIN `swars_finals` ON `swars_finals`.`id` = `swars_battles`.`final_id` WHERE `swars_memberships`.`id` IN (9818693, 8999691, 8999693, 8997060) AND `judges`.`key` = 'win' AND `swars_memberships`.`think_last` >= 45 AND `swars_finals`.`key` = 'TIMEOUT'
# >>   ↳ app/models/swars/user/stat/taunt_mate_stat.rb:42:in `count'
# >>   Swars::Membership Count (0.3ms)  SELECT COUNT(*) FROM `swars_memberships` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` WHERE `swars_memberships`.`id` IN (9818693, 8999691, 8999693, 8997060) AND (`swars_memberships`.`ai_wave_count` >= 3 OR `swars_memberships`.`ai_drop_total` >= 15 OR `swars_memberships`.`ai_two_freq` >= 0.6 AND `swars_battles`.`turn_max` >= 50 OR `swars_memberships`.`ai_gear_freq` >= 0.22 AND `swars_battles`.`turn_max` >= 50)
# >>   ↳ app/models/swars/user/stat/fraud_stat.rb:13:in `count'
# >>   Swars::Membership Count (0.4ms)  SELECT COUNT(*) FROM `swars_memberships` INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` INNER JOIN `swars_xmodes` ON `swars_xmodes`.`id` = `swars_battles`.`xmode_id` WHERE `swars_memberships`.`id` IN (9818693, 8999691, 8999693, 8997060) AND `judges`.`key` = 'win' AND `swars_xmodes`.`key` = '野良' AND `swars_memberships`.`grade_diff` >= 10
# >>   ↳ app/models/swars/user/stat/gdiff_stat.rb:67:in `block in row_grade_pretend_count'
# >>   Swars::Membership Count (0.2ms)  SELECT COUNT(*) FROM `swars_memberships` WHERE `swars_memberships`.`id` IN (9818693, 8999691, 8999693, 8997060) AND `swars_memberships`.`think_max` >= 180
# >>   ↳ app/models/swars/user/stat/prolonged_deliberation_stat.rb:27:in `block in count'
# >>   Swars::Membership Count (0.3ms)  SELECT COUNT(*) FROM `swars_memberships` INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` INNER JOIN `swars_finals` ON `swars_finals`.`id` = `swars_battles`.`final_id` WHERE `swars_memberships`.`id` IN (9818693, 8999691, 8999693, 8997060) AND `judges`.`key` = 'lose' AND `swars_finals`.`key` = 'TIMEOUT' AND `swars_memberships`.`think_last` >= 60
# >>   ↳ app/models/swars/user/stat/leave_alone_stat.rb:49:in `count'
# >>   Swars::Membership Count (0.3ms)  SELECT COUNT(*) FROM `swars_memberships` INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` WHERE `swars_memberships`.`id` IN (9818693, 8999691, 8999693, 8997060) AND `judges`.`key` = 'lose' AND `swars_memberships`.`think_last` IS NOT NULL AND `swars_memberships`.`think_max` != `swars_memberships`.`think_last` AND `swars_memberships`.`think_max` >= 300 AND `swars_battles`.`turn_max` >= 14
# >>   ↳ app/models/swars/user/stat/waiting_to_leave_stat.rb:34:in `block in count'
# >>   Swars::Membership Count (0.3ms)  SELECT COUNT(*) FROM `swars_memberships` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` INNER JOIN `swars_finals` ON `swars_finals`.`id` = `swars_battles`.`final_id` INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` WHERE `swars_memberships`.`id` IN (9818693, 8999691, 8999693, 8997060) AND `swars_battles`.`turn_max` < 2 AND `swars_finals`.`key` = 'DISCONNECT' AND `judges`.`key` = 'lose'
# >>   ↳ app/models/swars/user/stat/unstable_network_stat.rb:28:in `block in count'
# >>   Swars::Membership Pluck (0.3ms)  SELECT `swars_memberships`.`id` FROM `swars_memberships` WHERE `swars_memberships`.`id` IN (9818693, 8999691, 8999693, 8997060)
# >>   ↳ app/models/swars/user/stat/simple_matrix_stat.rb:73:in `find_one'
# >>   ActsAsTaggableOn::Tag Load (1.4ms)  SELECT tags.*, taggings.tags_count AS count FROM `tags` JOIN (SELECT taggings.tag_id, COUNT(taggings.tag_id) AS tags_count FROM `taggings` WHERE (taggings.taggable_type = 'Swars::Membership' AND taggings.context = 'attack_tags') AND (taggings.taggable_id IN ('8997060','8999691','8999693','9818693')) GROUP BY `taggings`.`tag_id` HAVING (COUNT(taggings.tag_id) > 0)) AS taggings ON taggings.tag_id = tags.id ORDER BY count DESC, tags.id ASC LIMIT 1
# >>   ↳ app/models/swars/user/stat/simple_matrix_stat.rb:79:in `find_one'
# >>   Swars::Membership Pluck (0.3ms)  SELECT `swars_memberships`.`id` FROM `swars_memberships` WHERE `swars_memberships`.`id` IN (9818693, 8999691, 8999693, 8997060)
# >>   ↳ app/models/swars/user/stat/simple_matrix_stat.rb:73:in `find_one'
# >>   ActsAsTaggableOn::Tag Load (1.0ms)  SELECT tags.*, taggings.tags_count AS count FROM `tags` JOIN (SELECT taggings.tag_id, COUNT(taggings.tag_id) AS tags_count FROM `taggings` WHERE (taggings.taggable_type = 'Swars::Membership' AND taggings.context = 'defense_tags') AND (taggings.taggable_id IN ('8997060','8999691','8999693','9818693')) GROUP BY `taggings`.`tag_id` HAVING (COUNT(taggings.tag_id) > 0)) AS taggings ON taggings.tag_id = tags.id ORDER BY count DESC, tags.id ASC LIMIT 1
# >>   ↳ app/models/swars/user/stat/simple_matrix_stat.rb:79:in `find_one'
# >>   Swars::Membership Ids (0.7ms)  SELECT `swars_memberships`.`id` FROM `swars_memberships` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` WHERE `swars_memberships`.`user_id` = 23501 ORDER BY `swars_battles`.`battled_at` DESC LIMIT 50
# >>   ↳ app/models/swars/user/stat/scope_ext.rb:30:in `scope_ids'
# >>   Swars::Membership Load (0.5ms)  SELECT swars_rules.key AS rule_key, MIN(swars_grades.priority) AS min_priority FROM `swars_memberships` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` INNER JOIN `swars_rules` ON `swars_rules`.`id` = `swars_battles`.`rule_id` INNER JOIN `swars_grades` ON `swars_grades`.`id` = `swars_memberships`.`grade_id` WHERE `swars_memberships`.`id` = 9818692 GROUP BY `rule_key`
# >>   ↳ app/models/swars/user/stat/grade_by_rules_stat.rb:40:in `block (2 levels) in grades_hash'
# >>   Swars::Membership Count (0.3ms)  SELECT COUNT(*) AS `count_all`, `judges`.`key` AS `judges_key` FROM `swars_memberships` INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` WHERE `swars_memberships`.`id` = 9818692 GROUP BY `judges`.`key`
# >>   ↳ app/models/swars/user/stat/membership_global_extension.rb:14:in `total_judge_counts'
# >>   Swars::Membership Count (0.4ms)  SELECT COUNT(*) FROM `swars_memberships` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` WHERE `swars_memberships`.`id` = 9818692 AND `swars_battles`.`battled_at` >= '2024-07-10 05:36:34'
# >>   ↳ app/models/swars/user/stat/vitality_stat.rb:25:in `block in count'
# >>   Swars::Membership Count (0.3ms)  SELECT COUNT(*) FROM `swars_memberships` WHERE `swars_memberships`.`id` = 9818692
# >>   ↳ app/models/swars/user/stat/scope_ext.rb:40:in `ids_count'
# >>   Swars::Membership Count (0.4ms)  SELECT COUNT(*) AS `count_all`, `swars_xmodes`.`key` AS `swars_xmodes_key`, `judges`.`key` AS `judges_key` FROM `swars_memberships` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` INNER JOIN `swars_xmodes` ON `swars_xmodes`.`id` = `swars_battles`.`xmode_id` INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` WHERE `swars_memberships`.`id` = 9818692 GROUP BY `swars_xmodes`.`key`, `judges`.`key`
# >>   ↳ app/models/swars/user/stat/xmode_judge_stat.rb:113:in `block in counts_hash'
# >>   Swars::Membership Count (0.4ms)  SELECT COUNT(*) AS `count_all`, `judges`.`key` AS `judges_key`, `swars_finals`.`key` AS `swars_finals_key` FROM `swars_memberships` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` INNER JOIN `swars_finals` ON `swars_finals`.`id` = `swars_battles`.`final_id` INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` WHERE `swars_memberships`.`id` = 9818692 AND `swars_battles`.`turn_max` >= 2 GROUP BY `judges`.`key`, `swars_finals`.`key`
# >>   ↳ app/models/swars/user/stat/judge_final_stat.rb:66:in `block in counts_hash'
# >>   Swars::Membership Average (0.3ms)  SELECT AVG(turn_max) AS `average_turn_max`, `judges`.`key` AS `judges_key` FROM `swars_memberships` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` WHERE `swars_memberships`.`id` = 9818692 GROUP BY `judges`.`key`
# >>   ↳ app/models/swars/user/stat/average_moves_by_outcome_stat.rb:30:in `block in averages_hash'
# >>   Swars::Membership Count (0.7ms)  SELECT COUNT(*) AS `count_all`, `tags`.`name` AS `tags_name`, `judges`.`key` AS `judges_key` FROM `swars_memberships` INNER JOIN `taggings` ON `taggings`.`taggable_type` = 'Swars::Membership' AND `taggings`.`taggable_id` = `swars_memberships`.`id` INNER JOIN `tags` ON `tags`.`id` = `taggings`.`tag_id` INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` WHERE `swars_memberships`.`id` = 9818692 GROUP BY `tags`.`name`, `judges`.`key`
# >>   ↳ app/models/swars/user/stat/tag_stat.rb:236:in `block in inside_counts_hash'
# >>   Swars::Membership Count (0.3ms)  SELECT COUNT(*) FROM `swars_memberships` INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` WHERE `swars_memberships`.`id` = 9818692 AND `judges`.`key` = 'draw'
# >>   ↳ app/models/swars/user/stat/sub_scope_methods.rb:43:in `draw_count'
# >>   Swars::Membership Average (0.3ms)  SELECT AVG(`swars_memberships`.`think_all_avg`) FROM `swars_memberships` WHERE `swars_memberships`.`id` = 9818692
# >>   ↳ app/models/swars/user/stat/think_stat.rb:44:in `average'
# >>   Swars::Membership Count (0.4ms)  SELECT COUNT(*) FROM `swars_memberships` INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` INNER JOIN `swars_finals` ON `swars_finals`.`id` = `swars_battles`.`final_id` WHERE `swars_memberships`.`id` = 9818692 AND `judges`.`key` = 'lose' AND (`swars_finals`.`key` = 'TORYO' OR `swars_finals`.`key` = 'CHECKMATE') AND `swars_battles`.`turn_max` BETWEEN 14 AND 44
# >>   ↳ app/models/swars/user/stat/lethargy_stat.rb:32:in `block in count'
# >>   Swars::Membership Count (0.4ms)  SELECT COUNT(*) FROM `swars_memberships` INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` INNER JOIN `swars_finals` ON `swars_finals`.`id` = `swars_battles`.`final_id` WHERE `swars_memberships`.`id` = 9818692 AND `judges`.`key` = 'lose' AND (`swars_finals`.`key` = 'TORYO' OR `swars_finals`.`key` = 'CHECKMATE') AND `swars_battles`.`turn_max` < 14
# >>   ↳ app/models/swars/user/stat/skill_adjust_stat.rb:25:in `block in count'
# >>   Swars::Membership Count (0.5ms)  SELECT COUNT(*) FROM `swars_memberships` INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` INNER JOIN `swars_finals` ON `swars_finals`.`id` = `swars_battles`.`final_id` WHERE `swars_memberships`.`id` = 9818692 AND `judges`.`key` = 'win' AND `swars_memberships`.`think_last` >= 45 AND `swars_finals`.`key` = 'CHECKMATE'
# >>   ↳ app/models/swars/user/stat/taunt_mate_stat.rb:42:in `count'
# >>   Swars::Membership Count (0.4ms)  SELECT COUNT(*) FROM `swars_memberships` INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` INNER JOIN `swars_finals` ON `swars_finals`.`id` = `swars_battles`.`final_id` WHERE `swars_memberships`.`id` = 9818692 AND `judges`.`key` = 'win' AND `swars_memberships`.`think_last` >= 45 AND `swars_finals`.`key` = 'TIMEOUT'
# >>   ↳ app/models/swars/user/stat/taunt_mate_stat.rb:42:in `count'
# >>   Swars::Membership Count (0.3ms)  SELECT COUNT(*) FROM `swars_memberships` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` WHERE `swars_memberships`.`id` = 9818692 AND (`swars_memberships`.`ai_wave_count` >= 3 OR `swars_memberships`.`ai_drop_total` >= 15 OR `swars_memberships`.`ai_two_freq` >= 0.6 AND `swars_battles`.`turn_max` >= 50 OR `swars_memberships`.`ai_gear_freq` >= 0.22 AND `swars_battles`.`turn_max` >= 50)
# >>   ↳ app/models/swars/user/stat/fraud_stat.rb:13:in `count'
# >>   Swars::Membership Count (0.4ms)  SELECT COUNT(*) FROM `swars_memberships` INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` INNER JOIN `swars_xmodes` ON `swars_xmodes`.`id` = `swars_battles`.`xmode_id` WHERE `swars_memberships`.`id` = 9818692 AND `judges`.`key` = 'win' AND `swars_xmodes`.`key` = '野良' AND `swars_memberships`.`grade_diff` >= 10
# >>   ↳ app/models/swars/user/stat/gdiff_stat.rb:67:in `block in row_grade_pretend_count'
# >>   Swars::Membership Count (0.3ms)  SELECT COUNT(*) FROM `swars_memberships` WHERE `swars_memberships`.`id` = 9818692 AND `swars_memberships`.`think_max` >= 180
# >>   ↳ app/models/swars/user/stat/prolonged_deliberation_stat.rb:27:in `block in count'
# >>   Swars::Membership Count (0.4ms)  SELECT COUNT(*) FROM `swars_memberships` INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` INNER JOIN `swars_finals` ON `swars_finals`.`id` = `swars_battles`.`final_id` WHERE `swars_memberships`.`id` = 9818692 AND `judges`.`key` = 'lose' AND `swars_finals`.`key` = 'TIMEOUT' AND `swars_memberships`.`think_last` >= 60
# >>   ↳ app/models/swars/user/stat/leave_alone_stat.rb:49:in `count'
# >>   Swars::Membership Count (0.3ms)  SELECT COUNT(*) FROM `swars_memberships` INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` WHERE `swars_memberships`.`id` = 9818692 AND `judges`.`key` = 'lose' AND `swars_memberships`.`think_last` IS NOT NULL AND `swars_memberships`.`think_max` != `swars_memberships`.`think_last` AND `swars_memberships`.`think_max` >= 300 AND `swars_battles`.`turn_max` >= 14
# >>   ↳ app/models/swars/user/stat/waiting_to_leave_stat.rb:34:in `block in count'
# >>   Swars::Membership Count (0.3ms)  SELECT COUNT(*) FROM `swars_memberships` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` INNER JOIN `swars_finals` ON `swars_finals`.`id` = `swars_battles`.`final_id` INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` WHERE `swars_memberships`.`id` = 9818692 AND `swars_battles`.`turn_max` < 2 AND `swars_finals`.`key` = 'DISCONNECT' AND `judges`.`key` = 'lose'
# >>   ↳ app/models/swars/user/stat/unstable_network_stat.rb:28:in `block in count'
# >>   Swars::Membership Pluck (0.2ms)  SELECT `swars_memberships`.`id` FROM `swars_memberships` WHERE `swars_memberships`.`id` = 9818692
# >>   ↳ app/models/swars/user/stat/simple_matrix_stat.rb:73:in `find_one'
# >>   ActsAsTaggableOn::Tag Load (0.9ms)  SELECT tags.*, taggings.tags_count AS count FROM `tags` JOIN (SELECT taggings.tag_id, COUNT(taggings.tag_id) AS tags_count FROM `taggings` WHERE (taggings.taggable_type = 'Swars::Membership' AND taggings.context = 'attack_tags') AND (taggings.taggable_id IN ('9818692')) GROUP BY `taggings`.`tag_id` HAVING (COUNT(taggings.tag_id) > 0)) AS taggings ON taggings.tag_id = tags.id ORDER BY count DESC, tags.id ASC LIMIT 1
# >>   ↳ app/models/swars/user/stat/simple_matrix_stat.rb:79:in `find_one'
# >>   Swars::Membership Pluck (0.2ms)  SELECT `swars_memberships`.`id` FROM `swars_memberships` WHERE `swars_memberships`.`id` = 9818692
# >>   ↳ app/models/swars/user/stat/simple_matrix_stat.rb:73:in `find_one'
# >>   ActsAsTaggableOn::Tag Load (0.7ms)  SELECT tags.*, taggings.tags_count AS count FROM `tags` JOIN (SELECT taggings.tag_id, COUNT(taggings.tag_id) AS tags_count FROM `taggings` WHERE (taggings.taggable_type = 'Swars::Membership' AND taggings.context = 'defense_tags') AND (taggings.taggable_id IN ('9818692')) GROUP BY `taggings`.`tag_id` HAVING (COUNT(taggings.tag_id) > 0)) AS taggings ON taggings.tag_id = tags.id ORDER BY count DESC, tags.id ASC LIMIT 1
# >>   ↳ app/models/swars/user/stat/simple_matrix_stat.rb:79:in `find_one'
# >>   Swars::User Pluck (0.3ms)  SELECT `swars_users`.`user_key` FROM `swars_users` WHERE `swars_users`.`user_key` IN ('SiroChannel', 'Kato_Hifumi')
# >>   ↳ app/models/quick_script/swars/user_script.rb:51:in `call'
# >>   Swars::User Exists? (0.3ms)  SELECT 1 AS one FROM `swars_users` WHERE `swars_users`.`user_key` IN ('SiroChannel', 'Kato_Hifumi') LIMIT 1
# >>   ↳ app/models/quick_script/swars/user_script.rb:57:in `call'
# >>   Swars::User Count (0.3ms)  SELECT COUNT(*) FROM `swars_users` WHERE `swars_users`.`user_key` IN ('SiroChannel', 'Kato_Hifumi')
# >>   ↳ app/models/quick_script/swars/user_script.rb:61:in `call'
# >>   Swars::User Load (0.4ms)  SELECT `swars_users`.* FROM `swars_users` WHERE `swars_users`.`user_key` IN ('SiroChannel', 'Kato_Hifumi') ORDER BY FIELD(swars_users.user_key, 'SiroChannel','Kato_Hifumi')
# >>   ↳ app/models/quick_script/swars/user_script.rb:173:in `collect'
# >>   Swars::Grade Load (0.3ms)  SELECT `swars_grades`.* FROM `swars_grades` WHERE `swars_grades`.`id` = 40 ORDER BY `swars_grades`.`priority` ASC
# >>   ↳ app/models/quick_script/swars/user_script.rb:173:in `collect'
# >>   Swars::Membership Load (0.4ms)  SELECT `swars_memberships`.* FROM `swars_memberships` WHERE `swars_memberships`.`user_id` IN (23502, 23501)
# >>   ↳ app/models/quick_script/swars/user_script.rb:173:in `collect'
# >>   Swars::Membership Ids (0.4ms)  SELECT `swars_memberships`.`id` FROM `swars_memberships` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` WHERE `swars_memberships`.`user_id` = 23502 ORDER BY `swars_battles`.`battled_at` DESC LIMIT 50
# >>   ↳ app/models/swars/user/stat/scope_ext.rb:30:in `scope_ids'
# >>   Swars::Membership Load (0.5ms)  SELECT swars_rules.key AS rule_key, MIN(swars_grades.priority) AS min_priority FROM `swars_memberships` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` INNER JOIN `swars_rules` ON `swars_rules`.`id` = `swars_battles`.`rule_id` INNER JOIN `swars_grades` ON `swars_grades`.`id` = `swars_memberships`.`grade_id` WHERE `swars_memberships`.`id` IN (9818693, 8999691, 8999693, 8997060) GROUP BY `rule_key`
# >>   ↳ app/models/swars/user/stat/grade_by_rules_stat.rb:40:in `block (2 levels) in grades_hash'
# >>   Swars::Membership Count (0.4ms)  SELECT COUNT(*) AS `count_all`, `judges`.`key` AS `judges_key` FROM `swars_memberships` INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` WHERE `swars_memberships`.`id` IN (9818693, 8999691, 8999693, 8997060) GROUP BY `judges`.`key`
# >>   ↳ app/models/swars/user/stat/membership_global_extension.rb:14:in `total_judge_counts'
# >>   Swars::Membership Count (0.4ms)  SELECT COUNT(*) FROM `swars_memberships` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` WHERE `swars_memberships`.`id` IN (9818693, 8999691, 8999693, 8997060) AND `swars_battles`.`battled_at` >= '2024-07-10 05:36:34'
# >>   ↳ app/models/swars/user/stat/vitality_stat.rb:25:in `block in count'
# >>   Swars::Membership Count (0.3ms)  SELECT COUNT(*) FROM `swars_memberships` WHERE `swars_memberships`.`id` IN (9818693, 8999691, 8999693, 8997060)
# >>   ↳ app/models/swars/user/stat/scope_ext.rb:40:in `ids_count'
# >>   Swars::Membership Count (0.6ms)  SELECT COUNT(*) AS `count_all`, `swars_xmodes`.`key` AS `swars_xmodes_key`, `judges`.`key` AS `judges_key` FROM `swars_memberships` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` INNER JOIN `swars_xmodes` ON `swars_xmodes`.`id` = `swars_battles`.`xmode_id` INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` WHERE `swars_memberships`.`id` IN (9818693, 8999691, 8999693, 8997060) GROUP BY `swars_xmodes`.`key`, `judges`.`key`
# >>   ↳ app/models/swars/user/stat/xmode_judge_stat.rb:113:in `block in counts_hash'
# >>   Swars::Membership Count (0.6ms)  SELECT COUNT(*) AS `count_all`, `judges`.`key` AS `judges_key`, `swars_finals`.`key` AS `swars_finals_key` FROM `swars_memberships` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` INNER JOIN `swars_finals` ON `swars_finals`.`id` = `swars_battles`.`final_id` INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` WHERE `swars_memberships`.`id` IN (9818693, 8999691, 8999693, 8997060) AND `swars_battles`.`turn_max` >= 2 GROUP BY `judges`.`key`, `swars_finals`.`key`
# >>   ↳ app/models/swars/user/stat/judge_final_stat.rb:66:in `block in counts_hash'
# >>   Swars::Membership Average (0.7ms)  SELECT AVG(turn_max) AS `average_turn_max`, `judges`.`key` AS `judges_key` FROM `swars_memberships` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` WHERE `swars_memberships`.`id` IN (9818693, 8999691, 8999693, 8997060) GROUP BY `judges`.`key`
# >>   ↳ app/models/swars/user/stat/average_moves_by_outcome_stat.rb:30:in `block in averages_hash'
# >>   Swars::Membership Count (1.1ms)  SELECT COUNT(*) AS `count_all`, `tags`.`name` AS `tags_name`, `judges`.`key` AS `judges_key` FROM `swars_memberships` INNER JOIN `taggings` ON `taggings`.`taggable_type` = 'Swars::Membership' AND `taggings`.`taggable_id` = `swars_memberships`.`id` INNER JOIN `tags` ON `tags`.`id` = `taggings`.`tag_id` INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` WHERE `swars_memberships`.`id` IN (9818693, 8999691, 8999693, 8997060) GROUP BY `tags`.`name`, `judges`.`key`
# >>   ↳ app/models/swars/user/stat/tag_stat.rb:236:in `block in inside_counts_hash'
# >>   Swars::Membership Count (0.5ms)  SELECT COUNT(*) FROM `swars_memberships` INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` WHERE `swars_memberships`.`id` IN (9818693, 8999691, 8999693, 8997060) AND `judges`.`key` = 'draw'
# >>   ↳ app/models/swars/user/stat/sub_scope_methods.rb:43:in `draw_count'
# >>   Swars::Membership Average (0.3ms)  SELECT AVG(`swars_memberships`.`think_all_avg`) FROM `swars_memberships` WHERE `swars_memberships`.`id` IN (9818693, 8999691, 8999693, 8997060)
# >>   ↳ app/models/swars/user/stat/think_stat.rb:44:in `average'
# >>   Swars::Membership Count (0.7ms)  SELECT COUNT(*) FROM `swars_memberships` INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` INNER JOIN `swars_finals` ON `swars_finals`.`id` = `swars_battles`.`final_id` WHERE `swars_memberships`.`id` IN (9818693, 8999691, 8999693, 8997060) AND `judges`.`key` = 'lose' AND (`swars_finals`.`key` = 'TORYO' OR `swars_finals`.`key` = 'CHECKMATE') AND `swars_battles`.`turn_max` BETWEEN 14 AND 44
# >>   ↳ app/models/swars/user/stat/lethargy_stat.rb:32:in `block in count'
# >>   Swars::Membership Count (0.7ms)  SELECT COUNT(*) FROM `swars_memberships` INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` INNER JOIN `swars_finals` ON `swars_finals`.`id` = `swars_battles`.`final_id` WHERE `swars_memberships`.`id` IN (9818693, 8999691, 8999693, 8997060) AND `judges`.`key` = 'lose' AND (`swars_finals`.`key` = 'TORYO' OR `swars_finals`.`key` = 'CHECKMATE') AND `swars_battles`.`turn_max` < 14
# >>   ↳ app/models/swars/user/stat/skill_adjust_stat.rb:25:in `block in count'
# >>   Swars::Membership Count (0.7ms)  SELECT COUNT(*) FROM `swars_memberships` INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` INNER JOIN `swars_finals` ON `swars_finals`.`id` = `swars_battles`.`final_id` WHERE `swars_memberships`.`id` IN (9818693, 8999691, 8999693, 8997060) AND `judges`.`key` = 'win' AND `swars_memberships`.`think_last` >= 45 AND `swars_finals`.`key` = 'CHECKMATE'
# >>   ↳ app/models/swars/user/stat/taunt_mate_stat.rb:42:in `count'
# >>   Swars::Membership Count (0.7ms)  SELECT COUNT(*) FROM `swars_memberships` INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` INNER JOIN `swars_finals` ON `swars_finals`.`id` = `swars_battles`.`final_id` WHERE `swars_memberships`.`id` IN (9818693, 8999691, 8999693, 8997060) AND `judges`.`key` = 'win' AND `swars_memberships`.`think_last` >= 45 AND `swars_finals`.`key` = 'TIMEOUT'
# >>   ↳ app/models/swars/user/stat/taunt_mate_stat.rb:42:in `count'
# >>   Swars::Membership Count (0.4ms)  SELECT COUNT(*) FROM `swars_memberships` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` WHERE `swars_memberships`.`id` IN (9818693, 8999691, 8999693, 8997060) AND (`swars_memberships`.`ai_wave_count` >= 3 OR `swars_memberships`.`ai_drop_total` >= 15 OR `swars_memberships`.`ai_two_freq` >= 0.6 AND `swars_battles`.`turn_max` >= 50 OR `swars_memberships`.`ai_gear_freq` >= 0.22 AND `swars_battles`.`turn_max` >= 50)
# >>   ↳ app/models/swars/user/stat/fraud_stat.rb:13:in `count'
# >>   Swars::Membership Count (0.8ms)  SELECT COUNT(*) FROM `swars_memberships` INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` INNER JOIN `swars_xmodes` ON `swars_xmodes`.`id` = `swars_battles`.`xmode_id` WHERE `swars_memberships`.`id` IN (9818693, 8999691, 8999693, 8997060) AND `judges`.`key` = 'win' AND `swars_xmodes`.`key` = '野良' AND `swars_memberships`.`grade_diff` >= 10
# >>   ↳ app/models/swars/user/stat/gdiff_stat.rb:67:in `block in row_grade_pretend_count'
# >>   Swars::Membership Count (0.3ms)  SELECT COUNT(*) FROM `swars_memberships` WHERE `swars_memberships`.`id` IN (9818693, 8999691, 8999693, 8997060) AND `swars_memberships`.`think_max` >= 180
# >>   ↳ app/models/swars/user/stat/prolonged_deliberation_stat.rb:27:in `block in count'
# >>   Swars::Membership Count (0.7ms)  SELECT COUNT(*) FROM `swars_memberships` INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` INNER JOIN `swars_finals` ON `swars_finals`.`id` = `swars_battles`.`final_id` WHERE `swars_memberships`.`id` IN (9818693, 8999691, 8999693, 8997060) AND `judges`.`key` = 'lose' AND `swars_finals`.`key` = 'TIMEOUT' AND `swars_memberships`.`think_last` >= 60
# >>   ↳ app/models/swars/user/stat/leave_alone_stat.rb:49:in `count'
# >>   Swars::Membership Count (0.7ms)  SELECT COUNT(*) FROM `swars_memberships` INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` WHERE `swars_memberships`.`id` IN (9818693, 8999691, 8999693, 8997060) AND `judges`.`key` = 'lose' AND `swars_memberships`.`think_last` IS NOT NULL AND `swars_memberships`.`think_max` != `swars_memberships`.`think_last` AND `swars_memberships`.`think_max` >= 300 AND `swars_battles`.`turn_max` >= 14
# >>   ↳ app/models/swars/user/stat/waiting_to_leave_stat.rb:34:in `block in count'
# >>   Swars::Membership Count (0.7ms)  SELECT COUNT(*) FROM `swars_memberships` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` INNER JOIN `swars_finals` ON `swars_finals`.`id` = `swars_battles`.`final_id` INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` WHERE `swars_memberships`.`id` IN (9818693, 8999691, 8999693, 8997060) AND `swars_battles`.`turn_max` < 2 AND `swars_finals`.`key` = 'DISCONNECT' AND `judges`.`key` = 'lose'
# >>   ↳ app/models/swars/user/stat/unstable_network_stat.rb:28:in `block in count'
# >>   Swars::Membership Pluck (0.3ms)  SELECT `swars_memberships`.`id` FROM `swars_memberships` WHERE `swars_memberships`.`id` IN (9818693, 8999691, 8999693, 8997060)
# >>   ↳ app/models/swars/user/stat/simple_matrix_stat.rb:73:in `find_one'
# >>   ActsAsTaggableOn::Tag Load (1.2ms)  SELECT tags.*, taggings.tags_count AS count FROM `tags` JOIN (SELECT taggings.tag_id, COUNT(taggings.tag_id) AS tags_count FROM `taggings` WHERE (taggings.taggable_type = 'Swars::Membership' AND taggings.context = 'attack_tags') AND (taggings.taggable_id IN ('8997060','8999691','8999693','9818693')) GROUP BY `taggings`.`tag_id` HAVING (COUNT(taggings.tag_id) > 0)) AS taggings ON taggings.tag_id = tags.id ORDER BY count DESC, tags.id ASC LIMIT 1
# >>   ↳ app/models/swars/user/stat/simple_matrix_stat.rb:79:in `find_one'
# >>   Swars::Membership Pluck (0.3ms)  SELECT `swars_memberships`.`id` FROM `swars_memberships` WHERE `swars_memberships`.`id` IN (9818693, 8999691, 8999693, 8997060)
# >>   ↳ app/models/swars/user/stat/simple_matrix_stat.rb:73:in `find_one'
# >>   ActsAsTaggableOn::Tag Load (0.9ms)  SELECT tags.*, taggings.tags_count AS count FROM `tags` JOIN (SELECT taggings.tag_id, COUNT(taggings.tag_id) AS tags_count FROM `taggings` WHERE (taggings.taggable_type = 'Swars::Membership' AND taggings.context = 'defense_tags') AND (taggings.taggable_id IN ('8997060','8999691','8999693','9818693')) GROUP BY `taggings`.`tag_id` HAVING (COUNT(taggings.tag_id) > 0)) AS taggings ON taggings.tag_id = tags.id ORDER BY count DESC, tags.id ASC LIMIT 1
# >>   ↳ app/models/swars/user/stat/simple_matrix_stat.rb:79:in `find_one'
# >>   Swars::Membership Ids (0.4ms)  SELECT `swars_memberships`.`id` FROM `swars_memberships` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` WHERE `swars_memberships`.`user_id` = 23501 ORDER BY `swars_battles`.`battled_at` DESC LIMIT 50
# >>   ↳ app/models/swars/user/stat/scope_ext.rb:30:in `scope_ids'
# >>   Swars::Membership Load (0.4ms)  SELECT swars_rules.key AS rule_key, MIN(swars_grades.priority) AS min_priority FROM `swars_memberships` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` INNER JOIN `swars_rules` ON `swars_rules`.`id` = `swars_battles`.`rule_id` INNER JOIN `swars_grades` ON `swars_grades`.`id` = `swars_memberships`.`grade_id` WHERE `swars_memberships`.`id` = 9818692 GROUP BY `rule_key`
# >>   ↳ app/models/swars/user/stat/grade_by_rules_stat.rb:40:in `block (2 levels) in grades_hash'
# >>   Swars::Membership Count (0.4ms)  SELECT COUNT(*) AS `count_all`, `judges`.`key` AS `judges_key` FROM `swars_memberships` INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` WHERE `swars_memberships`.`id` = 9818692 GROUP BY `judges`.`key`
# >>   ↳ app/models/swars/user/stat/membership_global_extension.rb:14:in `total_judge_counts'
# >>   Swars::Membership Count (0.3ms)  SELECT COUNT(*) FROM `swars_memberships` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` WHERE `swars_memberships`.`id` = 9818692 AND `swars_battles`.`battled_at` >= '2024-07-10 05:36:34'
# >>   ↳ app/models/swars/user/stat/vitality_stat.rb:25:in `block in count'
# >>   Swars::Membership Count (0.3ms)  SELECT COUNT(*) FROM `swars_memberships` WHERE `swars_memberships`.`id` = 9818692
# >>   ↳ app/models/swars/user/stat/scope_ext.rb:40:in `ids_count'
# >>   Swars::Membership Count (0.4ms)  SELECT COUNT(*) AS `count_all`, `swars_xmodes`.`key` AS `swars_xmodes_key`, `judges`.`key` AS `judges_key` FROM `swars_memberships` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` INNER JOIN `swars_xmodes` ON `swars_xmodes`.`id` = `swars_battles`.`xmode_id` INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` WHERE `swars_memberships`.`id` = 9818692 GROUP BY `swars_xmodes`.`key`, `judges`.`key`
# >>   ↳ app/models/swars/user/stat/xmode_judge_stat.rb:113:in `block in counts_hash'
# >>   Swars::Membership Count (0.4ms)  SELECT COUNT(*) AS `count_all`, `judges`.`key` AS `judges_key`, `swars_finals`.`key` AS `swars_finals_key` FROM `swars_memberships` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` INNER JOIN `swars_finals` ON `swars_finals`.`id` = `swars_battles`.`final_id` INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` WHERE `swars_memberships`.`id` = 9818692 AND `swars_battles`.`turn_max` >= 2 GROUP BY `judges`.`key`, `swars_finals`.`key`
# >>   ↳ app/models/swars/user/stat/judge_final_stat.rb:66:in `block in counts_hash'
# >>   Swars::Membership Average (0.4ms)  SELECT AVG(turn_max) AS `average_turn_max`, `judges`.`key` AS `judges_key` FROM `swars_memberships` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` WHERE `swars_memberships`.`id` = 9818692 GROUP BY `judges`.`key`
# >>   ↳ app/models/swars/user/stat/average_moves_by_outcome_stat.rb:30:in `block in averages_hash'
# >>   Swars::Membership Count (0.7ms)  SELECT COUNT(*) AS `count_all`, `tags`.`name` AS `tags_name`, `judges`.`key` AS `judges_key` FROM `swars_memberships` INNER JOIN `taggings` ON `taggings`.`taggable_type` = 'Swars::Membership' AND `taggings`.`taggable_id` = `swars_memberships`.`id` INNER JOIN `tags` ON `tags`.`id` = `taggings`.`tag_id` INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` WHERE `swars_memberships`.`id` = 9818692 GROUP BY `tags`.`name`, `judges`.`key`
# >>   ↳ app/models/swars/user/stat/tag_stat.rb:236:in `block in inside_counts_hash'
# >>   Swars::Membership Count (0.3ms)  SELECT COUNT(*) FROM `swars_memberships` INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` WHERE `swars_memberships`.`id` = 9818692 AND `judges`.`key` = 'draw'
# >>   ↳ app/models/swars/user/stat/sub_scope_methods.rb:43:in `draw_count'
# >>   Swars::Membership Average (0.2ms)  SELECT AVG(`swars_memberships`.`think_all_avg`) FROM `swars_memberships` WHERE `swars_memberships`.`id` = 9818692
# >>   ↳ app/models/swars/user/stat/think_stat.rb:44:in `average'
# >>   Swars::Membership Count (0.4ms)  SELECT COUNT(*) FROM `swars_memberships` INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` INNER JOIN `swars_finals` ON `swars_finals`.`id` = `swars_battles`.`final_id` WHERE `swars_memberships`.`id` = 9818692 AND `judges`.`key` = 'lose' AND (`swars_finals`.`key` = 'TORYO' OR `swars_finals`.`key` = 'CHECKMATE') AND `swars_battles`.`turn_max` BETWEEN 14 AND 44
# >>   ↳ app/models/swars/user/stat/lethargy_stat.rb:32:in `block in count'
# >>   Swars::Membership Count (0.4ms)  SELECT COUNT(*) FROM `swars_memberships` INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` INNER JOIN `swars_finals` ON `swars_finals`.`id` = `swars_battles`.`final_id` WHERE `swars_memberships`.`id` = 9818692 AND `judges`.`key` = 'lose' AND (`swars_finals`.`key` = 'TORYO' OR `swars_finals`.`key` = 'CHECKMATE') AND `swars_battles`.`turn_max` < 14
# >>   ↳ app/models/swars/user/stat/skill_adjust_stat.rb:25:in `block in count'
# >>   Swars::Membership Count (0.3ms)  SELECT COUNT(*) FROM `swars_memberships` INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` INNER JOIN `swars_finals` ON `swars_finals`.`id` = `swars_battles`.`final_id` WHERE `swars_memberships`.`id` = 9818692 AND `judges`.`key` = 'win' AND `swars_memberships`.`think_last` >= 45 AND `swars_finals`.`key` = 'CHECKMATE'
# >>   ↳ app/models/swars/user/stat/taunt_mate_stat.rb:42:in `count'
# >>   Swars::Membership Count (0.3ms)  SELECT COUNT(*) FROM `swars_memberships` INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` INNER JOIN `swars_finals` ON `swars_finals`.`id` = `swars_battles`.`final_id` WHERE `swars_memberships`.`id` = 9818692 AND `judges`.`key` = 'win' AND `swars_memberships`.`think_last` >= 45 AND `swars_finals`.`key` = 'TIMEOUT'
# >>   ↳ app/models/swars/user/stat/taunt_mate_stat.rb:42:in `count'
# >>   Swars::Membership Count (0.4ms)  SELECT COUNT(*) FROM `swars_memberships` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` WHERE `swars_memberships`.`id` = 9818692 AND (`swars_memberships`.`ai_wave_count` >= 3 OR `swars_memberships`.`ai_drop_total` >= 15 OR `swars_memberships`.`ai_two_freq` >= 0.6 AND `swars_battles`.`turn_max` >= 50 OR `swars_memberships`.`ai_gear_freq` >= 0.22 AND `swars_battles`.`turn_max` >= 50)
# >>   ↳ app/models/swars/user/stat/fraud_stat.rb:13:in `count'
# >>   Swars::Membership Count (0.3ms)  SELECT COUNT(*) FROM `swars_memberships` INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` INNER JOIN `swars_xmodes` ON `swars_xmodes`.`id` = `swars_battles`.`xmode_id` WHERE `swars_memberships`.`id` = 9818692 AND `judges`.`key` = 'win' AND `swars_xmodes`.`key` = '野良' AND `swars_memberships`.`grade_diff` >= 10
# >>   ↳ app/models/swars/user/stat/gdiff_stat.rb:67:in `block in row_grade_pretend_count'
# >>   Swars::Membership Count (0.3ms)  SELECT COUNT(*) FROM `swars_memberships` WHERE `swars_memberships`.`id` = 9818692 AND `swars_memberships`.`think_max` >= 180
# >>   ↳ app/models/swars/user/stat/prolonged_deliberation_stat.rb:27:in `block in count'
# >>   Swars::Membership Count (0.4ms)  SELECT COUNT(*) FROM `swars_memberships` INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` INNER JOIN `swars_finals` ON `swars_finals`.`id` = `swars_battles`.`final_id` WHERE `swars_memberships`.`id` = 9818692 AND `judges`.`key` = 'lose' AND `swars_finals`.`key` = 'TIMEOUT' AND `swars_memberships`.`think_last` >= 60
# >>   ↳ app/models/swars/user/stat/leave_alone_stat.rb:49:in `count'
# >>   Swars::Membership Count (0.4ms)  SELECT COUNT(*) FROM `swars_memberships` INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` WHERE `swars_memberships`.`id` = 9818692 AND `judges`.`key` = 'lose' AND `swars_memberships`.`think_last` IS NOT NULL AND `swars_memberships`.`think_max` != `swars_memberships`.`think_last` AND `swars_memberships`.`think_max` >= 300 AND `swars_battles`.`turn_max` >= 14
# >>   ↳ app/models/swars/user/stat/waiting_to_leave_stat.rb:34:in `block in count'
# >>   Swars::Membership Count (0.4ms)  SELECT COUNT(*) FROM `swars_memberships` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` INNER JOIN `swars_finals` ON `swars_finals`.`id` = `swars_battles`.`final_id` INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` WHERE `swars_memberships`.`id` = 9818692 AND `swars_battles`.`turn_max` < 2 AND `swars_finals`.`key` = 'DISCONNECT' AND `judges`.`key` = 'lose'
# >>   ↳ app/models/swars/user/stat/unstable_network_stat.rb:28:in `block in count'
# >>   Swars::Membership Pluck (0.2ms)  SELECT `swars_memberships`.`id` FROM `swars_memberships` WHERE `swars_memberships`.`id` = 9818692
# >>   ↳ app/models/swars/user/stat/simple_matrix_stat.rb:73:in `find_one'
# >>   ActsAsTaggableOn::Tag Load (0.8ms)  SELECT tags.*, taggings.tags_count AS count FROM `tags` JOIN (SELECT taggings.tag_id, COUNT(taggings.tag_id) AS tags_count FROM `taggings` WHERE (taggings.taggable_type = 'Swars::Membership' AND taggings.context = 'attack_tags') AND (taggings.taggable_id IN ('9818692')) GROUP BY `taggings`.`tag_id` HAVING (COUNT(taggings.tag_id) > 0)) AS taggings ON taggings.tag_id = tags.id ORDER BY count DESC, tags.id ASC LIMIT 1
# >>   ↳ app/models/swars/user/stat/simple_matrix_stat.rb:79:in `find_one'
# >>   Swars::Membership Pluck (0.2ms)  SELECT `swars_memberships`.`id` FROM `swars_memberships` WHERE `swars_memberships`.`id` = 9818692
# >>   ↳ app/models/swars/user/stat/simple_matrix_stat.rb:73:in `find_one'
# >>   ActsAsTaggableOn::Tag Load (0.7ms)  SELECT tags.*, taggings.tags_count AS count FROM `tags` JOIN (SELECT taggings.tag_id, COUNT(taggings.tag_id) AS tags_count FROM `taggings` WHERE (taggings.taggable_type = 'Swars::Membership' AND taggings.context = 'defense_tags') AND (taggings.taggable_id IN ('9818692')) GROUP BY `taggings`.`tag_id` HAVING (COUNT(taggings.tag_id) > 0)) AS taggings ON taggings.tag_id = tags.id ORDER BY count DESC, tags.id ASC LIMIT 1
# >>   ↳ app/models/swars/user/stat/simple_matrix_stat.rb:79:in `find_one'
# >> |------------------------------------------------------------------------------------------------------+------+------+-----+------+------+------+-------+--------+----------+----------+--------------+------------+--------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------+-----------------|
# >> | 名前                                                                                                 | 最高 | 10分 | 3分 | 10秒 | 勝率 | 勢い | 規範  | 居飛車 | 振り飛車 | 主戦法   | 主囲い       | 直近対局   | リンク1                                                                                          | リンク2                                                                                                   | リンク3                                                                                | リンク4                                                                                               | 最高段位(index) |
# >> |------------------------------------------------------------------------------------------------------+------+------+-----+------+------+------+-------+--------+----------+----------+--------------+------------+--------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------+-----------------|
# >> | {:_nuxt_link=>{:name=>"SiroChannel", :to=>{:name=>"swars-search", :query=>{:query=>"SiroChannel"}}}} | 十段 | 十段 |     |      | 75 % | 0.00 | 87 点 | 0 %    | 100 %    | 四間飛車 | 高美濃囲い   | 2024-06-28 | {:_nuxt_link=>{:name=>"棋譜(4)", :to=>{:name=>"swars-search", :query=>{:query=>"SiroChannel"}}}} | {:_nuxt_link=>{:name=>"プレイヤー情報", :to=>{:name=>"swars-users-key", :params=>{:key=>"SiroChannel"}}}} | <a href="https://shogiwars.heroz.jp/users/mypage/SiroChannel" target="_blank">本家</a> | <a href="https://www.google.co.jp/search?q=SiroChannel+%E5%B0%86%E6%A3%8B" target="_blank">ググる</a> |               0 |
# >> | {:_nuxt_link=>{:name=>"Kato_Hifumi", :to=>{:name=>"swars-search", :query=>{:query=>"Kato_Hifumi"}}}} | 十段 | 十段 |     |      | 0 %  | 0.00 | 99 点 | 100 %  | 0 %      | 棒銀     | ボナンザ囲い | 2024-06-28 | {:_nuxt_link=>{:name=>"棋譜(1)", :to=>{:name=>"swars-search", :query=>{:query=>"Kato_Hifumi"}}}} | {:_nuxt_link=>{:name=>"プレイヤー情報", :to=>{:name=>"swars-users-key", :params=>{:key=>"Kato_Hifumi"}}}} | <a href="https://shogiwars.heroz.jp/users/mypage/Kato_Hifumi" target="_blank">本家</a> | <a href="https://www.google.co.jp/search?q=Kato_Hifumi+%E5%B0%86%E6%A3%8B" target="_blank">ググる</a> |               0 |
# >> |------------------------------------------------------------------------------------------------------+------+------+-----+------+------+------+-------+--------+----------+----------+--------------+------------+--------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------+-----------------|
