#!/usr/bin/env ruby
require File.expand_path('../../config/environment', __FILE__)

list = ActiveRecord::Base.connection.tables.sort.flat_map do |table|
  ActiveRecord::Base.connection.indexes(table).collect do |obj|
    [:table, :name, :unique, :columns, :lengths, :orders, :opclasses, :where, :type, :using, :comment].inject({}) { |a, e| a.merge(e => obj.send(e)) }
  end
end
tp list
# >> |--------------------------------+-------------------------------------------------------------+--------+-----------------------------------------------------------------------------------+---------+--------+-----------+-------+------+-------+---------|
# >> | table                          | name                                                        | unique | columns                                                                           | lengths | orders | opclasses | where | type | using | comment |
# >> |--------------------------------+-------------------------------------------------------------+--------+-----------------------------------------------------------------------------------+---------+--------+-----------+-------+------+-------+---------|
# >> | active_storage_attachments     | index_active_storage_attachments_uniqueness                 | true   | ["record_type", "record_id", "name", "blob_id"]                                   | {}      | {}     | {}        |       |      | btree |         |
# >> | active_storage_attachments     | index_active_storage_attachments_on_blob_id                 | false  | ["blob_id"]                                                                       | {}      | {}     | {}        |       |      | btree |         |
# >> | active_storage_blobs           | index_active_storage_blobs_on_key                           | true   | ["key"]                                                                           | {}      | {}     | {}        |       |      | btree |         |
# >> | active_storage_variant_records | index_active_storage_variant_records_uniqueness             | true   | ["blob_id", "variation_digest"]                                                   | {}      | {}     | {}        |       |      | btree |         |
# >> | auth_infos                     | index_auth_infos_on_provider_and_uid                        | true   | ["provider", "uid"]                                                               | {}      | {}     | {}        |       |      | btree |         |
# >> | auth_infos                     | index_auth_infos_on_user_id                                 | false  | ["user_id"]                                                                       | {}      | {}     | {}        |       |      | btree |         |
# >> | cpu_battle_records             | index_cpu_battle_records_on_judge_key                       | false  | ["judge_key"]                                                                     | {}      | {}     | {}        |       |      | btree |         |
# >> | cpu_battle_records             | index_cpu_battle_records_on_user_id                         | false  | ["user_id"]                                                                       | {}      | {}     | {}        |       |      | btree |         |
# >> | emox_emotion_folders           | index_emox_emotion_folders_on_position                      | false  | ["position"]                                                                      | {}      | {}     | {}        |       |      | btree |         |
# >> | emox_finals                    | index_emox_finals_on_position                               | false  | ["position"]                                                                      | {}      | {}     | {}        |       |      | btree |         |
# >> | emox_judges                    | index_emox_judges_on_position                               | false  | ["position"]                                                                      | {}      | {}     | {}        |       |      | btree |         |
# >> | emox_lineages                  | index_emox_lineages_on_position                             | false  | ["position"]                                                                      | {}      | {}     | {}        |       |      | btree |         |
# >> | emox_ox_marks                  | index_emox_ox_marks_on_key                                  | false  | ["key"]                                                                           | {}      | {}     | {}        |       |      | btree |         |
# >> | emox_ox_marks                  | index_emox_ox_marks_on_position                             | false  | ["position"]                                                                      | {}      | {}     | {}        |       |      | btree |         |
# >> | emox_rules                     | index_emox_rules_on_position                                | false  | ["position"]                                                                      | {}      | {}     | {}        |       |      | btree |         |
# >> | emox_seasons                   | index_emox_seasons_on_generation                            | false  | ["generation"]                                                                    | {}      | {}     | {}        |       |      | btree |         |
# >> | emox_seasons                   | index_emox_seasons_on_begin_at                              | false  | ["begin_at"]                                                                      | {}      | {}     | {}        |       |      | btree |         |
# >> | emox_seasons                   | index_emox_seasons_on_end_at                                | false  | ["end_at"]                                                                        | {}      | {}     | {}        |       |      | btree |         |
# >> | emox_skills                    | index_emox_skills_on_position                               | false  | ["position"]                                                                      | {}      | {}     | {}        |       |      | btree |         |
# >> | emox_source_abouts             | index_emox_source_abouts_on_position                        | false  | ["position"]                                                                      | {}      | {}     | {}        |       |      | btree |         |
# >> | free_battles                   | index_free_battles_on_key                                   | true   | ["key"]                                                                           | {}      | {}     | {}        |       |      | btree |         |
# >> | free_battles                   | index_free_battles_on_battled_at                            | false  | ["battled_at"]                                                                    | {}      | {}     | {}        |       |      | btree |         |
# >> | free_battles                   | index_free_battles_on_turn_max                              | false  | ["turn_max"]                                                                      | {}      | {}     | {}        |       |      | btree |         |
# >> | free_battles                   | index_free_battles_on_critical_turn                         | false  | ["critical_turn"]                                                                 | {}      | {}     | {}        |       |      | btree |         |
# >> | free_battles                   | index_free_battles_on_saturn_key                            | false  | ["saturn_key"]                                                                    | {}      | {}     | {}        |       |      | btree |         |
# >> | free_battles                   | index_free_battles_on_outbreak_turn                         | false  | ["outbreak_turn"]                                                                 | {}      | {}     | {}        |       |      | btree |         |
# >> | free_battles                   | index_free_battles_on_use_key                               | false  | ["use_key"]                                                                       | {}      | {}     | {}        |       |      | btree |         |
# >> | free_battles                   | index_free_battles_on_user_id                               | false  | ["user_id"]                                                                       | {}      | {}     | {}        |       |      | btree |         |
# >> | free_battles                   | index_free_battles_on_accessed_at                           | false  | ["accessed_at"]                                                                   | {}      | {}     | {}        |       |      | btree |         |
# >> | free_battles                   | index_free_battles_on_preset_id                             | false  | ["preset_id"]                                                                     | {}      | {}     | {}        |       |      | btree |         |
# >> | judges                         | index_judges_on_key                                         | true   | ["key"]                                                                           | {}      | {}     | {}        |       |      | btree |         |
# >> | judges                         | index_judges_on_position                                    | false  | ["position"]                                                                      | {}      | {}     | {}        |       |      | btree |         |
# >> | kiwi_access_logs               | index_kiwi_access_logs_on_user_id                           | false  | ["user_id"]                                                                       | {}      | {}     | {}        |       |      | btree |         |
# >> | kiwi_access_logs               | index_kiwi_access_logs_on_banana_id                         | false  | ["banana_id"]                                                                     | {}      | {}     | {}        |       |      | btree |         |
# >> | kiwi_banana_messages           | index_kiwi_banana_messages_on_banana_id_and_position        | true   | ["banana_id", "position"]                                                         | {}      | {}     | {}        |       |      | btree |         |
# >> | kiwi_banana_messages           | index_kiwi_banana_messages_on_user_id                       | false  | ["user_id"]                                                                       | {}      | {}     | {}        |       |      | btree |         |
# >> | kiwi_banana_messages           | index_kiwi_banana_messages_on_banana_id                     | false  | ["banana_id"]                                                                     | {}      | {}     | {}        |       |      | btree |         |
# >> | kiwi_banana_messages           | index_kiwi_banana_messages_on_position                      | false  | ["position"]                                                                      | {}      | {}     | {}        |       |      | btree |         |
# >> | kiwi_bananas                   | index_kiwi_bananas_on_key                                   | true   | ["key"]                                                                           | {}      | {}     | {}        |       |      | btree |         |
# >> | kiwi_bananas                   | index_kiwi_bananas_on_lemon_id                              | true   | ["lemon_id"]                                                                      | {}      | {}     | {}        |       |      | btree |         |
# >> | kiwi_bananas                   | index_kiwi_bananas_on_user_id                               | false  | ["user_id"]                                                                       | {}      | {}     | {}        |       |      | btree |         |
# >> | kiwi_bananas                   | index_kiwi_bananas_on_folder_id                             | false  | ["folder_id"]                                                                     | {}      | {}     | {}        |       |      | btree |         |
# >> | kiwi_bananas                   | index_kiwi_bananas_on_banana_messages_count                 | false  | ["banana_messages_count"]                                                         | {}      | {}     | {}        |       |      | btree |         |
# >> | kiwi_bananas                   | index_kiwi_bananas_on_access_logs_count                     | false  | ["access_logs_count"]                                                             | {}      | {}     | {}        |       |      | btree |         |
# >> | kiwi_book_messages             | index_kiwi_book_messages_on_book_id_and_position            | true   | ["book_id", "position"]                                                           | {}      | {}     | {}        |       |      | btree |         |
# >> | kiwi_book_messages             | index_kiwi_book_messages_on_user_id                         | false  | ["user_id"]                                                                       | {}      | {}     | {}        |       |      | btree |         |
# >> | kiwi_book_messages             | index_kiwi_book_messages_on_book_id                         | false  | ["book_id"]                                                                       | {}      | {}     | {}        |       |      | btree |         |
# >> | kiwi_book_messages             | index_kiwi_book_messages_on_position                        | false  | ["position"]                                                                      | {}      | {}     | {}        |       |      | btree |         |
# >> | kiwi_books                     | index_kiwi_books_on_key                                     | true   | ["key"]                                                                           | {}      | {}     | {}        |       |      | btree |         |
# >> | kiwi_books                     | index_kiwi_books_on_lemon_id                                | true   | ["lemon_id"]                                                                      | {}      | {}     | {}        |       |      | btree |         |
# >> | kiwi_books                     | index_kiwi_books_on_user_id                                 | false  | ["user_id"]                                                                       | {}      | {}     | {}        |       |      | btree |         |
# >> | kiwi_books                     | index_kiwi_books_on_folder_id                               | false  | ["folder_id"]                                                                     | {}      | {}     | {}        |       |      | btree |         |
# >> | kiwi_books                     | index_kiwi_books_on_book_messages_count                     | false  | ["book_messages_count"]                                                           | {}      | {}     | {}        |       |      | btree |         |
# >> | kiwi_books                     | index_kiwi_books_on_access_logs_count                       | false  | ["access_logs_count"]                                                             | {}      | {}     | {}        |       |      | btree |         |
# >> | kiwi_folders                   | index_kiwi_folders_on_key                                   | true   | ["key"]                                                                           | {}      | {}     | {}        |       |      | btree |         |
# >> | kiwi_folders                   | index_kiwi_folders_on_position                              | false  | ["position"]                                                                      | {}      | {}     | {}        |       |      | btree |         |
# >> | kiwi_lemons                    | index_kiwi_lemons_on_user_id                                | false  | ["user_id"]                                                                       | {}      | {}     | {}        |       |      | btree |         |
# >> | kiwi_lemons                    | index_kiwi_lemons_on_recordable_type_and_recordable_id      | false  | ["recordable_type", "recordable_id"]                                              | {}      | {}     | {}        |       |      | btree |         |
# >> | kiwi_lemons                    | index_kiwi_lemons_on_process_begin_at                       | false  | ["process_begin_at"]                                                              | {}      | {}     | {}        |       |      | btree |         |
# >> | kiwi_lemons                    | index_kiwi_lemons_on_process_end_at                         | false  | ["process_end_at"]                                                                | {}      | {}     | {}        |       |      | btree |         |
# >> | kiwi_lemons                    | index_kiwi_lemons_on_successed_at                           | false  | ["successed_at"]                                                                  | {}      | {}     | {}        |       |      | btree |         |
# >> | kiwi_lemons                    | index_kiwi_lemons_on_errored_at                             | false  | ["errored_at"]                                                                    | {}      | {}     | {}        |       |      | btree |         |
# >> | kiwi_lemons                    | index_kiwi_lemons_on_created_at                             | false  | ["created_at"]                                                                    | {}      | {}     | {}        |       |      | btree |         |
# >> | locations                      | index_locations_on_key                                      | true   | ["key"]                                                                           | {}      | {}     | {}        |       |      | btree |         |
# >> | locations                      | index_locations_on_position                                 | false  | ["position"]                                                                      | {}      | {}     | {}        |       |      | btree |         |
# >> | mute_infos                     | index_mute_infos_on_user_id_and_target_user_id              | true   | ["user_id", "target_user_id"]                                                     | {}      | {}     | {}        |       |      | btree |         |
# >> | mute_infos                     | index_mute_infos_on_user_id                                 | false  | ["user_id"]                                                                       | {}      | {}     | {}        |       |      | btree |         |
# >> | mute_infos                     | index_mute_infos_on_target_user_id                          | false  | ["target_user_id"]                                                                | {}      | {}     | {}        |       |      | btree |         |
# >> | presets                        | index_presets_on_key                                        | true   | ["key"]                                                                           | {}      | {}     | {}        |       |      | btree |         |
# >> | presets                        | index_presets_on_position                                   | false  | ["position"]                                                                      | {}      | {}     | {}        |       |      | btree |         |
# >> | profiles                       | index_profiles_on_user_id                                   | true   | ["user_id"]                                                                       | {}      | {}     | {}        |       |      | btree |         |
# >> | share_board_battles            | index_share_board_battles_on_key                            | true   | ["key"]                                                                           | {}      | {}     | {}        |       |      | btree |         |
# >> | share_board_battles            | index_share_board_battles_on_room_id                        | false  | ["room_id"]                                                                       | {}      | {}     | {}        |       |      | btree |         |
# >> | share_board_battles            | index_share_board_battles_on_turn                           | false  | ["turn"]                                                                          | {}      | {}     | {}        |       |      | btree |         |
# >> | share_board_battles            | index_share_board_battles_on_win_location_id                | false  | ["win_location_id"]                                                               | {}      | {}     | {}        |       |      | btree |         |
# >> | share_board_battles            | index_share_board_battles_on_position                       | false  | ["position"]                                                                      | {}      | {}     | {}        |       |      | btree |         |
# >> | share_board_chat_messages      | index_share_board_chat_messages_on_room_id                  | false  | ["room_id"]                                                                       | {}      | {}     | {}        |       |      | btree |         |
# >> | share_board_chat_messages      | index_share_board_chat_messages_on_user_id                  | false  | ["user_id"]                                                                       | {}      | {}     | {}        |       |      | btree |         |
# >> | share_board_chat_messages      | index_share_board_chat_messages_on_message_scope_id         | false  | ["message_scope_id"]                                                              | {}      | {}     | {}        |       |      | btree |         |
# >> | share_board_chat_messages      | index_share_board_chat_messages_on_session_user_id          | false  | ["session_user_id"]                                                               | {}      | {}     | {}        |       |      | btree |         |
# >> | share_board_memberships        | index_share_board_memberships_on_battle_id                  | false  | ["battle_id"]                                                                     | {}      | {}     | {}        |       |      | btree |         |
# >> | share_board_memberships        | index_share_board_memberships_on_user_id                    | false  | ["user_id"]                                                                       | {}      | {}     | {}        |       |      | btree |         |
# >> | share_board_memberships        | index_share_board_memberships_on_judge_id                   | false  | ["judge_id"]                                                                      | {}      | {}     | {}        |       |      | btree |         |
# >> | share_board_memberships        | index_share_board_memberships_on_location_id                | false  | ["location_id"]                                                                   | {}      | {}     | {}        |       |      | btree |         |
# >> | share_board_memberships        | index_share_board_memberships_on_position                   | false  | ["position"]                                                                      | {}      | {}     | {}        |       |      | btree |         |
# >> | share_board_message_scopes     | index_share_board_message_scopes_on_key                     | true   | ["key"]                                                                           | {}      | {}     | {}        |       |      | btree |         |
# >> | share_board_message_scopes     | index_share_board_message_scopes_on_position                | false  | ["position"]                                                                      | {}      | {}     | {}        |       |      | btree |         |
# >> | share_board_rooms              | index_share_board_rooms_on_key                              | true   | ["key"]                                                                           | {}      | {}     | {}        |       |      | btree |         |
# >> | share_board_roomships          | index_share_board_roomships_on_room_id                      | false  | ["room_id"]                                                                       | {}      | {}     | {}        |       |      | btree |         |
# >> | share_board_roomships          | index_share_board_roomships_on_user_id                      | false  | ["user_id"]                                                                       | {}      | {}     | {}        |       |      | btree |         |
# >> | share_board_roomships          | index_share_board_roomships_on_win_count                    | false  | ["win_count"]                                                                     | {}      | {}     | {}        |       |      | btree |         |
# >> | share_board_roomships          | index_share_board_roomships_on_lose_count                   | false  | ["lose_count"]                                                                    | {}      | {}     | {}        |       |      | btree |         |
# >> | share_board_roomships          | index_share_board_roomships_on_win_rate                     | false  | ["win_rate"]                                                                      | {}      | {}     | {}        |       |      | btree |         |
# >> | share_board_roomships          | index_share_board_roomships_on_score                        | false  | ["score"]                                                                         | {}      | {}     | {}        |       |      | btree |         |
# >> | share_board_roomships          | index_share_board_roomships_on_rank                         | false  | ["rank"]                                                                          | {}      | {}     | {}        |       |      | btree |         |
# >> | share_board_users              | index_share_board_users_on_name                             | true   | ["name"]                                                                          | {}      | {}     | {}        |       |      | btree |         |
# >> | short_url_access_logs          | index_short_url_access_logs_on_component_id                 | false  | ["component_id"]                                                                  | {}      | {}     | {}        |       |      | btree |         |
# >> | short_url_components           | index_short_url_components_on_key                           | true   | ["key"]                                                                           | {}      | {}     | {}        |       |      | btree |         |
# >> | swars_ban_crawl_requests       | index_swars_ban_crawl_requests_on_user_id                   | false  | ["user_id"]                                                                       | {}      | {}     | {}        |       |      | btree |         |
# >> | swars_battles                  | index_swars_battles_on_key                                  | true   | ["key"]                                                                           | {}      | {}     | {}        |       |      | btree |         |
# >> | swars_battles                  | index_swars_battles_on_win_user_id                          | false  | ["win_user_id"]                                                                   | {}      | {}     | {}        |       |      | btree |         |
# >> | swars_battles                  | index_swars_battles_on_battled_at                           | false  | ["battled_at"]                                                                    | {}      | {}     | {}        |       |      | btree |         |
# >> | swars_battles                  | index_swars_battles_on_turn_max                             | false  | ["turn_max"]                                                                      | {}      | {}     | {}        |       |      | btree |         |
# >> | swars_battles                  | index_swars_battles_on_critical_turn                        | false  | ["critical_turn"]                                                                 | {}      | {}     | {}        |       |      | btree |         |
# >> | swars_battles                  | index_swars_battles_on_outbreak_turn                        | false  | ["outbreak_turn"]                                                                 | {}      | {}     | {}        |       |      | btree |         |
# >> | swars_battles                  | index_swars_battles_on_accessed_at                          | false  | ["accessed_at"]                                                                   | {}      | {}     | {}        |       |      | btree |         |
# >> | swars_battles                  | index_swars_battles_on_xmode_id                             | false  | ["xmode_id"]                                                                      | {}      | {}     | {}        |       |      | btree |         |
# >> | swars_battles                  | index_swars_battles_on_preset_id                            | false  | ["preset_id"]                                                                     | {}      | {}     | {}        |       |      | btree |         |
# >> | swars_battles                  | index_swars_battles_on_rule_id                              | false  | ["rule_id"]                                                                       | {}      | {}     | {}        |       |      | btree |         |
# >> | swars_battles                  | index_swars_battles_on_final_id                             | false  | ["final_id"]                                                                      | {}      | {}     | {}        |       |      | btree |         |
# >> | swars_crawl_reservations       | index_swars_crawl_reservations_on_user_id                   | false  | ["user_id"]                                                                       | {}      | {}     | {}        |       |      | btree |         |
# >> | swars_crawl_reservations       | index_swars_crawl_reservations_on_attachment_mode           | false  | ["attachment_mode"]                                                               | {}      | {}     | {}        |       |      | btree |         |
# >> | swars_finals                   | index_swars_finals_on_key                                   | true   | ["key"]                                                                           | {}      | {}     | {}        |       |      | btree |         |
# >> | swars_finals                   | index_swars_finals_on_position                              | false  | ["position"]                                                                      | {}      | {}     | {}        |       |      | btree |         |
# >> | swars_grades                   | index_swars_grades_on_key                                   | true   | ["key"]                                                                           | {}      | {}     | {}        |       |      | btree |         |
# >> | swars_grades                   | index_swars_grades_on_priority                              | false  | ["priority"]                                                                      | {}      | {}     | {}        |       |      | btree |         |
# >> | swars_membership_extras        | index_swars_membership_extras_on_membership_id              | true   | ["membership_id"]                                                                 | {}      | {}     | {}        |       |      | btree |         |
# >> | swars_memberships              | memberships_sbri_sbui                                       | true   | ["battle_id", "user_id"]                                                          | {}      | {}     | {}        |       |      | btree |         |
# >> | swars_memberships              | memberships_sbri_lk                                         | true   | ["battle_id", "location_id"]                                                      | {}      | {}     | {}        |       |      | btree |         |
# >> | swars_memberships              | memberships_bid_ouid                                        | true   | ["battle_id", "op_user_id"]                                                       | {}      | {}     | {}        |       |      | btree |         |
# >> | swars_memberships              | index_swars_memberships_on_battle_id                        | false  | ["battle_id"]                                                                     | {}      | {}     | {}        |       |      | btree |         |
# >> | swars_memberships              | index_swars_memberships_on_user_id                          | false  | ["user_id"]                                                                       | {}      | {}     | {}        |       |      | btree |         |
# >> | swars_memberships              | index_swars_memberships_on_grade_id                         | false  | ["grade_id"]                                                                      | {}      | {}     | {}        |       |      | btree |         |
# >> | swars_memberships              | index_swars_memberships_on_position                         | false  | ["position"]                                                                      | {}      | {}     | {}        |       |      | btree |         |
# >> | swars_memberships              | index_swars_memberships_on_grade_diff                       | false  | ["grade_diff"]                                                                    | {}      | {}     | {}        |       |      | btree |         |
# >> | swars_memberships              | index_swars_memberships_on_op_user_id                       | false  | ["op_user_id"]                                                                    | {}      | {}     | {}        |       |      | btree |         |
# >> | swars_memberships              | index_swars_memberships_on_judge_id                         | false  | ["judge_id"]                                                                      | {}      | {}     | {}        |       |      | btree |         |
# >> | swars_memberships              | index_swars_memberships_on_location_id                      | false  | ["location_id"]                                                                   | {}      | {}     | {}        |       |      | btree |         |
# >> | swars_memberships              | index_swars_memberships_on_style_id                         | false  | ["style_id"]                                                                      | {}      | {}     | {}        |       |      | btree |         |
# >> | swars_profiles                 | index_swars_profiles_on_user_id                             | false  | ["user_id"]                                                                       | {}      | {}     | {}        |       |      | btree |         |
# >> | swars_profiles                 | index_swars_profiles_on_ban_at                              | false  | ["ban_at"]                                                                        | {}      | {}     | {}        |       |      | btree |         |
# >> | swars_rules                    | index_swars_rules_on_key                                    | true   | ["key"]                                                                           | {}      | {}     | {}        |       |      | btree |         |
# >> | swars_rules                    | index_swars_rules_on_position                               | false  | ["position"]                                                                      | {}      | {}     | {}        |       |      | btree |         |
# >> | swars_search_logs              | index_swars_search_logs_on_user_id                          | false  | ["user_id"]                                                                       | {}      | {}     | {}        |       |      | btree |         |
# >> | swars_styles                   | index_swars_styles_on_key                                   | true   | ["key"]                                                                           | {}      | {}     | {}        |       |      | btree |         |
# >> | swars_styles                   | index_swars_styles_on_position                              | false  | ["position"]                                                                      | {}      | {}     | {}        |       |      | btree |         |
# >> | swars_users                    | index_swars_users_on_user_key                               | true   | ["user_key"]                                                                      | {}      | {}     | {}        |       |      | btree |         |
# >> | swars_users                    | index_swars_users_on_grade_id                               | false  | ["grade_id"]                                                                      | {}      | {}     | {}        |       |      | btree |         |
# >> | swars_users                    | index_swars_users_on_last_reception_at                      | false  | ["last_reception_at"]                                                             | {}      | {}     | {}        |       |      | btree |         |
# >> | swars_users                    | index_swars_users_on_updated_at                             | false  | ["updated_at"]                                                                    | {}      | {}     | {}        |       |      | btree |         |
# >> | swars_users                    | index_swars_users_on_ban_at                                 | false  | ["ban_at"]                                                                        | {}      | {}     | {}        |       |      | btree |         |
# >> | swars_xmodes                   | index_swars_xmodes_on_key                                   | true   | ["key"]                                                                           | {}      | {}     | {}        |       |      | btree |         |
# >> | swars_xmodes                   | index_swars_xmodes_on_position                              | false  | ["position"]                                                                      | {}      | {}     | {}        |       |      | btree |         |
# >> | swars_zip_dl_logs              | index_swars_zip_dl_logs_on_user_id                          | false  | ["user_id"]                                                                       | {}      | {}     | {}        |       |      | btree |         |
# >> | swars_zip_dl_logs              | index_swars_zip_dl_logs_on_swars_user_id                    | false  | ["swars_user_id"]                                                                 | {}      | {}     | {}        |       |      | btree |         |
# >> | swars_zip_dl_logs              | index_swars_zip_dl_logs_on_end_at                           | false  | ["end_at"]                                                                        | {}      | {}     | {}        |       |      | btree |         |
# >> | swars_zip_dl_logs              | index_swars_zip_dl_logs_on_created_at                       | false  | ["created_at"]                                                                    | {}      | {}     | {}        |       |      | btree |         |
# >> | taggings                       | taggings_idx                                                | true   | ["tag_id", "taggable_id", "taggable_type", "context", "tagger_id", "tagger_type"] | {}      | {}     | {}        |       |      | btree |         |
# >> | taggings                       | index_taggings_on_taggable_id_and_taggable_type_and_context | false  | ["taggable_id", "taggable_type", "context"]                                       | {}      | {}     | {}        |       |      | btree |         |
# >> | taggings                       | index_taggings_on_tag_id                                    | false  | ["tag_id"]                                                                        | {}      | {}     | {}        |       |      | btree |         |
# >> | taggings                       | index_taggings_on_taggable_id                               | false  | ["taggable_id"]                                                                   | {}      | {}     | {}        |       |      | btree |         |
# >> | taggings                       | index_taggings_on_taggable_type                             | false  | ["taggable_type"]                                                                 | {}      | {}     | {}        |       |      | btree |         |
# >> | taggings                       | index_taggings_on_tagger_id                                 | false  | ["tagger_id"]                                                                     | {}      | {}     | {}        |       |      | btree |         |
# >> | taggings                       | index_taggings_on_context                                   | false  | ["context"]                                                                       | {}      | {}     | {}        |       |      | btree |         |
# >> | taggings                       | index_taggings_on_tagger_id_and_tagger_type                 | false  | ["tagger_id", "tagger_type"]                                                      | {}      | {}     | {}        |       |      | btree |         |
# >> | taggings                       | taggings_idy                                                | false  | ["taggable_id", "taggable_type", "tagger_id", "context"]                          | {}      | {}     | {}        |       |      | btree |         |
# >> | tags                           | index_tags_on_name                                          | true   | ["name"]                                                                          | {}      | {}     | {}        |       |      | btree |         |
# >> | ppl_leagues                    | index_ppl_leagues_on_generation                             | false  | ["generation"]                                                                    | {}      | {}     | {}        |       |      | btree |         |
# >> | ppl_memberships                | index_ppl_memberships_on_league_id_and_user_id              | true   | ["league_id", "user_id"]                                                          | {}      | {}     | {}        |       |      | btree |         |
# >> | ppl_memberships                | index_ppl_memberships_on_league_id                          | false  | ["league_id"]                                                                     | {}      | {}     | {}        |       |      | btree |         |
# >> | ppl_memberships                | index_ppl_memberships_on_user_id                            | false  | ["user_id"]                                                                       | {}      | {}     | {}        |       |      | btree |         |
# >> | ppl_memberships                | index_ppl_memberships_on_result_key                         | false  | ["result_key"]                                                                    | {}      | {}     | {}        |       |      | btree |         |
# >> | ppl_memberships                | index_ppl_memberships_on_start_pos                          | false  | ["start_pos"]                                                                     | {}      | {}     | {}        |       |      | btree |         |
# >> | ppl_memberships                | index_ppl_memberships_on_win                                | false  | ["win"]                                                                           | {}      | {}     | {}        |       |      | btree |         |
# >> | ppl_memberships                | index_ppl_memberships_on_lose                               | false  | ["lose"]                                                                          | {}      | {}     | {}        |       |      | btree |         |
# >> | ppl_memberships                | index_ppl_memberships_on_previous_runner_up_count           | false  | ["previous_runner_up_count"]                                                      | {}      | {}     | {}        |       |      | btree |         |
# >> | ppl_users                      | index_ppl_users_on_name                                     | true   | ["name"]                                                                          | {}      | {}     | {}        |       |      | btree |         |
# >> | ppl_users                      | index_ppl_users_on_level_up_generation                      | false  | ["promotion_membership_id"]                                                           | {}      | {}     | {}        |       |      | btree |         |
# >> | users                          | index_users_on_key                                          | true   | ["key"]                                                                           | {}      | {}     | {}        |       |      | btree |         |
# >> | users                          | index_users_on_email                                        | true   | ["email"]                                                                         | {}      | {}     | {}        |       |      | btree |         |
# >> | users                          | index_users_on_reset_password_token                         | true   | ["reset_password_token"]                                                          | {}      | {}     | {}        |       |      | btree |         |
# >> | users                          | index_users_on_confirmation_token                           | true   | ["confirmation_token"]                                                            | {}      | {}     | {}        |       |      | btree |         |
# >> | users                          | index_users_on_unlock_token                                 | true   | ["unlock_token"]                                                                  | {}      | {}     | {}        |       |      | btree |         |
# >> | users                          | index_users_on_race_key                                     | false  | ["race_key"]                                                                      | {}      | {}     | {}        |       |      | btree |         |
# >> | wkbk_access_logs               | index_wkbk_access_logs_on_user_id                           | false  | ["user_id"]                                                                       | {}      | {}     | {}        |       |      | btree |         |
# >> | wkbk_access_logs               | index_wkbk_access_logs_on_book_id                           | false  | ["book_id"]                                                                       | {}      | {}     | {}        |       |      | btree |         |
# >> | wkbk_answer_kinds              | index_wkbk_answer_kinds_on_key                              | true   | ["key"]                                                                           | {}      | {}     | {}        |       |      | btree |         |
# >> | wkbk_answer_kinds              | index_wkbk_answer_kinds_on_position                         | false  | ["position"]                                                                      | {}      | {}     | {}        |       |      | btree |         |
# >> | wkbk_answer_logs               | index_wkbk_answer_logs_on_article_id                        | false  | ["article_id"]                                                                    | {}      | {}     | {}        |       |      | btree |         |
# >> | wkbk_answer_logs               | index_wkbk_answer_logs_on_answer_kind_id                    | false  | ["answer_kind_id"]                                                                | {}      | {}     | {}        |       |      | btree |         |
# >> | wkbk_answer_logs               | index_wkbk_answer_logs_on_book_id                           | false  | ["book_id"]                                                                       | {}      | {}     | {}        |       |      | btree |         |
# >> | wkbk_answer_logs               | index_wkbk_answer_logs_on_user_id                           | false  | ["user_id"]                                                                       | {}      | {}     | {}        |       |      | btree |         |
# >> | wkbk_answer_logs               | index_wkbk_answer_logs_on_spent_sec                         | false  | ["spent_sec"]                                                                     | {}      | {}     | {}        |       |      | btree |         |
# >> | wkbk_answer_logs               | index_wkbk_answer_logs_on_created_at                        | false  | ["created_at"]                                                                    | {}      | {}     | {}        |       |      | btree |         |
# >> | wkbk_articles                  | index_wkbk_articles_on_key                                  | true   | ["key"]                                                                           | {}      | {}     | {}        |       |      | btree |         |
# >> | wkbk_articles                  | index_wkbk_articles_on_user_id                              | false  | ["user_id"]                                                                       | {}      | {}     | {}        |       |      | btree |         |
# >> | wkbk_articles                  | index_wkbk_articles_on_folder_id                            | false  | ["folder_id"]                                                                     | {}      | {}     | {}        |       |      | btree |         |
# >> | wkbk_articles                  | index_wkbk_articles_on_lineage_id                           | false  | ["lineage_id"]                                                                    | {}      | {}     | {}        |       |      | btree |         |
# >> | wkbk_articles                  | index_wkbk_articles_on_init_sfen                            | false  | ["init_sfen"]                                                                     | {}      | {}     | {}        |       |      | btree |         |
# >> | wkbk_articles                  | index_wkbk_articles_on_turn_max                             | false  | ["turn_max"]                                                                      | {}      | {}     | {}        |       |      | btree |         |
# >> | wkbk_articles                  | index_wkbk_articles_on_difficulty                           | false  | ["difficulty"]                                                                    | {}      | {}     | {}        |       |      | btree |         |
# >> | wkbk_books                     | index_wkbk_books_on_key                                     | true   | ["key"]                                                                           | {}      | {}     | {}        |       |      | btree |         |
# >> | wkbk_books                     | index_wkbk_books_on_user_id                                 | false  | ["user_id"]                                                                       | {}      | {}     | {}        |       |      | btree |         |
# >> | wkbk_books                     | index_wkbk_books_on_folder_id                               | false  | ["folder_id"]                                                                     | {}      | {}     | {}        |       |      | btree |         |
# >> | wkbk_books                     | index_wkbk_books_on_sequence_id                             | false  | ["sequence_id"]                                                                   | {}      | {}     | {}        |       |      | btree |         |
# >> | wkbk_books                     | index_wkbk_books_on_access_logs_count                       | false  | ["access_logs_count"]                                                             | {}      | {}     | {}        |       |      | btree |         |
# >> | wkbk_bookships                 | index_wkbk_bookships_on_book_id_and_article_id              | true   | ["book_id", "article_id"]                                                         | {}      | {}     | {}        |       |      | btree |         |
# >> | wkbk_bookships                 | index_wkbk_bookships_on_user_id                             | false  | ["user_id"]                                                                       | {}      | {}     | {}        |       |      | btree |         |
# >> | wkbk_bookships                 | index_wkbk_bookships_on_book_id                             | false  | ["book_id"]                                                                       | {}      | {}     | {}        |       |      | btree |         |
# >> | wkbk_bookships                 | index_wkbk_bookships_on_article_id                          | false  | ["article_id"]                                                                    | {}      | {}     | {}        |       |      | btree |         |
# >> | wkbk_bookships                 | index_wkbk_bookships_on_position                            | false  | ["position"]                                                                      | {}      | {}     | {}        |       |      | btree |         |
# >> | wkbk_folders                   | index_wkbk_folders_on_key                                   | true   | ["key"]                                                                           | {}      | {}     | {}        |       |      | btree |         |
# >> | wkbk_folders                   | index_wkbk_folders_on_position                              | false  | ["position"]                                                                      | {}      | {}     | {}        |       |      | btree |         |
# >> | wkbk_lineages                  | index_wkbk_lineages_on_key                                  | true   | ["key"]                                                                           | {}      | {}     | {}        |       |      | btree |         |
# >> | wkbk_lineages                  | index_wkbk_lineages_on_position                             | false  | ["position"]                                                                      | {}      | {}     | {}        |       |      | btree |         |
# >> | wkbk_moves_answers             | index_wkbk_moves_answers_on_article_id                      | false  | ["article_id"]                                                                    | {}      | {}     | {}        |       |      | btree |         |
# >> | wkbk_moves_answers             | index_wkbk_moves_answers_on_moves_count                     | false  | ["moves_count"]                                                                   | {}      | {}     | {}        |       |      | btree |         |
# >> | wkbk_moves_answers             | index_wkbk_moves_answers_on_position                        | false  | ["position"]                                                                      | {}      | {}     | {}        |       |      | btree |         |
# >> | wkbk_sequences                 | index_wkbk_sequences_on_key                                 | true   | ["key"]                                                                           | {}      | {}     | {}        |       |      | btree |         |
# >> | wkbk_sequences                 | index_wkbk_sequences_on_position                            | false  | ["position"]                                                                      | {}      | {}     | {}        |       |      | btree |         |
# >> | xsettings                      | index_xsettings_on_var_key                                  | true   | ["var_key"]                                                                       | {}      | {}     | {}        |       |      | btree |         |
# >> | xy_master_rules                | index_xy_master_rules_on_position                           | false  | ["position"]                                                                      | {}      | {}     | {}        |       |      | btree |         |
# >> | xy_master_time_records         | index_xy_master_time_records_on_user_id                     | false  | ["user_id"]                                                                       | {}      | {}     | {}        |       |      | btree |         |
# >> | xy_master_time_records         | index_xy_master_time_records_on_rule_id                     | false  | ["rule_id"]                                                                       | {}      | {}     | {}        |       |      | btree |         |
# >> | xy_master_time_records         | index_xy_master_time_records_on_entry_name                  | false  | ["entry_name"]                                                                    | {}      | {}     | {}        |       |      | btree |         |
# >> |--------------------------------+-------------------------------------------------------------+--------+-----------------------------------------------------------------------------------+---------+--------+-----------+-------+------+-------+---------|
