require "./setup"
ModelStat.new(target: "quick_script").call
# >> |------+-----|
# >> | 全体 | 103 |
# >> |    o | 71  |
# >> |    x | 32  |
# >> |------+-----|
# >> |--------+-------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------|
# >> | テスト | SPEC                                                                                                  | モデル                                                                                          |
# >> |--------+-------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------|
# >> | ×     | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/about/credit_script_spec.rb                    | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/about/credit_script.rb                    |
# >> | ×     | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/about/privacy_policy_script_spec.rb            | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/about/privacy_policy_script.rb            |
# >> | ×     | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/about/terms_script_spec.rb                     | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/about/terms_script.rb                     |
# >> |        | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/account/destroy_script_spec.rb                 | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/account/destroy_script.rb                 |
# >> |        | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/account/email_edit_script_spec.rb              | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/account/email_edit_script.rb              |
# >> | ×     | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/account/info_script_spec.rb                    | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/account/info_script.rb                    |
# >> | ×     | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/account/kento_pro_destroy_script_spec.rb       | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/account/kento_pro_destroy_script.rb       |
# >> | ×     | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/account/logout_script_spec.rb                  | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/account/logout_script.rb                  |
# >> |        | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/account/name_edit_script_spec.rb               | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/account/name_edit_script.rb               |
# >> | ×     | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/account/ordered_index_spec.rb                  | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/account/ordered_index.rb                  |
# >> | ×     | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/account/profile_image_upload_script_spec.rb    | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/account/profile_image_upload_script.rb    |
# >> | ×     | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/account/sns_account_integration_script_spec.rb | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/account/sns_account_integration_script.rb |
# >> |        | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/admin/login_script_spec.rb                     | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/admin/login_script.rb                     |
# >> |        | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/admin/swars_agent_script_spec.rb               | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/admin/swars_agent_script.rb               |
# >> | ×     | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/background_mod_spec.rb                         | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/background_mod.rb                         |
# >> |        | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/base_spec.rb                                   | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/base.rb                                   |
# >> | ×     | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/chore/documentation_script_spec.rb             | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/chore/documentation_script.rb             |
# >> |        | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/chore/group_script_spec.rb                     | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/chore/group_script.rb                     |
# >> |        | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/chore/index_script_spec.rb                     | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/chore/index_script.rb                     |
# >> |        | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/chore/invisible_script_spec.rb                 | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/chore/invisible_script.rb                 |
# >> | ×     | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/chore/markdown_script_spec.rb                  | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/chore/markdown_script.rb                  |
# >> |        | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/chore/message_script_spec.rb                   | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/chore/message_script.rb                   |
# >> |        | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/chore/not_found_script_spec.rb                 | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/chore/not_found_script.rb                 |
# >> |        | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/chore/null_script_spec.rb                      | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/chore/null_script.rb                      |
# >> |        | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/chore/status_code_script_spec.rb               | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/chore/status_code_script.rb               |
# >> | ×     | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/dev/abstract_script_spec.rb                    | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/dev/abstract_script.rb                    |
# >> |        | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/dev/background_job_script_spec.rb              | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/dev/background_job_script.rb              |
# >> |        | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/dev/calc_script_spec.rb                        | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/dev/calc_script.rb                        |
# >> |        | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/dev/csv_download_get_script_spec.rb            | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/dev/csv_download_get_script.rb            |
# >> |        | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/dev/csv_download_post_script_spec.rb           | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/dev/csv_download_post_script.rb           |
# >> | ×     | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/dev/delegate_script_spec.rb                    | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/dev/delegate_script.rb                    |
# >> |        | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/dev/emoji_script_spec.rb                       | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/dev/emoji_script.rb                       |
# >> |        | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/dev/error_script_spec.rb                       | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/dev/error_script.rb                       |
# >> |        | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/dev/fake500_script_spec.rb                     | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/dev/fake500_script.rb                     |
# >> |        | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/dev/fetch_index_script_spec.rb                 | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/dev/fetch_index_script.rb                 |
# >> |        | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/dev/flash_script_spec.rb                       | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/dev/flash_script.rb                       |
# >> |        | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/dev/foo_bar_baz_script_spec.rb                 | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/dev/foo_bar_baz_script.rb                 |
# >> |        | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/dev/form_script_spec.rb                        | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/dev/form_script.rb                        |
# >> |        | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/dev/hello_script_spec.rb                       | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/dev/hello_script.rb                       |
# >> |        | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/dev/html_script_spec.rb                        | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/dev/html_script.rb                        |
# >> | ×     | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/dev/invalidate_basic_auth_script_spec.rb       | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/dev/invalidate_basic_auth_script.rb       |
# >> |        | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/dev/invisible_script_spec.rb                   | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/dev/invisible_script.rb                   |
# >> |        | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/dev/login_required1_script_spec.rb             | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/dev/login_required1_script.rb             |
# >> |        | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/dev/login_required2_script_spec.rb             | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/dev/login_required2_script.rb             |
# >> | ×     | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/dev/markdown_script_spec.rb                    | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/dev/markdown_script.rb                    |
# >> |        | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/dev/navibar_false_script_spec.rb               | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/dev/navibar_false_script.rb               |
# >> |        | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/dev/null_script_spec.rb                        | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/dev/null_script.rb                        |
# >> | ×     | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/dev/page_reload_script_spec.rb                 | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/dev/page_reload_script.rb                 |
# >> | ×     | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/dev/piyo_shogi_config_component_script_spec.rb | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/dev/piyo_shogi_config_component_script.rb |
# >> |        | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/dev/post1_script_spec.rb                       | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/dev/post1_script.rb                       |
# >> |        | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/dev/post2_form_counter_script_spec.rb          | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/dev/post2_form_counter_script.rb          |
# >> |        | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/dev/post3_session_counter_script_spec.rb       | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/dev/post3_session_counter_script.rb       |
# >> |        | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/dev/post_and_redirect_script_spec.rb           | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/dev/post_and_redirect_script.rb           |
# >> |        | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/dev/redirect1_script_spec.rb                   | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/dev/redirect1_script.rb                   |
# >> |        | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/dev/redirect2_script_spec.rb                   | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/dev/redirect2_script.rb                   |
# >> | ×     | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/dev/redirect3_script_spec.rb                   | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/dev/redirect3_script.rb                   |
# >> |        | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/dev/session_counter_script_spec.rb             | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/dev/session_counter_script.rb             |
# >> |        | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/dev/session_script_spec.rb                     | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/dev/session_script.rb                     |
# >> |        | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/dev/sheet_script_spec.rb                       | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/dev/sheet_script.rb                       |
# >> | ×     | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/dev/sidebar_script_spec.rb                     | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/dev/sidebar_script.rb                     |
# >> |        | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/dev/sleep_script_spec.rb                       | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/dev/sleep_script.rb                       |
# >> |        | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/dev/status_code_tester_script_spec.rb          | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/dev/status_code_tester_script.rb          |
# >> |        | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/dev/table_script_spec.rb                       | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/dev/table_script.rb                       |
# >> | ×     | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/dev/url_helpers_script_spec.rb                 | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/dev/url_helpers_script.rb                 |
# >> |        | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/dev/value_script_spec.rb                       | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/dev/value_script.rb                       |
# >> | ×     | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/dev/zip_download_post_script_spec.rb           | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/dev/zip_download_post_script.rb           |
# >> |        | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/dispatcher_spec.rb                             | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/dispatcher.rb                             |
# >> |        | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/form_mod_spec.rb                               | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/form_mod.rb                               |
# >> |        | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/group1/hello_script_spec.rb                    | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/group1/hello_script.rb                    |
# >> |        | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/layout_mod_spec.rb                             | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/layout_mod.rb                             |
# >> | ×     | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/markdown_info_spec.rb                          | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/markdown_info.rb                          |
# >> |        | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/meta_mod_spec.rb                               | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/meta_mod.rb                               |
# >> |        | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/middleware/autoexec_mod_spec.rb                | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/middleware/autoexec_mod.rb                |
# >> | ×     | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/middleware/bulma_mod_spec.rb                   | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/middleware/bulma_mod.rb                   |
# >> |        | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/middleware/controller_mod_spec.rb              | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/middleware/controller_mod.rb              |
# >> | ×     | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/middleware/custom_style_mod_spec.rb            | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/middleware/custom_style_mod.rb            |
# >> |        | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/middleware/exception_rescue_mod_spec.rb        | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/middleware/exception_rescue_mod.rb        |
# >> |        | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/middleware/flash_mod_spec.rb                   | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/middleware/flash_mod.rb                   |
# >> |        | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/middleware/helper_mod_spec.rb                  | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/middleware/helper_mod.rb                  |
# >> |        | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/middleware/invisible_mod_spec.rb               | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/middleware/invisible_mod.rb               |
# >> |        | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/middleware/login_user_mod_spec.rb              | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/middleware/login_user_mod.rb              |
# >> |        | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/middleware/order_mod_spec.rb                   | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/middleware/order_mod.rb                   |
# >> |        | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/middleware/pagination_mod_spec.rb              | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/middleware/pagination_mod.rb              |
# >> | ×     | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/middleware/parent_link_mod_spec.rb             | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/middleware/parent_link_mod.rb             |
# >> | ×     | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/middleware/primary_error_message_mod_spec.rb   | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/middleware/primary_error_message_mod.rb   |
# >> |        | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/middleware/process_type_mod_spec.rb            | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/middleware/process_type_mod.rb            |
# >> |        | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/middleware/redirect_mod_spec.rb                | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/middleware/redirect_mod.rb                |
# >> | ×     | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/middleware/sidebar_mod_spec.rb                 | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/middleware/sidebar_mod.rb                 |
# >> |        | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/middleware/throttle_mod_spec.rb                | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/middleware/throttle_mod.rb                |
# >> | ×     | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/middleware_spec.rb                             | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/middleware.rb                             |
# >> |        | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/parameter_spec.rb                              | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/parameter.rb                              |
# >> |        | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/qs_group_info_spec.rb                          | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/qs_group_info.rb                          |
# >> |        | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/swars/battle_history_script_spec.rb            | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/swars/battle_history_script.rb            |
# >> | ×     | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/swars/documentation_script_spec.rb             | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/swars/documentation_script.rb             |
# >> |        | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/swars/ordered_index_spec.rb                    | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/swars/ordered_index.rb                    |
# >> | ×     | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/swars/piyo_shogi_config_script_spec.rb         | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/swars/piyo_shogi_config_script.rb         |
# >> |        | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/swars/prison_all_script_spec.rb                | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/swars/prison_all_script.rb                |
# >> |        | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/swars/prison_new_script_spec.rb                | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/swars/prison_new_script.rb                |
# >> |        | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/swars/prison_search_script_spec.rb             | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/swars/prison_search_script.rb             |
# >> |        | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/swars/pro_script_spec.rb                       | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/swars/pro_script.rb                       |
# >> |        | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/swars/user_group_script_spec.rb                | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/swars/user_group_script.rb                |
# >> |        | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script/tool/short_url_script_spec.rb                  | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script/tool/short_url_script.rb                  |
# >> | ×     | /Users/ikeda/src/shogi/shogi-extend/spec/models/quick_script_spec.rb                                        | /Users/ikeda/src/shogi/shogi-extend/app/models/quick_script.rb                                        |
# >> |--------+-------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------|
