module Ppl
  class OrderInfo
    include ApplicationMemoryRecord
    memory_record [
      { key: "S31前", },
      { key: "S31後", },
      { key: "S32前", },
      { key: "S32後", },
      { key: "S33前", },
      { key: "S33後", },
      { key: "S34前", },
      { key: "S34後", },
      { key: "S35前", },
      { key: "S35後", },
      { key: "S36前", },
      { key: "S36後", },
      { key: "S37前", },
      { key: "S37後", },
      { key: "S38前", },
      { key: "S38後", },
      { key: "S39前", },
      { key: "S39後", },
      { key: "S40前", },
      { key: "S40後", },
      { key: "S41前", },
      { key: "S41後", },
      { key: "S42前", },
      { key: "S42後", },
      { key: "S43前", },
      { key: "S43後", },
      { key: "S44前", },
      { key: "S44後", },
      { key: "S45前", },
      { key: "S45後", },
      { key: "S46前", },
      { key: "S46後", },
      { key: "S47前", },
      { key: "S47後", },
      { key: "S48前", },
      { key: "S48後", },
      { key: "S49",   },
      { key: "S50",   },
      { key: "S51",   },
      { key: "S52",   },
      { key: "S53",   },
      { key: "S54",   },
      { key: "S55",   },
      { key: "S56",   },
      { key: "S57",   },
      { key: "S58",   },
      { key: "S59",   },
      { key: "S60",   },
      { key: "S61",   },
      { key: "S62",   },
    ]
  end
end
