#!/bin/sh
scp nginx_default.conf s:/etc/nginx/conf.d/default.conf
ssh s "sudo nginx -t && sudo systemctl restart nginx"

scp nuxt.service s:/etc/systemd/system/
ssh s sudo systemctl daemon-reload
ssh s sudo systemctl restart nuxt
ssh s sudo systemctl status nuxt
ssh s sudo systemctl reset-failed nuxt

curl -sI https://shogi-flow.xyz/vs-clock | head -1
curl -sI https://shogi-flow.xyz/app/experiment/async_data_test | head -1
