#!/usr/local/rbenv/shims/ruby
# -*- coding: utf-8; compile-command: "scp slack_notify s:/home/deploy; ssh s '/home/deploy/slack_notify sidekiq.service failed'" -*-
WEBHOOK_URL = "https://hooks.slack.com/services/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"
require "slack-notifier"
name, command = ARGV
name = name.to_s.scan(/\w+/).first
status = `systemctl status --no-pager --full #{name}`
oneline = status.match(/Active:\s*(.*)/).captures.first.strip
color = {failed: "bad", start: "good"}.fetch(command.to_s, "bad")
icon_emoji = {failed: ":red_circle:", start: ":large_green_circle:"}.fetch(command.to_sym, ":question:")
client = Slack::Notifier.new(WEBHOOK_URL, username: "systemd", icon_emoji: ":bow:")
# client.post(text: "[#{name}] #{command} #{oneline}", attachments: [{fallback: "#{name} #{command}", text: status, color: color}])
client.post(text: "#{icon_emoji} #{name} #{command} #{oneline}")
# client.post(text: ARGV.to_s)

# client.post(text: "#{name} #{command}", )

# require "slack-notify"
# command, name = ARGV
# 
# # icon_emoji = {failed: ":red_circle:", start: ":large_green_circle:"}.fetch(command.to_s, ":question:")
# # client = SlackNotify.new(icon_emoji: icon_emoji, username: "systemd", webhook_url: "https://hooks.slack.com/services/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")
# # status = `systemctl status --no-pager --full #{name}`
# # client.notify(status)
# 
# client = SlackNotify.new(icon_emoji: ":bow:", username: "systemd", webhook_url: "https://hooks.slack.com/services/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")
# client.notify("OK")
