#!/bin/sh
scp custom_profile.sh i:/etc/profile.d

ssh i 'sudo chown deploy:deploy -R /var/lib/nginx'

scp nginx.conf i:/etc/nginx/nginx.conf
ssh i 'sudo nginx -t && sudo systemctl restart nginx'

scp nginx_default.conf i:/etc/nginx/conf.d/default.conf
ssh i 'sudo nginx -t && sudo systemctl restart nginx'

curl -sI https://www.shogi-extend.com/ | head -1

scp puma.service i:/etc/systemd/system/
ssh i 'sudo systemctl daemon-reload'
ssh i 'sudo systemctl enable puma'
ssh i 'sudo systemctl restart puma'
ssh i 'sudo systemctl status puma'
ssh i 'sudo systemctl reset-failed puma'

scp sidekiq.service i:/etc/systemd/system/
ssh i 'sudo systemctl daemon-reload'
ssh i 'sudo systemctl enable sidekiq'
ssh i 'sudo systemctl restart sidekiq'
ssh i 'sudo systemctl status sidekiq'
ssh i 'sudo systemctl reset-failed sidekiq'

scp nuxt.service i:/etc/systemd/system/
ssh i 'sudo systemctl daemon-reload'
ssh i 'sudo systemctl enable nuxt'
ssh i 'sudo systemctl restart nuxt'
ssh i 'sudo systemctl status nuxt'
ssh i 'sudo systemctl reset-failed nuxt'
