#!/bin/sh
ssh i ls -al /etc/profile.d/custom_profile.sh

ssh i ls -al /etc/nginx/nginx.conf
ssh i ls -al /etc/nginx/conf.d/default.conf
ssh i sudo nginx -v
ssh i sudo nginx -t

ssh i ls -al /var/www/shogi_web_production/current/config/puma/production.rb

ssh i ls -al /usr/lib/systemd/system/nginx.service
ssh i ls -al /etc/systemd/system/puma.service
ssh i ls -al /etc/systemd/system/sidekiq.service
ssh i ls -al /etc/systemd/system/nuxt.service

ssh i ls -al /home/deploy/slack_notify
ssh i ls -al /etc/systemd/system/failed_notify@.service
ssh i ls -al /etc/sysconfig/systemd_secret_env

ssh i sudo systemctl status nginx
ssh i sudo systemctl status puma
ssh i sudo systemctl status sidekiq
ssh i sudo systemctl status nuxt

curl -sI https://www.shogi-extend.com/ | head -1
