#!/bin/sh
ssh i 'sudo touch         /etc/systemd/system/slack_notify@.service'
ssh i 'sudo chmod -v a+rw /etc/systemd/system/slack_notify@.service'
scp slack_notify@.service i:/etc/systemd/system
scp slack_notify i:/home/deploy
ssh i 'sudo systemctl daemon-reload'
# test
ssh i '/home/deploy/slack_notify sidekiq start'
ssh i '/home/deploy/slack_notify puma    start'
ssh i '/home/deploy/slack_notify nuxt    start'
# kill test
ssh i 'sudo systemctl kill sidekiq -s SIGKILL'
ssh i 'sudo systemctl kill puma    -s SIGKILL'
ssh i 'sudo systemctl kill nuxt    -s SIGKILL'
