#!/bin/sh
ssh i 'sudo touch               /etc/nginx/nginx.conf'
ssh i 'sudo chown deploy:deploy /etc/nginx/nginx.conf'

ssh i 'sudo touch               /etc/nginx/conf.d/default.conf'
ssh i 'sudo chown deploy:deploy /etc/nginx/conf.d/default.conf'

ssh i 'sudo touch               /etc/systemd/system/puma.service'
ssh i 'sudo chown deploy:deploy /etc/systemd/system/puma.service'

ssh i 'sudo touch               /etc/systemd/system/sidekiq.service'
ssh i 'sudo chown deploy:deploy /etc/systemd/system/sidekiq.service'

ssh i 'sudo touch               /etc/systemd/system/nuxt.service'
ssh i 'sudo chown deploy:deploy /etc/systemd/system/nuxt.service'

ssh i 'sudo touch               /etc/systemd/system/failed_notify@.service'
ssh i 'sudo chown deploy:deploy /etc/systemd/system/failed_notify@.service'

ssh i 'sudo systemctl daemon-reload'

ssh i 'mkdir -p /var/www/shogi_web_production/current/config/puma'

scp custom_profile.sh     i:/etc/profile.d
scp nginx.conf            i:/etc/nginx/nginx.conf
scp nginx_default.conf    i:/etc/nginx/conf.d/default.conf
scp puma.service          i:/etc/systemd/system/
scp sidekiq.service       i:/etc/systemd/system/
scp nuxt.service          i:/etc/systemd/system/
scp failed_notify@.service i:/etc/systemd/system/
scp slack_notify          i:/home/deploy/
scp ../puma/production.rb i:/var/www/shogi_web_production/current/config/puma/production.rb

ssh i sudo chkconfig nginx    on
ssh i sudo chkconfig puma     on
ssh i sudo chkconfig sidekiq  on
ssh i sudo chkconfig mysqld   on
ssh i sudo chkconfig redis    on

echo "0-reload の実行で反映する"
