#!/usr/local/rbenv/shims/ruby
# -*- coding: utf-8; compile-command: "scp slack_notify i:/home/deploy; ssh i '/home/deploy/slack_notify sidekiq failed'" -*-

require "slack-notifier"
name, command = ARGV
# status = `systemctl status --no-pager --full #{name}`
color = {failed: "bad", start: "good"}.fetch(command.to_s, "bad")
client = Slack::Notifier.new("https://hooks.slack.com/services/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", username: "systemd", icon_emoji: ":bow:")
client.post(text: "#{name} #{command}")
# client.post(text: ARGV.to_s)

# client.post(text: "#{name} #{command}", attachments: [{fallback: command, text: status, color: color}])

# require "slack-notify"
# command, name = ARGV
# 
# # icon_emoji = {failed: ":red_circle:", start: ":large_green_circle:"}.fetch(command.to_s, ":question:")
# # client = SlackNotify.new(icon_emoji: icon_emoji, username: "systemd", webhook_url: "https://hooks.slack.com/services/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")
# # status = `systemctl status --no-pager --full #{name}`
# # client.notify(status)
# 
# client = SlackNotify.new(icon_emoji: ":bow:", username: "systemd", webhook_url: "https://hooks.slack.com/services/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")
# client.notify("OK")
