require "../setup"
tp QuickScript::Account::ProfileImageUploadScript.new({ avatar: { data_uri: MiniImage.generate } }, {current_user: User.create!, _method: :post}).as_json
# >> 2024-07-28T02:48:40.658Z pid=5825 tid=3h INFO: Sidekiq 7.1.6 connecting to Redis with options {:size=>10, :pool_name=>"internal", :url=>"redis://localhost:6379/4"}
# >> |-------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
# >> |                          body |                                                                                                                                                                                                                                                                 |
# >> |               __script_meta__ | {:qs_group_key=>"account", :qs_page_key=>"profile_image_upload", :qs_path=>"/lab/account/profile-image-upload", :qs_group_info=>#<QuickScript::QsGroupInfo:0x00000001068bd718 @attributes={:key=>:account, :name=>"アカウント", :admin_only=>false, :code=>3}>} |
# >> |                   form_method | post                                                                                                                                                                                                                                                            |
# >> |                  button_label | 更新                                                                                                                                                                                                                                                            |
# >> |         params_add_submit_key |                                                                                                                                                                                                                                                                 |
# >> |            get_then_axios_get | false                                                                                                                                                                                                                                                           |
# >> | router_push_failed_then_fetch | false                                                                                                                                                                                                                                                           |
# >> |          button_click_loading | false                                                                                                                                                                                                                                                           |
# >> |                    form_parts | [{:label=>"プロフィール画像", :key=>:avatar, :type=>:file, :default=>nil}]                                                                                                                                                                                      |
# >> |                          meta | {:title=>"プロフィール画像更新", :description=>"プロフィール画像だけ更新する", :og_image_key=>:application, :og_card_size=>:small, :primary_error_message=>nil}                                                                                                 |
# >> |                main_component |                                                                                                                                                                                                                                                                 |
# >> |                  navibar_show | true                                                                                                                                                                                                                                                            |
# >> |                   container_width | large                                                                                                                                                                                                                                                           |
# >> |    nuxt_login_required_timing | immediately                                                                                                                                                                                                                                                     |
# >> |               login_link_show | true                                                                                                                                                                                                                                                            |
# >> |         primary_error_message |                                                                                                                                                                                                                                                                 |
# >> |                         flash | {}                                                                                                                                                                                                                                                              |
# >> |                   redirect_to | {:to=>"http://localhost:4000/lab/account/profile-image-upload", :type=>:hard}                                                                                                                                                                                   |
# >> |              auto_exec_action |                                                                                                                                                                                                                                                                 |
# >> |                auto_exec_code |                                                                                                                                                                                                                                                                 |
# >> |            axios_process_type | server                                                                                                                                                                                                                                                          |
# >> |                  custom_style |                                                                                                                                                                                                                                                                 |
# >> |             sideber_menu_show | false                                                                                                                                                                                                                                                           |
# >> |           sideber_menu_groups | []                                                                                                                                                                                                                                                              |
# >> |                   parent_link |                                                                                                                                                                                                                                                                 |
# >> |-------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
