import MemoryRecord from 'js-memory-record'

export class AudioThemeInfo extends MemoryRecord {
  static get field_label() {
    return "BGM"
  }

  static get field_message() {
    return ""
  }

  static get define() {
    return [
      // ../../../../../bioshogi/lib/bioshogi/audio_theme_info.rb
      { key: "audio_theme_custom",              name: "カスタム",                     type: "is-primary", environment: ["development", "staging", "production"], message: null, sample_m4a: null,                                                                                                                                                                                                                                                                               },
      { separator: true                                                                                                                                                                                                                                                                                                                                                                                                                                                         },
      { key: "audio_theme_headspin_only",       name: "ヘッドスピン",                 type: "is-primary", environment: ["development", "staging", "production"], message: null, sample_m4a: require('../../../../../bioshogi/lib/bioshogi/assets/audios/headspin_long.m4a'),      source_url: null,                                             author: null,                   author_raw: "GarageBand Sound Library より", desc: "",                                          },
      { key: "audio_theme_breakbeat_only",      name: "ブレイクビート",               type: "is-primary", environment: ["development", "staging", "production"], message: null, sample_m4a: require('../../../../../bioshogi/lib/bioshogi/assets/audios/breakbeat_long.m4a'),     source_url: null,                                             author: null,                   author_raw: "GarageBand Sound Library より", desc: "",                                          },
      { key: "audio_theme_dance_chain",         name: "ヘッドスピン→ブレイクビート", type: "is-primary", environment: ["development", "staging", "production"], message: null, sample_m4a: null,                                                                                 source_url: null,                                             author: null,                   author_raw: null,                            desc: "",                                          },
      { separator: true                                                                                                                                                                                                                                                                                                                                                                                                                                                         },
      { key: "audio_theme_nc97718",             name: "てってってー",                 type: "is-primary", environment: ["development", "staging", "production"], message: null, sample_m4a: require('../../../../../bioshogi/lib/bioshogi/assets/audios/nc97718.m4a'),            source_url: "https://commons.nicovideo.jp/material/nc97718",  author: "ターリー◆dtTARy/mt2", author_raw: null,                            desc: "",                                          },
      { key: "audio_theme_nc768",               name: "マーチ・マーチ",               type: "is-primary", environment: ["development", "staging", "production"], message: null, sample_m4a: require('../../../../../bioshogi/lib/bioshogi/assets/audios/nc768.m4a'),              source_url: "https://commons.nicovideo.jp/material/nc768",    author: "McCoy",                author_raw: null,                            desc: "",                                          },
      { separator: true                                                                                                                                                                                                                                                                                                                                                                                                                                                         },
      { key: "audio_theme_ds4712",              name: "昼下がり気分",                 type: "is-primary", environment: ["development", "staging", "production"], message: null, sample_m4a: require('../../../../../bioshogi/lib/bioshogi/assets/audios/ds4712.m4a'),             source_url: "https://dova-s.jp/bgm/play4712.html",            author: "KK",                   author_raw: null,                            desc: "作者の紹介でYoutube動画に適しているとある", },
      { key: "audio_theme_nc35943",             name: "昼下がり",                     type: "is-primary", environment: ["development", "staging", "production"], message: null, sample_m4a: require('../../../../../bioshogi/lib/bioshogi/assets/audios/nc35943.m4a'),            source_url: "https://commons.nicovideo.jp/material/nc35943",  author: "369",                  author_raw: null,                            desc: "loop",                                      },
      { key: "audio_theme_nc105702",            name: "ぐだぐだな感じ",               type: "is-primary", environment: ["development", "staging", "production"], message: null, sample_m4a: require('../../../../../bioshogi/lib/bioshogi/assets/audios/nc105702.m4a'),           source_url: "https://commons.nicovideo.jp/material/nc105702", author: "yuki",                 author_raw: null,                            desc: "",                                          },
      { key: "audio_theme_nc3366",              name: "はてな",                       type: "is-primary", environment: ["development", "staging", "production"], message: null, sample_m4a: require('../../../../../bioshogi/lib/bioshogi/assets/audios/nc3366.m4a'),             source_url: "https://commons.nicovideo.jp/material/nc3366",   author: "しましまP @shimakid",  author_raw: null,                            desc: "",                                          },
      { separator: true                                                                                                                                                                                                                                                                                                                                                                                                                                                         },
      { key: "audio_theme_nc770",               name: "優しい風",                     type: "is-primary", environment: ["development", "staging", "production"], message: null, sample_m4a: require('../../../../../bioshogi/lib/bioshogi/assets/audios/nc770.m4a'),              source_url: "https://commons.nicovideo.jp/material/nc770",    author: "McCoy",                author_raw: null,                            desc: "",                                          },
      { key: "audio_theme_nc43122",             name: "夜間航海",                     type: "is-primary", environment: ["development", "staging", "production"], message: null, sample_m4a: require('../../../../../bioshogi/lib/bioshogi/assets/audios/nc43122.m4a'),            source_url: "https://commons.nicovideo.jp/material/nc43122",  author: "McCoy",                author_raw: null,                            desc: "",                                          },
      { key: "audio_theme_ds12450",             name: "Somehow (Prod. Khaim)",        type: "is-primary", environment: ["development", "staging", "production"], message: null, sample_m4a: require('../../../../../bioshogi/lib/bioshogi/assets/audios/ds12450.m4a'),            source_url: "https://dova-s.jp/bgm/play12450.html",           author: "Khaim",                author_raw: null,                            desc: "loop",                                      },
      { key: "audio_theme_ds13037",             name: "YouTube向けラグタイム",        type: "is-primary", environment: ["development", "staging", "production"], message: null, sample_m4a: require('../../../../../bioshogi/lib/bioshogi/assets/audios/ds13037.m4a'),            source_url: "https://dova-s.jp/bgm/play13037.html",           author: "天休ひさし",           author_raw: null,                            desc: "loop",                                      },
      { key: "audio_theme_nc10812",             name: "BGM026 Jazz",                  type: "is-primary", environment: ["development", "staging", "production"], message: null, sample_m4a: require('../../../../../bioshogi/lib/bioshogi/assets/audios/nc10812.m4a'),            source_url: "https://commons.nicovideo.jp/material/nc10812",  author: "sanche",               author_raw: null,                            desc: "ニコ生の作品以外では要連絡",                },
      { separator: true                                                                                                                                                                                                                                                                                                                                                                                                                                                         },
      { key: "audio_theme_ds4000",              name: "Space Town (Brand New Mix)",   type: "is-primary", environment: ["development", "staging", "production"], message: null, sample_m4a: require('../../../../../bioshogi/lib/bioshogi/assets/audios/ds4000.m4a'),             source_url: "https://dova-s.jp/bgm/play4000.html",            author: "Khaim",                author_raw: null,                            desc: "loop",                                      },
      { key: "audio_theme_nc107860",            name: "Shall we meet ?",              type: "is-primary", environment: ["development", "staging", "production"], message: null, sample_m4a: require('../../../../../bioshogi/lib/bioshogi/assets/audios/nc107860.m4a'),           source_url: "https://commons.nicovideo.jp/material/nc107860", author: "MATSU",                author_raw: null,                            desc: "loop",                                      },
      { separator: true                                                                                                                                                                                                                                                                                                                                                                                                                                                         },
      { key: "audio_theme_ds7615",              name: "Winner",                       type: "is-primary", environment: ["development", "staging", "production"], message: null, sample_m4a: require('../../../../../bioshogi/lib/bioshogi/assets/audios/ds7615.m4a'),             source_url: "https://dova-s.jp/bgm/play7615.html",            author: "FLASH☆BEAT",          author_raw: null,                            desc: "loop",                                      },
      { key: "audio_theme_nc55257",             name: "3分クッキング (break beats)",  type: "is-primary", environment: ["development", "staging", "production"], message: null, sample_m4a: require('../../../../../bioshogi/lib/bioshogi/assets/audios/nc55257.m4a'),            source_url: "https://commons.nicovideo.jp/material/nc55257",  author: "ジェルバ",             author_raw: null,                            desc: "",                                          },
      { separator: true                                                                                                                                                                                                                                                                                                                                                                                                                                                         },
      { key: "audio_theme_ds5837",             name: "Taiko Warrior",                 type: "is-primary", environment: ["development", "staging", "production"], message: null, sample_m4a: require('../../../../../bioshogi/lib/bioshogi/assets/audios/ds5837.m4a'),             source_url: "https://dova-s.jp/bgm/play5837.html",            author: "MFP",                  author_raw: null,                            desc: "",                                          },
      { key: "audio_theme_nc176917",           name: "Neu Kabuki",                    type: "is-primary", environment: ["development", "staging", "production"], message: null, sample_m4a: require('../../../../../bioshogi/lib/bioshogi/assets/audios/nc176917.m4a'),           source_url: "https://commons.nicovideo.jp/material/nc176917", author: "MFP",                  author_raw: null,                            desc: "",                                          },
      { key: "audio_theme_ds5616",             name: "漢祭り",                        type: "is-primary", environment: ["development", "staging", "production"], message: null, sample_m4a: require('../../../../../bioshogi/lib/bioshogi/assets/audios/ds5616.m4a'),             source_url: "https://dova-s.jp/bgm/play5616.html",            author: "山口 壮",              author_raw: null,                            desc: "",                                          },
      { key: "audio_theme_nc142538",           name: "武蔵",                          type: "is-primary", environment: ["development", "staging", "production"], message: null, sample_m4a: require('../../../../../bioshogi/lib/bioshogi/assets/audios/nc142538.m4a'),           source_url: "https://commons.nicovideo.jp/material/nc142538", author: "yuki",                 author_raw: null,                            desc: "",                                          },
      { key: "audio_theme_shw_akatsuki_japan", name: "Akatsuki JAPAN",                type: "is-primary", environment: ["development", "staging", "production"], message: null, sample_m4a: require('../../../../../bioshogi/lib/bioshogi/assets/audios/shw_akatsuki_japan.m4a'), source_url: "http://shw.in/",                                 author: "SHW",                  author_raw: null,                            desc: "",                                          },
      { key: "audio_theme_ds3895",             name: "百花繚乱",                      type: "is-primary", environment: ["development", "staging", "production"], message: null, sample_m4a: require('../../../../../bioshogi/lib/bioshogi/assets/audios/ds3895.m4a'),             source_url: "https://dova-s.jp/bgm/play3895.html",            author: "天休ひさし",           author_raw: null,                            desc: "loop",                                      },
    ]
  }
}
