import MemoryRecord from "js-memory-record"
import dayjs from "dayjs"
import { Gs } from "../../models/gs.js"

export class AudioThemeInfo extends MemoryRecord {
  static get field_label() {
    return "BGM"
  }

  static get field_message() {
    return ""
  }

  static get define() {
    return [
      // ../../../../../bioshogi/lib/bioshogi/audio_theme_info.rb
      { key: "audio_theme_custom",              name: "カスタム",                              type: "is-primary", environment: ["development", "staging", "production"], message: null, sample_audio_source: null,                                                                                                                                                                                                                                                                                                                          },
      { separator: true,                                                                                           environment: ["development", "staging"], },
      { key: "audio_theme_is_headspin_only",       name: "ヘッドスピン",                          type: "is-primary", environment: ["development", "staging"], message: null, sample_audio_source: require("../../../../../bioshogi/lib/bioshogi/assets/audios/headspin_long.m4a"),      source_url: null,                                              author: null,                   author_raw: "GarageBand Sound Library より", bpm: null, audio_part_a_duration:  28.05, audio_part_a_loop: true,  desc: "",                           },
      { key: "audio_theme_is_breakbeat_only",      name: "ブレイクビート",                        type: "is-primary", environment: ["development", "staging"], message: null, sample_audio_source: require("../../../../../bioshogi/lib/bioshogi/assets/audios/breakbeat_long.m4a"),     source_url: null,                                              author: null,                   author_raw: "GarageBand Sound Library より", bpm: null, audio_part_a_duration:  35.55, audio_part_a_loop: false, desc: "",                           },
      { key: "audio_theme_is_dance_chain",         name: "ヘッドスピン → ブレイクビート",        type: "is-primary", environment: ["development", "staging"], message: null, sample_audio_source: null,                                                                                 source_url: null,                                              author: null,                   author_raw: null,                            bpm: null, audio_part_a_duration:  null,  audio_part_a_loop: false, desc: "",                           },
      { separator: true                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             },
      { key: "audio_theme_is_ds5837",              name: "Taiko Warrior",                          type: "is-primary", environment: ["development", "staging", "production"], message: null, sample_audio_source: require("../../../../../bioshogi/lib/bioshogi/assets/audios/ds5837.m4a"),             source_url: "https://dova-s.jp/bgm/play5837.html",             author: "MFP",                  author_raw: null,                           bpm: null, audio_part_a_duration: 123.69, audio_part_a_loop: true,  desc: "",                           },
      { key: "audio_theme_is_nc176917",            name: "Neu Kabuki",                             type: "is-primary", environment: ["development", "staging", "production"], message: null, sample_audio_source: require("../../../../../bioshogi/lib/bioshogi/assets/audios/nc176917.m4a"),           source_url: "https://commons.nicovideo.jp/material/nc176917",  author: "MFP",                  author_raw: null,                           bpm: null, audio_part_a_duration: 134.45, audio_part_a_loop: true,  desc: "",                           },
      { key: "audio_theme_is_ds5616",              name: "漢祭り",                                 type: "is-primary", environment: ["development", "staging", "production"], message: null, sample_audio_source: require("../../../../../bioshogi/lib/bioshogi/assets/audios/ds5616.m4a"),             source_url: "https://dova-s.jp/bgm/play5616.html",             author: "山口 壮",              author_raw: null,                           bpm: 85, audio_part_a_duration: 113.59, audio_part_a_loop: true,  desc: "",                           },
      { key: "audio_theme_is_nc142538",            name: "武蔵",                                   type: "is-primary", environment: ["development", "staging", "production"], message: null, sample_audio_source: require("../../../../../bioshogi/lib/bioshogi/assets/audios/nc142538.m4a"),           source_url: "https://commons.nicovideo.jp/material/nc142538",  author: "yuki",                 author_raw: null,                           bpm: null, audio_part_a_duration:  95.66, audio_part_a_loop: true,  desc: "",                           },
      { key: "audio_theme_is_shw_akatsuki_japan",  name: "Akatsuki JAPAN",                         type: "is-primary", environment: ["development", "staging", "production"], message: null, sample_audio_source: require("../../../../../bioshogi/lib/bioshogi/assets/audios/shw_akatsuki_japan.m4a"), source_url: "http://shw.in/",                                  author: "SHW",                  author_raw: null,                           bpm: 135,  audio_part_a_duration: 236.64, audio_part_a_loop: true,  desc: "",                           },
      { key: "audio_theme_is_ds3895",              name: "百花繚乱",                               type: "is-primary", environment: ["development", "staging", "production"], message: null, sample_audio_source: require("../../../../../bioshogi/lib/bioshogi/assets/audios/ds3895.m4a"),             source_url: "https://dova-s.jp/bgm/play3895.html",             author: "天休ひさし",           author_raw: null,                           bpm: 106, audio_part_a_duration: 133.7,  audio_part_a_loop: true,  desc: "loop",                       },
      { key: "audio_theme_is_shw_tsudzumi_japan3", name: "Tsudzumi JAPAN 3",                      type: "is-primary", environment: ["development", "staging", "production"], message: null, sample_audio_source: require("../../../../../bioshogi/lib/bioshogi/assets/audios/shw_tsudzumi_japan3.m4a"), source_url: "http://shw.in/",                                 author: "SHW",                  author_raw: null,                            bpm: 130,  audio_part_a_duration: 293.49, audio_part_a_loop: true,  desc: "loop",                       },
      { key: "audio_theme_is_nc145888",            name: "龍神 -Ryujin-",                         type: "is-primary", environment: ["development", "staging", "production"], message: null, sample_audio_source: require("../../../../../bioshogi/lib/bioshogi/assets/audios/nc145888.m4a"),            source_url: "https://commons.nicovideo.jp/material/nc145888", author: "謝謝P/魔界Symphony",   author_raw: null,                            bpm: 100, audio_part_a_duration: 128.0,  audio_part_a_loop: true,  desc: "2:08 でカットする必要あり",  },
      { key: "audio_theme_is_ds1245",              name: "流幻",                                  type: "is-primary", environment: ["development", "staging", "production"], message: null, sample_audio_source: require("../../../../../bioshogi/lib/bioshogi/assets/audios/ds1245.m4a"),              source_url: "https://dova-s.jp/bgm/play1245.html",            author: "かずち",               author_raw: null,                            bpm: 140, audio_part_a_duration: 96.05,  audio_part_a_loop: true,  desc: "",                           },
      { key: "audio_theme_is_ds2776",              name: "井の中の蛙",                            type: "is-primary", environment: ["development", "staging", "production"], message: null, sample_audio_source: require("../../../../../bioshogi/lib/bioshogi/assets/audios/ds2776.m4a"),              source_url: "https://dova-s.jp/bgm/play2776.html",            author: "スエノブ",             author_raw: null,                            bpm: 164, audio_part_a_duration: 35.16,  audio_part_a_loop: true,  desc: "",                           },
      { key: "audio_theme_is_ds11293",             name: "Jinrai Houto Rambu",                    type: "is-primary", environment: ["development", "staging", "production"], message: null, sample_audio_source: require("../../../../../bioshogi/lib/bioshogi/assets/audios/ds11293.m4a"),             source_url: "https://dova-s.jp/bgm/play11293.html",           author: "ISAo",                 author_raw: null,                            bpm: 104, audio_part_a_duration: 49.29,  audio_part_a_loop: true,  desc: "",                           },
      { separator: true                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             },
      { key: "audio_theme_is_ds6719",              name: "Hero",                                  type: "is-primary", environment: ["development", "staging", "production"], message: null, sample_audio_source: require("../../../../../bioshogi/lib/bioshogi/assets/audios/ds6719.m4a"),              source_url: "https://dova-s.jp/bgm/play6719.html",            author: "Low",                  author_raw: null,                            bpm: null, audio_part_a_duration: 158.17, audio_part_a_loop: true,  desc: "",                           },
      { key: "audio_theme_is_ds7615",              name: "Winner",                                type: "is-primary", environment: ["development", "staging", "production"], message: null, sample_audio_source: require("../../../../../bioshogi/lib/bioshogi/assets/audios/ds7615.m4a"),             source_url: "https://dova-s.jp/bgm/play7615.html",             author: "FLASH☆BEAT",          author_raw: null,                            bpm: null, audio_part_a_duration: 120.16, audio_part_a_loop: true,  desc: "loop",                       },
      { key: "audio_theme_is_ds11459",             name: "Dead End Strike",                       type: "is-primary", environment: ["development", "staging", "production"], message: null, sample_audio_source: require("../../../../../bioshogi/lib/bioshogi/assets/audios/ds11459.m4a"),             source_url: "https://dova-s.jp/bgm/play11459.html",           author: "ISAo",                 author_raw: null,                            bpm: 160,  audio_part_a_duration: 122.42, audio_part_a_loop: true,  desc: "",                           },
      { separator: true                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             },
      { key: "audio_theme_is_nc107860",            name: "Shall we meet ?",                       type: "is-primary", environment: ["development", "staging", "production"], message: null, sample_audio_source: require("../../../../../bioshogi/lib/bioshogi/assets/audios/nc107860.m4a"),           source_url: "https://commons.nicovideo.jp/material/nc107860",  author: "MATSU",                author_raw: null,                            bpm: null, audio_part_a_duration:  69.85, audio_part_a_loop: true,  desc: "loop",                       },
      { key: "audio_theme_is_ds11184",             name: "Gliese (Prod. Khaim)",                  type: "is-primary", environment: ["development", "staging", "production"], message: null, sample_audio_source: require("../../../../../bioshogi/lib/bioshogi/assets/audios/ds11184.m4a"),             source_url: "https://dova-s.jp/bgm/play11184.html",           author: "Khaim",                author_raw: null,                            bpm: null, audio_part_a_duration: 157.13, audio_part_a_loop: true,  desc: "",                           },
      { key: "audio_theme_is_ds3812",              name: "Three Keys (Freestyle Rap Beat No.02)", type: "is-primary", environment: ["development", "staging", "production"], message: null, sample_audio_source: require("../../../../../bioshogi/lib/bioshogi/assets/audios/ds3812.m4a"),              source_url: "https://dova-s.jp/bgm/play3812.html",            author: "Khaim",                author_raw: null,                            bpm: null, audio_part_a_duration: 237.72, audio_part_a_loop: false, desc: "",                           },
      { key: "audio_theme_is_ds14226",             name: "Somebody (Prod. Khaim)",                type: "is-primary", environment: ["development", "staging", "production"], message: null, sample_audio_source: require("../../../../../bioshogi/lib/bioshogi/assets/audios/ds14226.m4a"),             source_url: "https://dova-s.jp/bgm/play14226.html",           author: "Khaim",                author_raw: null,                            bpm: 86,   audio_part_a_duration: 158.17, audio_part_a_loop: true,  desc: "",                           },
      { key: "audio_theme_is_ds12450",             name: "Somehow (Prod. Khaim)",                 type: "is-primary", environment: ["development", "staging", "production"], message: null, sample_audio_source: require("../../../../../bioshogi/lib/bioshogi/assets/audios/ds12450.m4a"),            source_url: "https://dova-s.jp/bgm/play12450.html",            author: "Khaim",                author_raw: null,                            bpm: 170,  audio_part_a_duration: 203.34, audio_part_a_loop: true,  desc: "loop",                       },
      { key: "audio_theme_is_ds6574",              name: "Stay On Your Mind",                     type: "is-primary", environment: ["development", "staging", "production"], message: null, sample_audio_source: require("../../../../../bioshogi/lib/bioshogi/assets/audios/ds6574.m4a"),              source_url: "https://dova-s.jp/bgm/play6574.html",            author: "Khaim",                author_raw: null,                            bpm: 118,  audio_part_a_duration: 174.6,  audio_part_a_loop: true,  desc: "",                           },
      { key: "audio_theme_is_ds3479",              name: "Blue Ever",                             type: "is-primary", environment: ["development", "staging", "production"], message: null, sample_audio_source: require("../../../../../bioshogi/lib/bioshogi/assets/audios/ds3479.m4a"),              source_url: "https://dova-s.jp/bgm/play3479.html",            author: "Khaim",                author_raw: null,                            bpm: 120,  audio_part_a_duration: 56.03,  audio_part_a_loop: true,  desc: "",                           },
      { key: "audio_theme_is_ds4000",              name: "Space Town (Brand New Mix)",            type: "is-primary", environment: ["development", "staging", "production"], message: null, sample_audio_source: require("../../../../../bioshogi/lib/bioshogi/assets/audios/ds4000.m4a"),             source_url: "https://dova-s.jp/bgm/play4000.html",             author: "Khaim",                author_raw: null,                            bpm: 120,  audio_part_a_duration:  96.05, audio_part_a_loop: true,  desc: "loop",                       },
      { separator: true                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             },
      { key: "audio_theme_is_ds4712",              name: "昼下がり気分",                          type: "is-primary", environment: ["development", "staging", "production"], message: null, sample_audio_source: require("../../../../../bioshogi/lib/bioshogi/assets/audios/ds4712.m4a"),             source_url: "https://dova-s.jp/bgm/play4712.html",             author: "KK",                   author_raw: null,                            bpm: null, audio_part_a_duration: 235.26, audio_part_a_loop: true,  desc: "",                           },
      { key: "audio_theme_is_nc35943",             name: "昼下がり",                              type: "is-primary", environment: ["development", "staging", "production"], message: null, sample_audio_source: require("../../../../../bioshogi/lib/bioshogi/assets/audios/nc35943.m4a"),            source_url: "https://commons.nicovideo.jp/material/nc35943",   author: "369(みろく)",          author_raw: null,                            bpm: null, audio_part_a_duration:  83.54, audio_part_a_loop: true,  desc: "loop",                       },
      { key: "audio_theme_is_ds13037",             name: "YouTube向けラグタイム",                 type: "is-primary", environment: ["development", "staging", "production"], message: null, sample_audio_source: require("../../../../../bioshogi/lib/bioshogi/assets/audios/ds13037.m4a"),            source_url: "https://dova-s.jp/bgm/play13037.html",            author: "天休ひさし",           author_raw: null,                            bpm: null, audio_part_a_duration:  96.02, audio_part_a_loop: true,  desc: "loop",                       },
      { key: "audio_theme_is_nc105702",            name: "ぐだぐだな感じ",                        type: "is-primary", environment: ["development", "staging", "production"], message: null, sample_audio_source: require("../../../../../bioshogi/lib/bioshogi/assets/audios/nc105702.m4a"),           source_url: "https://commons.nicovideo.jp/material/nc105702",  author: "yuki",                 author_raw: null,                            bpm: null, audio_part_a_duration:  94.15, audio_part_a_loop: true,  desc: "",                           },
      { key: "audio_theme_is_nc3366",              name: "はてな",                                type: "is-primary", environment: ["development", "staging", "production"], message: null, sample_audio_source: require("../../../../../bioshogi/lib/bioshogi/assets/audios/nc3366.m4a"),             source_url: "https://commons.nicovideo.jp/material/nc3366",    author: "しましまP @shimakid",  author_raw: null,                            bpm: 92,   audio_part_a_duration:  54.81, audio_part_a_loop: true,  desc: "",                           },
      { separator: true                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             },
      { key: "audio_theme_is_nc770",               name: "優しい風",                              type: "is-primary", environment: ["development", "staging", "production"], message: null, sample_audio_source: require("../../../../../bioshogi/lib/bioshogi/assets/audios/nc770.m4a"),              source_url: "https://commons.nicovideo.jp/material/nc770",     author: "McCoy",                author_raw: null,                            bpm: null, audio_part_a_duration: 120.04, audio_part_a_loop: false, desc: "",                           },
      { key: "audio_theme_is_nc43122",             name: "夜間航海",                              type: "is-primary", environment: ["development", "staging", "production"], message: null, sample_audio_source: require("../../../../../bioshogi/lib/bioshogi/assets/audios/nc43122.m4a"),            source_url: "https://commons.nicovideo.jp/material/nc43122",   author: "McCoy",                author_raw: null,                            bpm: null, audio_part_a_duration: 277.14, audio_part_a_loop: false, desc: "",                           },
      { key: "audio_theme_is_nc10812",             name: "BGM026 Jazz",                           type: "is-primary", environment: ["development", "staging", "production"], message: null, sample_audio_source: require("../../../../../bioshogi/lib/bioshogi/assets/audios/nc10812.m4a"),            source_url: "https://commons.nicovideo.jp/material/nc10812",   author: "sanche",               author_raw: null,                            bpm: null, audio_part_a_duration: 144.04, audio_part_a_loop: true,  desc: "ニコ生の作品以外では要連絡", },
      { separator: true                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             },
      { key: "audio_theme_is_nc97718",             name: "てってってー",                          type: "is-primary", environment: ["development", "staging", "production"], message: null, sample_audio_source: require("../../../../../bioshogi/lib/bioshogi/assets/audios/nc97718.m4a"),            source_url: "https://commons.nicovideo.jp/material/nc97718",   author: "ターリー◆dtTARy/mt2", author_raw: null,                            bpm: null, audio_part_a_duration:  24.0,  audio_part_a_loop: true,  desc: "",                           },
      { key: "audio_theme_is_nc768",               name: "マーチ・マーチ",                        type: "is-primary", environment: ["development", "staging", "production"], message: null, sample_audio_source: require("../../../../../bioshogi/lib/bioshogi/assets/audios/nc768.m4a"),              source_url: "https://commons.nicovideo.jp/material/nc768",     author: "McCoy",                author_raw: null,                            bpm: null, audio_part_a_duration: 245.63, audio_part_a_loop: true,  desc: "",                           },
      { separator: true                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             },
      { key: "audio_theme_is_ds3480",              name: "ロデオ牧場",                            type: "is-primary", environment: ["development", "staging", "production"], message: null, sample_audio_source: require("../../../../../bioshogi/lib/bioshogi/assets/audios/ds3480.m4a"),              source_url: "https://dova-s.jp/bgm/play3480.html",            author: "かずち",               author_raw: null,                            bpm: 130,  audio_part_a_duration: 55.44,  audio_part_a_loop: true,  desc: "",                           },
      { key: "audio_theme_is_ds7138",              name: "パーティーはハチャメチャ大騒ぎ",        type: "is-primary", environment: ["development", "staging", "production"], message: null, sample_audio_source: require("../../../../../bioshogi/lib/bioshogi/assets/audios/ds7138.m4a"),              source_url: "https://dova-s.jp/bgm/play7138.html",            author: "スエノブ",             author_raw: null,                            bpm: 107,  audio_part_a_duration: 36.05,  audio_part_a_loop: true,  desc: "",                           },
      { key: "audio_theme_is_nc55257",             name: "3分クッキング (break beats)",           type: "is-primary", environment: ["development", "staging", "production"], message: null, sample_audio_source: require("../../../../../bioshogi/lib/bioshogi/assets/audios/nc55257.m4a"),            source_url: "https://commons.nicovideo.jp/material/nc55257",   author: "ジェルバ",             author_raw: null,                            bpm: null, audio_part_a_duration: 144.59, audio_part_a_loop: true,  desc: "",                           },
    ]
  }

  get duration_sec() {
    if (this.audio_part_a_duration) {
      return Gs.number_round(this.audio_part_a_duration)
    }
  }

  get duration_mmss() {
    if (this.audio_part_a_duration) {
      return dayjs.unix(this.duration_sec).format("mm:ss")
    }
  }

  get loop_support_p() {
    return this.audio_part_a_loop
  }
}
