#!/usr/bin/env ruby
require File.expand_path('../../../config/environment', __FILE__)

history_result = Swars::Agent::History.new(remote_run: true, user_key: "Jpriglim", page_index: 0, rule_key: :ten_min).fetch
tp history_result.all_keys
tp history_result.all_keys.collect { |key| Swars::Agent::Record.new(remote_run: true, key: key).fetch }

# >> |--------------------------------------|
# >> | cadenacchi-Jpriglim-20230103_171144  |
# >> | Jpriglim-mitsuisan-20230103_165411   |
# >> | Jpriglim-masa0845-20230103_154444    |
# >> | kazune_to-Jpriglim-20230103_140622   |
# >> | Jpriglim-ThomasNobuo-20230103_134734 |
# >> | Jpriglim-yurippe-20230103_133117     |
# >> | Jpriglim-kazuyama777-20230103_132606 |
# >> | Jpriglim-Sbpsh41-20230103_125817     |
# >> | Jpriglim-iwaei-20230103_111635       |
# >> | jabikun-Jpriglim-20230103_105913     |
# >> |--------------------------------------|
# >> |---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------+----------------+--------------------+-------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------|
# >> | gameHash                                                                                                                                                                                                                                                            | userConfig                                                                                          | isNeedRealtime | isNeedTargetParent | isNotReload | settings                                                                                                                                                                                                                | version |
# >> |---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------+----------------+--------------------+-------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------|
# >> | {"name"=>"cadenacchi-Jpriglim-20230103_171144", "gtype"=>"", "opponent_type"=>0, "sente"=>"cadenacchi", "gote"=>"Jpriglim", "sente_dan"=>0, "gote_dan"=>-1, "sente_avatar"=>"_", "gote_avatar"=>"_e2012s4c", "result"=>"GOTE_WIN_TORYO", "handicap"=>0, "init_sf... | {"imgPieceType"=>"ja_single", "soundEnable"=>true, "voiceType"=>0, "situationFormat"=>"evaluation"} | false          | false              | false       | {"cdn.web"=>"//shogiwars-cdn.heroz.jp", "cdn.image"=>"//image-pona.heroz.jp", "cdn.sound"=>"//sound-pona.heroz.jp", "goldengate.match.host"=>"wss://shogiwars-game-web.heroz.jp:7012", "javascript.log_level"=>"error"} |         |
# >> | {"name"=>"Jpriglim-mitsuisan-20230103_165411", "gtype"=>"", "opponent_type"=>0, "sente"=>"Jpriglim", "gote"=>"mitsuisan", "sente_dan"=>-1, "gote_dan"=>1, "sente_avatar"=>"_e2012s4c", "gote_avatar"=>"_e1912s2b", "result"=>"GOTE_WIN_TIMEOUT", "handicap"=>0, ... | {"imgPieceType"=>"ja_single", "soundEnable"=>true, "voiceType"=>0, "situationFormat"=>"evaluation"} | false          | false              | false       | {"cdn.web"=>"//shogiwars-cdn.heroz.jp", "cdn.image"=>"//image-pona.heroz.jp", "cdn.sound"=>"//sound-pona.heroz.jp", "goldengate.match.host"=>"wss://shogiwars-game-web.heroz.jp:7012", "javascript.log_level"=>"error"} |         |
# >> | {"name"=>"Jpriglim-masa0845-20230103_154444", "gtype"=>"", "opponent_type"=>0, "sente"=>"Jpriglim", "gote"=>"masa0845", "sente_dan"=>-1, "gote_dan"=>-1, "sente_avatar"=>"_e2012s4c", "gote_avatar"=>"_f190403a", "result"=>"SENTE_WIN_TORYO", "handicap"=>0, "i... | {"imgPieceType"=>"ja_single", "soundEnable"=>true, "voiceType"=>0, "situationFormat"=>"evaluation"} | false          | false              | false       | {"cdn.web"=>"//shogiwars-cdn.heroz.jp", "cdn.image"=>"//image-pona.heroz.jp", "cdn.sound"=>"//sound-pona.heroz.jp", "goldengate.match.host"=>"wss://shogiwars-game-web.heroz.jp:7012", "javascript.log_level"=>"error"} |         |
# >> | {"name"=>"kazune_to-Jpriglim-20230103_140622", "gtype"=>"", "opponent_type"=>0, "sente"=>"kazune_to", "gote"=>"Jpriglim", "sente_dan"=>0, "gote_dan"=>-1, "sente_avatar"=>"_03", "gote_avatar"=>"_e2012s4c", "result"=>"GOTE_WIN_CHECKMATE", "handicap"=>0, "ini... | {"imgPieceType"=>"ja_single", "soundEnable"=>true, "voiceType"=>0, "situationFormat"=>"evaluation"} | false          | false              | false       | {"cdn.web"=>"//shogiwars-cdn.heroz.jp", "cdn.image"=>"//image-pona.heroz.jp", "cdn.sound"=>"//sound-pona.heroz.jp", "goldengate.match.host"=>"wss://shogiwars-game-web.heroz.jp:7012", "javascript.log_level"=>"error"} |         |
# >> | {"name"=>"Jpriglim-ThomasNobuo-20230103_134734", "gtype"=>"", "opponent_type"=>0, "sente"=>"Jpriglim", "gote"=>"ThomasNobuo", "sente_dan"=>-1, "gote_dan"=>1, "sente_avatar"=>"_e2012s4c", "gote_avatar"=>"_e2112s6c", "result"=>"SENTE_WIN_TORYO", "handicap"=>... | {"imgPieceType"=>"ja_single", "soundEnable"=>true, "voiceType"=>0, "situationFormat"=>"evaluation"} | false          | false              | false       | {"cdn.web"=>"//shogiwars-cdn.heroz.jp", "cdn.image"=>"//image-pona.heroz.jp", "cdn.sound"=>"//sound-pona.heroz.jp", "goldengate.match.host"=>"wss://shogiwars-game-web.heroz.jp:7012", "javascript.log_level"=>"error"} |         |
# >> | {"name"=>"Jpriglim-yurippe-20230103_133117", "gtype"=>"", "opponent_type"=>0, "sente"=>"Jpriglim", "gote"=>"yurippe", "sente_dan"=>-1, "gote_dan"=>-1, "sente_avatar"=>"_e2012s4c", "gote_avatar"=>"_02", "result"=>"GOTE_WIN_CHECKMATE", "handicap"=>0, "init_s... | {"imgPieceType"=>"ja_single", "soundEnable"=>true, "voiceType"=>0, "situationFormat"=>"evaluation"} | false          | false              | false       | {"cdn.web"=>"//shogiwars-cdn.heroz.jp", "cdn.image"=>"//image-pona.heroz.jp", "cdn.sound"=>"//sound-pona.heroz.jp", "goldengate.match.host"=>"wss://shogiwars-game-web.heroz.jp:7012", "javascript.log_level"=>"error"} |         |
# >> | {"name"=>"Jpriglim-kazuyama777-20230103_132606", "gtype"=>"", "opponent_type"=>0, "sente"=>"Jpriglim", "gote"=>"kazuyama777", "sente_dan"=>-1, "gote_dan"=>0, "sente_avatar"=>"_e2012s4c", "gote_avatar"=>"_f230101a", "result"=>"GOTE_WIN_TORYO", "handicap"=>0... | {"imgPieceType"=>"ja_single", "soundEnable"=>true, "voiceType"=>0, "situationFormat"=>"evaluation"} | false          | false              | false       | {"cdn.web"=>"//shogiwars-cdn.heroz.jp", "cdn.image"=>"//image-pona.heroz.jp", "cdn.sound"=>"//sound-pona.heroz.jp", "goldengate.match.host"=>"wss://shogiwars-game-web.heroz.jp:7012", "javascript.log_level"=>"error"} |         |
# >> | {"name"=>"Jpriglim-Sbpsh41-20230103_125817", "gtype"=>"", "opponent_type"=>0, "sente"=>"Jpriglim", "gote"=>"Sbpsh41", "sente_dan"=>-1, "gote_dan"=>1, "sente_avatar"=>"_e2012s4c", "gote_avatar"=>"_e1912s4c", "result"=>"GOTE_WIN_TORYO", "handicap"=>0, "init_... | {"imgPieceType"=>"ja_single", "soundEnable"=>true, "voiceType"=>0, "situationFormat"=>"evaluation"} | false          | false              | false       | {"cdn.web"=>"//shogiwars-cdn.heroz.jp", "cdn.image"=>"//image-pona.heroz.jp", "cdn.sound"=>"//sound-pona.heroz.jp", "goldengate.match.host"=>"wss://shogiwars-game-web.heroz.jp:7012", "javascript.log_level"=>"error"} |         |
# >> | {"name"=>"Jpriglim-iwaei-20230103_111635", "gtype"=>"", "opponent_type"=>0, "sente"=>"Jpriglim", "gote"=>"iwaei", "sente_dan"=>-1, "gote_dan"=>1, "sente_avatar"=>"_e2012s4c", "gote_avatar"=>"_e2212s4c", "result"=>"SENTE_WIN_TORYO", "handicap"=>0, "init_sfe... | {"imgPieceType"=>"ja_single", "soundEnable"=>true, "voiceType"=>0, "situationFormat"=>"evaluation"} | false          | false              | false       | {"cdn.web"=>"//shogiwars-cdn.heroz.jp", "cdn.image"=>"//image-pona.heroz.jp", "cdn.sound"=>"//sound-pona.heroz.jp", "goldengate.match.host"=>"wss://shogiwars-game-web.heroz.jp:7012", "javascript.log_level"=>"error"} |         |
# >> | {"name"=>"jabikun-Jpriglim-20230103_105913", "gtype"=>"", "opponent_type"=>0, "sente"=>"jabikun", "gote"=>"Jpriglim", "sente_dan"=>0, "gote_dan"=>-1, "sente_avatar"=>"_e2207s7c", "gote_avatar"=>"_e2012s4c", "result"=>"SENTE_WIN_TORYO", "handicap"=>0, "init... | {"imgPieceType"=>"ja_single", "soundEnable"=>true, "voiceType"=>0, "situationFormat"=>"evaluation"} | false          | false              | false       | {"cdn.web"=>"//shogiwars-cdn.heroz.jp", "cdn.image"=>"//image-pona.heroz.jp", "cdn.sound"=>"//sound-pona.heroz.jp", "goldengate.match.host"=>"wss://shogiwars-game-web.heroz.jp:7012", "javascript.log_level"=>"error"} |         |
# >> |---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------+----------------+--------------------+-------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------|
