import { ApplicationMemoryRecord } from "@/components/models/application_memory_record.js"
import dayjs from "dayjs"
import { Gs } from "@/components/models/gs.js"

export class AudioThemeInfo extends ApplicationMemoryRecord {
  static field_label = "BGM"
  static field_message = ""

  static get define() {
    return [
      // ../../../../../bioshogi/lib/bioshogi/audio_theme_info.rb
      { key: "is_audio_theme_custom",             name: "カスタム",                              environment: ["development", "staging", "production"], sample_source: null,                                                                                                                                                                                                                                                                                                                                      },
      { key: "is_audio_theme_shw_akatsuki_japan", name: "Akatsuki JAPAN",                        environment: ["development", "staging", "production"], sample_source: require("../../../../../bioshogi/lib/bioshogi/assets/audios/shw_akatsuki_japan.m4a"),  source_url: "http://shw.in/",                                 author: "SHW",                                              bpm: 135.0,  audio_part_a_duration: 236.64, audio_part_a_loop: true,  desc: "",                          },
      { key: "is_audio_theme_ds13037",            name: "YouTube向けラグタイム",                 environment: ["development", "staging", "production"], sample_source: require("../../../../../bioshogi/lib/bioshogi/assets/audios/ds13037.m4a"),             source_url: "https://dova-s.jp/bgm/play13037.html",           author: "天休ひさし",                                       bpm: null,   audio_part_a_duration:  96.02, audio_part_a_loop: true,  desc: "loop",                      },
      { key: "is_audio_theme_ds3895",             name: "百花繚乱",                              environment: ["development", "staging", "production"], sample_source: require("../../../../../bioshogi/lib/bioshogi/assets/audios/ds3895.m4a"),              source_url: "https://dova-s.jp/bgm/play3895.html",            author: "天休ひさし",                                       bpm: 106.48, audio_part_a_duration: 133.7,  audio_part_a_loop: true,  desc: "loop",                      },
      { key: "is_audio_theme_ds3479",             name: "Blue Ever",                             environment: ["development", "staging", "production"], sample_source: require("../../../../../bioshogi/lib/bioshogi/assets/audios/ds3479.m4a"),              source_url: "https://dova-s.jp/bgm/play3479.html",            author: "Khaim",                                            bpm: 120.02, audio_part_a_duration: 56.03,  audio_part_a_loop: true,  desc: "",                          },
      { key: "is_audio_theme_ds14640",            name: "しゅわしゅわハニーレモン350ml",         environment: ["development", "staging", "production"], sample_source: require("../../../../../bioshogi/lib/bioshogi/assets/audios/ds14640.m4a"),             source_url: "https://dova-s.jp/bgm/play14640.html",           author: "しゃろう",                                         bpm: 125.03,   audio_part_a_duration:  60+36,  audio_part_a_loop: true,  desc: "",                         },
      { key: "is_audio_theme_ds1982",             name: "8-bit Aggressive1",                     environment: ["development", "staging", "production"], sample_source: require("../../../../../bioshogi/lib/bioshogi/assets/audios/ds1982.m4a"),              source_url: "https://dova-s.jp/bgm/play1982.html",        author: "もっぴーさうんど",                                               bpm: 104.86,   audio_part_a_duration: 60*1+58, audio_part_a_loop: false,  desc: "",                         },
      { key: "is_audio_theme_nc55257",            name: "3分クッキング (break beats)",           environment: ["development", "staging", "production"], sample_source: require("../../../../../bioshogi/lib/bioshogi/assets/audios/nc55257.m4a"),             source_url: "https://commons.nicovideo.jp/material/nc55257",  author: "ジェルバ",                                         bpm: 157.02, audio_part_a_duration: 144.59, audio_part_a_loop: true,  desc: "",                          },
      { key: "is_audio_theme_ds3480",             name: "ロデオ牧場",                            environment: ["development", "staging", "production"], sample_source: require("../../../../../bioshogi/lib/bioshogi/assets/audios/ds3480.m4a"),              source_url: "https://dova-s.jp/bgm/play3480.html",            author: "かずち",                                           bpm: 129.87, audio_part_a_duration: 55.44,  audio_part_a_loop: true,  desc: "",                          },
      { key: "is_audio_theme_nc97718",            name: "てってってー",                          environment: ["development", "staging", "production"], sample_source: require("../../../../../bioshogi/lib/bioshogi/assets/audios/nc97718.m4a"),             source_url: "https://commons.nicovideo.jp/material/nc97718",  author: "ターリー◆dtTARy/mt2",                             bpm: 100.05, audio_part_a_duration:  24.0,  audio_part_a_loop: true,  desc: "",                          },
      { key: "is_audio_theme_ds5616",             name: "漢祭り",                                environment: ["development", "staging", "production"], sample_source: require("../../../../../bioshogi/lib/bioshogi/assets/audios/ds5616.m4a"),              source_url: "https://dova-s.jp/bgm/play5616.html",            author: "山口 壮",                                          bpm: 85.24,  audio_part_a_duration: 113.59, audio_part_a_loop: false,  desc: "",                         },
      { key: "is_audio_theme_ds1022",             name: "パステルハウス",                        environment: ["development", "staging", "production"], sample_source: require("../../../../../bioshogi/lib/bioshogi/assets/audios/ds1022.m4a"),  source_url: "https://dova-s.jp/bgm/play1022.html",   author: "かずち",           bpm: 120,   audio_part_a_duration:  104.909,  audio_part_a_loop: true,  desc: "", },
      { key: "is_audio_theme_ds10827",            name: "Roll Roll Roll",                        environment: ["development", "staging", "production"], sample_source: require("../../../../../bioshogi/lib/bioshogi/assets/audios/ds10827.m4a"),  source_url: "https://dova-s.jp/bgm/play10827.html", author: "もっぴーさうんど", bpm: 91.54, audio_part_a_duration:  139.129,  audio_part_a_loop: true,  desc: "", },
      { key: "is_audio_theme_ds2142",             name: "いちごホイップ",                        environment: ["development", "staging", "production"], sample_source: require("../../../../../bioshogi/lib/bioshogi/assets/audios/ds2142.m4a"),  source_url: "https://dova-s.jp/bgm/play2142.html",   author: "yuki",             bpm: 157,   audio_part_a_duration:  124.529,  audio_part_a_loop: true,  desc: "", },
      { key: "is_audio_theme_ds4520",             name: "わくわくクッキングタイム的なBGM",       environment: ["development", "staging", "production"], sample_source: require("../../../../../bioshogi/lib/bioshogi/assets/audios/ds4520.m4a"),  source_url: "https://dova-s.jp/bgm/play4520.html",   author: "鷹尾まさき",       bpm: 130,   audio_part_a_duration:  61.205,   audio_part_a_loop: false, desc: "", },
      { key: "is_audio_theme_ds5615",             name: "shuffle shuffle",                       environment: ["development", "staging", "production"], sample_source: require("../../../../../bioshogi/lib/bioshogi/assets/audios/ds5615.m4a"),  source_url: "https://dova-s.jp/bgm/play5615.html",   author: "KK",               bpm: 170,   audio_part_a_duration:  129.96,   audio_part_a_loop: false, desc: "", },
      { key: "is_audio_theme_ds568",              name: "かえるのピアノ",                        environment: ["development", "staging", "production"], sample_source: require("../../../../../bioshogi/lib/bioshogi/assets/audios/ds568.m4a"),  source_url: "https://dova-s.jp/bgm/play568.html",     author: "こおろぎ",         bpm: null,  audio_part_a_duration:  331.938,  audio_part_a_loop: true,  desc: "", },
      { key: "is_audio_theme_ds8705",             name: "雲はながれて",                          environment: ["development", "staging", "production"], sample_source: require("../../../../../bioshogi/lib/bioshogi/assets/audios/ds8705.m4a"),  source_url: "https://dova-s.jp/bgm/play8705.html",   author: "Phalene",          bpm: 80,    audio_part_a_duration: 160.056,   audio_part_a_loop: false, desc: "", },
      { key: "is_audio_theme_headspin_only",      name: "ヘッドスピン",                          environment: ["development", "staging", "production"], sample_source: require("../../../../../bioshogi/lib/bioshogi/assets/audios/headspin_long.m4a"),       source_url: null,                                             author: "GarageBand Sound Library", bpm: 120,    audio_part_a_duration:  28.05, audio_part_a_loop: true,  desc: "",                          },
      { key: "is_audio_theme_breakbeat_only",     name: "ブレイクビート",                        environment: ["development", "staging"],               sample_source: require("../../../../../bioshogi/lib/bioshogi/assets/audios/breakbeat_long.m4a"),      source_url: null,                                             author: "GarageBand Sound Library", bpm: null,   audio_part_a_duration:  35.55, audio_part_a_loop: false, desc: "",                          },
      { key: "is_audio_theme_dance_chain",        name: "ヘッドスピン → ブレイクビート",        environment: ["development", "staging"],               sample_source: null,                                                                                  source_url: null,                                             author: "GarageBand Sound Library", bpm: null,   audio_part_a_duration:  null,  audio_part_a_loop: false, desc: "",                          },
      { key: "is_audio_theme_nc142538",           name: "武蔵",                                  environment: ["development", "staging", "production"], sample_source: require("../../../../../bioshogi/lib/bioshogi/assets/audios/nc142538.m4a"),            source_url: "https://commons.nicovideo.jp/material/nc142538", author: "yuki",                                             bpm: 147.91, audio_part_a_duration:  95.66, audio_part_a_loop: false,  desc: "",                          },
      { key: "is_audio_theme_nc107860",           name: "Shall we meet ?",                       environment: ["development", "staging", "production"], sample_source: require("../../../../../bioshogi/lib/bioshogi/assets/audios/nc107860.m4a"),            source_url: "https://commons.nicovideo.jp/material/nc107860", author: "MATSU",                                            bpm: 146.67, audio_part_a_duration:  69.85, audio_part_a_loop: true,  desc: "loop",                      },
      { key: "is_audio_theme_ds11184",            name: "Gliese (Prod. Khaim)",                  environment: ["development", "staging", "production"], sample_source: require("../../../../../bioshogi/lib/bioshogi/assets/audios/ds11184.m4a"),             source_url: "https://dova-s.jp/bgm/play11184.html",           author: "Khaim",                                            bpm: 110.03, audio_part_a_duration: 157.13, audio_part_a_loop: true,  desc: "",                          },
      { key: "is_audio_theme_ds3812",             name: "Three Keys (Freestyle Rap Beat No.02)", environment: ["development", "staging", "production"], sample_source: require("../../../../../bioshogi/lib/bioshogi/assets/audios/ds3812.m4a"),              source_url: "https://dova-s.jp/bgm/play3812.html",            author: "Khaim",                                            bpm: null,   audio_part_a_duration: 237.72, audio_part_a_loop: false, desc: "",                          },
      { key: "is_audio_theme_ds6574",             name: "Stay On Your Mind",                     environment: ["development", "staging", "production"], sample_source: require("../../../../../bioshogi/lib/bioshogi/assets/audios/ds6574.m4a"),              source_url: "https://dova-s.jp/bgm/play6574.html",            author: "Khaim",                                            bpm: 117.85, audio_part_a_duration: 174.6,  audio_part_a_loop: true,  desc: "",                          },
      { key: "is_audio_theme_ds4712",             name: "昼下がり気分",                          environment: ["development", "staging", "production"], sample_source: require("../../../../../bioshogi/lib/bioshogi/assets/audios/ds4712.m4a"),              source_url: "https://dova-s.jp/bgm/play4712.html",            author: "KK",                                               bpm: null,   audio_part_a_duration: 235.26, audio_part_a_loop: true,  desc: "",                          },
      { key: "is_audio_theme_ds4616",             name: "夏はsummer!!",                          environment: ["development", "staging", "production"], sample_source: require("../../../../../bioshogi/lib/bioshogi/assets/audios/ds4616.m4a"),              source_url: "https://dova-s.jp/bgm/play4616.html",            author: "Keyta",                                            bpm: 137.93,   audio_part_a_duration: 60*3+18, audio_part_a_loop: false, desc: "",                         },
      { key: "is_audio_theme_ds7138",             name: "パーティーはハチャメチャ大騒ぎ",        environment: ["development", "staging", "production"], sample_source: require("../../../../../bioshogi/lib/bioshogi/assets/audios/ds7138.m4a"),              source_url: "https://dova-s.jp/bgm/play7138.html",            author: "スエノブ",                                         bpm: 106.67, audio_part_a_duration: 36.05,  audio_part_a_loop: true,  desc: "",                          },
    ]
  }

  get duration_sec() {
    if (this.audio_part_a_duration) {
      return Gs.number_round(this.audio_part_a_duration)
    }
  }

  get duration_mmss() {
    if (this.audio_part_a_duration) {
      return dayjs.unix(this.duration_sec).format("mm:ss")
    }
  }

  get loop_support_p() {
    return this.audio_part_a_loop
  }

  get introduction() {
    const a = []
    if (this.author) {
      a.push(`${this.author}さんの`)
    }
    if (this.name) {
      a.push(this.name)
    }
    return a.join("")
  }
}
