import { ParamBase } from '@/components/models/param_base.js'

export class ParamInfo extends ParamBase {
  static get define() {
    return [
      { key: "room_key",                     type: "string",  name: "合言葉",                                 defaults: { development: null,                 production: "",                                  }, permanent: true,  relation: null,                   alias: ["room_code"], input_attrs: null,                     desc: null, after_set: null,                 },
      { key: "complement_room_keys",         type: "array",   name: "合言葉履歴",                             defaults: { development: null,                 production: [],                                  }, permanent: true,  relation: null,                   alias: null,          input_attrs: null,                     desc: null, after_set: null,                 },
      { key: "room_keys_limit",              type: "integer", name: "合言葉履歴の最大",                       defaults: { development: 3,                    production: 10,                                  }, permanent: false, relation: null,                   alias: null,          input_attrs: null,                     desc: null, after_set: null,                 },
      { key: "user_name",                    type: "string",  name: "名前",                                   defaults: { development: null,                 production: c => c.g_current_user_name || "",    }, permanent: true,  relation: null,                   alias: null,          input_attrs: null,                     desc: null, after_set: null,                 }, // c => c.xprofile_load(), },
      { key: "sp_mode",                      type: "string",  name: "将棋盤モード",                           defaults: { development: null,                 production: "play",                              }, permanent: false, relation: null,                   alias: null,          input_attrs: null,                     desc: null, after_set: null,                 },
      { key: "legal_key",                    type: "string",  name: "内部ルール",                             defaults: { development: null,                 production: "strict",                            }, permanent: false, relation: "LegalInfo",            alias: null,          input_attrs: null,                     desc: null, after_set: null,                 },
      { key: "color_theme_key",              type: "string",  name: "画像の配色",                             defaults: { development: null,                 production: "is_color_theme_modern",             }, permanent: true,  relation: "ColorThemeInfo",       alias: null,          input_attrs: null,                     desc: null, after_set: null,                 },
      { key: "appearance_theme_key",         type: "string",  name: "基本配色",                               defaults: { development: null,                 production: "is_appearance_theme_b",             }, permanent: true,  relation: "AppearanceThemeInfo",  alias: null,          input_attrs: null,                     desc: null, after_set: null,                 },
      { key: "mobile_layout_key",            type: "string",  name: "スマホ利用時の持駒位置",                 defaults: { development: null,                 production: "ml_vertical",                       }, permanent: true,  relation: "MobileLayoutInfo",     alias: null,          input_attrs: null,                     desc: null, after_set: null,                 },
      { key: "ctrl_mode_key",                type: "string",  name: "コントローラー表示",                     defaults: { development: null,                 production: "is_ctrl_mode_hidden",               }, permanent: false, relation: "CtrlModeInfo",         alias: null,          input_attrs: null,                     desc: null, after_set: null,                 },
      { key: "debug_mode_key",               type: "string",  name: "デバッグモード",                         defaults: { development: "on",   production: "off",                 }, permanent: false, relation: "DebugModeInfo",        alias: null,          input_attrs: null,                     desc: null, after_set: null,                 },
      { key: "lift_cancel_action",           type: "string",  name: "駒移動キャンセル",                       defaults: { development: "standard",           production: "standard",                          }, permanent: true,  relation: "LiftCancelActionInfo", alias: null,          input_attrs: null,                     desc: null, after_set: null,                 },

      { key: "yomiage_mode_key",             type: "string",  name: "読み上げモード",                         defaults: { development: null,                 production: "is_yomiage_mode_on",                }, permanent: true,  relation: "YomiageModeInfo",      alias: null,          input_attrs: null,                     desc: null, after_set: null,                 },
      { key: "ai_mode_key",                  type: "string",  name: "ChatGPTモード",                          defaults: { development: null,                 production: "ai_mode_on",                        }, permanent: true,  relation: "AiModeInfo",           alias: null,          input_attrs: null,                     desc: null, after_set: null,                 },
      { key: "byoyomi_mode_key",             type: "string",  name: "秒読みモード",                           defaults: { development: null,                 production: "byoyomi_mode_9s",                   }, permanent: true,  relation: "ByoyomiModeInfo",      alias: null,          input_attrs: null,                     desc: null, after_set: null,                 },
      { key: "vibration_mode_key",           type: "string",  name: "振動モード",                             defaults: { development: null,                 production: "vibration_mode_on",                 }, permanent: true,  relation: "VibrationModeInfo",    alias: null,          input_attrs: null,                     desc: null, after_set: null,                 },
      { key: "next_turn_call_key",           type: "string",  name: "手番コール",                             defaults: { development: null,                 production: "is_next_turn_call_on",              }, permanent: true,  relation: "NextTurnCallInfo",     alias: null,          input_attrs: null,                     desc: null, after_set: null,                 },

      { key: "common_volume_scale",          type: "integer", name: "音量 - マスター",                        defaults: { development: null,                  production: 5,                                   }, permanent: true,  relation: null,                   alias: null,          input_attrs: "CommonVolumeScaleInfo", desc: null, after_set: null, },
      { key: "talk_volume_scale",            type: "integer", name: "音量 - 音声",                            defaults: { development: null,                  production: 5,                                   }, permanent: true,  relation: null,                   alias: null,          input_attrs: "TalkVolumeScaleInfo",   desc: null, after_set: null, },
      { key: "clock_volume_scale",           type: "integer", name: "音量 - 秒読み",                          defaults: { development: null,                 production: 5,                                   }, permanent: true,  relation: null,                   alias: null,          input_attrs: "ClockVolumeScaleInfo",        desc: null, after_set: null,                },
      { key: "komaoto_volume_scale",         type: "integer", name: "音量 - 駒音",                            defaults: { development: null,                 production: 5,                                   }, permanent: true,  relation: null,                   alias: null,          input_attrs: "KomaotoVolumeScaleInfo",      desc: null, after_set: null,                }, // ::SE_PIECE_PUT_VOLUME:: nuxt_sidecomponents/models/sound_preset_info.js と合わせる

      { key: "setting_category_key",         type: "string",  name: "設定のカレントタブ位置",                 defaults: { development: null,                 production: "setting_tab_streamer",                 }, permanent: true,  relation: "SettingRootInfo",  alias: null,          input_attrs: null,                     desc: null, after_set: null,                 },
      { key: "clock_speed",                  type: "float",   name: "対局時計の速度",                         defaults: { development: null,                 production: 1,                                   }, permanent: false, relation: null,                   alias: null,          input_attrs: null,                     desc: null, after_set: null,                 },

      { key: "foul_mode_key",                type: "string",  name: "反則時の挙動",                           defaults: { development: null,                 production: "lose",                              }, permanent: true,  relation: "FoulModeInfo",         alias: null,          input_attrs: null,                     desc: null, after_set: null,                 },
      { key: "auto_resign_key",              type: "string",  name: "投了タイミング",                         defaults: { development: "is_auto_resign_off", production: "is_auto_resign_on",                 }, permanent: true,  relation: "AutoResignInfo",       alias: null,          input_attrs: null,                     desc: null, after_set: null,                 },
      { key: "change_per",                   type: "integer", name: "N手毎交代",                              defaults: { development: null,                 production: 1,                                   }, permanent: false, relation: null,                   alias: null,          input_attrs: null,                     desc: null, after_set: null,                 },

      { key: "sb_board_width",               type: "float",   name: "盤の大きさ",                             defaults: { development: null,                 production: 85.0,                                }, permanent: true,  relation: null,                   alias: null,          input_attrs: null,                     desc: null, after_set: null,                 },
      { key: "sb_grid_stroke",               type: "float",   name: "盤のグリッドの太さ",                     defaults: { development: null,                 production: 1.0,                                 }, permanent: true,  relation: null,                   alias: null,          input_attrs: null,                     desc: null, after_set: null,                 },

      { key: "message_scope_key",            type: "string",  name: "発言スコープ",                           defaults: { development: null,                 production: "ms_public",                         }, permanent: true,  relation: "MessageScopeInfo",     alias: null,          input_attrs: null,                     desc: null, after_set: null,                 }, // 部屋に入り直した際に発言スコープが ms_public に戻ったことに気づかないで発言する事例があったため永続化する
      { key: "send_trigger_key",             type: "string",  name: "送信トリガー",                           defaults: { development: null,                 production: "send_trigger_enter",                }, permanent: true,  relation: "SendTriggerInfo",      alias: null,          input_attrs: null,                     desc: null, after_set: null,                 },
      { key: "image_size_key",               type: "string",  name: "ダウンロード画像サイズ",                 defaults: { development: null,                 production: "is_image_size_1920x1080",           }, permanent: true,  relation: "ImageSizeInfo",        alias: null,          input_attrs: null,                     desc: null, after_set: null,                 },
      { key: "board_preset_key",             type: "string",  name: "手合割",                                 defaults: { development: null,                 production: "平手",                              }, permanent: true,  relation: "BoardPresetInfo",      alias: null,          input_attrs: null,                     desc: null, after_set: null,                 },
      { key: "quick_sync_key",               type: "string",  name: "同期タイミング",                         defaults: { development: null,                 production: "is_quick_sync_on",                  }, permanent: false, relation: "QuickSyncInfo",        alias: null,          input_attrs: null,                     desc: null, after_set: null,                 },
      { key: "faul_caution_key",             type: "string",  name: "反則時の自動注意",                       defaults: { development: null,                 production: "is_caution_on",                     }, permanent: false, relation: null,                   alias: null,          input_attrs: null,                     desc: null, after_set: null,                 },

      // デバッグ用
      { key: "fixed_order",                  type: "string",  name: "順番設定の順番",                         defaults: { development: null,                 production: "",                                  }, permanent: false, relation: null,                   alias: null,          input_attrs: null,                     desc: null, after_set: null,                 },
      { key: "fixed_order_state",            type: "string",  name: "順番設定の方法",                         defaults: { development: null,                 production: "to_o2_state",                       }, permanent: false, relation: null,                   alias: null,          input_attrs: null,                     desc: null, after_set: null,                 },

      { key: "order_enable_p",               type: "boolean", name: "順番設定が有効か？",                     defaults: { development: null,                 production: false,                               }, permanent: false, relation: null,                   alias: null,          input_attrs: null,                     desc: null, after_set: null,                 },
      { key: "ng_word_check_p",              type: "boolean", name: "ハンドルネームのNGバリデーションする？",   defaults: { development: false,               production: true,                                }, permanent: false, relation: null,                   alias: null,          input_attrs: null,                     desc: null, after_set: null,                 },
      { key: "auto_close_p",                 type: "boolean", name: "自動的に閉じるか？",                     defaults: { development: null,                 production: true,                                }, permanent: false, relation: null,                   alias: null,          input_attrs: null,                     desc: null, after_set: null,                 },
      { key: "room_url_copy_modal_p",        type: "boolean", name: "部屋リンクコピーモーダル出す？",         defaults: { development: null,                 production: true,                                }, permanent: false, relation: null,                   alias: null,          input_attrs: null,                     desc: null, after_set: null,                 },
      { key: "room_url_copy_modal_delay",    type: "float",   name: "部屋リンクコピーモーダル出すまでの秒数", defaults: { development: null,                 production: 2.5,                                 }, permanent: false, relation: null,                   alias: null,          input_attrs: null,                     desc: null, after_set: null,                 },
      { key: "shuffle_first",                type: "boolean", name: "順番設定初回自動シャッフル",             defaults: { development: null,                 production: true,                                }, permanent: false, relation: null,                   alias: null,          input_attrs: null,                     desc: null, after_set: null,                 },
      { key: "mh_per_page",                  type: "integer", name: "発言履歴読み込み件数(-1でスキップ)",     defaults: { development: 2,                    production: 25,                                  }, permanent: false, relation: null,                   alias: null,          input_attrs: null,                     desc: null, after_set: null,                 },
      { key: "mh_rows_size_max",             type: "integer", name: "発言履歴最大",                           defaults: { development: null,                 production: -1,                                  }, permanent: false, relation: null,                   alias: null,          input_attrs: null,                     desc: null, after_set: null,                 },

      { key: "room_restore_feature_p",       type: "boolean", name: "入室時の盤面復元の実行(API実行)",        defaults: { development: null,                 production: true,                                }, permanent: false, relation: null,                   alias: null,          input_attrs: null,                     desc: null, after_set: null,                 },
      { key: "room_restore_update_p",        type: "boolean", name: "入室時の盤面復元の実行(コールバック後)", defaults: { development: null,                 production: true,                                }, permanent: false, relation: null,                   alias: null,          input_attrs: null,                     desc: null, after_set: null,                 },
      { key: "room_restore_sleep",           type: "float",   name: "入室時の盤面復元までの秒数",             defaults: { development: null,                 production: 0,                                   }, permanent: false, relation: null,                   alias: null,          input_attrs: null,                     desc: null, after_set: null,                 },
      { key: "room_create_delay",            type: "float",   name: "部屋作成直前の待ち秒数",                 defaults: { development: null,                 production: 0,                                   }, permanent: false, relation: null,                   alias: null,          input_attrs: null,                     desc: null, after_set: null,                 },

      { key: "xmatch_wait_max",              type: "integer", name: "待ち時間最大",                           defaults: { development: null,                 production: 60 * 3,                              }, permanent: false, relation: null,                   alias: null,          input_attrs: null,                     desc: null, after_set: null,                 },
      { key: "xmatch_redis_ttl",             type: "integer", name: "マッチングエントリ度の更新TTL",          defaults: { development: null,                 production: 60 * 3 + 3,                          }, permanent: false, relation: null,                   alias: null,          input_attrs: null,                     desc: null, after_set: null,                 },
      { key: "xmatch_auth_key",              type: "string",  name: "ルール選択時に認証方法",                 defaults: { development: null,                 production: "handle_name_required",              }, permanent: false, relation: "XmatchAuthInfo",       alias: null,          input_attrs: null,                     desc: null, after_set: null,                 },

      { key: "persistent_cc_params",         type: "json",    name: "対局時計",                               defaults: { development: null,                 production: c => c.CcRuleInfo.default_cc_params, }, permanent: true,  relation: null,                   alias: null,          input_attrs: null,                     desc: null, after_set: c => c.cc_params_convert_to_array_of_hash(), },
      { key: "ai_hello_ymd",                 type: "string",  name: "GPTの挨拶記憶",                          defaults: { development: null,                 production: "",                                  }, permanent: true,  relation: null,                   alias: null,          input_attrs: null,                     desc: null, after_set: null,                                      },
      { key: "ai_auto_response_ratio",       type: "float",   name: "GPTの反応確率",                          defaults: { development: 1.0,                  production: 0.02,                                }, permanent: false, relation: null,                   alias: null,          input_attrs: null,                     desc: null, after_set: null,                                      },

      // { key: "think_mark_mode_global_p",  type: "boolean", name: "観戦者のマーク機能",                     defaults: { development: null,                 production: true,                                }, permanent: false, relation: null,                   alias: null,          input_attrs: null,                     desc: null, after_set: null,                 },
      { key: "think_mark_mode_p",            type: "boolean", name: "一時的なマーク機能有効化",               defaults: { development: null,                 production: false,                               }, permanent: false, relation: null,                   alias: null,          input_attrs: null,                     desc: null, after_set: null,                 },
      { key: "think_mark_receive_scope_key", type: "string",  name: "印の受信スコープ",                       defaults: { development: null,                 production: "tmrs_watcher_only",                 }, permanent: false, relation: null,                   alias: null,          input_attrs: null,                     desc: null, after_set: null,                 },
      { key: "think_mark_list_str",          type: "string",  name: "印の初期値",                             defaults: { development: null,                 production: "",                                  }, permanent: false, relation: null,                   alias: null,          input_attrs: null,                     desc: null, after_set: null,                 },
    ]
  }
}
