import { ParamBase } from '@/components/models/param_base.js'

export class ParamInfo extends ParamBase {
  static get define() {
    return [
      { key: "room_code",                  type: "string",  name: "合言葉",                                 defaults: { development: null,                      production: "",                                  }, permanent: true,  relation: null,                   input_attrs: null,               desc: null, after_set: null,                 },
      { key: "user_name",                  type: "string",  name: "名前",                                   defaults: { development: null,                      production: c => c.g_current_user_name || "",    }, permanent: true,  relation: null,                   input_attrs: null,               desc: null, after_set: c => c.medal_write(), },
      { key: "title",                      type: "string",  name: "タイトル",                               defaults: { development: null,                      production: "共有将棋盤",                        }, permanent: false, relation: null,                   input_attrs: null,               desc: null, after_set: null,                 },
      { key: "sp_mode",                    type: "string",  name: "将棋盤モード",                           defaults: { development: null,                      production: "play",                              }, permanent: false, relation: null,                   input_attrs: null,               desc: null, after_set: null,                 },
      { key: "legal_key",                  type: "string",  name: "内部ルール",                             defaults: { development: null,                      production: "strict",                            }, permanent: false, relation: "LegalInfo",            input_attrs: null,               desc: null, after_set: null,                 },
      { key: "color_theme_key",            type: "string",  name: "画像の配色",                             defaults: { development: null,                      production: "is_color_theme_real",               }, permanent: true,  relation: "ColorThemeInfo",       input_attrs: null,               desc: null, after_set: null,                 },
      { key: "appearance_theme_key",       type: "string",  name: "基本配色",                               defaults: { development: null,                      production: "is_appearance_theme_a",             }, permanent: true,  relation: "AppearanceThemeInfo",  input_attrs: null,               desc: null, after_set: null,                 },
      { key: "ctrl_mode_key",              type: "string",  name: "コントローラー表示",                     defaults: { development: "is_ctrl_mode_visible",    production: "is_ctrl_mode_hidden",               }, permanent: false, relation: "CtrlModeInfo",         input_attrs: null,               desc: null, after_set: null,                 },
      { key: "debug_mode_key",             type: "string",  name: "デバッグモード",                         defaults: { development: "is_debug_mode_on",        production: "is_debug_mode_off",                 }, permanent: false, relation: "DebugModeInfo",        input_attrs: null,               desc: null, after_set: null,                 },
      { key: "lift_cancel_action",         type: "string",  name: "駒移動キャンセル",                       defaults: { development: "standard", production: "standard",                                         }, permanent: true,  relation: "LiftCancelActionInfo", input_attrs: null,               desc: null, after_set: null,                 },

      { key: "yomiage_mode_key",            type: "string",  name: "読み上げモード",                        defaults: { development: null,                      production: "is_yomiage_mode_on",                }, permanent: true,  relation: "YomiageModeInfo",      input_attrs: null,               desc: null, after_set: null,                 },
      { key: "next_turn_call_key",          type: "string",  name: "手番コール",                           defaults: { development: null,                      production: "is_next_turn_call_on",                }, permanent: true,  relation: "NextTurnCallInfo",      input_attrs: null,               desc: null, after_set: null,                 },
      { key: "foo1_volume",                 type: "integer", name: "音量1",                                 defaults: { development: null,                      production: 5,                                   }, permanent: true,  relation: null,                   input_attrs: "Foo1VolumeInfo",   desc: null, after_set: null,                 },
      { key: "setting_category_key",        type: "string", name: "設定のカレントタブ位置",                defaults: { development: null,                       production: "setting_category1",                 }, permanent: true,  relation: "SettingCategoryInfo",  input_attrs: null,               desc: null, after_set: null,                 },

      { key: "illegal_behavior_key",       type: "string",  name: "反則制限モード",                         defaults: { development: null,                      production: "is_illegal_behavior_auto",          }, permanent: true,  relation: "IllegalBehaviorInfo",  input_attrs: null,               desc: null, after_set: null,                 },
      { key: "auto_resign_key",            type: "string",  name: "投了タイミング",                         defaults: { development: "is_auto_resign_off",      production: "is_auto_resign_on",                 }, permanent: true,  relation: "AutoResignInfo",       input_attrs: null,               desc: null, after_set: null,                 },
      { key: "tegoto",                     type: "integer", name: "N手毎交代",                              defaults: { development: null,                      production: 1,                                   }, permanent: false, relation: null,                   input_attrs: null,               desc: null, after_set: null,                 },

      { key: "board_width",                type: "float",   name: "盤の大きさ",                             defaults: { development: null,                      production: 80.0,                                }, permanent: true,  relation: null,                   input_attrs: null,               desc: null, after_set: null,                 },
      { key: "message_scope_key",          type: "string",  name: "発言スコープ",                           defaults: { development: null,                      production: "is_message_scope_public",           }, permanent: false, relation: "MessageScopeInfo",     input_attrs: null,               desc: null, after_set: null,                 },
      { key: "image_size_key",             type: "string",  name: "ダウンロード画像サイズ",                 defaults: { development: null,                      production: "is_image_size_1920x1080",           }, permanent: true,  relation: "ImageSizeInfo",        input_attrs: null,               desc: null, after_set: null,                 },
      { key: "board_preset_key",           type: "string",  name: "手合割",                                 defaults: { development: null,                      production: "平手",                              }, permanent: true,  relation: "BoardPresetInfo",      input_attrs: null,               desc: null, after_set: null,                 },
      { key: "quick_sync_key",             type: "string",  name: "同期タイミング",                         defaults: { development: null,                      production: "is_quick_sync_on",                  }, permanent: false, relation: "QuickSyncInfo",        input_attrs: null,               desc: null, after_set: null,                 },
      { key: "faul_caution_key",           type: "string",  name: "反則時の自動注意",                       defaults: { development: null,                      production: "is_caution_on",                     }, permanent: false, relation: null,                   input_attrs: null,               desc: null, after_set: null,                 },
      { key: "fixed_order_names",          type: "string",  name: "順番設定の順番",                         defaults: { development: null,                      production: "",                                  }, permanent: false, relation: null,                   input_attrs: null,               desc: null, after_set: null,                 },
      { key: "fixed_order_state",          type: "string",  name: "順番設定の方法",                         defaults: { development: null,                      production: "to_o2_state",                       }, permanent: false, relation: null,                   input_attrs: null,               desc: null, after_set: null,                 },
      { key: "order_enable_p",             type: "boolean", name: "順番設定が有効か？",                     defaults: { development: null,                      production: false,                               }, permanent: false, relation: null,                   input_attrs: null,               desc: null, after_set: null,                 },
      { key: "auto_close_p",               type: "boolean", name: "自動的に閉じるか？",                     defaults: { development: false,                     production: true,                                }, permanent: false, relation: null,                   input_attrs: null,               desc: null, after_set: null,                 },
      { key: "auto_room_url_copy_modal_p", type: "boolean", name: "部屋のリンクのコピーモーダルを出すか？", defaults: { development: false,                     production: true,                                }, permanent: false, relation: null,                   input_attrs: null,               desc: null, after_set: null,                 },
      { key: "shuffle_first",              type: "boolean", name: "順番設定初回自動シャッフル",             defaults: { development: null,                      production: true,                                }, permanent: false, relation: null,                   input_attrs: null,               desc: null, after_set: null,                 },

      { key: "xmatch_wait_max",            type: "integer", name: "待ち時間最大",                           defaults: { development: null,                      production: 60 * 3,                              }, permanent: false, relation: null,                   input_attrs: null,               desc: null, after_set: null,                 },
      { key: "xmatch_redis_ttl",           type: "integer", name: "マッチングエントリ度の更新TTL",          defaults: { development: null,                      production: 60 * 3 + 3,                          }, permanent: false, relation: null,                   input_attrs: null,               desc: null, after_set: null,                 },
      { key: "xmatch_auth_key",            type: "string",  name: "ルール選択時に認証方法",                 defaults: { development: null,                      production: "handle_name_required",              }, permanent: false, relation: "XmatchAuthInfo",       input_attrs: null,               desc: null, after_set: null,                 },

      { key: "acquire_medal_count",        type: "integer", name: "メダル保持数",                           defaults: { development: null,                      production: 0,                                   }, permanent: false, relation: null,                   input_attrs: null,               desc: null, after_set: null,                 },

      { key: "persistent_cc_params",       type: "json",    name: "対局時計",                               defaults: { development: null,                      production: c => c.CcRuleInfo.default_cc_params, }, permanent: true,  relation: null,                   input_attrs: null,               desc: null, after_set: c => c.persistent_cc_params_array_wrap(), },
      { key: "gpt_hello_ymd",              type: "string",  name: "GPTの挨拶記憶",                          defaults: { development: null,                      production: "",                                  }, permanent: true,  relation: null,                   input_attrs: null,               desc: null, after_set: null,                                      },
    ]
  }
}
