require "./setup"
tp QuickScript::Dev::Fake500Script.new.as_json # => {:body=>nil, :__script_meta__=>{:qs_group_key=>"dev", :qs_page_key=>"fake500", :qs_path=>"/lab/dev/fake500", :qs_group_info=>#<QuickScript::QsGroupInfo:0x000000010fcb16e0 @attributes={:key=>:dev, :name=>"開発用", :admin_only=>true, :code=>2}>}, :form_method=>nil, :button_label=>"実行", :params_add_submit_key=>nil, :get_then_axios_get=>false, :router_push_failed_then_fetch=>false, :button_click_loading=>false, :form_parts=>[], :button_with_nuxt_login_required=>false, :primary_error_message=>nil, :flash=>{}, :meta=>{:title=>"ぶっこわす", :description=>"ぶっこわすテスト", :primary_error_message=>nil, :og_image_key=>:application, :og_card_size=>:small}, :redirect_to=>nil, :auto_exec_action=>nil, :axios_process_type=>:server, :navibar_show=>true}
# >> |---------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
# >> |                            body |                                                                                                                                                                                                                           |
# >> |                 __script_meta__ | {:qs_group_key=>"dev", :qs_page_key=>"fake500", :qs_path=>"/lab/dev/fake500", :qs_group_info=>#<QuickScript::QsGroupInfo:0x000000010fcb16e0 @attributes={:key=>:dev, :name=>"開発用", :admin_only=>true, :code=>2}>} |
# >> |                     form_method |                                                                                                                                                                                                                           |
# >> |                    button_label | 実行                                                                                                                                                                                                                      |
# >> |           params_add_submit_key |                                                                                                                                                                                                                           |
# >> |              get_then_axios_get | false                                                                                                                                                                                                                     |
# >> |   router_push_failed_then_fetch | false                                                                                                                                                                                                                     |
# >> |            button_click_loading | false                                                                                                                                                                                                                     |
# >> |                      form_parts | []                                                                                                                                                                                                                        |
# >> | button_with_nuxt_login_required | false                                                                                                                                                                                                                     |
# >> |           primary_error_message |                                                                                                                                                                                                                           |
# >> |                           flash | {}                                                                                                                                                                                                                        |
# >> |                            meta | {:title=>"ぶっこわす", :description=>"ぶっこわすテスト", :primary_error_message=>nil, :og_image_key=>:application, :og_card_size=>:small}                                                                                 |
# >> |                     redirect_to |                                                                                                                                                                                                                           |
# >> |     auto_exec_action |                                                                                                                                                                                                                           |
# >> |              axios_process_type | server                                                                                                                                                                                                                    |
# >> |                    navibar_show | true                                                                                                                                                                                                                      |
# >> |---------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
