# https://railsguides.jp/action_cable_overview.html

<%
  db = AppConfig.fetch(:redis_db_for_actioncable)
  url = ENV.fetch("REDIS_URL") { "redis://localhost:6379/#{db}" }
%>

development:
  # adapter: async
  adapter: redis
  url: <%= url %>
  channel_prefix: shogi_web_development

production:
  adapter: redis
  url: <%= url %>
  channel_prefix: shogi_web_production

staging:
  adapter: redis
  url: <%= url %>
  channel_prefix: shogi_web_staging

test:
  adapter: test
