defaults: &defaults
  adapter: mysql2
  charset: utf8mb4
  collation: utf8mb4_unicode_ci
  encoding: utf8mb4
  host: 127.0.0.1
  password:
  reconnect: true
  username: root

development:
  <<: *defaults
  database: shogi_web_development

production:
  <<: *defaults
  database: shogi_web_production
  pool: 16

staging:
  <<: *defaults
  database: shogi_web_staging

test:
  <<: *defaults
  database: shogi_web_test
