defaults: &defaults
  adapter: mysql2
  charset: utf8mb4
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  reconnect: true
  host: 127.0.0.1
  username: root
  password:

development:
  <<: *defaults
  database: shogi_web_development

production:
  <<: *defaults
  database: shogi_web_production

staging:
  <<: *defaults
  database: shogi_web_staging

test:
  <<: *defaults
  database: shogi_web_test
