defaults: &defaults
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_general_ci
  username: root
  password:
  host: 127.0.0.1
  reconnect: true

development:
  <<: *defaults
  database: shogi_web_development

production:
  <<: *defaults
  database: shogi_web_production

staging:
  <<: *defaults
  database: shogi_web_staging

test:
  <<: *defaults
  database: shogi_web_test
