# defaults: &defaults
#   adapter: mysql2
#   username: root
#   password:
#   encoding: utf8
#   host: 127.0.0.1
#   reconnect: true
#
# development:
#   <<: *defaults
#   database: shogi_web_development
#
# production:
#   <<: *defaults
#   database: shogi_web_production
#
# test:
#   <<: *defaults
#   database: shogi_web_test

defaults: &defaults
  adapter: sqlite3
  pool: 5
  timeout: 3000

development:
  <<: *defaults
  database: db/development.sqlite3

test:
  <<: *defaults
  database: db/test.sqlite3

staging:
  <<: *defaults
  database: /var/www/shogi_web_staging/shared/db/staging.sqlite3

production:
  <<: *defaults
  database: /var/www/shogi_web_production/shared/db/production.sqlite3
