defaults: &defaults
  adapter: sqlite3
  pool: 5
  timeout: 3000

development:
  <<: *defaults
  database: db/development.sqlite3

test:
  <<: *defaults
  database: db/test.sqlite3

production:
  <<: *defaults
  database: /var/www/shogi_web_local/shared/db/production.sqlite3
