require "./setup"
# tp Swars::User.find_by(key: "SugarHuuko").user_stat.other_stat.time_stats
sql
puts Swars::User["HIKOUKI_GUMO"].user_stat(sample_max: 200).as_json
# >>   Swars::User Load (0.3ms)  SELECT `swars_users`.* FROM `swars_users` WHERE `swars_users`.`user_key` = 'HIKOUKI_GUMO' LIMIT 1
# >>   ↳ app/models/swars/user.rb:5:in `[]'
# >>   Swars::Membership Ids (34.8ms)  SELECT `swars_memberships`.`id` FROM `swars_memberships` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` WHERE `swars_memberships`.`user_id` = 23974 ORDER BY `swars_battles`.`battled_at` DESC LIMIT 5
# >>   ↳ app/models/swars/user_stat/base_scope_methods.rb:35:in `scope_ids'
# >>   Swars::Membership Load (0.2ms)  SELECT swars_rules.key AS rule_key, MIN(swars_grades.priority) AS min_priority FROM `swars_memberships` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` INNER JOIN `swars_rules` ON `swars_rules`.`id` = `swars_battles`.`rule_id` INNER JOIN `swars_grades` ON `swars_grades`.`id` = `swars_memberships`.`grade_id` WHERE `swars_memberships`.`id` IN (99305042, 99305045, 99305046, 99259352, 99305048) GROUP BY `rule_key`
# >>   ↳ app/models/swars/user_stat/grade_by_rules_stat.rb:18:in `block in to_chart'
# >>   Swars::Grade Load (0.2ms)  SELECT m.rule_key, swars_grades.key AS grade_name FROM `swars_grades` INNER JOIN (SELECT swars_rules.key AS rule_key, MIN(swars_grades.priority) AS min_priority FROM `swars_memberships` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` INNER JOIN `swars_rules` ON `swars_rules`.`id` = `swars_battles`.`rule_id` INNER JOIN `swars_grades` ON `swars_grades`.`id` = `swars_memberships`.`grade_id` WHERE `swars_memberships`.`id` IN (99305042, 99305045, 99305046, 99259352, 99305048) GROUP BY `rule_key`) m ON priority = m.min_priority ORDER BY `swars_grades`.`priority` ASC
# >>   ↳ app/models/swars/user_stat/grade_by_rules_stat.rb:30:in `block in to_chart'
# >>   Swars::Membership Count (0.3ms)  SELECT COUNT(*) AS `count_all`, `judges`.`key` AS `judges_key` FROM `swars_memberships` INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` WHERE `swars_memberships`.`id` IN (99305042, 99305045, 99305046, 99259352, 99305048) GROUP BY `judges`.`key`
# >>   ↳ app/models/swars/user_stat/membership_global_extension.rb:14:in `total_judge_counts'
# >>   Judge Load (0.2ms)  SELECT `judges`.* FROM `judges` WHERE `judges`.`key` = 'lose' ORDER BY `judges`.`position` ASC LIMIT 1
# >>   ↳ app/models/application_memory_record.rb:22:in `db_record!'
# >>   Swars::Final Load (0.2ms)  SELECT `swars_finals`.* FROM `swars_finals` WHERE `swars_finals`.`key` = 'DISCONNECT' ORDER BY `swars_finals`.`position` ASC LIMIT 1
# >>   ↳ app/models/application_memory_record.rb:22:in `db_record!'
# >>   Swars::Membership Count (0.4ms)  SELECT COUNT(*) AS `count_all`, `judges`.`key` AS `judges_key`, `swars_finals`.`key` AS `swars_finals_key` FROM `swars_memberships` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` INNER JOIN `swars_finals` ON `swars_finals`.`id` = `swars_battles`.`final_id` INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` WHERE `swars_memberships`.`id` IN (99305042, 99305045, 99305046, 99259352, 99305048) GROUP BY `judges`.`key`, `swars_finals`.`key`
# >>   ↳ app/models/swars/user_stat/judge_final_stat.rb:55:in `block in counts_hash'
# >>   Swars::Membership Count (0.4ms)  SELECT COUNT(*) FROM `swars_memberships` INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` INNER JOIN `swars_finals` ON `swars_finals`.`id` = `swars_battles`.`final_id` WHERE `swars_memberships`.`id` IN (99305042, 99305045, 99305046, 99259352, 99305048) AND `judges`.`key` = 'lose' AND `swars_finals`.`key` = 'TIMEOUT' AND `swars_memberships`.`think_last` >= 60
# >>   ↳ app/models/swars/user_stat/leave_alone_stat.rb:37:in `count'
# >>   Swars::Membership Count (0.2ms)  SELECT COUNT(*) FROM `swars_memberships` INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` WHERE `swars_memberships`.`id` IN (99305042, 99305045, 99305046, 99259352, 99305048) AND `judges`.`key` = 'lose'
# >>   ↳ app/models/swars/user_stat/sub_scope_methods.rb:33:in `lose_count'
# >>   Swars::Membership Count (0.5ms)  SELECT COUNT(*) FROM `swars_memberships` INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` INNER JOIN `swars_finals` ON `swars_finals`.`id` = `swars_battles`.`final_id` WHERE `swars_memberships`.`id` IN (99305042, 99305045, 99305046, 99259352, 99305048) AND `judges`.`key` = 'lose' AND (`swars_finals`.`key` = 'TORYO' OR `swars_finals`.`key` = 'CHECKMATE') AND `swars_battles`.`turn_max` <= 19
# >>   ↳ app/models/swars/user_stat/lethargy_stat.rb:29:in `block in count'
# >>   Swars::Membership Count (0.2ms)  SELECT COUNT(*) FROM `swars_memberships` WHERE `swars_memberships`.`id` IN (99305042, 99305045, 99305046, 99259352, 99305048) AND `swars_memberships`.`think_max` >= 180
# >>   ↳ app/models/swars/user_stat/prolonged_deliberation_stat.rb:15:in `block in count'
# >>   Swars::Membership Count (0.3ms)  SELECT COUNT(*) FROM `swars_memberships` INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` INNER JOIN `swars_finals` ON `swars_finals`.`id` = `swars_battles`.`final_id` WHERE `swars_memberships`.`id` IN (99305042, 99305045, 99305046, 99259352, 99305048) AND `judges`.`key` = 'win' AND `swars_memberships`.`think_last` >= 45 AND `swars_finals`.`key` = 'CHECKMATE'
# >>   ↳ app/models/swars/user_stat/mate_stat.rb:47:in `count'
# >>   Swars::Membership Count (0.3ms)  SELECT COUNT(*) FROM `swars_memberships` INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` WHERE `swars_memberships`.`id` IN (99305042, 99305045, 99305046, 99259352, 99305048) AND `judges`.`key` = 'lose' AND `swars_memberships`.`think_last` IS NOT NULL AND `swars_memberships`.`think_max` != `swars_memberships`.`think_last` AND `swars_memberships`.`think_max` >= 300 AND `swars_battles`.`turn_max` >= 14
# >>   ↳ app/models/swars/user_stat/waiting_to_leave_stat.rb:19:in `block in count'
# >>   Swars::Membership Pluck (0.2ms)  SELECT `swars_memberships`.`id` FROM `swars_memberships` WHERE `swars_memberships`.`id` IN (99305042, 99305045, 99305046, 99259352, 99305048)
# >>   ↳ app/models/swars/user_stat/tag_stat.rb:62:in `block in counts_hash'
# >>   ActsAsTaggableOn::Tag Load (0.8ms)  SELECT tags.*, taggings.tags_count AS count FROM `tags` JOIN (SELECT taggings.tag_id, COUNT(taggings.tag_id) AS tags_count FROM `taggings` WHERE (taggings.taggable_type = 'Swars::Membership') AND (taggings.taggable_id IN ('99259352','99305042','99305045','99305046','99305048')) GROUP BY `taggings`.`tag_id` HAVING (COUNT(taggings.tag_id) > 0)) AS taggings ON taggings.tag_id = tags.id
# >>   ↳ app/models/swars/user_stat/tag_stat.rb:63:in `each_with_object'
# >>   Swars::Membership Count (0.2ms)  SELECT COUNT(*) FROM `swars_memberships` WHERE `swars_memberships`.`id` IN (99305042, 99305045, 99305046, 99259352, 99305048)
# >>   ↳ app/models/swars/user_stat/base_scope_methods.rb:45:in `ids_count'
# >>   Swars::Membership Pluck (0.3ms)  SELECT `swars_memberships`.`id` FROM `swars_memberships` INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` WHERE `swars_memberships`.`id` IN (99305042, 99305045, 99305046, 99259352, 99305048) AND `judges`.`key` = 'win'
# >>   ↳ app/models/swars/user_stat/tag_stat.rb:62:in `block in counts_hash'
# >>   ActsAsTaggableOn::Tag Load (0.6ms)  SELECT tags.*, taggings.tags_count AS count FROM `tags` JOIN (SELECT taggings.tag_id, COUNT(taggings.tag_id) AS tags_count FROM `taggings` WHERE (taggings.taggable_type = 'Swars::Membership') AND (taggings.taggable_id IN ('99259352','99305042','99305045','99305046')) GROUP BY `taggings`.`tag_id` HAVING (COUNT(taggings.tag_id) > 0)) AS taggings ON taggings.tag_id = tags.id
# >>   ↳ app/models/swars/user_stat/tag_stat.rb:63:in `each_with_object'
# >>   Swars::Membership Count (0.3ms)  SELECT COUNT(*) FROM `swars_memberships` INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` WHERE `swars_memberships`.`id` IN (99305042, 99305045, 99305046, 99259352, 99305048) AND `judges`.`key` = 'win'
# >>   ↳ app/models/swars/user_stat/sub_scope_methods.rb:23:in `win_count'
# >>   Swars::Membership Pluck (0.2ms)  SELECT `judges`.`key` FROM `swars_memberships` INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` WHERE `swars_memberships`.`id` IN (99305042, 99305045, 99305046, 99259352, 99305048) ORDER BY FIELD(swars_memberships.id, '99305042','99305045','99305046','99259352','99305048')
# >>   ↳ app/models/application_record.rb:69:in `block in custom_belongs_to'
# >>   Swars::Membership Maximum (0.3ms)  SELECT MAX(`swars_battles`.`turn_max`) FROM `swars_memberships` INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` WHERE `swars_memberships`.`id` IN (99305042, 99305045, 99305046, 99259352, 99305048) AND `judges`.`key` = 'win'
# >>   ↳ app/models/swars/user_stat/turn_stat.rb:17:in `max'
# >>   Swars::Membership Average (0.3ms)  SELECT AVG(turn_max) AS `average_turn_max`, `judges`.`key` AS `judges_key` FROM `swars_memberships` INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` WHERE `swars_memberships`.`id` IN (99305042, 99305045, 99305046, 99259352, 99305048) GROUP BY `judges`.`key`
# >>   ↳ app/models/swars/user_stat/average_moves_by_outcome_stat.rb:45:in `block in averages_hash'
# >>   Swars::Membership Load (0.2ms)  SELECT DATE(CONVERT_TZ(battled_at, 'UTC', 'Asia/Tokyo')) AS battled_on, COUNT(*) AS count_all FROM `swars_memberships` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` WHERE `swars_memberships`.`id` IN (99305042, 99305045, 99305046, 99259352, 99305048) GROUP BY `battled_on`
# >>   ↳ app/models/swars/user_stat/daily_average_matches_stat.rb:41:in `block (2 levels) in aggregate_outcome'
# >>    (0.3ms)  SELECT AVG(count_all) AS average, MAX(count_all) AS max FROM (SELECT DATE(CONVERT_TZ(battled_at, 'UTC', 'Asia/Tokyo')) AS battled_on, COUNT(*) AS count_all FROM `swars_memberships` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` WHERE `swars_memberships`.`id` IN (99305042, 99305045, 99305046, 99259352, 99305048) GROUP BY `battled_on`) AS from_values
# >>   ↳ app/models/swars/user_stat/daily_average_matches_stat.rb:43:in `block in aggregate_outcome'
# >>   Judge Load (0.2ms)  SELECT `judges`.* FROM `judges` WHERE `judges`.`key` = 'lose' ORDER BY `judges`.`position` ASC LIMIT 1
# >>   ↳ app/models/application_memory_record.rb:22:in `db_record!'
# >>   Swars::Final Load (0.2ms)  SELECT `swars_finals`.* FROM `swars_finals` WHERE `swars_finals`.`key` = 'TORYO' ORDER BY `swars_finals`.`position` ASC LIMIT 1
# >>   ↳ app/models/application_memory_record.rb:22:in `db_record!'
# >>   Judge Load (0.1ms)  SELECT `judges`.* FROM `judges` WHERE `judges`.`key` = 'lose' ORDER BY `judges`.`position` ASC LIMIT 1
# >>   ↳ app/models/application_memory_record.rb:22:in `db_record!'
# >>   Swars::Final Load (0.1ms)  SELECT `swars_finals`.* FROM `swars_finals` WHERE `swars_finals`.`key` = 'TIMEOUT' ORDER BY `swars_finals`.`position` ASC LIMIT 1
# >>   ↳ app/models/application_memory_record.rb:22:in `db_record!'
# >>   Swars::Membership Pluck (0.2ms)  SELECT `swars_memberships`.`id` FROM `swars_memberships` WHERE `swars_memberships`.`id` IN (99305042, 99305045, 99305046, 99259352, 99305048)
# >>   ↳ app/models/swars/user_stat/rarity_stat.rb:73:in `block in tags'
# >>   ActsAsTaggableOn::Tag Load (0.6ms)  SELECT tags.*, taggings.tags_count AS count FROM `tags` JOIN (SELECT taggings.tag_id, COUNT(taggings.tag_id) AS tags_count FROM `taggings` WHERE (taggings.taggable_type = 'Swars::Membership' AND taggings.context = 'attack_tags') AND (taggings.taggable_id IN ('99259352','99305042','99305045','99305046','99305048')) GROUP BY `taggings`.`tag_id` HAVING (COUNT(taggings.tag_id) > 0)) AS taggings ON taggings.tag_id = tags.id
# >>   ↳ app/models/swars/user_stat/rarity_stat.rb:72:in `each'
# >>   Swars::Membership Pluck (0.2ms)  SELECT `swars_memberships`.`id` FROM `swars_memberships` WHERE `swars_memberships`.`id` IN (99305042, 99305045, 99305046, 99259352, 99305048)
# >>   ↳ app/models/swars/user_stat/rarity_stat.rb:73:in `block in tags'
# >>   ActsAsTaggableOn::Tag Load (0.6ms)  SELECT tags.*, taggings.tags_count AS count FROM `tags` JOIN (SELECT taggings.tag_id, COUNT(taggings.tag_id) AS tags_count FROM `taggings` WHERE (taggings.taggable_type = 'Swars::Membership' AND taggings.context = 'defense_tags') AND (taggings.taggable_id IN ('99259352','99305042','99305045','99305046','99305048')) GROUP BY `taggings`.`tag_id` HAVING (COUNT(taggings.tag_id) > 0)) AS taggings ON taggings.tag_id = tags.id
# >>   ↳ app/models/swars/user_stat/rarity_stat.rb:72:in `each'
# >>   Swars::Membership Count (0.3ms)  SELECT COUNT(*) FROM `swars_memberships` INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` WHERE `swars_memberships`.`id` IN (99305042, 99305045, 99305046, 99259352, 99305048) AND `judges`.`key` = 'lose' AND `swars_memberships`.`think_max` >= 150 AND `swars_memberships`.`think_max` < 180
# >>   ↳ app/models/swars/user_stat/overthinking_loss_stat.rb:26:in `block in count'
# >>   Swars::Membership Count (0.2ms)  SELECT COUNT(*) FROM `swars_memberships` INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` WHERE `swars_memberships`.`id` IN (99305042, 99305045, 99305046, 99259352, 99305048) AND `judges`.`key` = 'draw'
# >>   ↳ app/models/swars/user_stat/sub_scope_methods.rb:43:in `draw_count'
# >>   Swars::Membership Count (0.3ms)  SELECT COUNT(*) AS `count_all`, `swars_xmodes`.`key` AS `swars_xmodes_key`, `judges`.`key` AS `judges_key` FROM `swars_memberships` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` INNER JOIN `swars_xmodes` ON `swars_xmodes`.`id` = `swars_battles`.`xmode_id` INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` WHERE `swars_memberships`.`id` IN (99305042, 99305045, 99305046, 99259352, 99305048) GROUP BY `swars_xmodes`.`key`, `judges`.`key`
# >>   ↳ app/models/swars/user_stat/xmode_judge_stat.rb:52:in `block in counts_hash'
# >>   Swars::Membership Count (0.3ms)  SELECT COUNT(*) FROM `swars_memberships` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` WHERE `swars_memberships`.`id` IN (99305042, 99305045, 99305046, 99259352, 99305048) AND (`swars_memberships`.`ai_wave_count` >= 3 OR `swars_memberships`.`ai_drop_total` >= 15 OR `swars_memberships`.`ai_two_freq` >= 0.6 AND `swars_battles`.`turn_max` >= 50 OR `swars_memberships`.`ai_gear_freq` >= 0.22 AND `swars_battles`.`turn_max` >= 50)
# >>   ↳ app/models/swars/user_stat/fraud_stat.rb:13:in `count'
# >>   Swars::Membership Pluck (0.2ms)  SELECT `judges`.`key` FROM `swars_memberships` INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` WHERE `swars_memberships`.`id` IN (99305042, 99305045, 99305046, 99259352, 99305048) ORDER BY FIELD(swars_memberships.id, '99305042','99305045','99305046','99259352','99305048') LIMIT 17
# >>   ↳ app/models/application_record.rb:69:in `block in custom_belongs_to'
# >>   Judge Load (0.2ms)  SELECT `judges`.* FROM `judges` WHERE `judges`.`key` = 'win' ORDER BY `judges`.`position` ASC LIMIT 1
# >>   ↳ app/models/concerns/memory_record_bind.rb:77:in `lookup'
# >>   Judge Load (0.1ms)  SELECT `judges`.* FROM `judges` WHERE `judges`.`key` = 'lose' ORDER BY `judges`.`position` ASC LIMIT 1
# >>   ↳ app/models/concerns/memory_record_bind.rb:77:in `lookup'
# >>   Swars::Membership Load (0.3ms)  SELECT DATE(CONVERT_TZ(battled_at, 'UTC', 'Asia/Tokyo')) AS battled_on, COUNT(judge_id = 1  OR NULL) AS win, COUNT(judge_id = 2 OR NULL) AS lose FROM `swars_memberships` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` WHERE `swars_memberships`.`id` IN (99305042, 99305045, 99305046, 99259352, 99305048) GROUP BY battled_on ORDER BY battled_on DESC
# >>   ↳ app/models/swars/user_stat/daily_win_loss_list_stat.rb:24:in `collect'
# >>   Swars::Membership Ids (25.5ms)  SELECT `swars_memberships`.`id` FROM `swars_memberships` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` WHERE `swars_memberships`.`op_user_id` = 23974 ORDER BY `swars_battles`.`battled_at` DESC LIMIT 5
# >>   ↳ app/models/swars/user_stat/vs_stat.rb:88:in `ids'
# >>   Swars::Membership Count (0.3ms)  SELECT COUNT(*) AS `count_all`, `swars_grades`.`key` AS `swars_grades_key`, `judges`.`key` AS `judges_key` FROM `swars_memberships` INNER JOIN `swars_grades` ON `swars_grades`.`id` = `swars_memberships`.`grade_id` INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` WHERE `swars_memberships`.`id` IN (99305043, 99305044, 99305047, 99259351, 99305049) GROUP BY `swars_grades`.`key`, `judges`.`key` ORDER BY `swars_grades`.`priority` ASC
# >>   ↳ app/models/swars/user_stat/vs_stat.rb:17:in `to_chart'
# >>   Swars::Membership Ids (11.8ms)  SELECT `swars_memberships`.`id` FROM `swars_memberships` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` WHERE `swars_memberships`.`user_id` = 23974 ORDER BY `swars_battles`.`battled_at` DESC LIMIT 5
# >>   ↳ app/models/swars/user_stat/matrix_stat.rb:44:in `build_by'
# >>   Swars::Membership Pluck (0.2ms)  SELECT `swars_memberships`.`id` FROM `swars_memberships` WHERE `swars_memberships`.`id` IN (99305042, 99305045, 99305046, 99259352, 99305048)
# >>   ↳ app/models/swars/user_stat/matrix_stat.rb:51:in `build_by'
# >>   ActsAsTaggableOn::Tag Load (0.4ms)  SELECT tags.*, taggings.tags_count AS count FROM `tags` JOIN (SELECT taggings.tag_id, COUNT(taggings.tag_id) AS tags_count FROM `taggings` WHERE (taggings.taggable_type = 'Swars::Membership' AND taggings.context = 'attack_tags') AND (taggings.taggable_id IN ('99259352','99305042','99305045','99305046','99305048')) GROUP BY `taggings`.`tag_id` HAVING (COUNT(taggings.tag_id) > 0)) AS taggings ON taggings.tag_id = tags.id ORDER BY count desc
# >>   ↳ app/models/swars/user_stat/matrix_stat.rb:52:in `collect'
# >>   Swars::Membership Count (0.3ms)  SELECT COUNT(*) AS `count_all`, `judges`.`key` AS `judges_key` FROM `swars_memberships` INNER JOIN `taggings` `swars::membe_taggings_f5d5141` ON `swars::membe_taggings_f5d5141`.`taggable_id` = `swars_memberships`.`id` AND `swars::membe_taggings_f5d5141`.`taggable_type` = 'Swars::Membership' AND `swars::membe_taggings_f5d5141`.`tag_id` IN (SELECT `tags`.`id` FROM `tags` WHERE `tags`.`name` LIKE '力戦' ESCAPE '!') AND `swars::membe_taggings_f5d5141`.`context` = 'attack_tags' INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` WHERE `swars_memberships`.`id` IN (99305042, 99305045, 99305046, 99259352, 99305048) GROUP BY `judges`.`key`
# >>   ↳ app/models/swars/user_stat/matrix_stat.rb:61:in `block (2 levels) in build_by'
# >>   Swars::Membership Count (0.2ms)  SELECT COUNT(*) AS `count_all`, `judges`.`key` AS `judges_key` FROM `swars_memberships` INNER JOIN `taggings` `swars::membe_taggings_ad02ba7` ON `swars::membe_taggings_ad02ba7`.`taggable_id` = `swars_memberships`.`id` AND `swars::membe_taggings_ad02ba7`.`taggable_type` = 'Swars::Membership' AND `swars::membe_taggings_ad02ba7`.`tag_id` IN (SELECT `tags`.`id` FROM `tags` WHERE `tags`.`name` LIKE '角換わり' ESCAPE '!') AND `swars::membe_taggings_ad02ba7`.`context` = 'attack_tags' INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` WHERE `swars_memberships`.`id` IN (99305042, 99305045, 99305046, 99259352, 99305048) GROUP BY `judges`.`key`
# >>   ↳ app/models/swars/user_stat/matrix_stat.rb:61:in `block (2 levels) in build_by'
# >>   Swars::Membership Count (0.2ms)  SELECT COUNT(*) AS `count_all`, `judges`.`key` AS `judges_key` FROM `swars_memberships` INNER JOIN `taggings` `swars::membe_taggings_06aa9d9` ON `swars::membe_taggings_06aa9d9`.`taggable_id` = `swars_memberships`.`id` AND `swars::membe_taggings_06aa9d9`.`taggable_type` = 'Swars::Membership' AND `swars::membe_taggings_06aa9d9`.`tag_id` IN (SELECT `tags`.`id` FROM `tags` WHERE `tags`.`name` LIKE '棒銀' ESCAPE '!') AND `swars::membe_taggings_06aa9d9`.`context` = 'attack_tags' INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` WHERE `swars_memberships`.`id` IN (99305042, 99305045, 99305046, 99259352, 99305048) GROUP BY `judges`.`key`
# >>   ↳ app/models/swars/user_stat/matrix_stat.rb:61:in `block (2 levels) in build_by'
# >>   Swars::Membership Count (0.2ms)  SELECT COUNT(*) AS `count_all`, `judges`.`key` AS `judges_key` FROM `swars_memberships` INNER JOIN `taggings` `swars::membe_taggings_720d116` ON `swars::membe_taggings_720d116`.`taggable_id` = `swars_memberships`.`id` AND `swars::membe_taggings_720d116`.`taggable_type` = 'Swars::Membership' AND `swars::membe_taggings_720d116`.`tag_id` IN (SELECT `tags`.`id` FROM `tags` WHERE `tags`.`name` LIKE '▲７八飛戦法' ESCAPE '!') AND `swars::membe_taggings_720d116`.`context` = 'attack_tags' INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` WHERE `swars_memberships`.`id` IN (99305042, 99305045, 99305046, 99259352, 99305048) GROUP BY `judges`.`key`
# >>   ↳ app/models/swars/user_stat/matrix_stat.rb:61:in `block (2 levels) in build_by'
# >>   Swars::Membership Count (0.2ms)  SELECT COUNT(*) AS `count_all`, `judges`.`key` AS `judges_key` FROM `swars_memberships` INNER JOIN `taggings` `swars::membe_taggings_5588c1e` ON `swars::membe_taggings_5588c1e`.`taggable_id` = `swars_memberships`.`id` AND `swars::membe_taggings_5588c1e`.`taggable_type` = 'Swars::Membership' AND `swars::membe_taggings_5588c1e`.`tag_id` IN (SELECT `tags`.`id` FROM `tags` WHERE `tags`.`name` LIKE '向かい飛車' ESCAPE '!') AND `swars::membe_taggings_5588c1e`.`context` = 'attack_tags' INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` WHERE `swars_memberships`.`id` IN (99305042, 99305045, 99305046, 99259352, 99305048) GROUP BY `judges`.`key`
# >>   ↳ app/models/swars/user_stat/matrix_stat.rb:61:in `block (2 levels) in build_by'
# >>   Swars::Membership Count (0.2ms)  SELECT COUNT(*) AS `count_all`, `judges`.`key` AS `judges_key` FROM `swars_memberships` INNER JOIN `taggings` `swars::membe_taggings_1033e80` ON `swars::membe_taggings_1033e80`.`taggable_id` = `swars_memberships`.`id` AND `swars::membe_taggings_1033e80`.`taggable_type` = 'Swars::Membership' AND `swars::membe_taggings_1033e80`.`tag_id` IN (SELECT `tags`.`id` FROM `tags` WHERE `tags`.`name` LIKE '三間飛車ミレニアム' ESCAPE '!') AND `swars::membe_taggings_1033e80`.`context` = 'attack_tags' INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` WHERE `swars_memberships`.`id` IN (99305042, 99305045, 99305046, 99259352, 99305048) GROUP BY `judges`.`key`
# >>   ↳ app/models/swars/user_stat/matrix_stat.rb:61:in `block (2 levels) in build_by'
# >>   Swars::Membership Ids (8.0ms)  SELECT `swars_memberships`.`id` FROM `swars_memberships` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` WHERE `swars_memberships`.`op_user_id` = 23974 ORDER BY `swars_battles`.`battled_at` DESC LIMIT 5
# >>   ↳ app/models/swars/user_stat/matrix_stat.rb:44:in `build_by'
# >>   Swars::Membership Pluck (0.1ms)  SELECT `swars_memberships`.`id` FROM `swars_memberships` WHERE `swars_memberships`.`id` IN (99305043, 99305044, 99305047, 99259351, 99305049)
# >>   ↳ app/models/swars/user_stat/matrix_stat.rb:51:in `build_by'
# >>   ActsAsTaggableOn::Tag Load (0.3ms)  SELECT tags.*, taggings.tags_count AS count FROM `tags` JOIN (SELECT taggings.tag_id, COUNT(taggings.tag_id) AS tags_count FROM `taggings` WHERE (taggings.taggable_type = 'Swars::Membership' AND taggings.context = 'attack_tags') AND (taggings.taggable_id IN ('99259351','99305043','99305044','99305047','99305049')) GROUP BY `taggings`.`tag_id` HAVING (COUNT(taggings.tag_id) > 0)) AS taggings ON taggings.tag_id = tags.id ORDER BY count desc
# >>   ↳ app/models/swars/user_stat/matrix_stat.rb:52:in `collect'
# >>   Swars::Membership Count (0.2ms)  SELECT COUNT(*) AS `count_all`, `judges`.`key` AS `judges_key` FROM `swars_memberships` INNER JOIN `taggings` `swars::membe_taggings_2e29728` ON `swars::membe_taggings_2e29728`.`taggable_id` = `swars_memberships`.`id` AND `swars::membe_taggings_2e29728`.`taggable_type` = 'Swars::Membership' AND `swars::membe_taggings_2e29728`.`tag_id` IN (SELECT `tags`.`id` FROM `tags` WHERE `tags`.`name` LIKE '5筋位取り中飛車' ESCAPE '!') AND `swars::membe_taggings_2e29728`.`context` = 'attack_tags' INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` WHERE `swars_memberships`.`id` IN (99305043, 99305044, 99305047, 99259351, 99305049) GROUP BY `judges`.`key`
# >>   ↳ app/models/swars/user_stat/matrix_stat.rb:61:in `block (2 levels) in build_by'
# >>   Swars::Membership Count (0.2ms)  SELECT COUNT(*) AS `count_all`, `judges`.`key` AS `judges_key` FROM `swars_memberships` INNER JOIN `taggings` `swars::membe_taggings_ad02ba7` ON `swars::membe_taggings_ad02ba7`.`taggable_id` = `swars_memberships`.`id` AND `swars::membe_taggings_ad02ba7`.`taggable_type` = 'Swars::Membership' AND `swars::membe_taggings_ad02ba7`.`tag_id` IN (SELECT `tags`.`id` FROM `tags` WHERE `tags`.`name` LIKE '角換わり' ESCAPE '!') AND `swars::membe_taggings_ad02ba7`.`context` = 'attack_tags' INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` WHERE `swars_memberships`.`id` IN (99305043, 99305044, 99305047, 99259351, 99305049) GROUP BY `judges`.`key`
# >>   ↳ app/models/swars/user_stat/matrix_stat.rb:61:in `block (2 levels) in build_by'
# >>   Swars::Membership Count (0.2ms)  SELECT COUNT(*) AS `count_all`, `judges`.`key` AS `judges_key` FROM `swars_memberships` INNER JOIN `taggings` `swars::membe_taggings_fbf8131` ON `swars::membe_taggings_fbf8131`.`taggable_id` = `swars_memberships`.`id` AND `swars::membe_taggings_fbf8131`.`taggable_type` = 'Swars::Membership' AND `swars::membe_taggings_fbf8131`.`tag_id` IN (SELECT `tags`.`id` FROM `tags` WHERE `tags`.`name` LIKE '九間飛車' ESCAPE '!') AND `swars::membe_taggings_fbf8131`.`context` = 'attack_tags' INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` WHERE `swars_memberships`.`id` IN (99305043, 99305044, 99305047, 99259351, 99305049) GROUP BY `judges`.`key`
# >>   ↳ app/models/swars/user_stat/matrix_stat.rb:61:in `block (2 levels) in build_by'
# >>   Swars::Membership Count (0.2ms)  SELECT COUNT(*) AS `count_all`, `judges`.`key` AS `judges_key` FROM `swars_memberships` INNER JOIN `taggings` `swars::membe_taggings_a11b922` ON `swars::membe_taggings_a11b922`.`taggable_id` = `swars_memberships`.`id` AND `swars::membe_taggings_a11b922`.`taggable_type` = 'Swars::Membership' AND `swars::membe_taggings_a11b922`.`tag_id` IN (SELECT `tags`.`id` FROM `tags` WHERE `tags`.`name` LIKE '腰掛け銀' ESCAPE '!') AND `swars::membe_taggings_a11b922`.`context` = 'attack_tags' INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` WHERE `swars_memberships`.`id` IN (99305043, 99305044, 99305047, 99259351, 99305049) GROUP BY `judges`.`key`
# >>   ↳ app/models/swars/user_stat/matrix_stat.rb:61:in `block (2 levels) in build_by'
# >>   Swars::Membership Count (0.2ms)  SELECT COUNT(*) AS `count_all`, `judges`.`key` AS `judges_key` FROM `swars_memberships` INNER JOIN `taggings` `swars::membe_taggings_24fec36` ON `swars::membe_taggings_24fec36`.`taggable_id` = `swars_memberships`.`id` AND `swars::membe_taggings_24fec36`.`taggable_type` = 'Swars::Membership' AND `swars::membe_taggings_24fec36`.`tag_id` IN (SELECT `tags`.`id` FROM `tags` WHERE `tags`.`name` LIKE '右四間飛車' ESCAPE '!') AND `swars::membe_taggings_24fec36`.`context` = 'attack_tags' INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` WHERE `swars_memberships`.`id` IN (99305043, 99305044, 99305047, 99259351, 99305049) GROUP BY `judges`.`key`
# >>   ↳ app/models/swars/user_stat/matrix_stat.rb:61:in `block (2 levels) in build_by'
# >>   Swars::Membership Count (0.2ms)  SELECT COUNT(*) AS `count_all`, `judges`.`key` AS `judges_key` FROM `swars_memberships` INNER JOIN `taggings` `swars::membe_taggings_9de03ff` ON `swars::membe_taggings_9de03ff`.`taggable_id` = `swars_memberships`.`id` AND `swars::membe_taggings_9de03ff`.`taggable_type` = 'Swars::Membership' AND `swars::membe_taggings_9de03ff`.`tag_id` IN (SELECT `tags`.`id` FROM `tags` WHERE `tags`.`name` LIKE '対振り持久戦' ESCAPE '!') AND `swars::membe_taggings_9de03ff`.`context` = 'attack_tags' INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` WHERE `swars_memberships`.`id` IN (99305043, 99305044, 99305047, 99259351, 99305049) GROUP BY `judges`.`key`
# >>   ↳ app/models/swars/user_stat/matrix_stat.rb:61:in `block (2 levels) in build_by'
# >>   Swars::Membership Ids (6.9ms)  SELECT `swars_memberships`.`id` FROM `swars_memberships` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` WHERE `swars_memberships`.`user_id` = 23974 ORDER BY `swars_battles`.`battled_at` DESC LIMIT 5
# >>   ↳ app/models/swars/user_stat/matrix_stat.rb:44:in `build_by'
# >>   Swars::Membership Pluck (0.1ms)  SELECT `swars_memberships`.`id` FROM `swars_memberships` WHERE `swars_memberships`.`id` IN (99305042, 99305045, 99305046, 99259352, 99305048)
# >>   ↳ app/models/swars/user_stat/matrix_stat.rb:51:in `build_by'
# >>   ActsAsTaggableOn::Tag Load (0.2ms)  SELECT tags.*, taggings.tags_count AS count FROM `tags` JOIN (SELECT taggings.tag_id, COUNT(taggings.tag_id) AS tags_count FROM `taggings` WHERE (taggings.taggable_type = 'Swars::Membership' AND taggings.context = 'defense_tags') AND (taggings.taggable_id IN ('99259352','99305042','99305045','99305046','99305048')) GROUP BY `taggings`.`tag_id` HAVING (COUNT(taggings.tag_id) > 0)) AS taggings ON taggings.tag_id = tags.id ORDER BY count desc
# >>   ↳ app/models/swars/user_stat/matrix_stat.rb:52:in `collect'
# >>   Swars::Membership Count (0.2ms)  SELECT COUNT(*) AS `count_all`, `judges`.`key` AS `judges_key` FROM `swars_memberships` INNER JOIN `taggings` `swars::membe_taggings_c581859` ON `swars::membe_taggings_c581859`.`taggable_id` = `swars_memberships`.`id` AND `swars::membe_taggings_c581859`.`taggable_type` = 'Swars::Membership' AND `swars::membe_taggings_c581859`.`tag_id` IN (SELECT `tags`.`id` FROM `tags` WHERE `tags`.`name` LIKE '美濃囲い' ESCAPE '!') AND `swars::membe_taggings_c581859`.`context` = 'defense_tags' INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` WHERE `swars_memberships`.`id` IN (99305042, 99305045, 99305046, 99259352, 99305048) GROUP BY `judges`.`key`
# >>   ↳ app/models/swars/user_stat/matrix_stat.rb:61:in `block (2 levels) in build_by'
# >>   Swars::Membership Count (0.2ms)  SELECT COUNT(*) AS `count_all`, `judges`.`key` AS `judges_key` FROM `swars_memberships` INNER JOIN `taggings` `swars::membe_taggings_9598db9` ON `swars::membe_taggings_9598db9`.`taggable_id` = `swars_memberships`.`id` AND `swars::membe_taggings_9598db9`.`taggable_type` = 'Swars::Membership' AND `swars::membe_taggings_9598db9`.`tag_id` IN (SELECT `tags`.`id` FROM `tags` WHERE `tags`.`name` LIKE '振り飛車ミレニアム' ESCAPE '!') AND `swars::membe_taggings_9598db9`.`context` = 'defense_tags' INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` WHERE `swars_memberships`.`id` IN (99305042, 99305045, 99305046, 99259352, 99305048) GROUP BY `judges`.`key`
# >>   ↳ app/models/swars/user_stat/matrix_stat.rb:61:in `block (2 levels) in build_by'
# >>   Swars::Membership Ids (6.8ms)  SELECT `swars_memberships`.`id` FROM `swars_memberships` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` WHERE `swars_memberships`.`op_user_id` = 23974 ORDER BY `swars_battles`.`battled_at` DESC LIMIT 5
# >>   ↳ app/models/swars/user_stat/matrix_stat.rb:44:in `build_by'
# >>   Swars::Membership Pluck (0.1ms)  SELECT `swars_memberships`.`id` FROM `swars_memberships` WHERE `swars_memberships`.`id` IN (99305043, 99305044, 99305047, 99259351, 99305049)
# >>   ↳ app/models/swars/user_stat/matrix_stat.rb:51:in `build_by'
# >>   ActsAsTaggableOn::Tag Load (0.2ms)  SELECT tags.*, taggings.tags_count AS count FROM `tags` JOIN (SELECT taggings.tag_id, COUNT(taggings.tag_id) AS tags_count FROM `taggings` WHERE (taggings.taggable_type = 'Swars::Membership' AND taggings.context = 'defense_tags') AND (taggings.taggable_id IN ('99259351','99305043','99305044','99305047','99305049')) GROUP BY `taggings`.`tag_id` HAVING (COUNT(taggings.tag_id) > 0)) AS taggings ON taggings.tag_id = tags.id ORDER BY count desc
# >>   ↳ app/models/swars/user_stat/matrix_stat.rb:52:in `collect'
# >>   Swars::Membership Count (0.2ms)  SELECT COUNT(*) AS `count_all`, `judges`.`key` AS `judges_key` FROM `swars_memberships` INNER JOIN `taggings` `swars::membe_taggings_d0162ee` ON `swars::membe_taggings_d0162ee`.`taggable_id` = `swars_memberships`.`id` AND `swars::membe_taggings_d0162ee`.`taggable_type` = 'Swars::Membership' AND `swars::membe_taggings_d0162ee`.`tag_id` IN (SELECT `tags`.`id` FROM `tags` WHERE `tags`.`name` LIKE '角換わり右玉' ESCAPE '!') AND `swars::membe_taggings_d0162ee`.`context` = 'defense_tags' INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` WHERE `swars_memberships`.`id` IN (99305043, 99305044, 99305047, 99259351, 99305049) GROUP BY `judges`.`key`
# >>   ↳ app/models/swars/user_stat/matrix_stat.rb:61:in `block (2 levels) in build_by'
# >>   Swars::Membership Count (0.2ms)  SELECT COUNT(*) AS `count_all`, `judges`.`key` AS `judges_key` FROM `swars_memberships` INNER JOIN `taggings` `swars::membe_taggings_8927555` ON `swars::membe_taggings_8927555`.`taggable_id` = `swars_memberships`.`id` AND `swars::membe_taggings_8927555`.`taggable_type` = 'Swars::Membership' AND `swars::membe_taggings_8927555`.`tag_id` IN (SELECT `tags`.`id` FROM `tags` WHERE `tags`.`name` LIKE '振り飛車穴熊' ESCAPE '!') AND `swars::membe_taggings_8927555`.`context` = 'defense_tags' INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` WHERE `swars_memberships`.`id` IN (99305043, 99305044, 99305047, 99259351, 99305049) GROUP BY `judges`.`key`
# >>   ↳ app/models/swars/user_stat/matrix_stat.rb:61:in `block (2 levels) in build_by'
# >>   Swars::Membership Count (0.3ms)  SELECT COUNT(*) AS `count_all`, `judges`.`key` AS `judges_key` FROM `swars_memberships` INNER JOIN `taggings` `swars::membe_taggings_94f3238` ON `swars::membe_taggings_94f3238`.`taggable_id` = `swars_memberships`.`id` AND `swars::membe_taggings_94f3238`.`taggable_type` = 'Swars::Membership' AND `swars::membe_taggings_94f3238`.`tag_id` IN (SELECT `tags`.`id` FROM `tags` WHERE `tags`.`name` LIKE '左山囲い' ESCAPE '!') AND `swars::membe_taggings_94f3238`.`context` = 'defense_tags' INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` WHERE `swars_memberships`.`id` IN (99305043, 99305044, 99305047, 99259351, 99305049) GROUP BY `judges`.`key`
# >>   ↳ app/models/swars/user_stat/matrix_stat.rb:61:in `block (2 levels) in build_by'
# >>   Swars::Membership Count (0.2ms)  SELECT COUNT(*) AS `count_all`, `judges`.`key` AS `judges_key` FROM `swars_memberships` INNER JOIN `taggings` `swars::membe_taggings_15dd54e` ON `swars::membe_taggings_15dd54e`.`taggable_id` = `swars_memberships`.`id` AND `swars::membe_taggings_15dd54e`.`taggable_type` = 'Swars::Membership' AND `swars::membe_taggings_15dd54e`.`tag_id` IN (SELECT `tags`.`id` FROM `tags` WHERE `tags`.`name` LIKE '舟囲い' ESCAPE '!') AND `swars::membe_taggings_15dd54e`.`context` = 'defense_tags' INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` WHERE `swars_memberships`.`id` IN (99305043, 99305044, 99305047, 99259351, 99305049) GROUP BY `judges`.`key`
# >>   ↳ app/models/swars/user_stat/matrix_stat.rb:61:in `block (2 levels) in build_by'
# >>   Swars::Membership Count (0.2ms)  SELECT COUNT(*) AS `count_all`, `judges`.`key` AS `judges_key` FROM `swars_memberships` INNER JOIN `taggings` `swars::membe_taggings_bdddf7d` ON `swars::membe_taggings_bdddf7d`.`taggable_id` = `swars_memberships`.`id` AND `swars::membe_taggings_bdddf7d`.`taggable_type` = 'Swars::Membership' AND `swars::membe_taggings_bdddf7d`.`tag_id` IN (SELECT `tags`.`id` FROM `tags` WHERE `tags`.`name` LIKE '居飛車穴熊' ESCAPE '!') AND `swars::membe_taggings_bdddf7d`.`context` = 'defense_tags' INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` WHERE `swars_memberships`.`id` IN (99305043, 99305044, 99305047, 99259351, 99305049) GROUP BY `judges`.`key`
# >>   ↳ app/models/swars/user_stat/matrix_stat.rb:61:in `block (2 levels) in build_by'
# >>   Swars::Membership Count (0.2ms)  SELECT COUNT(*) FROM `swars_memberships` INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` INNER JOIN `swars_finals` ON `swars_finals`.`id` = `swars_battles`.`final_id` WHERE `swars_memberships`.`id` IN (99305042, 99305045, 99305046, 99259352, 99305048) AND `judges`.`key` = 'lose' AND `swars_battles`.`turn_max` >= 14 AND `swars_finals`.`key` = 'DISCONNECT'
# >>   ↳ app/models/swars/user_stat/disconnect_escape_stat.rb:18:in `count'
# >>   Swars::Membership Count (0.3ms)  SELECT COUNT(*) AS `count_all`, `judges`.`key` AS `judges_key` FROM `swars_memberships` INNER JOIN `taggings` `swars::membe_taggings_a7ebda8` ON `swars::membe_taggings_a7ebda8`.`taggable_id` = `swars_memberships`.`id` AND `swars::membe_taggings_a7ebda8`.`taggable_type` = 'Swars::Membership' AND `swars::membe_taggings_a7ebda8`.`tag_id` IN (SELECT `tags`.`id` FROM `tags` WHERE `tags`.`name` LIKE '居飛車' ESCAPE '!') AND `swars::membe_taggings_a7ebda8`.`context` = 'note_tags' INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` WHERE `swars_memberships`.`id` IN (99305042, 99305045, 99305046, 99259352, 99305048) GROUP BY `judges`.`key`
# >>   ↳ app/models/swars/user_stat/note_stat.rb:23:in `to_chart'
# >>   Swars::Membership Count (0.2ms)  SELECT COUNT(*) AS `count_all`, `judges`.`key` AS `judges_key` FROM `swars_memberships` INNER JOIN `taggings` `swars::membe_taggings_a9c1913` ON `swars::membe_taggings_a9c1913`.`taggable_id` = `swars_memberships`.`id` AND `swars::membe_taggings_a9c1913`.`taggable_type` = 'Swars::Membership' AND `swars::membe_taggings_a9c1913`.`tag_id` IN (SELECT `tags`.`id` FROM `tags` WHERE `tags`.`name` LIKE '振り飛車' ESCAPE '!') AND `swars::membe_taggings_a9c1913`.`context` = 'note_tags' INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` WHERE `swars_memberships`.`id` IN (99305042, 99305045, 99305046, 99259352, 99305048) GROUP BY `judges`.`key`
# >>   ↳ app/models/swars/user_stat/note_stat.rb:23:in `to_chart'
# >>   Swars::Membership Count (0.2ms)  SELECT COUNT(*) AS `count_all`, `judges`.`key` AS `judges_key` FROM `swars_memberships` INNER JOIN `taggings` `swars::membe_taggings_aa182c2` ON `swars::membe_taggings_aa182c2`.`taggable_id` = `swars_memberships`.`id` AND `swars::membe_taggings_aa182c2`.`taggable_type` = 'Swars::Membership' AND `swars::membe_taggings_aa182c2`.`tag_id` IN (SELECT `tags`.`id` FROM `tags` WHERE `tags`.`name` LIKE '相居飛車' ESCAPE '!') AND `swars::membe_taggings_aa182c2`.`context` = 'note_tags' INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` WHERE `swars_memberships`.`id` IN (99305042, 99305045, 99305046, 99259352, 99305048) GROUP BY `judges`.`key`
# >>   ↳ app/models/swars/user_stat/note_stat.rb:23:in `to_chart'
# >>   Swars::Membership Count (0.2ms)  SELECT COUNT(*) AS `count_all`, `judges`.`key` AS `judges_key` FROM `swars_memberships` INNER JOIN `taggings` `swars::membe_taggings_0deaf82` ON `swars::membe_taggings_0deaf82`.`taggable_id` = `swars_memberships`.`id` AND `swars::membe_taggings_0deaf82`.`taggable_type` = 'Swars::Membership' AND `swars::membe_taggings_0deaf82`.`tag_id` IN (SELECT `tags`.`id` FROM `tags` WHERE `tags`.`name` LIKE '対振り' ESCAPE '!') AND `swars::membe_taggings_0deaf82`.`context` = 'note_tags' INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` WHERE `swars_memberships`.`id` IN (99305042, 99305045, 99305046, 99259352, 99305048) GROUP BY `judges`.`key`
# >>   ↳ app/models/swars/user_stat/note_stat.rb:23:in `to_chart'
# >>   Swars::Membership Count (0.2ms)  SELECT COUNT(*) AS `count_all`, `judges`.`key` AS `judges_key` FROM `swars_memberships` INNER JOIN `taggings` `swars::membe_taggings_6b8ff07` ON `swars::membe_taggings_6b8ff07`.`taggable_id` = `swars_memberships`.`id` AND `swars::membe_taggings_6b8ff07`.`taggable_type` = 'Swars::Membership' AND `swars::membe_taggings_6b8ff07`.`tag_id` IN (SELECT `tags`.`id` FROM `tags` WHERE `tags`.`name` LIKE '対抗形' ESCAPE '!') AND `swars::membe_taggings_6b8ff07`.`context` = 'note_tags' INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` WHERE `swars_memberships`.`id` IN (99305042, 99305045, 99305046, 99259352, 99305048) GROUP BY `judges`.`key`
# >>   ↳ app/models/swars/user_stat/note_stat.rb:23:in `to_chart'
# >>   Swars::Membership Count (0.2ms)  SELECT COUNT(*) AS `count_all`, `judges`.`key` AS `judges_key` FROM `swars_memberships` INNER JOIN `taggings` `swars::membe_taggings_7a1d286` ON `swars::membe_taggings_7a1d286`.`taggable_id` = `swars_memberships`.`id` AND `swars::membe_taggings_7a1d286`.`taggable_type` = 'Swars::Membership' AND `swars::membe_taggings_7a1d286`.`tag_id` IN (SELECT `tags`.`id` FROM `tags` WHERE `tags`.`name` LIKE '相振り' ESCAPE '!') AND `swars::membe_taggings_7a1d286`.`context` = 'note_tags' INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` WHERE `swars_memberships`.`id` IN (99305042, 99305045, 99305046, 99259352, 99305048) GROUP BY `judges`.`key`
# >>   ↳ app/models/swars/user_stat/note_stat.rb:23:in `to_chart'
# >>   Swars::Membership Count (0.2ms)  SELECT COUNT(*) AS `count_all`, `judges`.`key` AS `judges_key` FROM `swars_memberships` INNER JOIN `taggings` `swars::membe_taggings_f8fd97d` ON `swars::membe_taggings_f8fd97d`.`taggable_id` = `swars_memberships`.`id` AND `swars::membe_taggings_f8fd97d`.`taggable_type` = 'Swars::Membership' AND `swars::membe_taggings_f8fd97d`.`tag_id` IN (SELECT `tags`.`id` FROM `tags` WHERE `tags`.`name` LIKE '大駒全ブッチ' ESCAPE '!') AND `swars::membe_taggings_f8fd97d`.`context` = 'note_tags' INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` WHERE `swars_memberships`.`id` IN (99305042, 99305045, 99305046, 99259352, 99305048) GROUP BY `judges`.`key`
# >>   ↳ app/models/swars/user_stat/note_stat.rb:23:in `to_chart'
# >>   Swars::Membership Count (0.2ms)  SELECT COUNT(*) AS `count_all`, `judges`.`key` AS `judges_key` FROM `swars_memberships` INNER JOIN `taggings` `swars::membe_taggings_9c84015` ON `swars::membe_taggings_9c84015`.`taggable_id` = `swars_memberships`.`id` AND `swars::membe_taggings_9c84015`.`taggable_type` = 'Swars::Membership' AND `swars::membe_taggings_9c84015`.`tag_id` IN (SELECT `tags`.`id` FROM `tags` WHERE `tags`.`name` LIKE '大駒コンプリート' ESCAPE '!') AND `swars::membe_taggings_9c84015`.`context` = 'note_tags' INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` WHERE `swars_memberships`.`id` IN (99305042, 99305045, 99305046, 99259352, 99305048) GROUP BY `judges`.`key`
# >>   ↳ app/models/swars/user_stat/note_stat.rb:23:in `to_chart'
# >>   Swars::Membership Count (0.2ms)  SELECT COUNT(*) AS `count_all`, `judges`.`key` AS `judges_key` FROM `swars_memberships` INNER JOIN `taggings` `swars::membe_taggings_f11a8b7` ON `swars::membe_taggings_f11a8b7`.`taggable_id` = `swars_memberships`.`id` AND `swars::membe_taggings_f11a8b7`.`taggable_type` = 'Swars::Membership' AND `swars::membe_taggings_f11a8b7`.`tag_id` IN (SELECT `tags`.`id` FROM `tags` WHERE `tags`.`name` LIKE '入玉' ESCAPE '!') AND `swars::membe_taggings_f11a8b7`.`context` = 'note_tags' INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` WHERE `swars_memberships`.`id` IN (99305042, 99305045, 99305046, 99259352, 99305048) GROUP BY `judges`.`key`
# >>   ↳ app/models/swars/user_stat/note_stat.rb:23:in `to_chart'
# >>   Swars::Membership Count (0.2ms)  SELECT COUNT(*) AS `count_all`, `judges`.`key` AS `judges_key` FROM `swars_memberships` INNER JOIN `taggings` `swars::membe_taggings_e5a6191` ON `swars::membe_taggings_e5a6191`.`taggable_id` = `swars_memberships`.`id` AND `swars::membe_taggings_e5a6191`.`taggable_type` = 'Swars::Membership' AND `swars::membe_taggings_e5a6191`.`tag_id` IN (SELECT `tags`.`id` FROM `tags` WHERE `tags`.`name` LIKE '急戦' ESCAPE '!') AND `swars::membe_taggings_e5a6191`.`context` = 'note_tags' INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` WHERE `swars_memberships`.`id` IN (99305042, 99305045, 99305046, 99259352, 99305048) GROUP BY `judges`.`key`
# >>   ↳ app/models/swars/user_stat/note_stat.rb:23:in `to_chart'
# >>   Swars::Membership Count (0.2ms)  SELECT COUNT(*) AS `count_all`, `judges`.`key` AS `judges_key` FROM `swars_memberships` INNER JOIN `taggings` `swars::membe_taggings_8afafbc` ON `swars::membe_taggings_8afafbc`.`taggable_id` = `swars_memberships`.`id` AND `swars::membe_taggings_8afafbc`.`taggable_type` = 'Swars::Membership' AND `swars::membe_taggings_8afafbc`.`tag_id` IN (SELECT `tags`.`id` FROM `tags` WHERE `tags`.`name` LIKE '持久戦' ESCAPE '!') AND `swars::membe_taggings_8afafbc`.`context` = 'note_tags' INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` WHERE `swars_memberships`.`id` IN (99305042, 99305045, 99305046, 99259352, 99305048) GROUP BY `judges`.`key`
# >>   ↳ app/models/swars/user_stat/note_stat.rb:23:in `to_chart'
# >>   Swars::Membership Count (0.2ms)  SELECT COUNT(*) AS `count_all`, `judges`.`key` AS `judges_key` FROM `swars_memberships` INNER JOIN `taggings` `swars::membe_taggings_411d086` ON `swars::membe_taggings_411d086`.`taggable_id` = `swars_memberships`.`id` AND `swars::membe_taggings_411d086`.`taggable_type` = 'Swars::Membership' AND `swars::membe_taggings_411d086`.`tag_id` IN (SELECT `tags`.`id` FROM `tags` WHERE `tags`.`name` LIKE '短手数' ESCAPE '!') AND `swars::membe_taggings_411d086`.`context` = 'note_tags' INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` WHERE `swars_memberships`.`id` IN (99305042, 99305045, 99305046, 99259352, 99305048) GROUP BY `judges`.`key`
# >>   ↳ app/models/swars/user_stat/note_stat.rb:23:in `to_chart'
# >>   Swars::Membership Count (0.2ms)  SELECT COUNT(*) AS `count_all`, `judges`.`key` AS `judges_key` FROM `swars_memberships` INNER JOIN `taggings` `swars::membe_taggings_4f7abbb` ON `swars::membe_taggings_4f7abbb`.`taggable_id` = `swars_memberships`.`id` AND `swars::membe_taggings_4f7abbb`.`taggable_type` = 'Swars::Membership' AND `swars::membe_taggings_4f7abbb`.`tag_id` IN (SELECT `tags`.`id` FROM `tags` WHERE `tags`.`name` LIKE '長手数' ESCAPE '!') AND `swars::membe_taggings_4f7abbb`.`context` = 'note_tags' INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` WHERE `swars_memberships`.`id` IN (99305042, 99305045, 99305046, 99259352, 99305048) GROUP BY `judges`.`key`
# >>   ↳ app/models/swars/user_stat/note_stat.rb:23:in `to_chart'
# >>   Swars::Membership Maximum (0.1ms)  SELECT MAX(`swars_battles`.`turn_max`) FROM `swars_memberships` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` WHERE `swars_memberships`.`id` IN (99305042, 99305045, 99305046, 99259352, 99305048)
# >>   ↳ app/models/swars/user_stat/turn_stat.rb:17:in `max'
# >>   Swars::Membership Average (0.1ms)  SELECT AVG(`swars_battles`.`turn_max`) FROM `swars_memberships` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` WHERE `swars_memberships`.`id` IN (99305042, 99305045, 99305046, 99259352, 99305048)
# >>   ↳ app/models/swars/user_stat/turn_stat.rb:24:in `block in average'
# >>   Swars::Membership Average (0.1ms)  SELECT AVG(`swars_battles`.`turn_max`) FROM `swars_memberships` INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` INNER JOIN `swars_finals` ON `swars_finals`.`id` = `swars_battles`.`final_id` WHERE `swars_memberships`.`id` IN (99305042, 99305045, 99305046, 99259352, 99305048) AND `judges`.`key` = 'lose' AND `swars_finals`.`key` = 'TORYO'
# >>   ↳ app/models/swars/user_stat/average_moves_at_resignation_stat.rb:15:in `average'
# >>   Swars::Membership Count (0.1ms)  SELECT COUNT(*) AS `count_all`, `swars_rules`.`key` AS `swars_rules_key` FROM `swars_memberships` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` INNER JOIN `swars_rules` ON `swars_rules`.`id` = `swars_battles`.`rule_id` WHERE `swars_memberships`.`id` IN (99305042, 99305045, 99305046, 99259352, 99305048) GROUP BY `swars_rules`.`key`
# >>   ↳ app/models/swars/user_stat/rule_stat.rb:13:in `block in to_chart'
# >>   Swars::Membership Count (0.1ms)  SELECT COUNT(*) AS `count_all`, `swars_xmodes`.`key` AS `swars_xmodes_key` FROM `swars_memberships` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` INNER JOIN `swars_xmodes` ON `swars_xmodes`.`id` = `swars_battles`.`xmode_id` WHERE `swars_memberships`.`id` IN (99305042, 99305045, 99305046, 99259352, 99305048) GROUP BY `swars_xmodes`.`key`
# >>   ↳ app/models/swars/user_stat/xmode_stat.rb:33:in `block in counts_hash'
# >>   Judge Load (0.1ms)  SELECT `judges`.* FROM `judges` WHERE `judges`.`key` = 'win' ORDER BY `judges`.`position` ASC LIMIT 1
# >>   ↳ app/models/application_memory_record.rb:22:in `db_record!'
# >>   Swars::Final Load (0.1ms)  SELECT `swars_finals`.* FROM `swars_finals` WHERE `swars_finals`.`key` = 'TORYO' ORDER BY `swars_finals`.`position` ASC LIMIT 1
# >>   ↳ app/models/application_memory_record.rb:22:in `db_record!'
# >>   Judge Load (0.1ms)  SELECT `judges`.* FROM `judges` WHERE `judges`.`key` = 'win' ORDER BY `judges`.`position` ASC LIMIT 1
# >>   ↳ app/models/application_memory_record.rb:22:in `db_record!'
# >>   Swars::Final Load (0.1ms)  SELECT `swars_finals`.* FROM `swars_finals` WHERE `swars_finals`.`key` = 'TIMEOUT' ORDER BY `swars_finals`.`position` ASC LIMIT 1
# >>   ↳ app/models/application_memory_record.rb:22:in `db_record!'
# >>   Judge Load (0.1ms)  SELECT `judges`.* FROM `judges` WHERE `judges`.`key` = 'win' ORDER BY `judges`.`position` ASC LIMIT 1
# >>   ↳ app/models/application_memory_record.rb:22:in `db_record!'
# >>   Swars::Final Load (0.1ms)  SELECT `swars_finals`.* FROM `swars_finals` WHERE `swars_finals`.`key` = 'CHECKMATE' ORDER BY `swars_finals`.`position` ASC LIMIT 1
# >>   ↳ app/models/application_memory_record.rb:22:in `db_record!'
# >>   Judge Load (0.1ms)  SELECT `judges`.* FROM `judges` WHERE `judges`.`key` = 'win' ORDER BY `judges`.`position` ASC LIMIT 1
# >>   ↳ app/models/application_memory_record.rb:22:in `db_record!'
# >>   Swars::Final Load (0.1ms)  SELECT `swars_finals`.* FROM `swars_finals` WHERE `swars_finals`.`key` = 'DISCONNECT' ORDER BY `swars_finals`.`position` ASC LIMIT 1
# >>   ↳ app/models/application_memory_record.rb:22:in `db_record!'
# >>   Judge Load (0.1ms)  SELECT `judges`.* FROM `judges` WHERE `judges`.`key` = 'win' ORDER BY `judges`.`position` ASC LIMIT 1
# >>   ↳ app/models/application_memory_record.rb:22:in `db_record!'
# >>   Swars::Final Load (0.1ms)  SELECT `swars_finals`.* FROM `swars_finals` WHERE `swars_finals`.`key` = 'ENTERINGKING' ORDER BY `swars_finals`.`position` ASC LIMIT 1
# >>   ↳ app/models/application_memory_record.rb:22:in `db_record!'
# >>   Judge Load (0.1ms)  SELECT `judges`.* FROM `judges` WHERE `judges`.`key` = 'win' ORDER BY `judges`.`position` ASC LIMIT 1
# >>   ↳ app/models/application_memory_record.rb:22:in `db_record!'
# >>   Swars::Final Load (0.1ms)  SELECT `swars_finals`.* FROM `swars_finals` WHERE `swars_finals`.`key` = 'DRAW_SENNICHI' ORDER BY `swars_finals`.`position` ASC LIMIT 1
# >>   ↳ app/models/application_memory_record.rb:22:in `db_record!'
# >>   Judge Load (0.1ms)  SELECT `judges`.* FROM `judges` WHERE `judges`.`key` = 'win' ORDER BY `judges`.`position` ASC LIMIT 1
# >>   ↳ app/models/application_memory_record.rb:22:in `db_record!'
# >>   Swars::Final Load (0.1ms)  SELECT `swars_finals`.* FROM `swars_finals` WHERE `swars_finals`.`key` = 'OUTE_SENNICHI' ORDER BY `swars_finals`.`position` ASC LIMIT 1
# >>   ↳ app/models/application_memory_record.rb:22:in `db_record!'
# >>   Judge Load (0.1ms)  SELECT `judges`.* FROM `judges` WHERE `judges`.`key` = 'lose' ORDER BY `judges`.`position` ASC LIMIT 1
# >>   ↳ app/models/application_memory_record.rb:22:in `db_record!'
# >>   Swars::Final Load (0.1ms)  SELECT `swars_finals`.* FROM `swars_finals` WHERE `swars_finals`.`key` = 'TORYO' ORDER BY `swars_finals`.`position` ASC LIMIT 1
# >>   ↳ app/models/application_memory_record.rb:22:in `db_record!'
# >>   Judge Load (0.1ms)  SELECT `judges`.* FROM `judges` WHERE `judges`.`key` = 'lose' ORDER BY `judges`.`position` ASC LIMIT 1
# >>   ↳ app/models/application_memory_record.rb:22:in `db_record!'
# >>   Swars::Final Load (0.1ms)  SELECT `swars_finals`.* FROM `swars_finals` WHERE `swars_finals`.`key` = 'TIMEOUT' ORDER BY `swars_finals`.`position` ASC LIMIT 1
# >>   ↳ app/models/application_memory_record.rb:22:in `db_record!'
# >>   Judge Load (0.1ms)  SELECT `judges`.* FROM `judges` WHERE `judges`.`key` = 'lose' ORDER BY `judges`.`position` ASC LIMIT 1
# >>   ↳ app/models/application_memory_record.rb:22:in `db_record!'
# >>   Swars::Final Load (0.2ms)  SELECT `swars_finals`.* FROM `swars_finals` WHERE `swars_finals`.`key` = 'CHECKMATE' ORDER BY `swars_finals`.`position` ASC LIMIT 1
# >>   ↳ app/models/application_memory_record.rb:22:in `db_record!'
# >>   Judge Load (0.1ms)  SELECT `judges`.* FROM `judges` WHERE `judges`.`key` = 'lose' ORDER BY `judges`.`position` ASC LIMIT 1
# >>   ↳ app/models/application_memory_record.rb:22:in `db_record!'
# >>   Swars::Final Load (0.1ms)  SELECT `swars_finals`.* FROM `swars_finals` WHERE `swars_finals`.`key` = 'DISCONNECT' ORDER BY `swars_finals`.`position` ASC LIMIT 1
# >>   ↳ app/models/application_memory_record.rb:22:in `db_record!'
# >>   Judge Load (0.1ms)  SELECT `judges`.* FROM `judges` WHERE `judges`.`key` = 'lose' ORDER BY `judges`.`position` ASC LIMIT 1
# >>   ↳ app/models/application_memory_record.rb:22:in `db_record!'
# >>   Swars::Final Load (0.1ms)  SELECT `swars_finals`.* FROM `swars_finals` WHERE `swars_finals`.`key` = 'ENTERINGKING' ORDER BY `swars_finals`.`position` ASC LIMIT 1
# >>   ↳ app/models/application_memory_record.rb:22:in `db_record!'
# >>   Judge Load (0.1ms)  SELECT `judges`.* FROM `judges` WHERE `judges`.`key` = 'lose' ORDER BY `judges`.`position` ASC LIMIT 1
# >>   ↳ app/models/application_memory_record.rb:22:in `db_record!'
# >>   Swars::Final Load (0.1ms)  SELECT `swars_finals`.* FROM `swars_finals` WHERE `swars_finals`.`key` = 'DRAW_SENNICHI' ORDER BY `swars_finals`.`position` ASC LIMIT 1
# >>   ↳ app/models/application_memory_record.rb:22:in `db_record!'
# >>   Judge Load (0.1ms)  SELECT `judges`.* FROM `judges` WHERE `judges`.`key` = 'lose' ORDER BY `judges`.`position` ASC LIMIT 1
# >>   ↳ app/models/application_memory_record.rb:22:in `db_record!'
# >>   Swars::Final Load (0.1ms)  SELECT `swars_finals`.* FROM `swars_finals` WHERE `swars_finals`.`key` = 'OUTE_SENNICHI' ORDER BY `swars_finals`.`position` ASC LIMIT 1
# >>   ↳ app/models/application_memory_record.rb:22:in `db_record!'
# >>   Swars::Membership Ids (0.2ms)  SELECT `swars_memberships`.`id` FROM `swars_memberships` INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` INNER JOIN `swars_finals` ON `swars_finals`.`id` = `swars_battles`.`final_id` WHERE `swars_memberships`.`id` IN (99305042, 99305045, 99305046, 99259352, 99305048) AND `judges`.`key` = 'lose' AND `swars_battles`.`turn_max` >= 14 AND `swars_finals`.`key` = 'TORYO'
# >>   ↳ app/models/swars/user_stat/resignation_stat.rb:70:in `block in scope'
# >>   Swars::Membership Maximum (0.1ms)  SELECT MAX(`swars_memberships`.`think_last`) FROM `swars_memberships` WHERE `swars_memberships`.`id` = 99305048
# >>   ↳ app/models/swars/user_stat/resignation_stat.rb:50:in `max'
# >>   Swars::Membership Count (0.1ms)  SELECT COUNT(*) AS `count_all`, think_last DIV 10 AS `think_last_div_10` FROM `swars_memberships` WHERE `swars_memberships`.`id` = 99305048 AND `swars_memberships`.`think_last` < 60 GROUP BY think_last DIV 10 ORDER BY count_all desc
# >>   ↳ app/models/swars/user_stat/resignation_stat.rb:20:in `to_chart'
# >>   Swars::Membership Average (0.1ms)  SELECT AVG(`swars_memberships`.`think_last`) FROM `swars_memberships` WHERE `swars_memberships`.`id` = 99305048
# >>   ↳ app/models/swars/user_stat/resignation_stat.rb:56:in `block in average'
# >>   Swars::Membership Maximum (0.1ms)  SELECT MAX(`swars_memberships`.`think_max`) FROM `swars_memberships` WHERE `swars_memberships`.`id` IN (99305042, 99305045, 99305046, 99259352, 99305048)
# >>   ↳ app/models/swars/user_stat/think_stat.rb:12:in `max'
# >>   Swars::Membership Average (0.1ms)  SELECT AVG(`swars_memberships`.`think_all_avg`) FROM `swars_memberships` WHERE `swars_memberships`.`id` IN (99305042, 99305045, 99305046, 99259352, 99305048)
# >>   ↳ app/models/swars/user_stat/think_stat.rb:18:in `block in average'
# >>   Swars::Membership Average (0.2ms)  SELECT AVG(`swars_memberships`.`think_end_avg`) FROM `swars_memberships` INNER JOIN `judges` ON `judges`.`id` = `swars_memberships`.`judge_id` INNER JOIN `swars_battles` ON `swars_battles`.`id` = `swars_memberships`.`battle_id` INNER JOIN `swars_finals` ON `swars_finals`.`id` = `swars_battles`.`final_id` WHERE `swars_memberships`.`id` IN (99305042, 99305045, 99305046, 99259352, 99305048) AND `judges`.`key` = 'win' AND `swars_finals`.`key` = 'CHECKMATE'
# >>   ↳ app/models/swars/user_stat/mate_speed_stat.rb:15:in `average'
# >>   Swars::Membership Load (0.1ms)  SELECT `swars_memberships`.* FROM `swars_memberships` WHERE `swars_memberships`.`id` IN (99305042, 99305045, 99305046, 99259352, 99305048)
# >>   ↳ app/models/swars/user_stat/piece_stat.rb:48:in `block in counts_hash'
# >>   Swars::MembershipExtra Load (0.1ms)  SELECT `swars_membership_extras`.* FROM `swars_membership_extras` WHERE `swars_membership_extras`.`membership_id` IN (99259352, 99305042, 99305045, 99305046, 99305048)
# >>   ↳ app/models/swars/user_stat/piece_stat.rb:48:in `block in counts_hash'
# >>   Swars::Membership Average (0.1ms)  SELECT AVG(`swars_memberships`.`grade_diff`) FROM `swars_memberships` WHERE `swars_memberships`.`id` IN (99305042, 99305045, 99305046, 99259352, 99305048)
# >>   ↳ app/models/swars/user_stat/gdiff_stat.rb:11:in `average'
# >>   Swars::Membership Pluck (0.2ms)  SELECT `swars_memberships`.`battle_id` FROM `swars_memberships` WHERE `swars_memberships`.`id` IN (99305042, 99305045, 99305046, 99259352, 99305048)
# >>   ↳ app/models/swars/user_stat/match_time_period_stat.rb:11:in `to_chart'
# >>   Swars::Battle Count (0.1ms)  SELECT COUNT(*) AS `count_all`, HOUR(CONVERT_TZ(battled_at, 'UTC', 'Asia/Tokyo')) AS `hour_convert_tz_battled_at_utc_asia_tokyo` FROM `swars_battles` WHERE `swars_battles`.`id` IN (49743466, 49766574, 49766575, 49766576, 49766577) GROUP BY HOUR(CONVERT_TZ(battled_at, 'UTC', 'Asia/Tokyo'))
# >>   ↳ app/models/swars/user_stat/match_time_period_stat.rb:14:in `to_chart'
