require "../setup"
user = Swars::User.find_by(key: "SugarHuuko")
tp Swars::User.find_by(key: "SugarHuuko").user_stat.etc_stat.time_stats
_ { pp user.user_stat.to_hash }    # => "347.12 ms"

@record = Swars::Battle.create!
@hash = @record.memberships.first.user.user_stat.to_hash.as_json
@hash["user"]                   # => {"key"=>"user957292", "ban_at"=>nil}
@hash["rule_items"]         # => [{"rule_key"=>"ten_min", "rule_name"=>"10分", "grade_name"=>"30級"}, {"rule_key"=>"three_min", "rule_name"=>"3分", "grade_name"=>nil}, {"rule_key"=>"ten_sec", "rule_name"=>"10秒", "grade_name"=>nil}]
@hash["judge_counts"]           # => {"win"=>1}

# >> |--------------------------------------+-------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
# >> | 項目                                 | 時間  | 結果                                                                                                                                                                                                                                                                      |
# >> |--------------------------------------+-------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
# >> | ids_count                            | 92.36 |                                                                                                                                                                                                                                                                        50 |
# >> | 1日の平均対局数                      | 22.78 |                                                                                                                                                                                                                                                                      12.5 |
# >> | 駒の使用率                           | 12.56 | [{:name=>"玉", :value=>0.08155080213903744}, {:name=>"飛", :value=>0.08422459893048129}, {:name=>"角", :value=>0.09180035650623886}, {:name=>"金", :value=>0.10338680926916222}, {:name=>"銀", :value=>0.16310160427807488}, {:name=>"桂", :value=>0.08600713012477719... |
# >> | 角不成                               |  8.76 |                                                                                                                                                                                                                                                                           |
# >> | 棋風                                 |  6.21 | [{:name=>"王道", :value=>21}, {:name=>"準王道", :value=>8}, {:name=>"準変態", :value=>14}, {:name=>"変態", :value=>7}]                                                                                                                                                    |
# >> | 対局モード                           |  6.11 | [{:name=>"野良", :value=>50}, {:name=>"友達", :value=>0}, {:name=>"指導", :value=>0}]                                                                                                                                                                                     |
# >> | 切断逃亡                             |  5.02 |                                                                                                                                                                                                                                                                           |
# >> | ルール別対局頻度                     |  3.73 | [{:name=>"10分", :value=>0}, {:name=>"3分", :value=>45}, {:name=>"10秒", :value=>5}]                                                                                                                                                                                      |
# >> | 対振り                               |  3.07 | {:judge_counts=>{"win"=>13, "lose"=>3, "draw"=>2}}                                                                                                                                                                                                                        |
# >> | 投了までの心の準備                   |  3.05 | [{:name=>"10秒未満", :value=>7}]                                                                                                                                                                                                                                          |
# >> | 勝ち                                 |  2.92 | [{:key=>"TORYO", :name=>"投了", :value=>27}, {:key=>"CHECKMATE", :name=>"詰み", :value=>7}, {:key=>"TIMEOUT", :name=>"時間切れ", :value=>5}]                                                                                                                              |
# >> | 居飛車                               |  2.30 | {:judge_counts=>{"win"=>39, "lose"=>8, "draw"=>3}}                                                                                                                                                                                                                        |
# >> | 投了時の平均手数                     |  2.08 |                                                                                                                                                                                                                                                                       108 |
# >> | 1手詰を焦らして悦に入った回数        |  2.07 |                                                                                                                                                                                                                                                                           |
# >> | 対局時間帯                           |  2.05 | [{:name=>"4", :value=>7}, {:name=>"5", :value=>8}, {:name=>"6", :value=>8}, {:name=>"7", :value=>5}, {:name=>"8", :value=>0}, {:name=>"9", :value=>0}, {:name=>"10", :value=>0}, {:name=>"11", :value=>0}, {:name=>"12", :value=>0}, {:name=>"13", :value=>0}, {...       |
# >> | 将棋ウォーズの運営を支える力         |  2.02 |                                                                                                                                                                                                                                                                           |
# >> | 長手数                               |  2.01 | {:judge_counts=>{"lose"=>7, "win"=>21}}                                                                                                                                                                                                                                   |
# >> | 詰ます速度 (1手平均)                 |  2.00 |                                                                                                                                                                                                                                                                      1.86 |
# >> | 平均手数                             |  1.98 |                                                                                                                                                                                                                                                                        89 |
# >> | 短手数                               |  1.97 | {:judge_counts=>{"win"=>17, "draw"=>1, "lose"=>1}}                                                                                                                                                                                                                        |
# >> | 投了せずに放置した回数               |  1.95 |                                                                                                                                                                                                                                                                           |
# >> | 対抗形                               |  1.94 | {:judge_counts=>{"win"=>13, "lose"=>3, "draw"=>2}}                                                                                                                                                                                                                        |
# >> | 急戦                                 |  1.85 | {:judge_counts=>{"win"=>18, "lose"=>3, "draw"=>1}}                                                                                                                                                                                                                        |
# >> | 負け                                 |  1.79 | [{:key=>"TORYO", :name=>"投了", :value=>7}, {:key=>"TIMEOUT", :name=>"時間切れ", :value=>1}]                                                                                                                                                                              |
# >> | 持久戦                               |  1.78 | {:judge_counts=>{"lose"=>5, "win"=>18}}                                                                                                                                                                                                                                   |
# >> | 相振り                               |  1.72 |                                                                                                                                                                                                                                                                           |
# >> | 勝敗別平均手数                       |  1.64 | [{:name=>"勝ち", :value=>89}, {:name=>"負け", :value=>109}]                                                                                                                                                                                                               |
# >> | 連勝                                 |  1.55 |                                                                                                                                                                                                                                                                        12 |
# >> | 相居飛車                             |  1.36 | {:judge_counts=>{"lose"=>5, "win"=>26, "draw"=>1}}                                                                                                                                                                                                                        |
# >> | 振り飛車                             |  1.35 |                                                                                                                                                                                                                                                                           |
# >> | 対戦相手との段級差 (平均)             |  1.17 |                                                                                                                                                                                                                                                                     -1.48 |
# >> | 最長考                          |  0.94 |                                                                                                                                                                                                                                                                        71 |
# >> | 平均思考                             |  0.70 |                                                                                                                                                                                                                                                                       1.5 |
# >> | 右玉度                               |  0.56 | [{:name=>"右玉", :value=>4}, {:name=>"その他", :value=>46}]                                                                                                                                                                                                               |
# >> | 投了までの心の準備 (平均)            |  0.46 |                                                                                                                                                                                                                                                                       2.0 |
# >> | 不屈の闘志                           |  0.26 |                                                                                                                                                                                                                                                                        10 |
# >> | 右玉ファミリー                       |  0.02 | [{:name=>:右玉, :value=>3}, {:name=>:三段右玉, :value=>1}]                                                                                                                                                                                                                |
# >> | 派閥                                 |  0.01 | [{:name=>:居飛車, :value=>50}, {:name=>:振り飛車, :value=>0}]                                                                                                                                                                                                             |
# >> | 棋風 (速度)                          |  0.01 | [{:name=>:急戦, :value=>22}, {:name=>:持久戦, :value=>23}]                                                                                                                                                                                                                |
# >> | 棋風 (手数)                          |  0.01 | [{:name=>:短手数, :value=>19}, {:name=>:長手数, :value=>28}]                                                                                                                                                                                                              |
# >> | 1手詰を焦らして悦に入った時間 (最長) |  0.00 |                                                                                                                                                                                                                                                                           |
# >> | 投了せずに放置した時間 (最長)        |  0.00 |                                                                                                                                                                                                                                                                           |
# >> | テスト                               |  0.00 | [{:name=>"a", :value=>1}, {:name=>"b", :value=>2}, {:name=>"c", :value=>3}, {:name=>"d", :value=>4}, {:name=>"e", :value=>5}]                                                                                                                                             |
# >> | 飛車不成                             |  0.00 |                                                                                                                                                                                                                                                                           |
# >> | 投了せずに放置した頻度               |  0.00 |                                                                                                                                                                                                                                                                           |
# >> | 連敗                                 |  0.00 |                                                                                                                                                                                                                                                                         2 |
# >> | 1手詰を焦らして悦に入った頻度        |  0.00 |                                                                                                                                                                                                                                                                           |
# >> | 投了までの心の準備 (最長)            |  0.00 |                                                                                                                                                                                                                                                                         5 |
# >> | 最長手数                             |  0.00 |                                                                                                                                                                                                                                                                       177 |
# >> |--------------------------------------+-------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
# >> {:onetime_key=>"f2134e096a6cc8e19a3c5c2a2475de0f",
# >>  :sample_max=>50,
# >>  :user=>{:key=>"SugarHuuko", :ban_at=>nil},
# >>  :rule_items=>
# >>   [{:rule_key=>:ten_min, :rule_name=>"10分", :grade_name=>nil},
# >>    {:rule_key=>:three_min, :rule_name=>"3分", :grade_name=>"七段"},
# >>    {:rule_key=>:ten_sec, :rule_name=>"10秒", :grade_name=>"六段"}],
# >>  :judge_counts=>{"win"=>39, "lose"=>8, "draw"=>3},
# >>  :medal_stat=>
# >>   [{:message=>"居飛車党", :method=>"raw", :name=>"⬆️", :type=>nil},
# >>    {:message=>"右玉で勝った", :method=>"raw", :name=>"🌛", :type=>nil},
# >>    {:message=>"UFO銀で勝った", :method=>"raw", :name=>"🛸", :type=>nil},
# >>    {:message=>"大駒全部捨てて勝った", :method=>"raw", :name=>"🧠", :type=>nil},
# >>    {:message=>"10連勝した", :method=>"raw", :name=>"💮", :type=>nil},
# >>    {:message=>"対局放棄と受け取られかねない長考をした", :method=>"raw", :name=>"🚫", :type=>nil},
# >>    {:message=>"開幕千日手をした", :method=>"raw", :name=>"❓", :type=>nil},
# >>    {:message=>"千日手があった", :method=>"raw", :name=>"🍌", :type=>nil}],
# >>  :judge_keys=>
# >>   ["win",
# >>    "win",
# >>    "win",
# >>    "draw",
# >>    "lose",
# >>    "lose",
# >>    "win",
# >>    "win",
# >>    "win",
# >>    "draw",
# >>    "win",
# >>    "win",
# >>    "lose",
# >>    "win",
# >>    "lose",
# >>    "win",
# >>    "lose"],
# >>  :day_items=>
# >>   [{:battled_on=>Tue, 21 May 2024,
# >>     :day_type=>nil,
# >>     :judge_counts=>{:win=>7, :lose=>3}},
# >>    {:battled_on=>Mon, 20 May 2024,
# >>     :day_type=>nil,
# >>     :judge_counts=>{:win=>25, :lose=>4}},
# >>    {:battled_on=>Sun, 19 May 2024,
# >>     :day_type=>:danger,
# >>     :judge_counts=>{:win=>2, :lose=>0}},
# >>    {:battled_on=>Wed, 15 May 2024,
# >>     :day_type=>nil,
# >>     :judge_counts=>{:win=>5, :lose=>1}}],
# >>  :vs_grade_items=>
# >>   [{:grade_name=>"八段", :judge_counts=>{:draw=>2}, :appear_ratio=>0.04},
# >>    {:grade_name=>"七段",
# >>     :judge_counts=>{:lose=>5, :win=>6},
# >>     :appear_ratio=>0.22},
# >>    {:grade_name=>"六段",
# >>     :judge_counts=>{:win=>14, :lose=>1},
# >>     :appear_ratio=>0.3},
# >>    {:grade_name=>"五段",
# >>     :judge_counts=>{:win=>11, :lose=>2},
# >>     :appear_ratio=>0.26},
# >>    {:grade_name=>"四段",
# >>     :judge_counts=>{:win=>6, :draw=>1},
# >>     :appear_ratio=>0.14},
# >>    {:grade_name=>"三段", :judge_counts=>{:win=>1}, :appear_ratio=>0.02},
# >>    {:grade_name=>"9級", :judge_counts=>{:win=>1}, :appear_ratio=>0.02}],
# >>  :my_attack_items=>
# >>   [{:tag=>{"name"=>"力戦", "count"=>17},
# >>     :appear_ratio=>0.34,
# >>     :judge_counts=>{"win"=>13, "lose"=>3, "draw"=>1}},
# >>    {:tag=>{"name"=>"原始棒銀", "count"=>5},
# >>     :appear_ratio=>0.1,
# >>     :judge_counts=>{"win"=>5}},
# >>    {:tag=>{"name"=>"UFO銀", "count"=>5},
# >>     :appear_ratio=>0.1,
# >>     :judge_counts=>{"win"=>5}},
# >>    {:tag=>{"name"=>"角交換型", "count"=>3},
# >>     :appear_ratio=>0.06,
# >>     :judge_counts=>{"win"=>3}},
# >>    {:tag=>{"name"=>"▲４五歩早仕掛け", "count"=>2},
# >>     :appear_ratio=>0.04,
# >>     :judge_counts=>{"win"=>2}},
# >>    {:tag=>{"name"=>"銀雲雀", "count"=>1},
# >>     :appear_ratio=>0.02,
# >>     :judge_counts=>{"win"=>1}},
# >>    {:tag=>{"name"=>"対振り持久戦", "count"=>1},
# >>     :appear_ratio=>0.02,
# >>     :judge_counts=>{"win"=>1}},
# >>    {:tag=>{"name"=>"相掛かり", "count"=>1},
# >>     :appear_ratio=>0.02,
# >>     :judge_counts=>{"win"=>1}},
# >>    {:tag=>{"name"=>"△３三角型空中戦法", "count"=>1},
# >>     :appear_ratio=>0.02,
# >>     :judge_counts=>{"win"=>1}},
# >>    {:tag=>{"name"=>"角換わり", "count"=>1},
# >>     :appear_ratio=>0.02,
# >>     :judge_counts=>{"win"=>1}},
# >>    {:tag=>{"name"=>"手得角交換型", "count"=>1},
# >>     :appear_ratio=>0.02,
# >>     :judge_counts=>{"win"=>1}},
# >>    {:tag=>{"name"=>"地下鉄飛車", "count"=>1},
# >>     :appear_ratio=>0.02,
# >>     :judge_counts=>{"win"=>1}},
# >>    {:tag=>{"name"=>"へなちょこ急戦", "count"=>1},
# >>     :appear_ratio=>0.02,
# >>     :judge_counts=>{"draw"=>1}}],
# >>  :vs_attack_items=>
# >>   [{:tag=>{"name"=>"力戦", "count"=>12},
# >>     :appear_ratio=>0.24,
# >>     :judge_counts=>{"win"=>9, "lose"=>2, "draw"=>1}},
# >>    {:tag=>{"name"=>"5筋位取り中飛車", "count"=>5},
# >>     :appear_ratio=>0.1,
# >>     :judge_counts=>{"lose"=>1, "win"=>4}},
# >>    {:tag=>{"name"=>"角交換振り飛車", "count"=>5},
# >>     :appear_ratio=>0.1,
# >>     :judge_counts=>{"lose"=>nil, "draw"=>1, "win"=>4}},
# >>    {:tag=>{"name"=>"四間飛車", "count"=>4},
# >>     :appear_ratio=>0.08,
# >>     :judge_counts=>{"lose"=>1, "win"=>3}},
# >>    {:tag=>{"name"=>"三間飛車", "count"=>4},
# >>     :appear_ratio=>0.08,
# >>     :judge_counts=>{"lose"=>nil, "draw"=>1, "win"=>3}},
# >>    {:tag=>{"name"=>"新嬉野流", "count"=>4},
# >>     :appear_ratio=>0.08,
# >>     :judge_counts=>{"lose"=>nil, "win"=>4}},
# >>    {:tag=>{"name"=>"棒銀", "count"=>3},
# >>     :appear_ratio=>0.06,
# >>     :judge_counts=>{"lose"=>nil, "win"=>3}},
# >>    {:tag=>{"name"=>"向かい飛車", "count"=>3},
# >>     :appear_ratio=>0.06,
# >>     :judge_counts=>{"lose"=>nil, "win"=>3}},
# >>    {:tag=>{"name"=>"角交換型", "count"=>3},
# >>     :appear_ratio=>0.06,
# >>     :judge_counts=>{"lose"=>nil, "win"=>3}},
# >>    {:tag=>{"name"=>"地下鉄飛車", "count"=>2},
# >>     :appear_ratio=>0.04,
# >>     :judge_counts=>{"lose"=>nil, "win"=>2}},
# >>    {:tag=>{"name"=>"原始棒銀", "count"=>2},
# >>     :appear_ratio=>0.04,
# >>     :judge_counts=>{"win"=>nil, "lose"=>2}},
# >>    {:tag=>{"name"=>"UFO銀", "count"=>2},
# >>     :appear_ratio=>0.04,
# >>     :judge_counts=>{"win"=>nil, "lose"=>2}},
# >>    {:tag=>{"name"=>"右四間飛車", "count"=>2},
# >>     :appear_ratio=>0.04,
# >>     :judge_counts=>{"win"=>1, "lose"=>1}},
# >>    {:tag=>{"name"=>"ゴキゲン中飛車", "count"=>1},
# >>     :appear_ratio=>0.02,
# >>     :judge_counts=>{"lose"=>nil, "win"=>1}},
# >>    {:tag=>{"name"=>"四間飛車ミレニアム", "count"=>1},
# >>     :appear_ratio=>0.02,
# >>     :judge_counts=>{"lose"=>nil, "win"=>1}},
# >>    {:tag=>{"name"=>"相掛かり", "count"=>1},
# >>     :appear_ratio=>0.02,
# >>     :judge_counts=>{"lose"=>nil, "win"=>1}},
# >>    {:tag=>{"name"=>"相掛かり棒銀", "count"=>1},
# >>     :appear_ratio=>0.02,
# >>     :judge_counts=>{"lose"=>nil, "win"=>1}},
# >>    {:tag=>{"name"=>"横歩取り", "count"=>1},
# >>     :appear_ratio=>0.02,
# >>     :judge_counts=>{"lose"=>nil, "win"=>1}},
# >>    {:tag=>{"name"=>"腰掛け銀", "count"=>1},
# >>     :appear_ratio=>0.02,
# >>     :judge_counts=>{"lose"=>nil, "win"=>1}},
# >>    {:tag=>{"name"=>"角換わり", "count"=>1},
# >>     :appear_ratio=>0.02,
# >>     :judge_counts=>{"lose"=>nil, "win"=>1}},
# >>    {:tag=>{"name"=>"手損角交換型", "count"=>1},
# >>     :appear_ratio=>0.02,
# >>     :judge_counts=>{"lose"=>nil, "win"=>1}},
# >>    {:tag=>{"name"=>"鬼殺し向かい飛車", "count"=>1},
# >>     :appear_ratio=>0.02,
# >>     :judge_counts=>{"lose"=>nil, "win"=>1}}],
# >>  :my_defense_items=>
# >>   [{:tag=>{"name"=>"居玉", "count"=>11},
# >>     :appear_ratio=>0.22,
# >>     :judge_counts=>{"lose"=>2, "win"=>9}},
# >>    {:tag=>{"name"=>"舟囲い", "count"=>9},
# >>     :appear_ratio=>0.18,
# >>     :judge_counts=>{"win"=>6, "lose"=>2, "draw"=>1}},
# >>    {:tag=>{"name"=>"新型雁木", "count"=>6},
# >>     :appear_ratio=>0.12,
# >>     :judge_counts=>{"win"=>5, "lose"=>1}},
# >>    {:tag=>{"name"=>"右玉", "count"=>3},
# >>     :appear_ratio=>0.06,
# >>     :judge_counts=>{"lose"=>1, "win"=>2}},
# >>    {:tag=>{"name"=>"居飛車金美濃", "count"=>2},
# >>     :appear_ratio=>0.04,
# >>     :judge_counts=>{"win"=>2}},
# >>    {:tag=>{"name"=>"カブト囲い", "count"=>1},
# >>     :appear_ratio=>0.02,
# >>     :judge_counts=>{"lose"=>1}},
# >>    {:tag=>{"name"=>"箱入り娘", "count"=>1},
# >>     :appear_ratio=>0.02,
# >>     :judge_counts=>{"win"=>1}},
# >>    {:tag=>{"name"=>"ツノ銀雁木", "count"=>1},
# >>     :appear_ratio=>0.02,
# >>     :judge_counts=>{"lose"=>1}},
# >>    {:tag=>{"name"=>"オールド雁木", "count"=>1},
# >>     :appear_ratio=>0.02,
# >>     :judge_counts=>{"win"=>1}},
# >>    {:tag=>{"name"=>"へこみ矢倉", "count"=>1},
# >>     :appear_ratio=>0.02,
# >>     :judge_counts=>{"lose"=>1}},
# >>    {:tag=>{"name"=>"串カツ囲い", "count"=>1},
# >>     :appear_ratio=>0.02,
# >>     :judge_counts=>{"lose"=>1}},
# >>    {:tag=>{"name"=>"金盾囲い", "count"=>1},
# >>     :appear_ratio=>0.02,
# >>     :judge_counts=>{"draw"=>1}},
# >>    {:tag=>{"name"=>"三段右玉", "count"=>1},
# >>     :appear_ratio=>0.02,
# >>     :judge_counts=>{"win"=>1}}],
# >>  :vs_defense_items=>
# >>   [{:tag=>{"name"=>"居玉", "count"=>8},
# >>     :appear_ratio=>0.16,
# >>     :judge_counts=>{"win"=>7, "lose"=>1}},
# >>    {:tag=>{"name"=>"高美濃囲い", "count"=>5},
# >>     :appear_ratio=>0.1,
# >>     :judge_counts=>{"lose"=>nil, "win"=>5}},
# >>    {:tag=>{"name"=>"中住まい", "count"=>2},
# >>     :appear_ratio=>0.04,
# >>     :judge_counts=>{"lose"=>nil, "win"=>2}},
# >>    {:tag=>{"name"=>"右玉", "count"=>2},
# >>     :appear_ratio=>0.04,
# >>     :judge_counts=>{"lose"=>nil, "win"=>2}},
# >>    {:tag=>{"name"=>"振り飛車ミレニアム", "count"=>1},
# >>     :appear_ratio=>0.02,
# >>     :judge_counts=>{"lose"=>nil, "win"=>1}},
# >>    {:tag=>{"name"=>"片美濃囲い", "count"=>1},
# >>     :appear_ratio=>0.02,
# >>     :judge_counts=>{"lose"=>nil, "win"=>1}},
# >>    {:tag=>{"name"=>"銀冠", "count"=>1},
# >>     :appear_ratio=>0.02,
# >>     :judge_counts=>{"lose"=>nil, "win"=>1}},
# >>    {:tag=>{"name"=>"ツノ銀雁木", "count"=>1},
# >>     :appear_ratio=>0.02,
# >>     :judge_counts=>{"win"=>nil, "lose"=>1}},
# >>    {:tag=>{"name"=>"木村美濃", "count"=>1},
# >>     :appear_ratio=>0.02,
# >>     :judge_counts=>{"win"=>nil, "lose"=>1}},
# >>    {:tag=>{"name"=>"右矢倉", "count"=>1},
# >>     :appear_ratio=>0.02,
# >>     :judge_counts=>{"lose"=>nil, "win"=>1}},
# >>    {:tag=>{"name"=>"新型雁木", "count"=>1},
# >>     :appear_ratio=>0.02,
# >>     :judge_counts=>{"lose"=>nil, "win"=>1}},
# >>    {:tag=>{"name"=>"カブト囲い", "count"=>1},
# >>     :appear_ratio=>0.02,
# >>     :judge_counts=>{"lose"=>nil, "win"=>1}},
# >>    {:tag=>{"name"=>"振り飛車穴熊", "count"=>1},
# >>     :appear_ratio=>0.02,
# >>     :judge_counts=>{"win"=>nil, "lose"=>1}},
# >>    {:tag=>{"name"=>"早囲い", "count"=>1},
# >>     :appear_ratio=>0.02,
# >>     :judge_counts=>{"win"=>nil, "lose"=>1}},
# >>    {:tag=>{"name"=>"金矢倉", "count"=>1},
# >>     :appear_ratio=>0.02,
# >>     :judge_counts=>{"lose"=>nil, "win"=>1}},
# >>    {:tag=>{"name"=>"美濃囲い", "count"=>1},
# >>     :appear_ratio=>0.02,
# >>     :judge_counts=>{"lose"=>nil, "win"=>1}}],
# >>  :etc_items=>
# >>   [{:name=>"テスト",
# >>     :chart_type=>:pie,
# >>     :chart_options=>{:pie_type=>:is_many_values},
# >>     :body=>
# >>      [{:name=>"a", :value=>1},
# >>       {:name=>"b", :value=>2},
# >>       {:name=>"c", :value=>3},
# >>       {:name=>"d", :value=>4},
# >>       {:name=>"e", :value=>5}]},
# >>    {:name=>"ids_count", :chart_type=>:simple, :chart_options=>{}, :body=>50},
# >>    {:name=>"切断逃亡",
# >>     :chart_type=>:simple,
# >>     :chart_options=>{:simple_type=>:numeric_with_unit, :unit=>"回"},
# >>     :body=>nil},
# >>    {:name=>"角不成",
# >>     :chart_type=>:simple,
# >>     :chart_options=>{:simple_type=>:numeric_with_unit, :unit=>"回"},
# >>     :body=>nil},
# >>    {:name=>"飛車不成",
# >>     :chart_type=>:simple,
# >>     :chart_options=>{:simple_type=>:numeric_with_unit, :unit=>"回"},
# >>     :body=>nil},
# >>    {:name=>"棋風",
# >>     :chart_type=>:pie,
# >>     :chart_options=>{:pie_type=>:is_many_values},
# >>     :body=>
# >>      [{:name=>"王道", :value=>21},
# >>       {:name=>"準王道", :value=>8},
# >>       {:name=>"準変態", :value=>14},
# >>       {:name=>"変態", :value=>7}]},
# >>    {:name=>"派閥",
# >>     :chart_type=>:pie,
# >>     :chart_options=>{:pie_type=>:is_many_values},
# >>     :body=>[{:name=>:居飛車, :value=>50}, {:name=>:振り飛車, :value=>0}]},
# >>    {:name=>"居飛車",
# >>     :chart_type=>:win_lose_circle,
# >>     :chart_options=>
# >>      {:click_method=>:win_lose_with_tag_click_handle, :tag=>"居飛車"},
# >>     :body=>{:judge_counts=>{"win"=>39, "lose"=>8, "draw"=>3}}},
# >>    {:name=>"振り飛車",
# >>     :chart_type=>:win_lose_circle,
# >>     :chart_options=>
# >>      {:click_method=>:win_lose_with_tag_click_handle, :tag=>"振り飛車"},
# >>     :body=>nil},
# >>    {:name=>"相居飛車",
# >>     :chart_type=>:win_lose_circle,
# >>     :chart_options=>
# >>      {:click_method=>:win_lose_with_tag_click_handle, :tag=>"相居飛車"},
# >>     :body=>{:judge_counts=>{"lose"=>5, "win"=>26, "draw"=>1}}},
# >>    {:name=>"対振り",
# >>     :chart_type=>:win_lose_circle,
# >>     :chart_options=>
# >>      {:click_method=>:win_lose_with_tag_click_handle, :tag=>"対振り"},
# >>     :body=>{:judge_counts=>{"win"=>13, "lose"=>3, "draw"=>2}}},
# >>    {:name=>"対抗形",
# >>     :chart_type=>:win_lose_circle,
# >>     :chart_options=>
# >>      {:click_method=>:win_lose_with_tag_click_handle, :tag=>"対抗形"},
# >>     :body=>{:judge_counts=>{"win"=>13, "lose"=>3, "draw"=>2}}},
# >>    {:name=>"相振り",
# >>     :chart_type=>:win_lose_circle,
# >>     :chart_options=>
# >>      {:click_method=>:win_lose_with_tag_click_handle, :tag=>"相振り"},
# >>     :body=>nil},
# >>    {:name=>"棋風 (速度)",
# >>     :chart_type=>:pie,
# >>     :chart_options=>{:pie_type=>:is_many_values},
# >>     :body=>[{:name=>:急戦, :value=>22}, {:name=>:持久戦, :value=>23}]},
# >>    {:name=>"急戦",
# >>     :chart_type=>:win_lose_circle,
# >>     :chart_options=>
# >>      {:click_method=>:win_lose_with_tag_click_handle, :tag=>"急戦"},
# >>     :body=>{:judge_counts=>{"win"=>18, "lose"=>3, "draw"=>1}}},
# >>    {:name=>"持久戦",
# >>     :chart_type=>:win_lose_circle,
# >>     :chart_options=>
# >>      {:click_method=>:win_lose_with_tag_click_handle, :tag=>"持久戦"},
# >>     :body=>{:judge_counts=>{"lose"=>5, "win"=>18}}},
# >>    {:name=>"棋風 (手数)",
# >>     :chart_type=>:pie,
# >>     :chart_options=>{:pie_type=>:is_many_values},
# >>     :body=>[{:name=>:短手数, :value=>19}, {:name=>:長手数, :value=>28}]},
# >>    {:name=>"短手数",
# >>     :chart_type=>:win_lose_circle,
# >>     :chart_options=>
# >>      {:click_method=>:win_lose_with_tag_click_handle, :tag=>"短手数"},
# >>     :body=>{:judge_counts=>{"win"=>17, "draw"=>1, "lose"=>1}}},
# >>    {:name=>"長手数",
# >>     :chart_type=>:win_lose_circle,
# >>     :chart_options=>
# >>      {:click_method=>:win_lose_with_tag_click_handle, :tag=>"長手数"},
# >>     :body=>{:judge_counts=>{"lose"=>7, "win"=>21}}},
# >>    {:name=>"ルール別対局頻度",
# >>     :chart_type=>:pie,
# >>     :chart_options=>{:pie_type=>:is_many_values},
# >>     :body=>
# >>      [{:name=>"10分", :value=>0},
# >>       {:name=>"3分", :value=>45},
# >>       {:name=>"10秒", :value=>5}]},
# >>    {:name=>"対局モード",
# >>     :chart_type=>:pie,
# >>     :chart_options=>{:pie_type=>:is_many_values},
# >>     :body=>
# >>      [{:name=>"野良", :value=>50},
# >>       {:name=>"友達", :value=>0},
# >>       {:name=>"指導", :value=>0}]},
# >>    {:name=>"連勝",
# >>     :chart_type=>:simple,
# >>     :chart_options=>{:simple_type=>:numeric_with_unit, :unit=>"連勝"},
# >>     :body=>12},
# >>    {:name=>"連敗",
# >>     :chart_type=>:simple,
# >>     :chart_options=>{:simple_type=>:numeric_with_unit, :unit=>"連敗"},
# >>     :body=>2},
# >>    {:name=>"勝敗別平均手数",
# >>     :chart_type=>:pie,
# >>     :chart_options=>{:pie_type=>:is_many_values},
# >>     :body=>[{:name=>"勝ち", :value=>89}, {:name=>"負け", :value=>109}],
# >>     :bottom_message=>"負けそうなときも粘り強く指すタイプ"},
# >>    {:name=>"不屈の闘志", :chart_type=>:simple, :chart_options=>{}, :body=>10},
# >>    {:name=>"平均手数",
# >>     :chart_type=>:simple,
# >>     :chart_options=>{:simple_type=>:numeric_with_unit, :unit=>"手"},
# >>     :body=>89},
# >>    {:name=>"最長手数",
# >>     :chart_type=>:simple,
# >>     :chart_options=>{:simple_type=>:numeric_with_unit, :unit=>"手"},
# >>     :body=>177},
# >>    {:name=>"投了時の平均手数",
# >>     :chart_type=>:simple,
# >>     :chart_options=>{:simple_type=>:numeric_with_unit, :unit=>"手"},
# >>     :body=>108},
# >>    {:name=>"投了せずに放置した回数",
# >>     :chart_type=>:simple,
# >>     :chart_options=>{:simple_type=>:numeric_with_unit, :unit=>"回"},
# >>     :body=>nil},
# >>    {:name=>"投了せずに放置した時間 (最長)",
# >>     :chart_type=>:simple,
# >>     :chart_options=>{:simple_type=>:second},
# >>     :body=>nil},
# >>    {:name=>"投了せずに放置した頻度",
# >>     :chart_type=>:pie,
# >>     :chart_options=>{:pie_type=>:is_many_values},
# >>     :body=>nil},
# >>    {:name=>"1日の平均対局数",
# >>     :chart_type=>:simple,
# >>     :chart_options=>{:simple_type=>:numeric_with_unit, :unit=>"局"},
# >>     :body=>12.5},
# >>    {:name=>"対局時間帯",
# >>     :chart_type=>:bar,
# >>     :chart_options=>{:bar_type=>:is_default},
# >>     :body=>
# >>      [{:name=>"4", :value=>7},
# >>       {:name=>"5", :value=>8},
# >>       {:name=>"6", :value=>8},
# >>       {:name=>"7", :value=>5},
# >>       {:name=>"8", :value=>0},
# >>       {:name=>"9", :value=>0},
# >>       {:name=>"10", :value=>0},
# >>       {:name=>"11", :value=>0},
# >>       {:name=>"12", :value=>0},
# >>       {:name=>"13", :value=>0},
# >>       {:name=>"14", :value=>0},
# >>       {:name=>"15", :value=>0},
# >>       {:name=>"16", :value=>0},
# >>       {:name=>"17", :value=>0},
# >>       {:name=>"18", :value=>0},
# >>       {:name=>"19", :value=>0},
# >>       {:name=>"20", :value=>0},
# >>       {:name=>"21", :value=>0},
# >>       {:name=>"22", :value=>6},
# >>       {:name=>"23", :value=>2},
# >>       {:name=>"0", :value=>8},
# >>       {:name=>"1", :value=>6},
# >>       {:name=>"2", :value=>0},
# >>       {:name=>"3", :value=>0}]},
# >>    {:name=>"勝ち",
# >>     :chart_type=>:pie,
# >>     :chart_options=>{:pie_type=>:is_many_values},
# >>     :body=>
# >>      [{:key=>"TORYO", :name=>"投了", :value=>27},
# >>       {:key=>"CHECKMATE", :name=>"詰み", :value=>7},
# >>       {:key=>"TIMEOUT", :name=>"時間切れ", :value=>5}]},
# >>    {:name=>"1手詰を焦らして悦に入った回数",
# >>     :chart_type=>:simple,
# >>     :chart_options=>{:simple_type=>:numeric_with_unit, :unit=>"回"},
# >>     :body=>nil},
# >>    {:name=>"1手詰を焦らして悦に入った時間 (最長)",
# >>     :chart_type=>:simple,
# >>     :chart_options=>{:simple_type=>:second},
# >>     :body=>nil},
# >>    {:name=>"1手詰を焦らして悦に入った頻度",
# >>     :chart_type=>:pie,
# >>     :chart_options=>{:pie_type=>:is_many_values},
# >>     :body=>nil},
# >>    {:name=>"負け",
# >>     :chart_type=>:pie,
# >>     :chart_options=>{:pie_type=>:is_many_values},
# >>     :body=>
# >>      [{:key=>"TORYO", :name=>"投了", :value=>7},
# >>       {:key=>"TIMEOUT", :name=>"時間切れ", :value=>1}]},
# >>    {:name=>"投了までの心の準備",
# >>     :chart_type=>:pie,
# >>     :chart_options=>{:pie_type=>:is_many_values},
# >>     :body=>[{:name=>"10秒未満", :value=>7}]},
# >>    {:name=>"投了までの心の準備 (平均)",
# >>     :chart_type=>:simple,
# >>     :chart_options=>{:simple_type=>:second},
# >>     :body=>2.0},
# >>    {:name=>"投了までの心の準備 (最長)",
# >>     :chart_type=>:simple,
# >>     :chart_options=>{:simple_type=>:second},
# >>     :body=>5},
# >>    {:name=>"最長考",
# >>     :chart_type=>:simple,
# >>     :chart_options=>{:simple_type=>:second},
# >>     :body=>71},
# >>    {:name=>"平均思考",
# >>     :chart_type=>:simple,
# >>     :chart_options=>{:simple_type=>:second},
# >>     :body=>1.5},
# >>    {:name=>"詰ます速度 (1手平均)",
# >>     :chart_type=>:simple,
# >>     :chart_options=>{:simple_type=>:second},
# >>     :body=>1.86},
# >>    {:name=>"駒の使用率",
# >>     :chart_type=>:bar,
# >>     :chart_options=>
# >>      {:bar_type=>:is_default, :tategaki_p=>true, :value_format=>:percentage},
# >>     :body=>
# >>      [{:name=>"玉", :value=>0.08155080213903744},
# >>       {:name=>"飛", :value=>0.08422459893048129},
# >>       {:name=>"角", :value=>0.09180035650623886},
# >>       {:name=>"金", :value=>0.10338680926916222},
# >>       {:name=>"銀", :value=>0.16310160427807488},
# >>       {:name=>"桂", :value=>0.08600713012477719},
# >>       {:name=>"香", :value=>0.01693404634581105},
# >>       {:name=>"歩", :value=>0.3092691622103387},
# >>       {:name=>"龍", :value=>0.027629233511586453},
# >>       {:name=>"馬", :value=>0.021836007130124777},
# >>       {:name=>"全", :value=>0.0022281639928698753},
# >>       {:name=>"圭", :value=>0.0035650623885918},
# >>       {:name=>"杏", :value=>0.0035650623885918},
# >>       {:name=>"と", :value=>0.004901960784313725}]},
# >>    {:name=>"対戦相手との段級差 (平均)",
# >>     :chart_type=>:simple,
# >>     :chart_options=>{:simple_type=>:raw},
# >>     :body=>-1.48},
# >>    {:name=>"右玉度",
# >>     :chart_type=>:pie,
# >>     :chart_options=>{:pie_type=>:is_pair_values},
# >>     :body=>[{:name=>"右玉", :value=>4}, {:name=>"その他", :value=>46}]},
# >>    {:name=>"右玉ファミリー",
# >>     :chart_type=>:pie,
# >>     :chart_options=>{:pie_type=>:is_many_values},
# >>     :body=>[{:name=>:右玉, :value=>3}, {:name=>:三段右玉, :value=>1}]},
# >>    {:name=>"将棋ウォーズの運営を支える力",
# >>     :chart_type=>:pie,
# >>     :chart_options=>{:pie_type=>:is_pair_values},
# >>     :body=>nil}],
# >>  :debug_hash=>
# >>   {"対象サンプル数"=>50,
# >>    "勝ち数"=>39,
# >>    "負け数"=>8,
# >>    "勝率"=>0.78,
# >>    "引き分け率"=>0.02,
# >>    "切れ負け率(分母:負け数)"=>0.125,
# >>    "切断率(分母:負け数)"=>0.0,
# >>    "居飛車率"=>1.0,
# >>    "振り飛車率"=>0.0,
# >>    "居玉勝率"=>0.18,
# >>    "アヒル囲い率"=>0.0,
# >>    "嬉野流率"=>0.0,
# >>    "棋風"=>
# >>     {:rarity_key_SSR=>0.14,
# >>      :rarity_key_SR=>0.28,
# >>      :rarity_key_R=>0.16,
# >>      :rarity_key_N=>0.42},
# >>    "1手詰を詰まさないでじらした割合"=>0.0,
# >>    "絶対投了しない率"=>0.0,
# >>    "大長考または放置率"=>0.02,
# >>    "棋神降臨疑惑対局数"=>0,
# >>    "長考または放置率"=>0.02,
# >>    "最大連勝連敗"=>{:lose=>2, :win=>12, :draw=>1},
# >>    "タグの重み"=>
# >>     {:力戦=>17,
# >>      :居飛車=>50,
# >>      :カブト囲い=>1,
# >>      :箱入り娘=>1,
# >>      :銀雲雀=>1,
# >>      :舟囲い=>9,
# >>      :居飛車金美濃=>2,
# >>      :対振り持久戦=>1,
# >>      :新型雁木=>6,
# >>      :相掛かり=>1,
# >>      :▲４五歩早仕掛け=>2,
# >>      :居玉=>11,
# >>      :△３三角型空中戦法=>1,
# >>      :ツノ銀雁木=>1,
# >>      :オールド雁木=>1,
# >>      :原始棒銀=>5,
# >>      :UFO銀=>5,
# >>      :へこみ矢倉=>1,
# >>      :串カツ囲い=>1,
# >>      :金盾囲い=>1,
# >>      :角交換型=>3,
# >>      :角換わり=>1,
# >>      :右玉=>3,
# >>      :手得角交換型=>1,
# >>      :地下鉄飛車=>1,
# >>      :三段右玉=>1,
# >>      :へなちょこ急戦=>1,
# >>      :垂れ歩=>12,
# >>      :対振り=>18,
# >>      :対抗形=>18,
# >>      :持久戦=>23,
# >>      :短手数=>19,
# >>      :急戦=>22,
# >>      :相居飛車=>32,
# >>      :長手数=>28,
# >>      :大駒コンプリート=>7,
# >>      :継ぎ桂=>3,
# >>      :相居玉=>6,
# >>      :腹銀=>1,
# >>      :ふんどしの桂=>5,
# >>      :桂頭の銀=>1,
# >>      :割り打ちの銀=>1,
# >>      :大駒全消失=>1,
# >>      :背水の陣=>1}},
# >>  :streak_stat=>{:lose=>2, :win=>12, :draw=>1}}
# >> {"onetime_key"=>"ffd203de32a6dd35de0a182458f2d86d",
# >>  "sample_max"=>50,
# >>  "user"=>{"key"=>"user957292", "ban_at"=>nil},
# >>  "rule_items"=>
# >>   [{"rule_key"=>"ten_min", "rule_name"=>"10分", "grade_name"=>"30級"},
# >>    {"rule_key"=>"three_min", "rule_name"=>"3分", "grade_name"=>nil},
# >>    {"rule_key"=>"ten_sec", "rule_name"=>"10秒", "grade_name"=>nil}],
# >>  "judge_counts"=>{"win"=>1},
# >>  "medal_stat"=>
# >>   [{"message"=>"居飛車党", "method"=>"raw", "name"=>"⬆️", "type"=>nil},
# >>    {"message"=>"嬉野流で勝った", "method"=>"raw", "name"=>"↗️", "type"=>nil}],
# >>  "judge_keys"=>["win"],
# >>  "day_items"=>
# >>   [{"battled_on"=>"2024-05-31",
# >>     "day_type"=>nil,
# >>     "judge_counts"=>{"win"=>1, "lose"=>0}}],
# >>  "vs_grade_items"=>
# >>   [{"grade_name"=>"30級", "judge_counts"=>{"win"=>1}, "appear_ratio"=>1.0}],
# >>  "my_attack_items"=>
# >>   [{"tag"=>{"name"=>"新嬉野流", "count"=>1},
# >>     "appear_ratio"=>1.0,
# >>     "judge_counts"=>{"win"=>1}}],
# >>  "vs_attack_items"=>
# >>   [{"tag"=>{"name"=>"2手目△３ニ飛戦法", "count"=>1},
# >>     "appear_ratio"=>1.0,
# >>     "judge_counts"=>{"lose"=>nil, "win"=>1}}],
# >>  "my_defense_items"=>[],
# >>  "vs_defense_items"=>[],
# >>  "etc_items"=>
# >>   [{"name"=>"テスト",
# >>     "chart_type"=>"pie",
# >>     "chart_options"=>{"pie_type"=>"is_many_values"},
# >>     "body"=>
# >>      [{"name"=>"a", "value"=>1},
# >>       {"name"=>"b", "value"=>2},
# >>       {"name"=>"c", "value"=>3},
# >>       {"name"=>"d", "value"=>4},
# >>       {"name"=>"e", "value"=>5}]},
# >>    {"name"=>"ids_count",
# >>     "chart_type"=>"simple",
# >>     "chart_options"=>{},
# >>     "body"=>1},
# >>    {"name"=>"切断逃亡",
# >>     "chart_type"=>"simple",
# >>     "chart_options"=>{"simple_type"=>"numeric_with_unit", "unit"=>"回"},
# >>     "body"=>nil},
# >>    {"name"=>"角不成",
# >>     "chart_type"=>"simple",
# >>     "chart_options"=>{"simple_type"=>"numeric_with_unit", "unit"=>"回"},
# >>     "body"=>nil},
# >>    {"name"=>"飛車不成",
# >>     "chart_type"=>"simple",
# >>     "chart_options"=>{"simple_type"=>"numeric_with_unit", "unit"=>"回"},
# >>     "body"=>nil},
# >>    {"name"=>"棋風",
# >>     "chart_type"=>"pie",
# >>     "chart_options"=>{"pie_type"=>"is_many_values"},
# >>     "body"=>
# >>      [{"name"=>"王道", "value"=>0},
# >>       {"name"=>"準王道", "value"=>1},
# >>       {"name"=>"準変態", "value"=>0},
# >>       {"name"=>"変態", "value"=>0}]},
# >>    {"name"=>"派閥",
# >>     "chart_type"=>"pie",
# >>     "chart_options"=>{"pie_type"=>"is_many_values"},
# >>     "body"=>[{"name"=>"居飛車", "value"=>1}, {"name"=>"振り飛車", "value"=>0}]},
# >>    {"name"=>"居飛車",
# >>     "chart_type"=>"win_lose_circle",
# >>     "chart_options"=>
# >>      {"click_method"=>"win_lose_with_tag_click_handle", "tag"=>"居飛車"},
# >>     "body"=>{"judge_counts"=>{"win"=>1}}},
# >>    {"name"=>"振り飛車",
# >>     "chart_type"=>"win_lose_circle",
# >>     "chart_options"=>
# >>      {"click_method"=>"win_lose_with_tag_click_handle", "tag"=>"振り飛車"},
# >>     "body"=>nil},
# >>    {"name"=>"相居飛車",
# >>     "chart_type"=>"win_lose_circle",
# >>     "chart_options"=>
# >>      {"click_method"=>"win_lose_with_tag_click_handle", "tag"=>"相居飛車"},
# >>     "body"=>nil},
# >>    {"name"=>"対振り",
# >>     "chart_type"=>"win_lose_circle",
# >>     "chart_options"=>
# >>      {"click_method"=>"win_lose_with_tag_click_handle", "tag"=>"対振り"},
# >>     "body"=>{"judge_counts"=>{"win"=>1}}},
# >>    {"name"=>"対抗形",
# >>     "chart_type"=>"win_lose_circle",
# >>     "chart_options"=>
# >>      {"click_method"=>"win_lose_with_tag_click_handle", "tag"=>"対抗形"},
# >>     "body"=>{"judge_counts"=>{"win"=>1}}},
# >>    {"name"=>"相振り",
# >>     "chart_type"=>"win_lose_circle",
# >>     "chart_options"=>
# >>      {"click_method"=>"win_lose_with_tag_click_handle", "tag"=>"相振り"},
# >>     "body"=>nil},
# >>    {"name"=>"棋風 (速度)",
# >>     "chart_type"=>"pie",
# >>     "chart_options"=>{"pie_type"=>"is_many_values"},
# >>     "body"=>nil},
# >>    {"name"=>"急戦",
# >>     "chart_type"=>"win_lose_circle",
# >>     "chart_options"=>
# >>      {"click_method"=>"win_lose_with_tag_click_handle", "tag"=>"急戦"},
# >>     "body"=>nil},
# >>    {"name"=>"持久戦",
# >>     "chart_type"=>"win_lose_circle",
# >>     "chart_options"=>
# >>      {"click_method"=>"win_lose_with_tag_click_handle", "tag"=>"持久戦"},
# >>     "body"=>nil},
# >>    {"name"=>"棋風 (手数)",
# >>     "chart_type"=>"pie",
# >>     "chart_options"=>{"pie_type"=>"is_many_values"},
# >>     "body"=>nil},
# >>    {"name"=>"短手数",
# >>     "chart_type"=>"win_lose_circle",
# >>     "chart_options"=>
# >>      {"click_method"=>"win_lose_with_tag_click_handle", "tag"=>"短手数"},
# >>     "body"=>nil},
# >>    {"name"=>"長手数",
# >>     "chart_type"=>"win_lose_circle",
# >>     "chart_options"=>
# >>      {"click_method"=>"win_lose_with_tag_click_handle", "tag"=>"長手数"},
# >>     "body"=>nil},
# >>    {"name"=>"ルール別対局頻度",
# >>     "chart_type"=>"pie",
# >>     "chart_options"=>{"pie_type"=>"is_many_values"},
# >>     "body"=>
# >>      [{"name"=>"10分", "value"=>1},
# >>       {"name"=>"3分", "value"=>0},
# >>       {"name"=>"10秒", "value"=>0}]},
# >>    {"name"=>"対局モード",
# >>     "chart_type"=>"pie",
# >>     "chart_options"=>{"pie_type"=>"is_many_values"},
# >>     "body"=>
# >>      [{"name"=>"野良", "value"=>1},
# >>       {"name"=>"友達", "value"=>0},
# >>       {"name"=>"指導", "value"=>0}]},
# >>    {"name"=>"連勝",
# >>     "chart_type"=>"simple",
# >>     "chart_options"=>{"simple_type"=>"numeric_with_unit", "unit"=>"連勝"},
# >>     "body"=>1},
# >>    {"name"=>"連敗",
# >>     "chart_type"=>"simple",
# >>     "chart_options"=>{"simple_type"=>"numeric_with_unit", "unit"=>"連敗"},
# >>     "body"=>nil},
# >>    {"name"=>"勝敗別平均手数",
# >>     "chart_type"=>"pie",
# >>     "chart_options"=>{"pie_type"=>"is_many_values"},
# >>     "body"=>[{"name"=>"勝ち", "value"=>5}, {"name"=>"負け", "value"=>0}],
# >>     "bottom_message"=>nil},
# >>    {"name"=>"不屈の闘志", "chart_type"=>"simple", "chart_options"=>{}, "body"=>nil},
# >>    {"name"=>"平均手数",
# >>     "chart_type"=>"simple",
# >>     "chart_options"=>{"simple_type"=>"numeric_with_unit", "unit"=>"手"},
# >>     "body"=>5},
# >>    {"name"=>"最長手数",
# >>     "chart_type"=>"simple",
# >>     "chart_options"=>{"simple_type"=>"numeric_with_unit", "unit"=>"手"},
# >>     "body"=>5},
# >>    {"name"=>"投了時の平均手数",
# >>     "chart_type"=>"simple",
# >>     "chart_options"=>{"simple_type"=>"numeric_with_unit", "unit"=>"手"},
# >>     "body"=>nil},
# >>    {"name"=>"投了せずに放置した回数",
# >>     "chart_type"=>"simple",
# >>     "chart_options"=>{"simple_type"=>"numeric_with_unit", "unit"=>"回"},
# >>     "body"=>nil},
# >>    {"name"=>"投了せずに放置した時間 (最長)",
# >>     "chart_type"=>"simple",
# >>     "chart_options"=>{"simple_type"=>"second"},
# >>     "body"=>nil},
# >>    {"name"=>"投了せずに放置した頻度",
# >>     "chart_type"=>"pie",
# >>     "chart_options"=>{"pie_type"=>"is_many_values"},
# >>     "body"=>nil},
# >>    {"name"=>"1日の平均対局数",
# >>     "chart_type"=>"simple",
# >>     "chart_options"=>{"simple_type"=>"numeric_with_unit", "unit"=>"局"},
# >>     "body"=>1.0},
# >>    {"name"=>"対局時間帯",
# >>     "chart_type"=>"bar",
# >>     "chart_options"=>{"bar_type"=>"is_default"},
# >>     "body"=>
# >>      [{"name"=>"4", "value"=>0},
# >>       {"name"=>"5", "value"=>0},
# >>       {"name"=>"6", "value"=>0},
# >>       {"name"=>"7", "value"=>0},
# >>       {"name"=>"8", "value"=>0},
# >>       {"name"=>"9", "value"=>0},
# >>       {"name"=>"10", "value"=>0},
# >>       {"name"=>"11", "value"=>0},
# >>       {"name"=>"12", "value"=>0},
# >>       {"name"=>"13", "value"=>0},
# >>       {"name"=>"14", "value"=>0},
# >>       {"name"=>"15", "value"=>0},
# >>       {"name"=>"16", "value"=>0},
# >>       {"name"=>"17", "value"=>0},
# >>       {"name"=>"18", "value"=>0},
# >>       {"name"=>"19", "value"=>0},
# >>       {"name"=>"20", "value"=>0},
# >>       {"name"=>"21", "value"=>0},
# >>       {"name"=>"22", "value"=>0},
# >>       {"name"=>"23", "value"=>0},
# >>       {"name"=>"0", "value"=>1},
# >>       {"name"=>"1", "value"=>0},
# >>       {"name"=>"2", "value"=>0},
# >>       {"name"=>"3", "value"=>0}]},
# >>    {"name"=>"勝ち",
# >>     "chart_type"=>"pie",
# >>     "chart_options"=>{"pie_type"=>"is_many_values"},
# >>     "body"=>[{"key"=>"TORYO", "name"=>"投了", "value"=>1}]},
# >>    {"name"=>"1手詰を焦らして悦に入った回数",
# >>     "chart_type"=>"simple",
# >>     "chart_options"=>{"simple_type"=>"numeric_with_unit", "unit"=>"回"},
# >>     "body"=>nil},
# >>    {"name"=>"1手詰を焦らして悦に入った時間 (最長)",
# >>     "chart_type"=>"simple",
# >>     "chart_options"=>{"simple_type"=>"second"},
# >>     "body"=>nil},
# >>    {"name"=>"1手詰を焦らして悦に入った頻度",
# >>     "chart_type"=>"pie",
# >>     "chart_options"=>{"pie_type"=>"is_many_values"},
# >>     "body"=>nil},
# >>    {"name"=>"負け",
# >>     "chart_type"=>"pie",
# >>     "chart_options"=>{"pie_type"=>"is_many_values"},
# >>     "body"=>nil},
# >>    {"name"=>"投了までの心の準備",
# >>     "chart_type"=>"pie",
# >>     "chart_options"=>{"pie_type"=>"is_many_values"},
# >>     "body"=>nil},
# >>    {"name"=>"投了までの心の準備 (平均)",
# >>     "chart_type"=>"simple",
# >>     "chart_options"=>{"simple_type"=>"second"},
# >>     "body"=>nil},
# >>    {"name"=>"投了までの心の準備 (最長)",
# >>     "chart_type"=>"simple",
# >>     "chart_options"=>{"simple_type"=>"second"},
# >>     "body"=>nil},
# >>    {"name"=>"最長考",
# >>     "chart_type"=>"simple",
# >>     "chart_options"=>{"simple_type"=>"second"},
# >>     "body"=>5},
# >>    {"name"=>"平均思考",
# >>     "chart_type"=>"simple",
# >>     "chart_options"=>{"simple_type"=>"second"},
# >>     "body"=>2.0},
# >>    {"name"=>"詰ます速度 (1手平均)",
# >>     "chart_type"=>"simple",
# >>     "chart_options"=>{"simple_type"=>"second"},
# >>     "body"=>nil},
# >>    {"name"=>"駒の使用率",
# >>     "chart_type"=>"bar",
# >>     "chart_options"=>
# >>      {"bar_type"=>"is_default",
# >>       "tategaki_p"=>true,
# >>       "value_format"=>"percentage"},
# >>     "body"=>
# >>      [{"name"=>"玉", "value"=>0.0},
# >>       {"name"=>"飛", "value"=>0.0},
# >>       {"name"=>"角", "value"=>0.0},
# >>       {"name"=>"金", "value"=>0.0},
# >>       {"name"=>"銀", "value"=>0.6666666666666666},
# >>       {"name"=>"桂", "value"=>0.0},
# >>       {"name"=>"香", "value"=>0.0},
# >>       {"name"=>"歩", "value"=>0.3333333333333333},
# >>       {"name"=>"龍", "value"=>0.0},
# >>       {"name"=>"馬", "value"=>0.0},
# >>       {"name"=>"全", "value"=>0.0},
# >>       {"name"=>"圭", "value"=>0.0},
# >>       {"name"=>"杏", "value"=>0.0},
# >>       {"name"=>"と", "value"=>0.0}]},
# >>    {"name"=>"対戦相手との段級差 (平均)",
# >>     "chart_type"=>"simple",
# >>     "chart_options"=>{"simple_type"=>"raw"},
# >>     "body"=>0.0},
# >>    {"name"=>"右玉度",
# >>     "chart_type"=>"pie",
# >>     "chart_options"=>{"pie_type"=>"is_pair_values"},
# >>     "body"=>nil},
# >>    {"name"=>"右玉ファミリー",
# >>     "chart_type"=>"pie",
# >>     "chart_options"=>{"pie_type"=>"is_many_values"},
# >>     "body"=>nil},
# >>    {"name"=>"将棋ウォーズの運営を支える力",
# >>     "chart_type"=>"pie",
# >>     "chart_options"=>{"pie_type"=>"is_pair_values"},
# >>     "body"=>nil}],
# >>  "debug_hash"=>
# >>   {"対象サンプル数"=>1,
# >>    "勝ち数"=>1,
# >>    "負け数"=>0,
# >>    "勝率"=>1.0,
# >>    "引き分け率"=>0.0,
# >>    "切れ負け率(分母:負け数)"=>nil,
# >>    "切断率(分母:負け数)"=>nil,
# >>    "居飛車率"=>1.0,
# >>    "振り飛車率"=>0.0,
# >>    "居玉勝率"=>0.0,
# >>    "アヒル囲い率"=>0.0,
# >>    "嬉野流率"=>0.0,
# >>    "棋風"=>
# >>     {"rarity_key_SSR"=>0.0,
# >>      "rarity_key_SR"=>0.0,
# >>      "rarity_key_R"=>1.0,
# >>      "rarity_key_N"=>0.0},
# >>    "1手詰を詰まさないでじらした割合"=>0.0,
# >>    "絶対投了しない率"=>0.0,
# >>    "大長考または放置率"=>0.0,
# >>    "棋神降臨疑惑対局数"=>0,
# >>    "長考または放置率"=>0.0,
# >>    "最大連勝連敗"=>{"win"=>1},
# >>    "タグの重み"=>{"新嬉野流"=>1, "居飛車"=>1, "対振り"=>1, "対抗形"=>1}},
# >>  "streak_stat"=>{"win"=>1}}
