require "../setup"
tp Swars::User["SugarHuuko"].user_stat.medal_stat.to_debug_hash
_ { Swars::User["SugarHuuko"].user_stat.medal_stat.to_a } # =>
s { Swars::User["SugarHuuko"].user_stat.medal_stat.to_a } # =>

Swars::User["SugarHuuko"].user_stat.win_tag.to_h # =>

# ~> <internal:/opt/rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require': --> /Users/ikeda/src/shogi-extend/app/models/swars/user_stat/medal_info.rb
# ~> Unmatched `{', missing `}' ?
# ~>    5  module Swars
# ~>    6    module UserStat
# ~>    7      class MedalInfo
# ~>    9        memory_record [
# ~> > 11          { key: "居飛車党",           medal_params: { message: "居飛車党",                                     method: "raw",  name: "⬆️",                 type: nil,                            }, if_cond: proc { win_tag.group_ibis?                                                                                                                                                },},
# ~> > 12          { key: "振り飛車党",         medal_params: { message: "振り飛車党",                                   method: "raw",  name: "⬅️",                type: nil,                             }, if_cond: proc { win_tag.group_furi?                                                                                                                                          },},
# ~> > 13          { key: "オールラウンダー",   medal_params: { message: "オールラウンダー",                             method: "icon", name: "augmented-reality", type: nil,                            }, if_cond: proc { win_tag.group_ar?                                                                                                                     },},
# ~> > 14          { key: "嬉野マン",           medal_params: { message: "嬉野流で勝った",                               method: "raw",  name: "↗️",                type: nil,                             }, if_cond: proc { win_tag.exist?(:"嬉野流") || win_tag.exist?(:"新嬉野流")                                                                                                     },},
# ~> > 15          { key: "パックマン野郎",     medal_params: { message: "パックマンで勝った",                           method: "icon", name: "pac-man",           type: "is-warning",                   }, if_cond: proc { win_tag.exist?(:"パックマン戦法")                                                                                                                                          },},
# ~> > 16          { key: "耀龍マン",           medal_params: { message: "耀龍戦法で勝った",                             method: "raw",  name: "🐉",                type: nil,                            }, if_cond: proc { win_tag.to_s.include?("耀龍") }, },
# ~> > 17          { key: "右玉マン",           medal_params: { message: "右玉で勝った",                                 method: "raw",  name: "🌛",                 type: nil,                           }, if_cond: proc { win_tag.to_s.include?("右玉") }, },
# ~> > 18          { key: "ロケットマン",       medal_params: { message: "ロケットで勝った",                             method: "raw",  name: "🚀",                type: nil,                            }, if_cond: proc { win_tag.exist?(:"ロケット")                                                                                                                                                },},
# ~> > 19          { key: "遠見の角マン",       medal_params: { message: "遠見の角で勝った",                             method: "raw",  name: "🔭",                type: nil,                            }, if_cond: proc { win_tag.exist?(:"遠見の角")                                                                                                                                                },},
# ~> > 20          { key: "屋敷マン",           medal_params: { message: "屋敷流二枚銀で勝った",                         method: "raw",  name: "🥷",                type: nil,                            }, if_cond: proc { win_tag.exist?(:"屋敷流二枚銀") || win_tag.exist?(:"屋敷流二枚銀棒銀型")                                                                                        },},
# ~> > 21          { key: "UFOマン",            medal_params: { message: "UFO銀で勝った",                                method: "raw",  name: "🛸",                type: nil,                            }, if_cond: proc { win_tag.exist?(:"UFO銀")                                                                                                                                                   },},
# ~> > 22          { key: "カニ執着マン",       medal_params: { message: "カニ系戦法で勝った",                           method: "raw",  name: "🦀",                type: nil,                            }, if_cond: proc { win_tag.exist?(:"カニカニ銀") || win_tag.exist?(:"カニカニ金") || win_tag.exist?(:"カニ囲い") || win_tag.exist?(:"カニ缶囲い") },},
# ~> > 23          { key: "一間飛車マン",       medal_params: { message: "一間飛車で勝った",                             method: "raw",  name: "1️⃣",                 type: nil,                            }, if_cond: proc { win_tag.exist?(:"一間飛車") || win_tag.exist?(:"一間飛車穴熊") }, },
# ~> > 24          { key: "カメレオンマン",     medal_params: { message: "カメレオン系戦法で勝った",                     method: "raw",  name: "🦎",                type: nil,                            }, if_cond: proc { win_tag.exist?(:"英春流カメレオン") || win_tag.exist?(:"カメレオン戦法")                                                                                 },},
# ~> > 25          { key: "ポンポンマン",       medal_params: { message: "ポンポン桂で勝った",                           method: "raw",  name: "🐴",                type: nil,                            }, if_cond: proc { win_tag.exist?(:"ポンポン桂")                                                                                                                                              },},
# ~> > 26          { key: "右四間飛車マン",     medal_params: { message: "右四間飛車で勝った",                           method: "raw",  name: "⚔",                 type: nil,                            }, if_cond: proc { win_tag.exist?(:"右四間飛車") || win_tag.exist?(:"右四間飛車急戦") || win_tag.exist?(:"右四間飛車左美濃") }},
# ~> > 27          { key: "穴熊マン",           medal_params: { message: "穴熊で勝った",                                 method: "raw",  name: "🐻",                type: nil,                            }, if_cond: proc { win_tag.to_s.include?("熊")                                                                                                                                                },},
# ~> > 28          { key: "ダイヤマン",         medal_params: { message: "ダイヤモンド美濃で勝った",                     method: "raw",  name: "💎",                type: nil,                            }, if_cond: proc { win_tag.exist?(:"ダイヤモンド美濃")                                                                                                                                        },},
# ~> > 29          { key: "チョコレートマン",   medal_params: { message: "チョコレート囲いで勝った",                     method: "raw",  name: "🍫",                type: nil,                            }, if_cond: proc { win_tag.exist?(:"チョコレート囲い")                                                                                                                                        },},
# ~> > 30          { key: "幽霊角マン",         medal_params: { message: "幽霊角で勝った",                               method: "raw",  name: "👻",                type: nil,                            }, if_cond: proc { win_tag.exist?(:"幽霊角")                                                                                                                                                  },},
# ~> > 31          { key: "極限早繰りマン",     medal_params: { message: "極限早繰り銀で勝った",                         method: "raw",  name: "🏃🏻",              type: nil,                            }, if_cond: proc { win_tag.exist?(:"極限早繰り銀")                                                                                                                                            },},
# ~> > 32          { key: "坊主マン",           medal_params: { message: "坊主美濃で勝った",                             method: "raw",  name: "👴🏻",              type: nil,                            }, if_cond: proc { win_tag.exist?(:"坊主美濃")                                                                                                                                                },},
# ~> > 33          { key: "袖飛車マン",         medal_params: { message: "袖飛車で勝った",                               method: "raw",  name: "👘",              type: nil,                              }, if_cond: proc { win_tag.exist?(:"袖飛車")                                                                                                                                                  },},
# ~> > 34          { key: "中飛車マン",         medal_params: { message: "中飛車で勝った",                               method: "raw",  name: "🀄",                type: nil,                            }, if_cond: proc { win_tag.to_s.include?("中飛車")                                                                                                                                            },},
# ~> > 35          { key: "レグスペマン",       medal_params: { message: "レグスペで勝った",                             method: "raw",  name: "🐔",                type: nil,                            }, if_cond: proc { win_tag.exist?(:"レグスペ")                                                                                                                                                },},
# ~> > 36          { key: "音無しマン",         medal_params: { message: "居飛穴音無しの構えで勝った",                   method: "raw",  name: "🦉",                type: nil,                            }, if_cond: proc { win_tag.exist?(:"居飛穴音無しの構え")                                                                                                                                      },},
# ~> > 37          { key: "筋違い角おじさん",   medal_params: { message: "筋違い角おじさん",                             method: "raw",  name: "👨🏻",              type: nil,                            }, if_cond: proc { all_tag.exist?(:"筋違い角")                                                                                                                                                        },},
# ~> > 38          { key: "スイーツマン",       medal_params: { message: "いちご囲いで勝った",                           method: "raw",  name: "🍓",                type: nil,                            }, if_cond: proc { win_tag.exist?(:"いちご囲い")                                                                                                                                              },},
# ~> > 39          { key: "無敵囲いマン",       medal_params: { message: "無敵囲いで勝った",                             method: "raw",  name: "🔰",                type: nil,                            }, if_cond: proc { win_tag.exist?(:"無敵囲い")                                                                                                                                                },},
# ~> > 40          { key: "背水マン",           medal_params: { message: "大駒全部捨てて勝った",                         method: "raw",  name: "🧠",                type: nil,                            }, if_cond: proc { win_tag.exist?(:"背水の陣")                                                                                                                                                },},
# ~> > 41          { key: "エルモマン",         medal_params: { message: "エルモ囲いで勝った",                           method: "raw",  name: "🐒",                type: nil,                            }, if_cond: proc { win_tag.exist?(:"エルモ囲い")                                                                                                                                              },},
# ~> > 42          { key: "小部屋マン",         medal_params: { message: "銀冠の小部屋で勝った",                         method: "raw",  name: "🛖",                type: nil,                            }, if_cond: proc { win_tag.exist?(:"銀冠の小部屋")                                                                                                                                            },},
# ~> > 43          { key: "鬼殺しマン",         medal_params: { message: "鬼殺しで勝った",                               method: "raw",  name: "👹",                type: nil,                            }, if_cond: proc { win_tag.exist?(:"鬼殺し向かい飛車") || win_tag.exist?(:"鬼殺し") || win_tag.exist?(:"新鬼殺し")                                                                  },},
# ~> > 44          { key: "アヒル初級",         medal_params: { message: "アヒル戦法初級者",                             method: "raw",  name: "🐣",                type: nil,                            }, if_cond: proc { (0.1...0.3).cover?(all_tag.ratio(:"アヒル囲い"))                                                                                                                                      },},
# ~> > 45          { key: "アヒル中級",         medal_params: { message: "アヒル戦法中級者",                             method: "raw",  name: "🐥",                type: nil,                            }, if_cond: proc { (0.3...0.5).cover?(all_tag.ratio(:"アヒル囲い"))                                                                                                                                      },},
# ~> > 46          { key: "アヒル上級",         medal_params: { message: "アヒル戦法上級者",                             method: "raw",  name: "🐤",                type: nil,                            }, if_cond: proc { (0.5..1.0).cover?(all_tag.ratio(:"アヒル囲い")) && win_ratio >= 0.5                                                                                                                   },},
# ~> > 50          { key: "5連勝",              medal_params: { message: "5連勝した",                                    method: "raw",  name: "🍰",                type: nil,                            }, if_cond: proc { consecutive_wins_and_losses_stat.count(:win).between?(5, 9)                              },},
# ~> > 51          { key: "10連勝",             medal_params: { message: "10連勝した",                                   method: "raw",  name: "💮",                type: nil,                            }, if_cond: proc { consecutive_wins_and_losses_stat.count(:win) >= 10                                       },},
# ~> > 53          { key: "5連敗",              medal_params: { message: "5連敗した",                                    method: "raw",  name: "🌧",                type: nil,                             }, if_cond: proc { consecutive_wins_and_losses_stat.count(:lose).between?(5, 9)                             },},
# ~> > 54          { key: "10連敗",             medal_params: { message: "10連敗した",                                   method: "raw",  name: "⛈",                type: nil,                             }, if_cond: proc { consecutive_wins_and_losses_stat.count(:lose) >= 10                                      },},
# ~> > 56          { key: "波が激しいマン",     medal_params: { message: "勝ち負けの波が激しい",                         method: "raw",  name: "🌊",                type: nil,                            }, if_cond: proc { consecutive_wins_and_losses_stat.count(:win) >= 5 && consecutive_wins_and_losses_stat.count(:lose) >= 5 },},
# ~> > 60          { key: "100手勝ちマン",      medal_params: { message: "ちょうど100手で勝った",                        method: "raw",  name: "💯",                type: nil,                            }, if_cond: proc { one_hundred_win_rate > 0                                                                                                                                                                 },},
# ~> > 61          { key: "居玉勝ちマン",       medal_params: { message: "居玉で勝った",                                 method: "raw",  name: "🗿",                type: nil,                            }, if_cond: proc { win_tag.exist?(:"居玉")
# ~> > 62          { key: "入玉勝ちマン",       medal_params: { message: "入玉で勝った",                                 method: "raw",  name: "🏈",                 type: nil,                           }, if_cond: proc { win_tag.exist?(:"入玉")                                                                                                                                                    },},
# ~> > 63          { key: "切れ負けマン",       medal_params: { message: "切れ負けが多い",                               method: "raw",  name: "⌛",                 type: nil,                           }, if_cond: proc { (r = lose_ratio_of("TIMEOUT")) && r >= 0.25                                                                                                                                              },},
# ~> > 64          { key: "レア戦法マン",       medal_params: { message: "変態戦法の使い手",                             method: "raw",  name: "🍀",                type: nil,                            }, if_cond: proc { user_stat.rarity_stat.minority?                                                                                                                                                         },},
# ~> > 65          { key: "切断マン",           medal_params: { message: "切断の使い手",                                 method: "raw",  name: "💩",                type: nil,                            }, if_cond: proc { (r = lose_ratio_of("DISCONNECT")) && r > 0                                                                                                                                               },},
# ~> > 66          { key: "角不成マン",         medal_params: { message: "角不成で舐めプした",                           method: "raw",  name: "☠",                 type: nil,                            }, if_cond: proc { all_tag.exist?(:"角不成") }           },
# ~> > 67          { key: "飛車不成マン",       medal_params: { message: "飛車不成で舐めプした",                         method: "raw",  name: "💀",                type: nil,                            }, if_cond: proc { all_tag.exist?(:"飛車不成") }           },
# ~> > 68          { key: "1手詰じらしマン",    medal_params: { message: "1手詰を焦らして歪んだ優越感に浸った",            method: "raw",  name: "😈",                type: nil,                          }, if_cond: proc { (r = jirasi_ratio) && r > 0 } },
# ~> > 69          { key: "絶対投了しないマン", medal_params: { message: "悔しかったので時間切れまで放置した",           method: "raw",  name: "🪳",                type: nil,                            }, if_cond: proc { (r = zettai_toryo_sinai_ratio) && r > 0 } },
# ~> > 70          { key: "相手退席待ちマン",   medal_params: { message: "放置に痺れを切らした相手が離席したころを見計らって着手し逆時間切れ勝ちを狙ったが失敗", method: "raw",  name: "🧟",   type: nil, }, if_cond: proc { (r = taisekimachi_ratio) && r > 0 } },
# ~> > 71          { key: "大長考マン",         medal_params: { message: "対局放棄と受け取られかねない長考をした",       method: "raw",  name: "🚫",                type: nil,                            }, if_cond: proc { (r = long_think_ratio) && r > 0 } },
# ~> > 72          { key: "長考マン",           medal_params: { message: "考えすぎて負けがち",                           method: "raw",  name: "🤯",                type: nil,                            }, if_cond: proc { (r = short_think_ratio) && r > 0.1 } },
# ~> > 73          { key: "無気力マン",         medal_params: { message: "無気力な対局をした",                           method: "raw",  name: "🦥",                type: nil,                            }, if_cond: proc { (r = hayai_toryo) && r > 0 } },
# ~> > 74          { key: "開幕千日手",         medal_params: { message: "開幕千日手をした",                             method: "raw",  name: "❓",                type: nil                             }, if_cond: proc { (r = start_draw_ratio) && r > 0 } },
# ~> > 75          { key: "ただの千日手",       medal_params: { message: "千日手があった",                               method: "raw",  name: "🍌",                type: nil                             }, if_cond: proc { (r = draw_ratio) && r > 0 } },
# ~> > 76          { key: "友対マン",           medal_params: { message: "友達対局をした",                               method: "raw",  name: "👬",                 type: nil,                           }, if_cond: proc { xmode_stat.exist?(:"友達") } },
# ~> > 77          { key: "指導受けマン",       medal_params: { message: "指導対局を受けた",                             method: "raw",  name: "🔥",                type: nil,                            }, if_cond: proc { xmode_stat.exist?(:"指導") } },
# ~> > 78          { key: "運営支えマン",       medal_params: { message: "将棋ウォーズの運営を支える力がある",           method: "raw",  name: "🧙‍♂️",                type: nil                           }, if_cond: proc { fraud_stat.count.positive? } },
# ~>   79        ]
# ~>   80      end
# ~>   81    end
# ~>   82  end
# ~> /Users/ikeda/src/shogi-extend/app/models/swars/user_stat/medal_info.rb:62: syntax error, unexpected ',', expecting '}' (SyntaxError)
# ~> ...                           },},
# ~> ...                              ^
# ~>
# ~>    from <internal:/opt/rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
# ~>    from /opt/rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
# ~>    from /opt/rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.15/lib/zeitwerk/kernel.rb:26:in `require'
# ~>    from /Users/ikeda/src/shogi-extend/app/models/swars/user_stat/medal_stat.rb:92:in `matched_medal_infos'
# ~>    from /Users/ikeda/src/shogi-extend/app/models/swars/user_stat/medal_stat.rb:42:in `to_a'
# ~>    from -:3:in `block in <main>'
# ~>    from /Users/ikeda/src/shogi-extend/workbench/swars/setup.rb:4:in `block (2 levels) in _'
# ~>    from /Users/ikeda/src/shogi-extend/workbench/swars/setup.rb:4:in `times'
# ~>    from /Users/ikeda/src/shogi-extend/workbench/swars/setup.rb:4:in `block in _'
# ~>    from /opt/rbenv/versions/3.2.2/lib/ruby/3.2.0/benchmark.rb:311:in `realtime'
# ~>    from /opt/rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.2/lib/active_support/core_ext/benchmark.rb:14:in `ms'
# ~>    from /Users/ikeda/src/shogi-extend/workbench/swars/setup.rb:4:in `_'
# ~>    from -:3:in `<main>'
# >> |---------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
# >> |                  対象サンプル数 | 50                                                                                                                                                                                                                                                                                                                                                                           |
# >> |                          勝ち数 | 39                                                                                                                                                                                                                                                                                                                                                                           |
# >> |                          負け数 | 8                                                                                                                                                                                                                                                                                                                                                                            |
# >> |                            勝率 | 0.78                                                                                                                                                                                                                                                                                                                                                                         |
# >> |                      引き分け率 | 0.02                                                                                                                                                                                                                                                                                                                                                                         |
# >> |         切れ負け率(分母:負け数) | 0.125                                                                                                                                                                                                                                                                                                                                                                        |
# >> |             切断率(分母:負け数) | 0.0                                                                                                                                                                                                                                                                                                                                                                          |
# >> |                        居飛車率 | 1.0                                                                                                                                                                                                                                                                                                                                                                          |
# >> |                      振り飛車率 | 0.0                                                                                                                                                                                                                                                                                                                                                                          |
# >> |                        居玉勝率 | 0.18                                                                                                                                                                                                                                                                                                                                                                         |
# >> |                    アヒル囲い率 | 0.0                                                                                                                                                                                                                                                                                                                                                                          |
# >> |                        嬉野流率 | 0.0                                                                                                                                                                                                                                                                                                                                                                          |
# >> |                            棋風 | {:rarity_key_SSR=>0.14, :rarity_key_SR=>0.28, :rarity_key_R=>0.16, :rarity_key_N=>0.42}                                                                                                                                                                                                                                                                                      |
# >> | 1手詰を詰まさないでじらした割合 | 0.0                                                                                                                                                                                                                                                                                                                                                                          |
# >> |                絶対投了しない率 | 0.0                                                                                                                                                                                                                                                                                                                                                                          |
# >> |              大長考または放置率 | 0.02                                                                                                                                                                                                                                                                                                                                                                         |
# >> |              棋神降臨疑惑対局数 | 0                                                                                                                                                                                                                                                                                                                                                                            |
# >> |                長考または放置率 | 0.02                                                                                                                                                                                                                                                                                                                                                                         |
# >> |                    最大連勝連敗 | {:lose=>2, :win=>12, :draw=>1}                                                                                                                                                                                                                                                                                                                                               |
# >> |                      タグの重み | {:力戦=>17, :居飛車=>50, :カブト囲い=>1, :箱入り娘=>1, :銀雲雀=>1, :舟囲い=>9, :居飛車金美濃=>2, :対振り持久戦=>1, :新型雁木=>6, :相掛かり=>1, :▲４五歩早仕掛け=>2, :居玉=>11, :△３三角型空中戦法=>1, :ツノ銀雁木=>1, :オールド雁木=>1, :原始棒銀=>5, :UFO銀=>5, :へこみ矢倉=>1, :串カツ囲い=>1, :金盾囲い=>1, :角交換型=>3, :角換わり=>1, :右玉=>3, :手得角交換型=>1, ... |
# >> |---------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
