require "./setup"
QuickScript::Dev::FooBarBazScript.qs_key       # => "dev/foo_bar_baz"
QuickScript::Dev::FooBarBazScript.qs_path      # => "/lab/dev/foo-bar-baz"
QuickScript::Dev::FooBarBazScript.qs_url       # => "http://localhost:4000/lab/dev/foo-bar-baz"
QuickScript::Dev::FooBarBazScript.qs_api_url   # => "http://localhost:3000/api/lab/dev/foo_bar_baz.json"
QuickScript::Dev::FooBarBazScript.qs_group_key # => "dev"
QuickScript::Dev::FooBarBazScript.qs_page_key  # => "foo_bar_baz"
QuickScript::Dev::FooBarBazScript.title        # => "スクリプト名のテスト"
QuickScript::Dev::FooBarBazScript.description  # => "スクリプト名にハイフンを含むため URL では foo-bar-baz となるのが正しい"
