require "./setup"
# QuickScript::Dispatcher.dispatch(qs_group_key: "dev", qs_page_key: "foo-bar-baz") # => #<QuickScript::Dev::FooBarBazScript:0x000000010c8fe460 @params={:qs_group_key=>"dev", :qs_page_key=>"foo_bar_baz"}, @options={}>
# QuickScript::Dispatcher.dispatch(qs_group_key: "dev", qs_page_key: "foo_bar_baz") # => #<QuickScript::Dev::FooBarBazScript:0x000000010cc7e2e8 @params={:qs_group_key=>"dev", :qs_page_key=>"foo_bar_baz"}, @options={}>
# tp QuickScript::Dispatcher.info

tp QuickScript::Dispatcher.all
tp QuickScript::Base.deep_subclasses
# >> |---------------------------------------------------|
# >> | QuickScript::Chore::DocumentationScript           |
# >> | QuickScript::About::CreditScript                  |
# >> | QuickScript::About::PrivacyPolicyScript           |
# >> | QuickScript::About::TermsScript                   |
# >> | QuickScript::Account::DestroyScript               |
# >> | QuickScript::Account::EmailEditScript             |
# >> | QuickScript::Account::InfoScript                  |
# >> | QuickScript::Account::KentoProDestroyScript       |
# >> | QuickScript::Account::LogoutScript                |
# >> | QuickScript::Account::NameEditScript              |
# >> | QuickScript::Account::ProfileImageUploadScript    |
# >> | QuickScript::Account::SnsAccountIntegrationScript |
# >> | QuickScript::Admin::LoginScript                   |
# >> | QuickScript::Admin::SwarsAgentScript              |
# >> | QuickScript::Chore::GroupScript                   |
# >> | QuickScript::Chore::IndexScript                   |
# >> | QuickScript::Chore::InvisibleScript               |
# >> | QuickScript::Chore::MessageScript                 |
# >> | QuickScript::Chore::NotFoundScript                |
# >> | QuickScript::Chore::NullScript                    |
# >> | QuickScript::Chore::SitemapScript                 |
# >> | QuickScript::Chore::StatusCodeScript              |
# >> | QuickScript::Dev::BackgroundJobScript             |
# >> | QuickScript::Dev::CalcScript                      |
# >> | QuickScript::Dev::CsvDownloadGetScript            |
# >> | QuickScript::Dev::CsvDownloadPostScript           |
# >> | QuickScript::Dev::DelegateScript                  |
# >> | QuickScript::Dev::EmojiScript                     |
# >> | QuickScript::Dev::ErrorScript                     |
# >> | QuickScript::Dev::EvalScript                      |
# >> | QuickScript::Dev::Fake500Script                   |
# >> | QuickScript::Dev::FetchIndexScript                |
# >> | QuickScript::Dev::FlashScript                     |
# >> | QuickScript::Dev::FooBarBazScript                 |
# >> | QuickScript::Dev::FormBuefyTaginputScript         |
# >> | QuickScript::Dev::FormCheckboxButtonScript        |
# >> | QuickScript::Dev::FormScript                      |
# >> | QuickScript::Dev::FormStringScript                |
# >> | QuickScript::Dev::FormValueSessionRestoreScript   |
# >> | QuickScript::Dev::HelloScript                     |
# >> | QuickScript::Dev::HtmlScript                      |
# >> | QuickScript::Dev::InvalidateBasicAuthScript       |
# >> | QuickScript::Dev::InvisibleScript                 |
# >> | QuickScript::Dev::LoginRequired1Script            |
# >> | QuickScript::Dev::LoginRequired2Script            |
# >> | QuickScript::Dev::MarkdownScript                  |
# >> | QuickScript::Dev::NavibarFalseScript              |
# >> | QuickScript::Dev::NullScript                      |
# >> | QuickScript::Dev::PageReloadScript                |
# >> | QuickScript::Dev::ParamsScript                    |
# >> | QuickScript::Dev::ParentLinkScript                |
# >> | QuickScript::Dev::Post1Script                     |
# >> | QuickScript::Dev::Post2FormCounterScript          |
# >> | QuickScript::Dev::Post3SessionCounterScript       |
# >> | QuickScript::Dev::PostAndRedirectScript           |
# >> | QuickScript::Dev::Redirect1Script                 |
# >> | QuickScript::Dev::Redirect2Script                 |
# >> | QuickScript::Dev::Redirect3Script                 |
# >> | QuickScript::Dev::SessionCounterScript            |
# >> | QuickScript::Dev::SessionScript                   |
# >> | QuickScript::Dev::SheetScript                     |
# >> | QuickScript::Dev::SidebarScript                   |
# >> | QuickScript::Dev::SleepScript                     |
# >> | QuickScript::Dev::StatusCodeTesterScript          |
# >> | QuickScript::Dev::TableScript                     |
# >> | QuickScript::Dev::UrlHelpersScript                |
# >> | QuickScript::Dev::ValueScript                     |
# >> | QuickScript::Dev::ZipDownloadPostScript           |
# >> | QuickScript::General::EncyclopediaScript          |
# >> | QuickScript::General::PiyoShogiConfigScript       |
# >> | QuickScript::Group1::HelloScript                  |
# >> | QuickScript::Swars::BasicStatScript               |
# >> | QuickScript::Swars::BattleDownloadScript          |
# >> | QuickScript::Swars::BattleHistoryScript           |
# >> | QuickScript::Swars::CrawlerBatchScript            |
# >> | QuickScript::Swars::CrossSearchScript             |
# >> | QuickScript::Swars::DocumentationScript           |
# >> | QuickScript::Swars::GradeStatScript               |
# >> | QuickScript::Swars::TacticListScript              |
# >> | QuickScript::Swars::TacticStatScript              |
# >> | QuickScript::Swars::SearchDefaultScript           |
# >> | QuickScript::Swars::UserGroupScript               |
# >> | QuickScript::Swars::ProScript                     |
# >> | QuickScript::Swars::SearchScript                  |
# >> | QuickScript::Swars::PrisonAllScript               |
# >> | QuickScript::Swars::PrisonSearchScript            |
# >> | QuickScript::Swars::PrisonNewScript               |
# >> | QuickScript::Swars::TacticFreqScript              |
# >> | QuickScript::Swars::TacticJudgeScript             |
# >> | QuickScript::Tool::ShortUrlScript                 |
# >> |---------------------------------------------------|
# >> |---------------------------------------------------|
# >> | QuickScript::Chore::DocumentationScript           |
# >> | QuickScript::About::CreditScript                  |
# >> | QuickScript::About::PrivacyPolicyScript           |
# >> | QuickScript::About::TermsScript                   |
# >> | QuickScript::Account::DestroyScript               |
# >> | QuickScript::Account::EmailEditScript             |
# >> | QuickScript::Account::InfoScript                  |
# >> | QuickScript::Account::KentoProDestroyScript       |
# >> | QuickScript::Account::LogoutScript                |
# >> | QuickScript::Account::NameEditScript              |
# >> | QuickScript::Account::ProfileImageUploadScript    |
# >> | QuickScript::Account::SnsAccountIntegrationScript |
# >> | QuickScript::Admin::LoginScript                   |
# >> | QuickScript::Admin::SwarsAgentScript              |
# >> | QuickScript::Chore::GroupScript                   |
# >> | QuickScript::Chore::IndexScript                   |
# >> | QuickScript::Chore::InvisibleScript               |
# >> | QuickScript::Chore::MessageScript                 |
# >> | QuickScript::Chore::NotFoundScript                |
# >> | QuickScript::Chore::NullScript                    |
# >> | QuickScript::Chore::SitemapScript                 |
# >> | QuickScript::Chore::StatusCodeScript              |
# >> | QuickScript::Dev::AbstractScript                  |
# >> | QuickScript::Dev::BackgroundJobScript             |
# >> | QuickScript::Dev::CalcScript                      |
# >> | QuickScript::Dev::CsvDownloadGetScript            |
# >> | QuickScript::Dev::CsvDownloadPostScript           |
# >> | QuickScript::Dev::DelegateScript                  |
# >> | QuickScript::Dev::EmojiScript                     |
# >> | QuickScript::Dev::ErrorScript                     |
# >> | QuickScript::Dev::EvalScript                      |
# >> | QuickScript::Dev::Fake500Script                   |
# >> | QuickScript::Dev::FetchIndexScript                |
# >> | QuickScript::Dev::FlashScript                     |
# >> | QuickScript::Dev::FooBarBazScript                 |
# >> | QuickScript::Dev::FormBuefyTaginputScript         |
# >> | QuickScript::Dev::FormCheckboxButtonScript        |
# >> | QuickScript::Dev::FormScript                      |
# >> | QuickScript::Dev::FormStringScript                |
# >> | QuickScript::Dev::FormValueSessionRestoreScript   |
# >> | QuickScript::Dev::HelloScript                     |
# >> | QuickScript::Dev::HtmlScript                      |
# >> | QuickScript::Dev::InvalidateBasicAuthScript       |
# >> | QuickScript::Dev::InvisibleScript                 |
# >> | QuickScript::Dev::LoginRequired1Script            |
# >> | QuickScript::Dev::LoginRequired2Script            |
# >> | QuickScript::Dev::MarkdownScript                  |
# >> | QuickScript::Dev::NavibarFalseScript              |
# >> | QuickScript::Dev::NullScript                      |
# >> | QuickScript::Dev::PageReloadScript                |
# >> | QuickScript::Dev::ParamsScript                    |
# >> | QuickScript::Dev::ParentLinkScript                |
# >> | QuickScript::Dev::Post1Script                     |
# >> | QuickScript::Dev::Post2FormCounterScript          |
# >> | QuickScript::Dev::Post3SessionCounterScript       |
# >> | QuickScript::Dev::PostAndRedirectScript           |
# >> | QuickScript::Dev::Redirect1Script                 |
# >> | QuickScript::Dev::Redirect2Script                 |
# >> | QuickScript::Dev::Redirect3Script                 |
# >> | QuickScript::Dev::SessionCounterScript            |
# >> | QuickScript::Dev::SessionScript                   |
# >> | QuickScript::Dev::SheetScript                     |
# >> | QuickScript::Dev::SidebarScript                   |
# >> | QuickScript::Dev::SleepScript                     |
# >> | QuickScript::Dev::StatusCodeTesterScript          |
# >> | QuickScript::Dev::TableScript                     |
# >> | QuickScript::Dev::UrlHelpersScript                |
# >> | QuickScript::Dev::ValueScript                     |
# >> | QuickScript::Dev::ZipDownloadPostScript           |
# >> | QuickScript::General::EncyclopediaScript          |
# >> | QuickScript::General::PiyoShogiConfigScript       |
# >> | QuickScript::Group1::HelloScript                  |
# >> | QuickScript::Swars::BasicStatScript               |
# >> | QuickScript::Swars::BattleDownloadScript          |
# >> | QuickScript::Swars::BattleHistoryScript           |
# >> | QuickScript::Swars::CrawlerBatchScript            |
# >> | QuickScript::Swars::CrossSearchScript             |
# >> | QuickScript::Swars::DocumentationScript           |
# >> | QuickScript::Swars::GradeStatScript               |
# >> | QuickScript::Swars::TacticListScript              |
# >> | QuickScript::Swars::TacticStatScript              |
# >> | QuickScript::Swars::SearchDefaultScript           |
# >> | QuickScript::Swars::UserGroupScript               |
# >> | QuickScript::Swars::ProScript                     |
# >> | QuickScript::Swars::SearchScript                  |
# >> | QuickScript::Swars::PrisonAllScript               |
# >> | QuickScript::Swars::PrisonSearchScript            |
# >> | QuickScript::Swars::PrisonNewScript               |
# >> | QuickScript::Swars::TacticFreqScript              |
# >> | QuickScript::Swars::TacticJudgeScript             |
# >> | QuickScript::Tool::ShortUrlScript                 |
# >> |---------------------------------------------------|
