class ServiceInfo
  include ApplicationMemoryRecord
  memory_record [
    {
      display_p: true,
      link_path: UrlProxy.wrap("/swars/search"),
      title: "将棋ウォーズ棋譜検索",
      image_source: "ogp/swars-search.png",
      description: "直近の対局の検討することを目的とした棋譜取得サービス",
      feature_items: [
        "ぴよ将棋やKENTOと連携",
        "激指に転送するための棋譜コピー",
        "段級位毎の勝率表示",
      ],
    },
    {
      display_p: true,
      link_path: UrlProxy.wrap("/vs-clock"),
      title: "対局時計",
      new_p: false,
      image_source: "ogp/vs-clock.png",
      description: "チェスクロックやゲームクロックとも呼ばれている",
      feature_items: [
        "一般的なネット対局のプリセットを用意",
        "24の猶予時間対応",
        "フィッシャールール可",
      ],
    },
    {
      display_p: true,
      link_path: UrlProxy.wrap("/xy"),
      title: "符号の鬼",
      image_source: "ogp/xy.png",
      description: "符号マスター養成所",
      feature_items: [
        "タップするルールはスマホ用",
        # "キーボードで入力するルールはPC用",
        "100問正解するまでの時間を競う",
        "1分半切ったら卒業",
        # "先後両方の視点で練習可",
        # "ランキングあり",
        # "キーボードで入力するルールはパソコン用",
      ],
    },
    {
      display_p: true,
      link_path: UrlProxy.wrap("/three-stage-leagues"),
      title: "奨励会三段リーグ成績早見表",
      image_source: [
        "ogp/three-stage-leagues.png",
        "ogp/three-stage-league-players.png",
      ],
      description: "成績が一目でわかるサービス",
      feature_items: [
        "スマホに最適化",
        "個人毎の総成績表示",
        "在籍期間の表示",
      ],
    },
    {
      display_p: true,
      link_path: UrlProxy.wrap("/adapter"),
      title: "なんでも棋譜変換",
      image_source: "ogp/adapter.png",
      description: "多種多様な棋譜形式を正規化するサービス",
      feature_items: [
        "将棋倶楽部24や将棋クエストの棋譜を正規化",
        "KENTOや将棋DB2のURLを棋譜化",
        "KIF・KI2・SFEN・BOD 形式の相互変換",
        # "「ぴよ将棋」や「KENTO」に橋渡し",
        # "棋譜共有(ツイートできる)",
        # "特定局面の画像化",
      ],
    },
    {
      display_p: true,
      link_path: UrlProxy.wrap("/share-board"),
      title: "共有将棋盤",
      image_source: "ogp/share-board.png",
      description: "リレー将棋などを目的としたサービス",
      feature_items: [
        "SNS等での指し継ぎ",
        "課題局面や詰将棋の作成",
        "オンライン対局向けのリアルタイム盤共有",
        # "URLをTwitter等のSNSに貼ると局面画像が現れる",
        # "URLから訪れた人は指し継げる (駒を動かしながら詰将棋が解ける)",
        # "棋譜や視点の情報はすべてURLに含まれている",
        # "そのため分岐しても前の状態に影響を与えない",
        # "部屋を立てるとリアルタイムに盤面を共有する",
      ],
    },
    {
      display_p: true,
      link_path: UrlProxy.wrap("/stopwatch"),
      title: "詰将棋RTA用ストップウォッチ",
      image_source: "ogp/stopwatch.png",
      description: "詰将棋を解く時間と正解率の計測サービス",
      feature_items: [
        "間違えた問題だけの復習が簡単",
        "途中からの再開可",
        "問題は自分で用意してください",
        # "復習問題のリストが固定URLに入っている(のでブックマークしていれば再開が簡単)",
        # "開始と終了のタイミングで状態をブラウザに保存しているので(ブックマークしてなくても)再開が簡単",
      ],
    },
    {
      display_p: true,
      link_path: UrlProxy.wrap("/cpu-battle"),
      title: "CPU対戦",
      image_source: "ogp/cpu-battle.png",
      description: "自作の将棋AIと対戦",
      feature_items: [
        # "コンピュータ将棋が初めて生まれたときぐらいのアリゴリズムで動作",
        # "CPUは矢倉・右四間飛車・嬉野流・アヒル戦法・振り飛車・英春流かまいたち戦法を指せます",
        "将棋に特化したプログラムであってAIではない",
        "見掛け倒しな矢倉や右四間飛車が指せる",
        "作者に似てめちゃくちゃ弱い",
      ],
    },
    {
      on_swars_search_p: false,
      display_p: Actb::Config[:actb_display_p],
      link_path: UrlProxy.wrap("/training"),
      title: "将棋トレーニングバトル",
      new_p: false,
      image_source: "ogp/training.png",
      description: "将棋の問題を解く力を競う対戦ゲーム",
      feature_items: [
        "詰将棋以外の問題もある",
        "自作の問題を作れる",
        "過疎っている",
        # "自作の問題を作れる",
        # "対戦は 23:00 - 23:15 のみ",
        # "棋力アップしません",
        # "対戦→見直し→対戦のサイクルで棋力アップ(？)",
        # "ランキング上位をめざす必要はありません",
        # "アヒル戦法の誰得問題集があります",
      ],
    },
    {
      display_p: true,
      link_path: UrlProxy.wrap("/swars/professional"),
      title: "将棋ウォーズ十段の成績",
      image_source: "ogp/swars-professional.png",
      description: "プロとの対局の棋譜を探したいときに使えるかもしれない",
      feature_items: [
        "なぜか電脳少女シロ(SiroChannel)の成績もある",
        "名前タップで検索できる",
        "他とくになし",
      ],
    },
    {
      display_p: true,
      link_path: UrlProxy.wrap("/swars/top-runner"),
      title: "将棋ウォーズイベント上位プレイヤー",
      image_source: "ogp/swars-top-runner.png",
      description: "勢いのあるプレイヤーがわかる",
      feature_items: [
        "棋士団戦の期間は幽霊団員も出てきてしまう",
        "名前タップで検索できる",
        "他とくになし",
      ],
    },
    {
      display_p: true,
      link_path: UrlProxy.wrap("/swars/histograms/attack"),
      title: "将棋ウォーズ戦法分布",
      image_source: "ogp/swars-histograms-attack.png",
      description: "人気のある戦法の傾向がわかる",
      feature_items: [
        "全体だと変動しなくておもしろくないので最近のだけ出してる",
        "囲いの分布もある",
        "段級位の分布もある",
      ],
    },
  ]
end
